/* build-boss.js — assemble per-branch boss vignettes (pipeline/boss/<branchId>.json) into
 * data/boss.js  ->  window.BOSSES = { branchId: [ {stem,options,answer,explanation,meds,...} ] }.
 * Validates each item against the deck (answer ∈ options, options are real generics, meds ids
 * exist) and drops malformed entries. Mirrors build-content.js. Run: node pipeline/build-boss.js */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, '..');

// Load a classic browser script (assigns window.<name>) in a sandbox and return that global.
function loadGlobal(rel, name) {
  const code = fs.readFileSync(path.join(ROOT, rel), 'utf8');
  const win = {};
  new Function('window', code)(win);
  return win[name];
}

const MEDS = loadGlobal('data/deck.js', 'MEDS') || [];
const CURRICULUM = loadGlobal('data/curriculum.js', 'CURRICULUM');
const byId = {}; MEDS.forEach((m) => { byId[m.id] = m; });
const BRANCHES = (CURRICULUM.branches || []).map((b) => b.id);

// Resolve a display generic (as written by the authoring agents, e.g. "Valproate",
// "Buprenorphine/naloxone") to a deck id, tolerating the deck's qualified generics
// ("Valproate / Divalproex", "Guanfacine XR", "Dexmedetomidine (sublingual)").
const STOP = new Set(['xr', 'er', 'sr', 'la', 'ir', 'odt', 'extended', 'release', 'sublingual',
  'transdermal', 'oral', 'hydrochloride', 'hcl', 'sulfate', 'decanoate', 'embonate', 'pamoate']);
function toks(s) {
  return s.toLowerCase().replace(/\([^)]*\)/g, ' ').replace(/[^a-z0-9]+/g, ' ')
    .split(/\s+/).filter((t) => t && !STOP.has(t));
}
function norm(s) { return toks(s).sort().join(' '); }
const normMap = {};                       // exact normalized generic -> id
const tokSets = MEDS.map((m) => ({ id: m.id, set: new Set(toks(m.generic)) }));
MEDS.forEach((m) => { normMap[norm(m.generic)] = m.id; });
function isSubset(a, b) { for (const t of a) if (!b.has(t)) return false; return true; }
function resolveId(opt) {
  if (normMap[norm(opt)]) return normMap[norm(opt)];           // exact (after normalisation)
  const o = new Set(toks(opt));
  const hits = tokSets.filter((m) => isSubset(o, m.set) || isSubset(m.set, o));
  return hits.length === 1 ? hits[0].id : null;               // unique token-subset match
}

const bossDir = path.join(ROOT, 'pipeline/boss');
const out = {};
const totals = { kept: 0, dropped: 0 };

BRANCHES.forEach((bid) => {
  const f = path.join(bossDir, bid + '.json');
  if (!fs.existsSync(f)) { console.warn('  (no file for branch ' + bid + ')'); out[bid] = []; return; }
  let arr;
  try { arr = JSON.parse(fs.readFileSync(f, 'utf8')); }
  catch (e) { console.error('  ✗ ' + bid + '.json does not parse: ' + e.message); out[bid] = []; return; }
  if (!Array.isArray(arr)) { console.error('  ✗ ' + bid + '.json is not an array'); out[bid] = []; return; }

  const kept = [];
  arr.forEach((v, i) => {
    const where = bid + '[' + i + ']';
    if (!v || !v.stem || !Array.isArray(v.options) || v.options.length !== 4 || !v.answer) {
      console.warn('  drop ' + where + ': missing fields / not 4 options'); totals.dropped++; return;
    }
    if (v.options.indexOf(v.answer) < 0) { console.warn('  drop ' + where + ': answer not among options'); totals.dropped++; return; }
    const optIds = v.options.map(resolveId);
    const bad = v.options.filter((o, k) => !optIds[k]);
    if (bad.length) { console.warn('  drop ' + where + ': cannot resolve options to deck ids: ' + bad.join(', ')); totals.dropped++; return; }
    v.meds = optIds;                              // meds = the 4 option ids, in order
    v.answerId = resolveId(v.answer);            // deck id for XP attribution in the runner
    kept.push(v);
    totals.kept++;
  });
  out[bid] = kept;
  console.log('  ' + bid + ': ' + kept.length + ' vignettes');
});

const banner = '// data/boss.js — GENERATED by pipeline/build-boss.js. DO NOT EDIT BY HAND.\n' +
  '// Per-branch "boss" discrimination vignettes for the learning path (window.BOSSES[branchId]).\n';
fs.writeFileSync(path.join(ROOT, 'data/boss.js'), banner + 'window.BOSSES = ' + JSON.stringify(out) + ';\n');
console.log('\nWrote data/boss.js — ' + totals.kept + ' vignettes across ' + Object.keys(out).length + ' branches (' + totals.dropped + ' dropped).');
