/* build-reviews.js — assemble per-row Review checkpoints (pipeline/reviews/<branchId>.json, each a
 * { "<tierIndex>": [ {question} ] } object) into data/reviews.js:
 *   window.REVIEWS = { "<branchId>:<tierIndex>": [ {stem,options,answer,explanation,meds,answerId,...} ] }
 * Resolves option generics to deck ids tolerantly, validates (answer ∈ options, 2-4 options, all
 * resolvable), and drops malformed items. Mirrors build-boss.js. Run: node pipeline/build-reviews.js */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, '..');

function loadGlobal(rel, name) {
  const code = fs.readFileSync(path.join(ROOT, rel), 'utf8');
  const win = {};
  new Function('window', code)(win);
  return win[name];
}

const MEDS = loadGlobal('data/deck.js', 'MEDS') || [];
const CURRICULUM = loadGlobal('data/curriculum.js', 'CURRICULUM');
const byId = {}; MEDS.forEach((m) => { byId[m.id] = m; });
const BRANCHES = (CURRICULUM.branches || []).map((b) => b.id);

// tolerant generic -> id resolver (matches build-boss.js)
const STOP = new Set(['xr', 'er', 'sr', 'la', 'ir', 'odt', 'extended', 'release', 'sublingual',
  'transdermal', 'oral', 'hydrochloride', 'hcl', 'sulfate', 'decanoate', 'embonate', 'pamoate']);
function toks(s) {
  return s.toLowerCase().replace(/\([^)]*\)/g, ' ').replace(/[^a-z0-9]+/g, ' ')
    .split(/\s+/).filter((t) => t && !STOP.has(t));
}
function norm(s) { return toks(s).sort().join(' '); }
const normMap = {};
const tokSets = MEDS.map((m) => ({ id: m.id, set: new Set(toks(m.generic)) }));
MEDS.forEach((m) => { normMap[norm(m.generic)] = m.id; });
function isSubset(a, b) { for (const t of a) if (!b.has(t)) return false; return true; }
function resolveId(opt) {
  if (normMap[norm(opt)]) return normMap[norm(opt)];
  const o = new Set(toks(opt));
  const hits = tokSets.filter((m) => isSubset(o, m.set) || isSubset(m.set, o));
  return hits.length === 1 ? hits[0].id : null;
}

const out = {};
const totals = { kept: 0, dropped: 0, rows: 0 };

BRANCHES.forEach((bid) => {
  const f = path.join(ROOT, 'pipeline/reviews', bid + '.json');
  if (!fs.existsSync(f)) { console.warn('  (no review file for branch ' + bid + ')'); return; }
  let obj;
  try { obj = JSON.parse(fs.readFileSync(f, 'utf8')); }
  catch (e) { console.error('  ✗ ' + bid + '.json does not parse: ' + e.message); return; }

  Object.keys(obj).forEach((tierIndex) => {
    const arr = obj[tierIndex];
    if (!Array.isArray(arr)) { console.warn('  ✗ ' + bid + ':' + tierIndex + ' not an array'); return; }
    const kept = [];
    arr.forEach((v, i) => {
      const where = bid + ':' + tierIndex + '[' + i + ']';
      if (!v || !v.stem || !Array.isArray(v.options) || v.options.length < 2 || v.options.length > 4 || !v.answer) {
        console.warn('  drop ' + where + ': missing fields / options not 2-4'); totals.dropped++; return;
      }
      if (v.options.indexOf(v.answer) < 0) { console.warn('  drop ' + where + ': answer not among options'); totals.dropped++; return; }
      const optIds = v.options.map(resolveId);
      const bad = v.options.filter((o, k) => !optIds[k]);
      if (bad.length) { console.warn('  drop ' + where + ': cannot resolve: ' + bad.join(', ')); totals.dropped++; return; }
      v.meds = optIds;
      v.answerId = resolveId(v.answer);
      kept.push(v);
      totals.kept++;
    });
    if (kept.length) { out[bid + ':' + tierIndex] = kept; totals.rows++; }
  });
  const rowKeys = Object.keys(out).filter((k) => k.indexOf(bid + ':') === 0);
  console.log('  ' + bid + ': ' + rowKeys.length + ' rows, ' + rowKeys.reduce((a, k) => a + out[k].length, 0) + ' questions');
});

const banner = '// data/reviews.js — GENERATED by pipeline/build-reviews.js. DO NOT EDIT BY HAND.\n' +
  '// Per-row Review checkpoints for the roadmap (window.REVIEWS["<branchId>:<tierIndex>"]).\n';
fs.writeFileSync(path.join(ROOT, 'data/reviews.js'), banner + 'window.REVIEWS = ' + JSON.stringify(out) + ';\n');
console.log('\nWrote data/reviews.js — ' + totals.kept + ' questions across ' + totals.rows + ' rows (' + totals.dropped + ' dropped).');
