// build-content.js — merge authored lessons + cross-med vignettes into browser data files.
//   node build-content.js
// Writes ../data/lessons.js (window.LESSONS) and ../data/vignettes.js (window.VIGNETTES).

import { readFile, writeFile, readdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { today } from './lib/http.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA = join(__dirname, '..', 'data');

async function mergeDir(dir, kind) {
  const full = join(__dirname, dir);
  if (!existsSync(full)) return kind === 'array' ? [] : {};
  const files = (await readdir(full)).filter((f) => f.endsWith('.js') && !f.startsWith('_'));
  let out = kind === 'array' ? [] : {};
  for (const f of files) {
    const mod = await import(pathToFileURL(join(full, f)).href);
    if (kind === 'array') out = out.concat(mod.default || []);
    else Object.assign(out, mod.default || {});
  }
  return out;
}

// ---- lessons ----
const lessons = await mergeDir('lessons', 'object');
const banner = (name) => `// data/${name} — GENERATED by pipeline/build-content.js on ${today()}. DO NOT EDIT BY HAND.\n`;
await writeFile(join(DATA, 'lessons.js'), banner('lessons.js') + `window.LESSONS = ${JSON.stringify(lessons)};\n`);
console.log(`lessons.js: ${Object.keys(lessons).length} lessons`);

// ---- vignettes ----
const vignettes = await mergeDir('vignettes', 'array');
// de-dup by id, drop malformed
const seen = new Set();
const clean = vignettes.filter((v) => {
  if (!v || !v.id || seen.has(v.id)) return false;
  if (!Array.isArray(v.options) || v.options.indexOf(v.answer) < 0) return false;
  seen.add(v.id); return true;
});
await writeFile(join(DATA, 'vignettes.js'), banner('vignettes.js') + `window.VIGNETTES = ${JSON.stringify(clean)};\n`);
console.log(`vignettes.js: ${clean.length} vignettes (dropped ${vignettes.length - clean.length})`);

// quick validity: vignette answers in options, meds ids exist
const deck = JSON.parse(await readFile(join(DATA, 'deck.json'), 'utf8'));
const deckIds = new Set(deck.map((c) => c.id));
const badMeds = clean.filter((v) => (v.meds || []).some((id) => !deckIds.has(id)));
if (badMeds.length) console.log(`  WARN: ${badMeds.length} vignettes reference unknown med ids (first: ${badMeds[0].id} → ${badMeds[0].meds})`);
const disorders = [...new Set(clean.map((v) => v.disorder).filter(Boolean))].sort();
console.log(`  disorders covered (${disorders.length}): ${disorders.join(', ')}`);
