// provenance.js — generate data/PROVENANCE.md from the built deck. Run: node provenance.js
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { SAFETY_CRITICAL, FIELDS } from './schema.js';
import { CLASSES } from './scope.js';
import { today } from './lib/http.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA = join(__dirname, '..', 'data');
const deck = JSON.parse(await readFile(join(DATA, 'deck.json'), 'utf8'));

const labelOf = Object.fromEntries(FIELDS.map((f) => [f.key, f.label]));

function has(v) { return v != null && v !== '' && !(Array.isArray(v) && v.length === 0); }

// coverage per class
const byClass = {};
for (const c of deck) {
  const k = c.class;
  byClass[k] = byClass[k] || { total: 0, usOnly: 0, verify: 0 };
  byClass[k].total++;
  if (c._meta.usOnly) byClass[k].usOnly++;
  if (c._meta.verifyFlag) byClass[k].verify++;
}

// source grounding by field
const fieldStats = {};
let scPop = 0, scGround = 0, scAuthored = 0;
const originCounts = {};
for (const c of deck) {
  const prov = c._meta.provenance || {};
  for (const key of SAFETY_CRITICAL) {
    if (!has(c[key])) continue;
    scPop++;
    fieldStats[key] = fieldStats[key] || { pop: 0, grounded: 0, authored: 0 };
    fieldStats[key].pop++;
    const p = prov[key];
    if (p && p.origin && p.origin !== 'authored') { scGround++; fieldStats[key].grounded++; originCounts[p.origin] = (originCounts[p.origin] || 0) + 1; }
    else { scAuthored++; fieldStats[key].authored++; }
  }
}

// per-drug model-authored safety fields
const authoredByDrug = deck
  .filter((c) => (c._meta.verifyFlags || []).length)
  .map((c) => ({ id: c.id, generic: c.generic, us: c._meta.usOnly, fields: c._meta.verifyFlags }))
  .sort((a, b) => b.fields.length - a.fields.length);

const usOnly = deck.filter((c) => c._meta.usOnly);

const lines = [];
lines.push('# data/PROVENANCE.md');
lines.push('');
lines.push(`_Generated by \`pipeline/provenance.js\` on ${today()} from the built deck (${deck.length} molecules)._`);
lines.push('');
lines.push('This report discloses, per the project\'s safety rules, exactly which fields are');
lines.push('**source-extracted** from a real source vs which **fell back to model authorship** (and');
lines.push('therefore carry `verifyFlag: true` and a ⚠ badge in the app). See');
lines.push('[../DATA_SOURCES.md](../DATA_SOURCES.md) for the provenance model.');
lines.push('');
lines.push('## Coverage');
lines.push('');
lines.push('| Class | Molecules | US-only (awareness) | Cards with ≥1 model-authored safety field |');
lines.push('|---|---:|---:|---:|');
for (const cls of CLASSES) {
  const s = byClass[cls]; if (!s) continue;
  lines.push(`| ${cls} | ${s.total} | ${s.usOnly} | ${s.verify} |`);
}
lines.push(`| **Total** | **${deck.length}** | **${usOnly.length}** | **${deck.filter((c) => c._meta.verifyFlag).length}** |`);
lines.push('');
lines.push('## Source grounding of safety-critical fields');
lines.push('');
lines.push(`Across the deck, **${scPop}** safety-critical field values are populated:`);
lines.push('');
lines.push(`- **${scGround} (${Math.round(100 * scGround / scPop)}%) are source-grounded** — extracted from a cited source (Health Canada DPD, openFDA/DailyMed label text, FAERS, or CANMAT) with the source and, for label-derived fields, the verbatim excerpt attached to the card.`);
lines.push(`- **${scAuthored} (${Math.round(100 * scAuthored / scPop)}%) fell back to model authorship** and are flagged \`verifyFlag: true\` (⚠ badge). These need verification against the current Health Canada monograph.`);
lines.push('');
lines.push('Grounded fields by source origin:');
lines.push('');
for (const [o, n] of Object.entries(originCounts).sort((a, b) => b[1] - a[1])) {
  const name = { dpd: 'Health Canada DPD', openfda: 'openFDA/DailyMed label', faers: 'openFDA FAERS', canmat: 'CANMAT guideline', monograph: 'Health Canada monograph', dailymed: 'DailyMed' }[o] || o;
  lines.push(`- ${name}: ${n}`);
}
lines.push('');
lines.push('### By field');
lines.push('');
lines.push('| Safety-critical field | Populated | Source-grounded | Model-authored |');
lines.push('|---|---:|---:|---:|');
for (const key of SAFETY_CRITICAL) {
  const s = fieldStats[key]; if (!s) continue;
  lines.push(`| ${labelOf[key] || key} | ${s.pop} | ${s.grounded} | ${s.authored} |`);
}
lines.push('');
lines.push('## US-only agents (kept for awareness, flagged in-app)');
lines.push('');
lines.push('These molecules are not currently found as Health Canada–approved in the DPD query and are');
lines.push('labelled **US-only — for awareness**:');
lines.push('');
lines.push(usOnly.map((c) => `\`${c.generic}\``).join(', ') + '.');
lines.push('');
lines.push('## Model-authored safety fields, by drug');
lines.push('');
lines.push('The following cards have one or more safety-critical fields that fell back to model');
lines.push('authorship (most commonly because the drug is Canada-only with no US label, so the openFDA');
lines.push('section was unavailable). Each is flagged in-app. **Verify these against the monograph.**');
lines.push('');
lines.push('| Drug | US-only | Model-authored safety fields |');
lines.push('|---|:--:|---|');
for (const d of authoredByDrug) {
  lines.push(`| ${d.generic} | ${d.us ? '✓' : ''} | ${d.fields.map((f) => labelOf[f] || f).join(', ')} |`);
}
lines.push('');
lines.push('## Note');
lines.push('');
lines.push('Boxed warnings and contraindications are pulled **verbatim** from the openFDA/DailyMed label');
lines.push('text and are never model-authored. DINs, brands, formulations, and controlled status come');
lines.push('directly from the Health Canada DPD. Pedagogical content (mnemonics, confusables, pearls,');
lines.push('vignettes, pronunciation) is model-authored by design but tests source-grounded facts.');
lines.push('');

await writeFile(join(DATA, 'PROVENANCE.md'), lines.join('\n'));
console.log(`Wrote data/PROVENANCE.md — ${deck.length} molecules, ${scGround}/${scPop} safety fields grounded, ${authoredByDrug.length} cards with model-authored safety fields.`);
