// run.js — pipeline orchestrator.
//
//   node run.js                 build every molecule in scope
//   node run.js --class="SSRI"  build only a subclass/class match (substring, case-insensitive)
//   node run.js --only=id1,id2  build only these molecule ids
//   node run.js --refresh       bypass the raw cache and re-hit the live APIs
//
// Builds cards, validates them, and UPSERTS into data/deck.json (merge-friendly source of
// truth), then regenerates data/deck.js (window.MEDS = …) for the browser. Building one class
// at a time lets M4 fan out per class and accumulate the full deck.

import { readFile, writeFile, mkdir, readdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { SCOPE, CLASSES } from './scope.js';
import { buildDeck } from './build.js';
import { validateCard } from './schema.js';
import { today } from './lib/http.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA = join(__dirname, '..', 'data');
const DECK_JSON = join(DATA, 'deck.json');
const DECK_JS = join(DATA, 'deck.js');

function arg(name) {
  const hit = process.argv.find((a) => a.startsWith(`--${name}=`) || a.startsWith(`--${name}`));
  if (!hit) return null;
  const eq = hit.indexOf('=');
  return eq >= 0 ? hit.slice(eq + 1).replace(/^["']|["']$/g, '') : true;
}

async function loadOverlays() {
  const dir = join(__dirname, 'authored');
  if (!existsSync(dir)) return {};
  const files = (await readdir(dir)).filter((f) => f.endsWith('.js'));
  const merged = {};
  for (const f of files) {
    const mod = await import(pathToFileURL(join(dir, f)).href);
    Object.assign(merged, mod.default || {});
  }
  return merged;
}

async function loadDeck() {
  if (!existsSync(DECK_JSON)) return [];
  try { return JSON.parse(await readFile(DECK_JSON, 'utf8')); } catch { return []; }
}

function classOrder(a, b) {
  const ca = CLASSES.indexOf(a.class), cb = CLASSES.indexOf(b.class);
  if (ca !== cb) return ca - cb;
  return String(a.generic).localeCompare(String(b.generic));
}

async function writeDeck(deck) {
  deck.sort(classOrder);
  await mkdir(DATA, { recursive: true });
  await writeFile(DECK_JSON, JSON.stringify(deck, null, 2));
  const banner = `// data/deck.js — GENERATED by pipeline/run.js on ${today()}. DO NOT EDIT BY HAND.\n` +
    `// The app loads this via <script> and reads window.MEDS. Regenerate with: cd pipeline && node run.js\n` +
    `// Source-attributed: safety-critical fields carry provenance; verifyFlag marks model-authored fallbacks.\n`;
  const js = `${banner}window.MEDS = ${JSON.stringify(deck)};\n` +
    `window.MEDS_META = ${JSON.stringify({ generated: today(), count: deck.length })};\n`;
  await writeFile(DECK_JS, js);
}

async function main() {
  const refresh = !!arg('refresh');
  const classFilter = arg('class');
  const onlyArg = arg('only');
  const onlyIds = onlyArg && onlyArg !== true ? String(onlyArg).split(',').map((s) => s.trim()) : null;

  let scope = SCOPE;
  if (onlyIds) scope = scope.filter((s) => onlyIds.includes(s.id));
  else if (classFilter && classFilter !== true) {
    const cf = String(classFilter).toLowerCase();
    scope = scope.filter((s) => s.class.toLowerCase().includes(cf) || (s.subclass || '').toLowerCase().includes(cf) || s.id.includes(cf));
  }

  if (!scope.length) {
    console.error('No molecules matched the filter.');
    process.exit(1);
  }

  const overlays = await loadOverlays();
  console.log(`Building ${scope.length} molecule(s)…  (overlays loaded: ${Object.keys(overlays).length})`);

  const built = [];
  const report = [];
  const { cards } = await buildDeck(scope, overlays, {
    log: (card) => {
      const v = validateCard(card);
      const flags = card._meta.verifyFlags.length;
      const status = v.ok ? '✓' : '✗';
      const us = card._meta.usOnly ? ' [US-only]' : '';
      console.log(`  ${status} ${card.id}${us}  brands:${(card.brandsCanada || []).length} sections:${card._meta.availableSections.length} verifyFlags:${flags}` +
        (v.errors.length ? `\n      ERRORS: ${v.errors.join('; ')}` : ''));
    },
  });

  for (const card of cards) {
    const v = validateCard(card);
    built.push(card);
    report.push({ id: card.id, ok: v.ok, errors: v.errors, warnings: v.warnings.length });
  }

  // Upsert into existing deck
  const existing = await loadDeck();
  const byId = new Map(existing.map((c) => [c.id, c]));
  for (const c of built) byId.set(c.id, c);
  const deck = [...byId.values()];
  await writeDeck(deck);

  const okCount = report.filter((r) => r.ok).length;
  console.log(`\nBuilt ${built.length} card(s); ${okCount}/${built.length} valid. Deck now has ${deck.length} card(s).`);
  const bad = report.filter((r) => !r.ok);
  if (bad.length) {
    console.log('INVALID CARDS:');
    for (const b of bad) console.log(`  ${b.id}: ${b.errors.join('; ')}`);
    process.exitCode = 2;
  }
}

main().catch((e) => { console.error(e); process.exit(1); });
