// authored/adhd.js — authored overlay for the ADHD agents (stimulants + non-stimulants).
//
// Mechanism/PK/dosing summaries + the pedagogical layer, grounded in established
// pharmacology and the fetched openFDA/monograph label sections. `_prov` declares which
// safety-critical fields the label text grounds; build.js attaches that source text and,
// where a field cannot be grounded, downgrades it to origin 'authored' + verifyFlag.
//
// Class theme — STIMULANTS (methylphenidate, amphetamines) are first-line and most
// effective. Amphetamines RELEASE dopamine/norepinephrine (reverse transporters, also
// block reuptake); methylphenidate purely BLOCKS DAT/NET reuptake. Shared stimulant SEs:
// appetite suppression / weight loss, insomnia, ↑HR/BP, growth monitoring in children,
// misuse / diversion, caution in structural cardiac disease, and they can unmask/worsen
// psychosis or tics. CONTRAINDICATED with MAOIs (hypertensive crisis) — the marquee DDI.
// NON-STIMULANTS (atomoxetine = selective NRI; guanfacine/clonidine = α2 agonists) are
// slower and carry no misuse potential; the α2 agonists cause sedation + hypotension +
// bradycardia and REBOUND HYPERTENSION if stopped abruptly.

const ADHD_PROV = {
  startingDose: 'openfda', maxDose: 'openfda', seriousAE: 'openfda', syndromes: 'openfda',
  majorDDI: 'openfda', contraindicatedCombos: 'openfda', overdoseLethality: 'openfda',
  baselineWorkup: 'openfda', ongoingMonitoring: 'openfda', pregnancy: 'openfda',
};

export default {
  methylphenidate: {
    pronunciation: 'meth-il-FEN-i-date',
    moa: 'Blocks presynaptic dopamine and norepinephrine transporters (DAT/NET) → increases synaptic DA/NE. A pure REUPTAKE BLOCKER — it does NOT trigger vesicular release (the key contrast with amphetamines).',
    receptorProfile: 'DAT/NET reuptake inhibition; d-threo enantiomer is the active moiety. No direct receptor agonism.',
    onsetOfEffect: 'Behavioural effect within ~30–60 min of a dose; benefit is same-day (not delayed like non-stimulants).',
    halfLife: 'IR ~2–3 h (short); extended-release/OROS formulations give a longer functional duration (~8–12 h) despite a similar terminal half-life.',
    metabolism: 'De-esterified by carboxylesterase CES1A1 to ritalinic acid (inactive). Minimal CYP involvement → comparatively FEW pharmacokinetic drug interactions.',
    activeMetabolites: 'None clinically significant (ritalinic acid is inactive).',
    approvedCanada: ['ADHD', 'Narcolepsy'],
    approvedPopulations: 'Children ≥6 y, adolescents, adults.',
    startingDose: 'IR 5 mg PO BID (breakfast + lunch); ER products dosed once each morning (e.g., OROS 18 mg AM).',
    titration: 'Increase weekly; individualize to response and tolerability; pediatric dosing often ~0.3–1 mg/kg/dose.',
    maxDose: '~60 mg/day for most IR/ER products (formulation-dependent; OROS up to 72 mg/day in adults).',
    frequencyTiming: 'Morning ± early afternoon; give the last IR dose by mid-afternoon to avoid insomnia. ER once each morning.',
    startStopCrossTaper: 'No physiologic taper needed pharmacologically; a rebound of ADHD symptoms as levels fall is common in the late afternoon.',
    administrationNotes: 'Do not crush/chew ER products. OROS shell is non-absorbable and passes intact in stool ("ghost tablet") — reassure patients this is expected.',
    commonSE: ['Decreased appetite / weight loss', 'Insomnia', 'Headache', 'Increased heart rate / blood pressure', 'Irritability / late-day rebound', 'Abdominal pain', 'Dry mouth'],
    seriousAE: ['Sudden cardiac death with pre-existing structural heart disease', 'Hypertension / tachyarrhythmia', 'Growth suppression in children', 'Precipitation or worsening of psychosis or mania', 'New-onset or worsening motor/vocal tics', 'Priapism (rare)', 'Peripheral vasculopathy / Raynaud phenomenon'],
    syndromes: ['Sympathomimetic toxicity', 'Stimulant-induced psychosis', 'Growth suppression', 'Late-day symptom rebound'],
    overdoseLethality: 'Sympathomimetic overdose — agitation, hypertension, tachyarrhythmia, hyperthermia, seizures. Rarely fatal alone with supportive care, but dangerous; benzodiazepines are first-line for agitation/seizures.',
    baselineWorkup: ['Cardiac history + personal/family history of sudden death or structural heart disease', 'Baseline BP and heart rate', 'Height and weight (children)', 'Screen for psychosis/bipolar disorder and tics', 'Assess substance-misuse / diversion risk'],
    ongoingMonitoring: 'BP and HR at each visit; height/weight plotted on growth charts in children; appetite, sleep, mood, tics; adherence and diversion/misuse.',
    majorDDI: ['MAOIs (hypertensive crisis — contraindicated)', 'Other sympathomimetics / pressors (additive cardiovascular effects)', 'May raise levels of some CES1 substrates (e.g., warfarin, some anticonvulsants, TCAs)', 'Additive effects with other serotonergics/dopaminergics'],
    contraindicatedCombos: ['MAOIs (during use or within 14 days of stopping an MAOI)'],
    maoiWashout: 'Do not use with an MAOI or within 14 days of stopping one (hypertensive crisis).',
    pregnancy: 'Limited data; weigh maternal functional impairment against fetal exposure. Individualized decision.',
    pediatric: 'First-line pharmacotherapy for childhood ADHD. Monitor growth (height/weight percentiles); appetite suppression and insomnia are common; drug holidays are sometimes used.',
    cardiac: 'Avoid in serious structural cardiac abnormality, cardiomyopathy, or serious arrhythmia; use caution with pre-existing hypertension. ↑HR/BP expected.',
    pearls: [
      'Pure reuptake blocker (DAT/NET) — remember it does NOT release dopamine, unlike amphetamines.',
      'Metabolized by carboxylesterase (CES1), not CYP → far fewer PK interactions than most psychotropics.',
      'The OROS "ghost tablet" seen in stool is the empty non-absorbable shell — not treatment failure.',
    ],
    mnemonics: ['"methylpheniDATE just DATES the transporter" — it blocks reuptake (occupies DAT/NET) rather than forcing release.'],
    confusables: ['Methylphenidate (Ritalin/Concerta/Biphentin) vs dexmethylphenidate (the active d-enantiomer).', 'Concerta = OROS methylphenidate vs Biphentin = multilayer beads — different release kinetics.'],
    classDifferentiators: 'Stimulant that BLOCKS reuptake only (no release); CES1 (not CYP) metabolism; first-line, controlled.',
    examHooks: ['Which ADHD stimulant works by pure reuptake blockade rather than transmitter release? (methylphenidate)', 'A child on stimulant + MAOI risks what? (hypertensive crisis)'],
    counsellingPoints: ['Take in the morning; avoid late-afternoon doses to protect sleep.', 'Appetite may drop — offer calorie-dense breakfast/evening snacks and monitor weight.', 'An empty tablet shell in the stool with OROS is normal.', 'Never combine with an MAOI.'],
    vignettes: [
      {
        stem: 'A 9-year-old with ADHD on OROS methylphenidate is brought in by a worried parent who found "whole pills" in the toilet. Vitals and behaviour are unchanged and symptom control is good. What is the best explanation?',
        options: ['The medication is not being absorbed and the dose should be doubled', 'The child is not swallowing the tablets', 'The non-absorbable osmotic shell passes intact in stool', 'Malabsorption from gastroenteritis'],
        answer: 'The non-absorbable osmotic shell passes intact in stool',
        explanation: 'OROS methylphenidate uses an osmotic pump; the drug is released while the insoluble shell passes intact ("ghost tablet"). It does not indicate treatment failure and requires no dose change.',
        testedFact: 'OROS methylphenidate ghost tablet',
        source: { name: 'openFDA/DailyMed methylphenidate OROS label — administration', origin: 'openfda' },
      },
    ],
    _prov: ADHD_PROV,
  },

  dextroamphetamine: {
    pronunciation: 'deks-troh-am-FET-uh-meen',
    moa: 'Amphetamine — enters the presynaptic neuron via DAT/NET and drives RELEASE of dopamine and norepinephrine (reverses the transporters / VMAT2), and also blocks their reuptake and weakly inhibits MAO. Net: primarily a transmitter RELEASER (vs methylphenidate\'s pure reuptake block).',
    receptorProfile: 'Presynaptic DA/NE release + reuptake inhibition; the d-enantiomer is more CNS/dopaminergic.',
    onsetOfEffect: 'Same-day; IR within ~30–60 min.',
    halfLife: '~10–12 h in adults (shorter in children); Spansule sustained-release extends duration.',
    metabolism: 'Hepatic (CYP2D6 and oxidative deamination); renal excretion is urine-pH dependent — acidic urine increases clearance, alkaline urine prolongs it.',
    approvedCanada: ['ADHD', 'Narcolepsy'],
    approvedPopulations: 'Children ≥6 y, adolescents, adults.',
    startingDose: 'IR 5 mg PO once or twice daily.',
    titration: 'Increase by ~5 mg/day at weekly intervals to response.',
    maxDose: 'Typically up to ~40 mg/day (individualized).',
    frequencyTiming: 'Morning ± midday (last dose early afternoon to preserve sleep); sustained-release once daily AM.',
    commonSE: ['Decreased appetite / weight loss', 'Insomnia', 'Increased heart rate / blood pressure', 'Irritability / anxiety', 'Dry mouth', 'Headache'],
    seriousAE: ['Sudden cardiac death with structural heart disease', 'Hypertension / tachyarrhythmia', 'Growth suppression in children', 'Psychosis or mania (new or worsened)', 'New/worsening tics', 'Peripheral vasculopathy / Raynaud phenomenon', 'Dependence / misuse'],
    syndromes: ['Sympathomimetic toxicity', 'Stimulant-induced psychosis', 'Growth suppression'],
    overdoseLethality: 'Sympathomimetic crisis — severe hypertension, tachyarrhythmia, hyperthermia, agitation, seizures; benzodiazepines for agitation/seizures, cooling, supportive care.',
    baselineWorkup: ['Cardiac + family history of sudden death / structural disease', 'Baseline BP and heart rate', 'Height and weight (children)', 'Screen for psychosis/bipolar and substance misuse'],
    ongoingMonitoring: 'BP/HR each visit; growth (height/weight) in children; appetite, sleep, mood, tics; misuse/diversion.',
    majorDDI: ['MAOIs (hypertensive crisis — contraindicated)', 'Urinary acidifiers (↓ amphetamine levels) / alkalinizers (↑ levels)', 'Other sympathomimetics / serotonergics', 'Tricyclic antidepressants (potentiated cardiovascular effects)'],
    contraindicatedCombos: ['MAOIs (during use or within 14 days of stopping)'],
    maoiWashout: 'Do not use with an MAOI or within 14 days of stopping one.',
    pregnancy: 'Limited data; amphetamine exposure has been associated with adverse outcomes — individualized risk/benefit.',
    pediatric: 'Effective; monitor growth, appetite and sleep. Controlled substance — counsel on secure storage.',
    cardiac: 'Avoid in serious structural cardiac disease/arrhythmia; caution with hypertension.',
    pearls: [
      'Amphetamines RELEASE dopamine/norepinephrine (and block reuptake) — the mechanistic contrast tested against methylphenidate.',
      'Urine pH changes exposure: alkalinization (e.g., bicarbonate) raises levels and toxicity risk; acidification lowers them.',
    ],
    mnemonics: ['"AMPHetamine AMPlifies release" — it pushes transmitter out; methylphenidate merely blocks its return.'],
    confusables: ['Dextroamphetamine (active drug) vs lisdexamfetamine (its prodrug) vs mixed amphetamine salts (d+l blend).'],
    classDifferentiators: 'Pure d-amphetamine; releaser + reuptake blocker; immediate-acting stimulant, controlled.',
    examHooks: ['Which mechanism distinguishes amphetamines from methylphenidate? (presynaptic transmitter release)'],
    counsellingPoints: ['Take early in the day.', 'Store securely — high misuse/diversion potential.', 'Report chest pain, palpitations, or new hallucinations.', 'Never combine with an MAOI.'],
    vignettes: [
      {
        stem: 'On rounds you are asked how dextroamphetamine differs mechanistically from methylphenidate. Which statement is correct?',
        options: ['Both act solely by blocking dopamine reuptake', 'Dextroamphetamine promotes presynaptic release of dopamine/norepinephrine in addition to blocking reuptake', 'Methylphenidate is a dopamine-releasing agent while amphetamine only blocks reuptake', 'Neither affects norepinephrine'],
        answer: 'Dextroamphetamine promotes presynaptic release of dopamine/norepinephrine in addition to blocking reuptake',
        explanation: 'Amphetamines are substrate releasers: they enter via DAT/NET and drive efflux of dopamine/norepinephrine (plus reuptake blockade). Methylphenidate blocks reuptake only.',
        testedFact: 'Amphetamine release vs methylphenidate reuptake block',
        source: { name: 'Stahl Essential Psychopharmacology — stimulant mechanisms', origin: 'authored' },
      },
    ],
    _prov: ADHD_PROV,
  },

  lisdexamfetamine: {
    pronunciation: 'lis-deks-am-FET-uh-meen',
    moa: 'Inactive PRODRUG: d-amphetamine covalently bound to L-lysine. Enzymatically hydrolyzed in the blood (by red-blood-cell peptidases) to active dextroamphetamine + L-lysine, which then releases and blocks reuptake of DA/NE. Rate-limited conversion gives a smooth, long duration and LOWER misuse liability (cannot be "activated" by snorting/injecting).',
    receptorProfile: 'Acts through liberated d-amphetamine — presynaptic DA/NE release + reuptake inhibition.',
    onsetOfEffect: 'Same-day; smooth onset over ~1–2 h with long duration (~13–14 h).',
    halfLife: 'Prodrug itself <1 h; the liberated dextroamphetamine ~11 h (drives the clinical duration).',
    metabolism: 'Activated by hydrolysis via RBC peptidases (not CYP-dependent for activation) → dextroamphetamine, then metabolized as amphetamine.',
    approvedCanada: ['ADHD'],
    offLabel: ['Binge eating disorder (approved in the US)'],
    approvedPopulations: 'Children ≥6 y, adolescents, adults.',
    startingDose: '30 mg PO once daily in the morning.',
    titration: 'Adjust by ~10–20 mg/day at weekly intervals to response.',
    maxDose: '70 mg/day.',
    frequencyTiming: 'Once daily in the morning; the prodrug design gives a consistent all-day profile without a midday dose.',
    administrationNotes: 'Capsule may be opened and dissolved in water/yogurt; take the whole dose at once.',
    commonSE: ['Decreased appetite / weight loss', 'Insomnia', 'Dry mouth', 'Irritability', 'Increased heart rate / blood pressure', 'Headache'],
    seriousAE: ['Sudden cardiac death with structural heart disease', 'Hypertension / tachyarrhythmia', 'Growth suppression in children', 'Psychosis or mania (new or worsened)', 'New/worsening tics', 'Peripheral vasculopathy / Raynaud phenomenon', 'Dependence / misuse'],
    syndromes: ['Sympathomimetic toxicity', 'Stimulant-induced psychosis', 'Growth suppression'],
    overdoseLethality: 'Sympathomimetic crisis as with amphetamine; onset may be smoothed by prodrug kinetics but large ingestions are still dangerous — supportive care, benzodiazepines.',
    baselineWorkup: ['Cardiac + family history of sudden death / structural disease', 'Baseline BP and heart rate', 'Height and weight (children)', 'Screen for psychosis/bipolar and misuse risk'],
    ongoingMonitoring: 'BP/HR each visit; growth in children; appetite, sleep, mood, tics; misuse/diversion (lower but not zero).',
    majorDDI: ['MAOIs (hypertensive crisis — contraindicated)', 'Urinary alkalinizers/acidifiers (alter amphetamine exposure)', 'Other serotonergics / sympathomimetics'],
    contraindicatedCombos: ['MAOIs (during use or within 14 days of stopping)'],
    maoiWashout: 'Do not use with an MAOI or within 14 days of stopping one.',
    pregnancy: 'Limited data; amphetamine class — individualized risk/benefit.',
    pediatric: 'Convenient once-daily option with lower abuse liability; monitor growth, appetite, sleep.',
    cardiac: 'Same cautions as amphetamine — avoid in serious structural cardiac disease/arrhythmia.',
    pearls: [
      'PRODRUG activated in the bloodstream by RBC peptidases — the classic reason its abuse potential and IV/intranasal "high" are blunted.',
      'Once-daily, long smooth profile from rate-limited conversion; also FDA-approved for binge eating disorder.',
    ],
    mnemonics: ['"LISdexamfetamine is a LIStless prodrug until the blood LYSes off the lysine."'],
    confusables: ['Lisdexamfetamine (Vyvanse, prodrug) vs dextroamphetamine (its active drug) vs mixed amphetamine salts (Adderall XR).'],
    classDifferentiators: 'The amphetamine PRODRUG — inactive until hydrolyzed in blood; lower misuse liability; once-daily.',
    examHooks: ['Which ADHD stimulant is an inactive prodrug converted to dextroamphetamine in the blood? (lisdexamfetamine)'],
    counsellingPoints: ['Take once each morning.', 'It is inactive until your body converts it — do not expect a faster effect by altering the capsule.', 'Store securely; still a controlled substance.', 'Never combine with an MAOI.'],
    vignettes: [
      {
        stem: 'A clinician chooses lisdexamfetamine over immediate-release dextroamphetamine partly for its lower misuse liability. What pharmacologic feature explains this?',
        options: ['It blocks dopamine reuptake without any release', 'It is an inactive prodrug requiring enzymatic conversion in the blood to active drug', 'It has no central nervous system penetration', 'It is metabolized entirely by CYP3A4'],
        answer: 'It is an inactive prodrug requiring enzymatic conversion in the blood to active drug',
        explanation: 'Lisdexamfetamine must be hydrolyzed (by RBC peptidases) to liberate dextroamphetamine. This rate-limited activation blunts the rapid "high" from snorting/injecting, lowering abuse liability.',
        testedFact: 'Lisdexamfetamine prodrug activation',
        source: { name: 'openFDA/DailyMed lisdexamfetamine label — clinical pharmacology', origin: 'openfda' },
      },
    ],
    _prov: ADHD_PROV,
  },

  amphetamine_salts: {
    pronunciation: 'am-FET-uh-meen salts',
    moa: 'Mixed amphetamine salts (≈3:1 dextro- to levo-amphetamine). Like all amphetamines, drives presynaptic RELEASE of dopamine and norepinephrine and blocks their reuptake. The l-isomer contributes relatively more peripheral noradrenergic (cardiovascular) effect.',
    receptorProfile: 'Presynaptic DA/NE release + reuptake inhibition; d- and l-enantiomer blend.',
    onsetOfEffect: 'Same-day; XR beads give an extended once-daily profile.',
    halfLife: 'd-amphetamine ~10 h, l-amphetamine ~13 h (l-isomer slightly longer).',
    metabolism: 'Hepatic CYP2D6 and oxidative deamination; renal excretion is urine-pH dependent.',
    approvedCanada: ['ADHD'],
    approvedPopulations: 'Children ≥6 y, adolescents, adults (XR formulation).',
    startingDose: 'XR 10 mg PO each morning (adults may start 20 mg).',
    titration: 'Increase by ~10 mg/day at weekly intervals to response.',
    maxDose: '~30 mg/day in children; adults individualized (higher in some indications).',
    frequencyTiming: 'Once daily in the morning (XR); the beaded design avoids a midday dose.',
    administrationNotes: 'XR capsule may be opened and sprinkled on applesauce; do not chew the beads.',
    commonSE: ['Decreased appetite / weight loss', 'Insomnia', 'Increased heart rate / blood pressure', 'Irritability / mood lability', 'Dry mouth', 'Headache'],
    seriousAE: ['Sudden cardiac death with structural heart disease', 'Hypertension / tachyarrhythmia', 'Growth suppression in children', 'Psychosis or mania (new or worsened)', 'New/worsening tics', 'Peripheral vasculopathy / Raynaud phenomenon', 'Dependence / misuse'],
    syndromes: ['Sympathomimetic toxicity', 'Stimulant-induced psychosis', 'Growth suppression'],
    overdoseLethality: 'Sympathomimetic crisis — hypertension, tachyarrhythmia, hyperthermia, agitation, seizures; supportive care, benzodiazepines, cooling.',
    baselineWorkup: ['Cardiac + family history of sudden death / structural disease', 'Baseline BP and heart rate', 'Height and weight (children)', 'Screen for psychosis/bipolar and misuse risk'],
    ongoingMonitoring: 'BP/HR each visit; growth in children; appetite, sleep, mood, tics; misuse/diversion.',
    majorDDI: ['MAOIs (hypertensive crisis — contraindicated)', 'Urinary alkalinizers (↑ levels) / acidifiers (↓ levels)', 'CYP2D6 inhibitors (may raise amphetamine exposure)', 'Other serotonergics / sympathomimetics'],
    contraindicatedCombos: ['MAOIs (during use or within 14 days of stopping)'],
    maoiWashout: 'Do not use with an MAOI or within 14 days of stopping one.',
    pregnancy: 'Limited data; amphetamine class — individualized risk/benefit.',
    pediatric: 'Effective once-daily XR option; monitor growth, appetite, sleep; controlled substance.',
    cardiac: 'Avoid in serious structural cardiac disease/arrhythmia; l-isomer adds noradrenergic cardiovascular load.',
    pearls: [
      'A 3:1 d:l-amphetamine blend — the l-component adds relatively more peripheral noradrenergic (cardiovascular) effect than pure dextroamphetamine.',
      'Mechanistically a releaser (plus reuptake block), so it shares amphetamine\'s MAOI contraindication and misuse potential.',
    ],
    mnemonics: ['"Mixed salts = mixed enantiomers" — d for the brain, l for the body (more peripheral NE).'],
    confusables: ['Mixed amphetamine salts (Adderall XR) vs lisdexamfetamine (prodrug) vs dextroamphetamine (pure d-isomer).'],
    classDifferentiators: 'd+l amphetamine blend; releaser + reuptake blocker; once-daily XR; controlled.',
    examHooks: ['Which ADHD product is a d:l-amphetamine salt mixture? (mixed amphetamine salts / Adderall XR)'],
    counsellingPoints: ['Take once each morning.', 'Store securely; controlled substance with misuse potential.', 'Report chest pain, palpitations, or new hallucinations.', 'Never combine with an MAOI.'],
    vignettes: [
      {
        stem: 'A patient on mixed amphetamine salts is also taking high-dose sodium bicarbonate for a GI complaint and develops worsening tachycardia and agitation. What is the most likely pharmacokinetic mechanism?',
        options: ['Urinary alkalinization reduces amphetamine excretion, raising drug levels', 'Bicarbonate blocks CYP2D6, lowering amphetamine levels', 'Bicarbonate displaces amphetamine from albumin', 'Sodium loading increases renal amphetamine clearance'],
        answer: 'Urinary alkalinization reduces amphetamine excretion, raising drug levels',
        explanation: 'Amphetamine is a weak base; alkaline urine increases reabsorption and reduces renal clearance, raising plasma levels and sympathomimetic toxicity. Acidifying the urine has the opposite effect.',
        testedFact: 'Urine-pH effect on amphetamine clearance',
        source: { name: 'openFDA/DailyMed mixed amphetamine salts label — drug interactions', origin: 'openfda' },
      },
    ],
    _prov: ADHD_PROV,
  },

  atomoxetine: {
    pronunciation: 'at-oh-MOX-uh-teen',
    moa: 'Selective NOREPINEPHRINE reuptake inhibitor (blocks NET). NON-stimulant. In the prefrontal cortex NET also clears dopamine, so it raises PFC DA/NE without increasing striatal/nucleus-accumbens dopamine → little reward/reinforcement and NO misuse potential.',
    receptorProfile: 'Selective NET blockade; negligible affinity for other transporters/receptors.',
    onsetOfEffect: 'Delayed — meaningful benefit over 2–4 weeks (not same-day), unlike stimulants.',
    halfLife: '~5 h in CYP2D6 extensive metabolizers; up to ~24 h in poor metabolizers.',
    metabolism: 'Hepatic CYP2D6 → 4-hydroxyatomoxetine (then glucuronidated). Poor metabolizers and strong 2D6 inhibitors (fluoxetine, paroxetine, quinidine) markedly raise exposure.',
    activeMetabolites: '4-hydroxyatomoxetine (active but rapidly conjugated; minor contribution).',
    approvedCanada: ['ADHD'],
    approvedPopulations: 'Children ≥6 y, adolescents, adults.',
    startingDose: 'Children ≤70 kg: ~0.5 mg/kg/day; adults/≥70 kg: 40 mg/day. Increase after ≥3 days.',
    titration: 'Titrate to a target of ~1.2 mg/kg/day (or 80 mg/day) after ≥2–4 weeks.',
    maxDose: '1.4 mg/kg/day or 100 mg/day, whichever is less.',
    frequencyTiming: 'Once daily (AM) or split AM/late afternoon; timing is not insomnia-critical the way stimulants are.',
    startStopCrossTaper: 'No physiologic taper required; benefit builds and wanes over weeks, not hours.',
    commonSE: ['Decreased appetite', 'Nausea / GI upset', 'Dry mouth', 'Insomnia or somnolence', 'Fatigue / dizziness', 'Increased heart rate / blood pressure', 'Urinary hesitancy; sexual dysfunction (adults)'],
    seriousAE: ['Hepatotoxicity (rare, potentially severe — stop for jaundice or markedly elevated LFTs, do not rechallenge)', 'Suicidal ideation, especially in children/adolescents (monitor closely early)', 'Increased heart rate / blood pressure', 'Priapism (rare)', 'Severe allergic/hypersensitivity reactions'],
    syndromes: ['Drug-induced liver injury', 'Emergent suicidality (youth)', 'Sympathomimetic-type cardiovascular effects (milder than stimulants)'],
    overdoseLethality: 'Generally lower acute lethality than stimulants; somnolence, agitation, tachycardia, and (rarely) seizures/QT reported — supportive care.',
    baselineWorkup: ['Baseline BP and heart rate; cardiac history', 'Height and weight (children)', 'Screen for suicidality; counsel family on early monitoring', 'Baseline LFTs are not mandated but liver history should be reviewed'],
    ongoingMonitoring: 'BP/HR and growth (children); mood and emergent suicidality especially in first months; LFTs if symptoms of hepatotoxicity (jaundice, dark urine, RUQ pain, pruritus).',
    majorDDI: ['MAOIs (contraindicated)', 'Strong CYP2D6 inhibitors (fluoxetine, paroxetine, quinidine) — raise atomoxetine levels (reduce dose / titrate slowly)', 'Other sympathomimetics/pressors (additive cardiovascular effects)', 'Salbutamol/high-dose beta-agonists (additive HR/BP)'],
    contraindicatedCombos: ['MAOIs (during use or within 14 days of stopping)', 'Narrow-angle glaucoma (per label)'],
    maoiWashout: 'Do not use with an MAOI or within 14 days of stopping one.',
    pregnancy: 'Limited human data; individualized risk/benefit.',
    pediatric: 'Non-stimulant option (useful with tics, anxiety, or misuse concerns). Monitor growth and, importantly, emergent suicidal ideation in the early weeks.',
    cardiac: 'Raises HR/BP modestly; caution with hypertension, tachyarrhythmia, or structural cardiac disease. Not associated with the stimulant sudden-death signal but still cardiovascular-active.',
    pearls: [
      'NON-stimulant, not a controlled substance and no misuse potential — the go-to when diversion/misuse is a concern.',
      'Works via prefrontal NET (which also clears DA there), so it lacks the striatal dopamine surge → 2–4 weeks to full effect.',
      'CYP2D6 poor metabolizers (or patients on fluoxetine/paroxetine) get much higher levels — titrate cautiously.',
    ],
    mnemonics: ['"atomoxetine = ADHD without the buzz" — NRI, no reward pathway hit, no misuse, but slow (weeks) to work.'],
    confusables: ['Atomoxetine (ADHD NRI) vs reboxetine (antidepressant NRI) vs duloxetine (SNRI).'],
    classDifferentiators: 'Non-stimulant selective NRI; slow (2–4 wk) onset; not controlled; CYP2D6-dependent; hepatotoxicity + youth suicidality signals.',
    examHooks: ['Which ADHD drug is a non-controlled selective NRI that takes weeks to work? (atomoxetine)', 'Atomoxetine + fluoxetine → what happens to atomoxetine levels? (rise, via CYP2D6 inhibition)'],
    counsellingPoints: ['This is not a stimulant — expect 2–4 weeks before full benefit; keep taking it daily.', 'Report yellowing of the skin/eyes, dark urine, or right-upper-abdomen pain (liver).', 'Watch for new or worsening thoughts of self-harm, especially early — seek help urgently.', 'Never combine with an MAOI.'],
    vignettes: [
      {
        stem: 'A 14-year-old with ADHD and comorbid depression is started on atomoxetine and simultaneously on fluoxetine. Two weeks later he has marked nausea, dizziness, and a resting HR of 105. What best explains the atomoxetine-related toxicity?',
        options: ['Fluoxetine induces atomoxetine metabolism, lowering levels', 'Fluoxetine inhibits CYP2D6, raising atomoxetine levels', 'Atomoxetine displaces fluoxetine from albumin', 'Both drugs block dopamine release'],
        answer: 'Fluoxetine inhibits CYP2D6, raising atomoxetine levels',
        explanation: 'Atomoxetine is cleared by CYP2D6; fluoxetine is a potent 2D6 inhibitor, so co-administration behaves like a poor-metabolizer state with higher atomoxetine exposure and more dose-related adverse effects. Dose reduction/slow titration is advised.',
        testedFact: 'Atomoxetine CYP2D6 interaction with fluoxetine',
        source: { name: 'openFDA/DailyMed atomoxetine label — drug interactions (CYP2D6)', origin: 'openfda' },
      },
    ],
    _prov: ADHD_PROV,
  },

  guanfacine: {
    pronunciation: 'GWAN-fuh-seen',
    moa: 'Selective α2A-adrenergic receptor AGONIST. NON-stimulant. Postsynaptic α2A stimulation on prefrontal pyramidal neurons strengthens working-memory/attention network connectivity. More α2A-selective than clonidine → relatively less sedation/hypotension for its effect (though both still occur).',
    receptorProfile: 'α2A-selective agonist (postsynaptic PFC action); weaker at α2B/α2C than clonidine.',
    onsetOfEffect: 'Gradual over ~1–2 weeks (non-stimulant).',
    halfLife: '~17 h (extended-release, Intuniv).',
    metabolism: 'Hepatic CYP3A4 — strong 3A4 inhibitors (ketoconazole) raise levels; inducers (rifampin, carbamazepine) lower them.',
    approvedCanada: ['ADHD (extended-release, as monotherapy or adjunct to a stimulant)'],
    offLabel: ['Tics / Tourette', 'Aggression / oppositional behaviour'],
    approvedPopulations: 'Children/adolescents 6–17 y (XR).',
    startingDose: 'XR 1 mg PO once daily.',
    titration: 'Increase by ≤1 mg/week to response and tolerability; weight-based dosing (~0.05–0.12 mg/kg/day).',
    maxDose: '4 mg/day (children 6–12 y); up to ~7 mg/day in adolescents by weight.',
    frequencyTiming: 'Once daily; may dose at bedtime if daytime sedation is limiting. Do NOT crush the XR tablet and avoid taking with a high-fat meal (raises exposure).',
    startStopCrossTaper: 'TAPER on discontinuation (e.g., decrease by 1 mg every 3–7 days) to avoid rebound hypertension; do not stop abruptly.',
    discontinuationSyndrome: 'Abrupt cessation → rebound hypertension, tachycardia, nervousness — taper.',
    commonSE: ['Somnolence / sedation', 'Fatigue', 'Hypotension', 'Bradycardia', 'Dizziness', 'Dry mouth', 'Headache / abdominal pain'],
    seriousAE: ['Hypotension, bradycardia and syncope', 'Rebound hypertension with abrupt discontinuation', 'Sedation impairing activities', 'QT considerations at high exposure'],
    syndromes: ['α2-agonist sedation/hypotension', 'Rebound hypertension on withdrawal', 'Bradyarrhythmia / syncope'],
    overdoseLethality: 'Bradycardia, hypotension, sedation/lethargy and respiratory depression; supportive care with cardiac monitoring. Pediatric ingestions can be significant.',
    baselineWorkup: ['Baseline BP and heart rate', 'Cardiac history / syncope; screen for conduction abnormalities', 'Height and weight (children)', 'Review concomitant antihypertensives and CNS depressants'],
    ongoingMonitoring: 'BP and HR at baseline, after titration, and periodically (watch for hypotension/bradycardia/syncope); sedation; growth in children; do not stop abruptly.',
    majorDDI: ['Strong CYP3A4 inhibitors (ketoconazole) — reduce guanfacine dose', 'CYP3A4 inducers (rifampin, carbamazepine) — may need higher dose', 'Other antihypertensives (additive hypotension/bradycardia)', 'CNS depressants / alcohol (additive sedation)'],
    contraindicatedCombos: ['Additive with other centrally-acting antihypertensives and sedatives — use caution (not an absolute contraindication)'],
    pregnancy: 'Limited data; individualized risk/benefit.',
    pediatric: 'Useful non-stimulant, particularly with tics or when a stimulant is insufficient/poorly tolerated; monitor BP/HR, sedation and growth. Abrupt stop → rebound hypertension.',
    cardiac: 'Causes bradycardia, hypotension and syncope; caution with heart block, bradycardia, syncope history, or other AV-nodal/hypotensive drugs.',
    pearls: [
      'α2A-SELECTIVE agonist — less sedating/hypotensive than clonidine for a given effect, and the only α2 agonist with a specific ADHD (XR) indication + stimulant-adjunct role.',
      'Metabolized by CYP3A4 — dose down with strong inhibitors, up with inducers; avoid crushing the XR tablet.',
      'Never stop abruptly — rebound hypertension (though generally milder than with clonidine).',
    ],
    mnemonics: ['"GuanfAcine = α2A" — the A-selective, less-sedating α2 agonist; taper to avoid rebound.'],
    confusables: ['Guanfacine (α2A-selective, longer-acting, less sedating) vs clonidine (less selective, more sedating, more rebound HTN).'],
    classDifferentiators: 'Non-stimulant α2A-selective agonist; ADHD/stimulant-adjunct indication; CYP3A4; sedation + hypotension + rebound HTN.',
    examHooks: ['Which non-stimulant α2A-selective agonist is approved as ADHD monotherapy or stimulant adjunct? (guanfacine XR)', 'Why taper guanfacine? (rebound hypertension)'],
    counsellingPoints: ['May cause drowsiness and low blood pressure/dizziness — rise slowly; use caution driving.', 'Do not stop suddenly — blood pressure can rebound; taper with your prescriber.', 'Swallow the XR tablet whole; do not take with a fatty meal.', 'Tell your prescriber about other blood-pressure or sedating medications.'],
    vignettes: [
      {
        stem: 'A 10-year-old on extended-release guanfacine for ADHD runs out of medication and stops it abruptly. Three days later he presents with headache, agitation, HR 120 and BP 150/95. What is the most likely explanation?',
        options: ['Stimulant intoxication', 'Rebound hypertension from abrupt α2-agonist withdrawal', 'Serotonin syndrome', 'Hypertensive crisis from a tyramine meal'],
        answer: 'Rebound hypertension from abrupt α2-agonist withdrawal',
        explanation: 'Sudden withdrawal of a centrally acting α2 agonist causes a surge in sympathetic outflow → rebound hypertension and tachycardia. Guanfacine (and clonidine) should be tapered rather than stopped abruptly.',
        testedFact: 'Guanfacine rebound hypertension on abrupt discontinuation',
        source: { name: 'openFDA/DailyMed guanfacine XR label — warnings/discontinuation', origin: 'openfda' },
      },
    ],
    _prov: ADHD_PROV,
  },

  clonidine: {
    pronunciation: 'KLON-i-deen',
    moa: 'Central α2-adrenergic receptor AGONIST (less α2A-selective than guanfacine; also acts at imidazoline receptors). Reduces central sympathetic outflow. In ADHD it is used especially with tics, aggression/impulsivity, or sleep-onset insomnia — and also treats hypertension and eases opioid/other withdrawal.',
    receptorProfile: 'Non-selective α2 agonist (α2A/2B/2C) + imidazoline agonism → more sedation and hypotension than guanfacine.',
    onsetOfEffect: 'Sedation/BP effect within hours; ADHD benefit builds over 1–2 weeks.',
    halfLife: '~12–16 h (immediate-release); extended-release (Kapvay, US) prolongs it.',
    metabolism: 'About half hepatic metabolism and half renally excreted unchanged — dose caution in renal impairment.',
    approvedCanada: ['Hypertension'],
    offLabel: ['ADHD (esp. with tics or sleep-onset insomnia)', 'Tics / Tourette', 'Opioid and other withdrawal', 'Menopausal flushing'],
    approvedPopulations: 'Adults (HTN); pediatric ADHD use is largely off-label in Canada.',
    startingDose: 'For ADHD/sleep, often 0.05 mg (50 mcg) PO at bedtime; titrate slowly.',
    titration: 'Increase gradually in divided doses; give the larger portion at bedtime.',
    maxDose: '~0.4 mg/day in divided doses for ADHD (individualized).',
    frequencyTiming: 'Often at bedtime (sedation aids sleep) ± divided dosing; more sedating and shorter-acting than guanfacine.',
    startStopCrossTaper: 'TAPER on discontinuation — abrupt withdrawal causes rebound hypertension (more pronounced than with guanfacine).',
    discontinuationSyndrome: 'Abrupt stop → rebound hypertension, tachycardia, agitation, sweating — taper over days.',
    administrationNotes: 'Transdermal weekly patch and oral forms exist; the ER oral form should not be crushed.',
    commonSE: ['Sedation (marked)', 'Dry mouth', 'Hypotension', 'Bradycardia', 'Dizziness', 'Constipation', 'Irritability on wearing off'],
    seriousAE: ['Profound bradycardia, hypotension, AV block', 'Rebound hypertension on abrupt withdrawal', 'Excessive sedation / CNS depression', 'Syncope'],
    syndromes: ['α2-agonist sedation/hypotension', 'Rebound hypertension on withdrawal (marked)', 'Bradyarrhythmia / AV block'],
    overdoseLethality: 'Dangerous — particularly in young children: CNS and respiratory depression, bradycardia, hypotension, miosis (mimics opioid toxicity). Can be lethal in small ingestions in toddlers; supportive care, cardiac monitoring; naloxone response is variable.',
    baselineWorkup: ['Baseline BP and heart rate', 'Cardiac history / syncope / conduction disease', 'Height and weight (children)', 'Review other antihypertensives and CNS depressants; assess safe storage (pediatric overdose risk)'],
    ongoingMonitoring: 'BP and HR at baseline and with titration (watch hypotension/bradycardia/syncope); sedation; growth in children; do not stop abruptly.',
    majorDDI: ['Other antihypertensives (additive hypotension/bradycardia)', 'Beta-blockers (worse rebound hypertension on clonidine withdrawal; bradycardia)', 'CNS depressants / alcohol (additive sedation)', 'Tricyclic antidepressants (may blunt clonidine\'s antihypertensive effect)'],
    contraindicatedCombos: ['Caution—not absolute—with beta-blockers (rebound HTN risk) and additive sedatives/hypotensives'],
    pregnancy: 'Limited data; individualized risk/benefit.',
    pediatric: 'Off-label for ADHD (helpful for tics, aggression, and sleep-onset insomnia); very sedating. Counsel on SECURE STORAGE — accidental pediatric ingestion can be life-threatening. Do not stop abruptly.',
    cardiac: 'Bradycardia, hypotension, AV block; caution with conduction disease, syncope, or other AV-nodal/hypotensive agents. Beta-blocker co-use worsens rebound hypertension on withdrawal.',
    pearls: [
      'Less α2-selective, shorter-acting and MORE sedating than guanfacine → favoured for sleep-onset insomnia and tics, often dosed at bedtime.',
      'Rebound hypertension on abrupt withdrawal is more marked than with guanfacine — always taper (worse if on a beta-blocker).',
      'Pediatric overdose is a classic lethal ingestion — CNS/respiratory depression, bradycardia and miosis mimic opioid toxicity.',
    ],
    mnemonics: ['"CLONidine = CALM and DOWN" — sedation + lowered BP/HR; and "don\'t drop it fast" (rebound HTN).'],
    confusables: ['Clonidine (less selective, sedating, more rebound HTN, shorter-acting) vs guanfacine (α2A-selective, less sedating).', 'Clonidine vs clozapine vs clonazepam — sound-alikes, entirely different drugs.'],
    classDifferentiators: 'Non-selective α2 agonist; most sedating; ADHD use mostly off-label (tics/sleep); marked rebound HTN; dangerous in pediatric overdose.',
    examHooks: ['Which α2 agonist is preferred for ADHD with sleep-onset insomnia and is more sedating? (clonidine)', 'A toddler with bradycardia, miosis and CNS depression after a home ingestion — think which cardiovascular drug? (clonidine)'],
    counsellingPoints: ['Expect drowsiness; take the main dose at bedtime and rise slowly (dizziness).', 'Do NOT stop suddenly — blood pressure can rebound dangerously; taper with your prescriber.', 'Store securely away from young children — accidental ingestion can be life-threatening.', 'Tell your prescriber about beta-blockers and other blood-pressure or sedating medicines.'],
    vignettes: [
      {
        stem: 'A 2-year-old is found lethargic after getting into a sibling\'s ADHD/tic medication. She has HR 55, BP 78/40, pinpoint pupils and shallow breathing. Which medication ingestion best fits this picture?',
        options: ['Methylphenidate', 'Clonidine', 'Atomoxetine', 'Lisdexamfetamine'],
        answer: 'Clonidine',
        explanation: 'Central α2-agonist (clonidine) overdose causes bradycardia, hypotension, CNS/respiratory depression and miosis — a picture that mimics opioid toxicity. It is a classic dangerous pediatric ingestion; stimulants would instead cause tachycardia, hypertension and agitation.',
        testedFact: 'Clonidine pediatric overdose (opioid-toxidrome mimic)',
        source: { name: 'openFDA/DailyMed clonidine label — overdosage', origin: 'openfda' },
      },
    ],
    _prov: ADHD_PROV,
  },
};
