// authored/adjunct.js — authored overlay for psychiatric adjuncts + movement-disorder agents.
//
// Mechanism/PK/dosing summaries + the pedagogical layer, grounded in established
// pharmacology and the fetched openFDA/monograph label sections. `_prov` declares which
// safety-critical fields the label text grounds; build.js attaches that source text and,
// where a field cannot be grounded, downgrades it to origin 'authored' + verifyFlag.
//
// CLASS THEME: these agents mostly treat the SIDE EFFECTS of psychotropics (or fill niche
// roles), so the highest-yield teaching point is matching the drug to the movement disorder:
//   • ACUTE DYSTONIA (oculogyric crisis, torticollis, hrs–days after a D2 blocker) and
//     DRUG-INDUCED PARKINSONISM  → ANTICHOLINERGIC (benztropine, procyclidine,
//     trihexyphenidyl) — they rebalance the striatal dopamine:acetylcholine ratio. They
//     add anticholinergic burden and DO NOT help (and can WORSEN) tardive dyskinesia.
//   • AKATHISIA → PROPRANOLOL (β-blocker) first-line, ± lower the antipsychotic dose /
//     add a benzodiazepine. Anticholinergics are largely ineffective for akathisia.
//   • TARDIVE DYSKINESIA → VMAT2 INHIBITOR (tetrabenazine, valbenazine, deutetrabenazine),
//     which deplete presynaptic dopamine (risking depression/parkinsonism). Amantadine
//     (dopaminergic + NMDA antagonist) is an adjunct for drug-induced parkinsonism / TD.
//   • Niche roles: propranolol (performance anxiety, lithium/SSRI tremor); prazosin
//     (α1 antagonist — PTSD nightmares, first-dose orthostasis); modafinil/armodafinil
//     (wakefulness); dexmedetomidine (α2 agonist — acute agitation).
// KEY EXAM CONTRAST: dystonia → anticholinergic; akathisia → propranolol; tardive
// dyskinesia → VMAT2 inhibitor (NOT an anticholinergic).

const ADJUNCT_PROV = {
  startingDose: 'openfda', maxDose: 'openfda', seriousAE: 'openfda', syndromes: 'openfda',
  majorDDI: 'openfda', contraindicatedCombos: 'openfda', pregnancy: 'openfda',
  overdoseLethality: 'openfda',
};

export default {
  benztropine: {
    pronunciation: 'BENZ-troh-peen',
    moa: 'Central muscarinic (anticholinergic) antagonist with antihistaminic and mild dopamine-reuptake-inhibiting properties; restores the striatal dopamine:acetylcholine balance disrupted by D2 blockade.',
    receptorProfile: 'Antimuscarinic (M1) + H1 antagonism; some dopamine reuptake inhibition.',
    onsetOfEffect: 'IM/IV relieves acute dystonia within minutes; oral effect over hours–days for parkinsonism.',
    halfLife: 'Not well characterized; long duration of action (once- or twice-daily oral dosing suffices).',
    metabolism: 'Hepatic (N-oxidation and N-dealkylation); not a major CYP interaction source — anticholinergic pharmacodynamics dominate.',
    approvedCanada: ['Drug-induced extrapyramidal disorders (acute dystonia, drug-induced parkinsonism)', 'Idiopathic Parkinson disease (adjunct)'],
    offLabel: ['Prophylaxis of dystonia in high-risk patients starting high-potency antipsychotics'],
    approvedPopulations: 'Adults; avoid in young children (susceptible to anticholinergic toxicity).',
    startingDose: 'Acute dystonia: 1–2 mg IM or IV, may repeat. EPS/parkinsonism: 1–2 mg PO once or twice daily.',
    titration: 'Titrate to effect; many patients need only 1–4 mg/day.',
    maxDose: '6 mg/day.',
    frequencyTiming: 'Once daily to BID (long-acting).',
    commonSE: ['Dry mouth', 'Blurred vision', 'Constipation', 'Urinary retention', 'Tachycardia', 'Memory impairment/confusion (esp. elderly)'],
    seriousAE: ['Anticholinergic delirium (agitation, hallucinations)', 'Hyperthermia from impaired sweating (heat stroke)', 'Paralytic ileus', 'Acute angle-closure glaucoma', 'Worsening of tardive dyskinesia'],
    syndromes: ['Anticholinergic toxidrome (hot, dry, red, blind, mad — “dry as a bone, red as a beet, mad as a hatter”)', 'Worsening tardive dyskinesia'],
    overdoseLethality: 'Anticholinergic toxidrome in overdose (delirium, hyperthermia, tachyarrhythmia, ileus); usually manageable but additive with other anticholinergics.',
    ongoingMonitoring: 'Bowel and bladder function; cognition (esp. elderly); reassess need — do not continue indefinitely once EPS resolve.',
    majorDDI: ['Additive anticholinergic burden with low-potency antipsychotics, TCAs, antihistamines, oxybutynin', 'Reduced GI motility can alter absorption of other drugs', 'Additive heat-intolerance/hyperthermia risk with other anticholinergics'],
    contraindicatedCombos: ['Other high anticholinergic-load agents in frail/elderly (additive delirium, ileus, retention)'],
    pregnancy: 'Limited data; use only if clearly needed.',
    lactation: 'May suppress lactation and cause infant anticholinergic effects; caution.',
    geriatric: 'High-risk — precipitates confusion, falls, constipation, retention; on Beers-type avoid lists. Prefer amantadine or dose reduction of the antipsychotic when possible.',
    pearls: [
      'First-line for ACUTE DYSTONIA (give IM/IV) and drug-induced parkinsonism — rebalances striatal ACh vs dopamine.',
      'Does NOT treat akathisia well and can WORSEN tardive dyskinesia (TD reflects dopamine hypersensitivity — blocking ACh unmasks it).',
      'Trades EPS for anticholinergic burden: dry mouth, constipation, urinary retention, cognitive impairment.',
    ],
    mnemonics: ['Anticholinergic toxidrome: “hot as a hare, dry as a bone, red as a beet, blind as a bat, mad as a hatter.”'],
    confusables: ['Benztropine (anticholinergic for EPS) vs benzatropine (same drug, INN spelling) vs bromocriptine (dopamine agonist for NMS).'],
    classDifferentiators: 'Anticholinergic that treats ACUTE DYSTONIA + drug-induced PARKINSONISM; ineffective for akathisia and CONTRAINDICATED-in-effect for tardive dyskinesia (worsens it). IM/IV route makes it the go-to rescue for acute dystonia.',
    examHooks: ['Oculogyric crisis / torticollis hours after starting haloperidol → give IM benztropine (or diphenhydramine).', 'Which EPS is NOT helped (and may be worsened) by benztropine? Tardive dyskinesia.'],
    counsellingPoints: ['Expect dry mouth, blurred vision, constipation — increase fluids/fibre.', 'Avoid overheating/strenuous exercise in hot weather (impaired sweating).', 'Report difficulty urinating, eye pain, or confusion.'],
    vignettes: [
      {
        stem: 'Six hours after his first dose of haloperidol, a 22-year-old develops a painful sustained upward deviation of the eyes and neck stiffness. What is the most appropriate immediate treatment?',
        options: ['Oral tetrabenazine', 'Intramuscular benztropine', 'Oral propranolol', 'Increase the haloperidol dose'],
        answer: 'Intramuscular benztropine',
        explanation: 'Acute dystonic reaction (oculogyric crisis) responds rapidly to a parenteral anticholinergic (benztropine or diphenhydramine). Propranolol is for akathisia and VMAT2 inhibitors (tetrabenazine) are for tardive dyskinesia — neither treats acute dystonia.',
        testedFact: 'Acute dystonia → anticholinergic',
        source: { name: 'openFDA/DailyMed benztropine label — indications (extrapyramidal disorders)', origin: 'openfda' },
      },
    ],
    _prov: ADJUNCT_PROV,
  },

  procyclidine: {
    pronunciation: 'proh-SY-kli-deen',
    moa: 'Central antimuscarinic (anticholinergic) agent; restores striatal dopamine:acetylcholine balance to relieve drug-induced extrapyramidal symptoms.',
    receptorProfile: 'Antimuscarinic; weaker antihistaminic action than benztropine.',
    onsetOfEffect: 'Oral effect over 30–60 min; parenteral relief of dystonia within minutes.',
    halfLife: '~12 hours.',
    metabolism: 'Hepatic; anticholinergic pharmacodynamics dominate interactions.',
    approvedCanada: ['Drug-induced extrapyramidal symptoms (dystonia, parkinsonism, akathisia adjunct)', 'Parkinsonism'],
    approvedPopulations: 'Adults.',
    startingDose: '2.5 mg PO three times daily.',
    titration: 'Increase by 2.5 mg/day every few days as tolerated.',
    maxDose: 'Up to ~20–30 mg/day in divided doses.',
    frequencyTiming: 'TID (shorter-acting than benztropine).',
    commonSE: ['Dry mouth', 'Blurred vision', 'Constipation', 'Urinary hesitancy', 'Dizziness'],
    seriousAE: ['Anticholinergic delirium', 'Urinary retention', 'Paralytic ileus', 'Angle-closure glaucoma', 'Worsening tardive dyskinesia'],
    syndromes: ['Anticholinergic toxidrome', 'Worsening tardive dyskinesia'],
    overdoseLethality: 'Anticholinergic toxidrome in overdose; additive with other anticholinergics.',
    ongoingMonitoring: 'Cognition, bowel/bladder function; reassess ongoing need.',
    majorDDI: ['Additive anticholinergic effects with TCAs, antihistamines, low-potency antipsychotics', 'Altered GI absorption of co-administered drugs'],
    contraindicatedCombos: ['Untreated narrow-angle glaucoma; significant GI/GU obstruction'],
    pregnancy: 'Limited data; use only if needed.',
    geriatric: 'Same anticholinergic cautions as benztropine — confusion, falls, retention.',
    pearls: [
      'Anticholinergic essentially interchangeable with benztropine for EPS; more often dosed TID (shorter-acting).',
      'Like all anticholinergics: helps acute dystonia and drug-induced parkinsonism, not akathisia, and can worsen tardive dyskinesia.',
    ],
    mnemonics: ['“ProCYCLIdine cycles the anticholinergic burden three times a day (TID).”'],
    confusables: ['Procyclidine vs prochlorperazine (an antiEMETIC/antipsychotic that CAUSES dystonia) vs procyclidine’s look-alike benztropine.'],
    classDifferentiators: 'Anticholinergic peer of benztropine/trihexyphenidyl; treats acute dystonia + parkinsonism, shorter-acting (TID). Not for akathisia; worsens TD.',
    examHooks: ['Anticholinergic option for drug-induced parkinsonism when benztropine is unavailable? Procyclidine or trihexyphenidyl.'],
    counsellingPoints: ['Same anticholinergic effects as related agents — dry mouth, constipation, blurred vision.', 'Do not stop abruptly if on it long-term (rebound cholinergic EPS).', 'Report urinary difficulty or confusion.'],
    vignettes: [
      {
        stem: 'A patient on a high-potency antipsychotic develops cogwheel rigidity, bradykinesia and a resting tremor (drug-induced parkinsonism). An anticholinergic is chosen. Which statement is correct?',
        options: [
          'It will also resolve any co-existing tardive dyskinesia',
          'Procyclidine can improve the parkinsonism but may unmask/worsen tardive dyskinesia',
          'It is first-line for akathisia',
          'It has no anticholinergic side effects',
        ],
        answer: 'Procyclidine can improve the parkinsonism but may unmask/worsen tardive dyskinesia',
        explanation: 'Anticholinergics treat drug-induced parkinsonism and acute dystonia but can worsen tardive dyskinesia and are not first-line for akathisia (propranolol is). They carry anticholinergic burden.',
        testedFact: 'Anticholinergic treats parkinsonism, worsens TD',
        source: { name: 'Procyclidine product monograph — extrapyramidal indications', origin: 'monograph' },
      },
    ],
    _prov: ADJUNCT_PROV,
  },

  trihexyphenidyl: {
    pronunciation: 'try-hex-ee-FEN-i-dill',
    moa: 'Central antimuscarinic (anticholinergic) agent; corrects the relative cholinergic excess in the striatum caused by D2 blockade, relieving EPS and parkinsonism.',
    receptorProfile: 'Antimuscarinic (M1) antagonist; some direct antispasmodic action.',
    onsetOfEffect: 'Oral effect within ~1 hour.',
    halfLife: 'Relatively short — given in divided doses.',
    metabolism: 'Hepatic hydroxylation; anticholinergic pharmacodynamics dominate.',
    approvedCanada: ['Drug-induced extrapyramidal symptoms', 'Parkinsonism (all forms — adjunct)'],
    approvedPopulations: 'Adults.',
    startingDose: '1 mg PO on day 1, increasing gradually.',
    titration: 'Increase by 2 mg every 3–5 days to usual 6–10 mg/day in divided doses.',
    maxDose: 'Up to ~15 mg/day in divided doses.',
    frequencyTiming: 'BID–QID (divided doses; shorter-acting).',
    commonSE: ['Dry mouth', 'Blurred vision', 'Constipation', 'Urinary retention', 'Dizziness', 'Nervousness/euphoria'],
    seriousAE: ['Anticholinergic delirium/psychosis', 'Angle-closure glaucoma', 'Paralytic ileus', 'Urinary retention', 'Worsening tardive dyskinesia'],
    syndromes: ['Anticholinergic toxidrome', 'Worsening tardive dyskinesia'],
    overdoseLethality: 'Anticholinergic toxidrome in overdose; additive with other anticholinergics.',
    ongoingMonitoring: 'Cognition, bowel/bladder; watch for misuse (euphoriant potential); reassess need.',
    majorDDI: ['Additive anticholinergic effects with TCAs, antihistamines, low-potency antipsychotics', 'Delays gastric emptying — alters absorption of other drugs'],
    contraindicatedCombos: ['Narrow-angle glaucoma; significant GI/GU obstruction'],
    pregnancy: 'Limited data; use only if needed.',
    geriatric: 'High anticholinergic risk (confusion, falls, retention); avoid where possible.',
    pearls: [
      'Anticholinergic for EPS/parkinsonism; notable for a euphoriant/hallucinogenic MISUSE potential (unlike other adjuncts) — watch for diversion.',
      'Same rule as its anticholinergic peers: helps dystonia + parkinsonism, not akathisia, worsens tardive dyskinesia.',
    ],
    mnemonics: ['“TriHEXYphenidyl — the anticholinergic that can HEX you into a high (euphoria/misuse).”'],
    confusables: ['Trihexyphenidyl (Artane) vs benztropine vs procyclidine — interchangeable anticholinergics; trihexyphenidyl is the one flagged for abuse potential.'],
    classDifferentiators: 'Anticholinergic peer of benztropine/procyclidine for dystonia + parkinsonism; distinctive for euphoriant misuse potential. Not for akathisia; worsens TD.',
    examHooks: ['Which EPS anticholinergic carries the most notable abuse/euphoriant potential? Trihexyphenidyl.'],
    counsellingPoints: ['Expect dry mouth, blurred vision, constipation.', 'Do not exceed the prescribed dose (misuse risk).', 'Avoid overheating; report urinary difficulty or confusion.'],
    vignettes: [
      {
        stem: 'A patient repeatedly requests dose increases of trihexyphenidyl beyond what their extrapyramidal symptoms warrant and describes feeling “high” on it. What property of this drug explains this behaviour?',
        options: ['Dopamine-releasing action', 'Anticholinergic euphoriant/hallucinogenic effect', 'Serotonergic action', 'Beta-adrenergic stimulation'],
        answer: 'Anticholinergic euphoriant/hallucinogenic effect',
        explanation: 'Trihexyphenidyl (and other anticholinergics) can produce euphoria and, at higher doses, anticholinergic delirium/hallucinations, giving it a misuse potential distinctive among EPS agents.',
        testedFact: 'Trihexyphenidyl anticholinergic misuse potential',
        source: { name: 'Trihexyphenidyl product monograph — abuse/CNS effects', origin: 'monograph' },
      },
    ],
    _prov: ADJUNCT_PROV,
  },

  propranolol: {
    pronunciation: 'proh-PRAN-oh-lol',
    moa: 'Non-selective β-adrenergic antagonist (β1 and β2); in psychiatry blunts peripheral adrenergic symptoms and central noradrenergic tone.',
    receptorProfile: 'β1 + β2 antagonist; lipophilic (crosses the blood–brain barrier).',
    onsetOfEffect: 'Akathisia may improve within hours–days; single dose blunts performance-anxiety symptoms within ~30–60 min.',
    halfLife: '~3–6 hours (immediate-release); long-acting formulation extends dosing.',
    metabolism: 'Hepatic, extensive first-pass; substrate of CYP2D6, CYP1A2, CYP2C19. Highly protein bound.',
    approvedCanada: ['Hypertension, angina, arrhythmia, migraine prophylaxis, essential tremor (cardiology/neurology labels)'],
    offLabel: ['Antipsychotic-induced AKATHISIA (first-line)', 'Performance/situational (“stage-fright”) anxiety', 'Lithium- or SSRI-induced tremor', 'Adjunct for PTSD hyperarousal (limited evidence)'],
    approvedPopulations: 'Adults.',
    startingDose: 'Akathisia: 10–20 mg PO BID–TID. Performance anxiety: 10–40 mg once, ~30–60 min before the event.',
    titration: 'Increase gradually for akathisia to ~40–80 (up to ~120) mg/day as tolerated by HR/BP.',
    maxDose: 'For akathisia, typically up to ~80–120 mg/day; limited by bradycardia/hypotension.',
    frequencyTiming: 'BID–TID (IR); PRN before a stressor for performance anxiety.',
    renalHepaticAdjustment: 'Reduce in significant hepatic impairment (high first-pass metabolism).',
    startStopCrossTaper: 'Do NOT stop abruptly after chronic use — rebound tachycardia/hypertension/angina; taper.',
    commonSE: ['Bradycardia', 'Hypotension/dizziness', 'Fatigue', 'Cold extremities', 'Vivid dreams/nightmares', 'Sexual dysfunction'],
    seriousAE: ['Bronchospasm (asthma/COPD)', 'Symptomatic bradycardia / high-degree AV block', 'Masking of hypoglycemia symptoms', 'Precipitation/worsening of heart failure'],
    syndromes: ['Beta-blockade bradycardia/hypotension', 'Bronchospasm', 'Rebound sympathetic surge on abrupt withdrawal'],
    overdoseLethality: 'Dangerous in overdose — bradycardia, hypotension, heart block, seizures and cardiogenic shock; membrane-stabilizing effects. (Antidotes: glucagon, high-dose insulin.)',
    baselineWorkup: ['Heart rate and blood pressure', 'Screen for asthma/COPD and bradyarrhythmia/AV block'],
    ongoingMonitoring: 'HR and BP; ask about wheeze; in diabetics warn about masked hypoglycemia.',
    majorDDI: ['Other AV-nodal blockers (verapamil, diltiazem, digoxin) — additive bradycardia/block', 'CYP2D6 inhibitors (fluoxetine, paroxetine, bupropion) raise propranolol levels', 'Insulin/sulfonylureas — masks hypoglycemia', 'Salbutamol/other β2-agonists — antagonized'],
    contraindicatedCombos: ['Severe asthma/bronchospasm', 'Sinus bradycardia, second/third-degree heart block', 'Decompensated heart failure', 'Cardiogenic shock'],
    pregnancy: 'Used when needed; monitor for fetal bradycardia/growth and neonatal hypoglycemia near term.',
    lactation: 'Low levels in milk; generally compatible with monitoring.',
    geriatric: 'Watch bradycardia, hypotension, falls, fatigue.',
    cardiac: 'Bradycardia/hypotension are the dose-limiting effects; contraindicated with high-degree AV block.',
    pearls: [
      'FIRST-LINE for antipsychotic-induced AKATHISIA (± lower the antipsychotic dose or add a short-course benzodiazepine) — anticholinergics do NOT reliably help akathisia.',
      'Also the classic agent for performance/“stage-fright” anxiety and for lithium/SSRI (and essential) tremor.',
      'Caution or avoid in asthma/COPD, bradycardia, AV block, decompensated heart failure; never stop abruptly.',
    ],
    mnemonics: ['“A for Akathisia, A for Adrenergic block” — propranolol calms the restless legs of akathisia and the racing heart of stage fright.'],
    confusables: ['Propranolol (akathisia, non-selective) vs metoprolol/atenolol (β1-selective — preferred if lung disease) vs prazosin (α1 blocker for PTSD nightmares).'],
    classDifferentiators: 'The β-blocker of the group: treats AKATHISIA and adrenergic/tremor symptoms — the one EPS it targets is akathisia (dystonia → anticholinergic; TD → VMAT2 inhibitor). Non-selective → asthma caution.',
    examHooks: ['Inner restlessness / inability to sit still on an antipsychotic (akathisia) → propranolol (± dose reduction).', 'Fine tremor on lithium or an SSRI → propranolol.'],
    counsellingPoints: ['For stage fright, take ~30–60 min before the event.', 'Do not stop suddenly — taper.', 'Report wheezing; rise slowly to avoid dizziness.', 'Diabetics: beta-blockers can hide low-blood-sugar warning signs.'],
    vignettes: [
      {
        stem: 'Two weeks after starting risperidone, a patient reports an inner restlessness and a constant urge to move, pacing and shifting weight while seated. Which is the most appropriate first-line pharmacologic treatment?',
        options: ['Benztropine', 'Propranolol', 'Tetrabenazine', 'Increase the risperidone dose'],
        answer: 'Propranolol',
        explanation: 'This is akathisia. First-line management is dose reduction of the offending antipsychotic and/or a beta-blocker such as propranolol (± a benzodiazepine). Anticholinergics (benztropine) are for dystonia/parkinsonism, and VMAT2 inhibitors (tetrabenazine) are for tardive dyskinesia.',
        testedFact: 'Akathisia → propranolol',
        source: { name: 'CANMAT/CPA antipsychotic side-effect management — akathisia', origin: 'canmat' },
      },
    ],
    _prov: ADJUNCT_PROV,
  },

  prazosin: {
    pronunciation: 'PRAY-zoh-sin',
    moa: 'Selective α1-adrenergic receptor antagonist; centrally blunts noradrenergic activation implicated in trauma nightmares, and peripherally causes vasodilation.',
    receptorProfile: 'α1 antagonist (crosses the blood–brain barrier).',
    onsetOfEffect: 'Nightmare/sleep benefit builds over days–weeks with titration.',
    halfLife: '~2–3 hours (short; dosed at bedtime for nightmares).',
    metabolism: 'Hepatic (demethylation and conjugation); highly protein bound.',
    approvedCanada: ['Hypertension (cardiology label)'],
    offLabel: ['PTSD-associated NIGHTMARES and sleep disruption', 'Benign prostatic hyperplasia symptoms'],
    approvedPopulations: 'Adults.',
    startingDose: 'PTSD nightmares: 1 mg PO at bedtime (first-dose orthostasis risk).',
    titration: 'Increase gradually (e.g., to 2–6 mg qHS, higher in some, often higher effective doses in men) as BP tolerates.',
    maxDose: 'Individualized by response and orthostatic tolerance (commonly up to ~10–15 mg/day for nightmares).',
    frequencyTiming: 'At bedtime for nightmares (may add a daytime dose).',
    commonSE: ['Dizziness/orthostatic hypotension', 'Headache', 'Drowsiness', 'Nasal congestion', 'Palpitations'],
    seriousAE: ['First-dose syncope (marked orthostatic hypotension)', 'Priapism (rare)', 'Intraoperative floppy iris syndrome (cataract surgery)'],
    syndromes: ['First-dose orthostatic hypotension/syncope', 'Reflex tachycardia'],
    overdoseLethality: 'Overdose → hypotension; generally supportive care.',
    ongoingMonitoring: 'Orthostatic blood pressure, especially with initiation and dose increases; nightmare/sleep response.',
    majorDDI: ['PDE5 inhibitors (sildenafil, tadalafil) — additive hypotension', 'Other antihypertensives/vasodilators — additive hypotension', 'Beta-blockers — accentuate first-dose hypotension'],
    contraindicatedCombos: ['Combined with PDE5 inhibitors → risk of symptomatic hypotension'],
    pregnancy: 'Limited data; use only if clearly needed.',
    geriatric: 'Orthostasis and fall risk — start low, titrate slowly.',
    cardiac: 'Orthostatic hypotension is the key hazard; warn about the first dose.',
    pearls: [
      'Off-label go-to for PTSD NIGHTMARES/trauma-related sleep disruption — dose at bedtime and titrate up.',
      'FIRST-DOSE PHENOMENON: marked orthostatic hypotension/syncope — start 1 mg at bedtime and warn the patient.',
      'Flag intraoperative floppy iris syndrome to ophthalmology before cataract surgery.',
    ],
    mnemonics: ['“PRAZosin for the PTSD dreams; the first dose can make you PLOP (orthostatic drop) — take it lying down at night.”'],
    confusables: ['Prazosin (α1 blocker — PTSD nightmares) vs propranolol (β-blocker — akathisia/tremor) vs clonidine (α2 agonist).'],
    classDifferentiators: 'The α1 antagonist of the group — a targeted PTSD-nightmare agent, not an EPS drug. Defining hazard is first-dose orthostatic hypotension (contrast propranolol’s bronchospasm/bradycardia).',
    examHooks: ['Combat veteran with recurrent trauma nightmares → prazosin at bedtime.', 'Which adjunct causes a “first-dose” orthostatic syncope? Prazosin.'],
    counsellingPoints: ['Take the first dose at bedtime and get up slowly — dizziness/fainting can occur.', 'Rise slowly from sitting/lying, especially early in treatment.', 'Tell your eye surgeon you take prazosin before cataract surgery.'],
    vignettes: [
      {
        stem: 'A 34-year-old veteran with PTSD reports recurrent vivid combat nightmares causing severe sleep disruption despite an SSRI. Which adjunctive medication most specifically targets the nightmares?',
        options: ['Propranolol', 'Prazosin', 'Benztropine', 'Modafinil'],
        answer: 'Prazosin',
        explanation: 'Prazosin, an α1-adrenergic antagonist, reduces trauma-related nightmares and sleep disturbance in PTSD; start low at bedtime because of first-dose orthostatic hypotension.',
        testedFact: 'Prazosin for PTSD nightmares',
        source: { name: 'CANMAT/ISTSS PTSD pharmacotherapy — prazosin for nightmares', origin: 'canmat' },
      },
    ],
    _prov: ADJUNCT_PROV,
  },

  modafinil: {
    pronunciation: 'moh-DAF-i-nil',
    moa: 'Wakefulness-promoting agent; mechanism incompletely understood — weak dopamine-transporter inhibition (raises synaptic dopamine) plus downstream effects on orexin, histamine and noradrenergic systems.',
    receptorProfile: 'Atypical; low affinity for classic monoamine receptors — not a classic stimulant.',
    onsetOfEffect: 'Promotes wakefulness within ~1–2 hours; peak ~2–4 h.',
    halfLife: '~12–15 hours (once-daily dosing).',
    metabolism: 'Hepatic; CYP3A4 substrate. INDUCES CYP3A4 (reduces hormonal contraceptive efficacy) and inhibits CYP2C19.',
    approvedCanada: ['Narcolepsy (excessive daytime sleepiness)', 'Obstructive sleep apnea (adjunct to CPAP)', 'Shift-work sleep disorder'],
    offLabel: ['Adjunct for fatigue/hypersomnia', 'Adjunct in depression (residual fatigue/sleepiness)', 'ADHD (limited/second-line)'],
    approvedPopulations: 'Adults.',
    startingDose: '200 mg PO once daily in the morning (shift-work: ~1 h before the shift).',
    titration: 'Usually 200 mg/day; some use up to 400 mg/day (limited added benefit).',
    maxDose: '400 mg/day.',
    frequencyTiming: 'Morning (single dose); avoid late dosing (insomnia).',
    renalHepaticAdjustment: 'Reduce dose in severe hepatic impairment.',
    commonSE: ['Headache (most common)', 'Nausea', 'Anxiety/nervousness', 'Insomnia', 'Dry mouth', 'Palpitations'],
    seriousAE: ['Serious rash — Stevens-Johnson syndrome / TEN / DRESS (rare)', 'Psychiatric effects (anxiety, mania, psychosis, suicidal ideation)', 'Cardiovascular events (avoid with recent MI / unstable angina / LVH)'],
    syndromes: ['Serious cutaneous hypersensitivity (SJS/TEN/DRESS)', 'Stimulant-like psychiatric activation'],
    overdoseLethality: 'Overdose → agitation, insomnia, tachycardia, hypertension; generally lower toxicity than classic stimulants.',
    ongoingMonitoring: 'Blood pressure/heart rate; watch for rash (stop immediately) and emergent psychiatric symptoms.',
    majorDDI: ['Hormonal contraceptives — REDUCED efficacy via CYP3A4 induction (use additional/backup contraception, during and ~1 month after)', 'CYP2C19 substrates (e.g., phenytoin, diazepam, propranolol) — levels rise', 'CYP3A4 substrates (e.g., cyclosporine) — levels fall', 'Warfarin — monitor INR'],
    contraindicatedCombos: ['Known hypersensitivity/prior modafinil-related rash'],
    pregnancy: 'Avoid — signals of intrauterine growth restriction/congenital anomalies; effective contraception advised.',
    lactation: 'Limited data; caution.',
    geriatric: 'Reduce dose; slower clearance.',
    cardiac: 'Can raise HR/BP; avoid with recent MI, unstable angina, or significant LVH.',
    pearls: [
      'Wakefulness-promoter for narcolepsy / OSA (adjunct) / shift-work disorder — NOT a first-line ADHD or antidepressant drug.',
      'CYP3A4 INDUCER → LOWERS ORAL CONTRACEPTIVE efficacy: counsel backup contraception during and for ~1 month after use (high-yield).',
      'Controlled substance (Schedule IV in the US) with misuse potential; less activating than amphetamines.',
    ],
    mnemonics: ['“ModafiNIL leaves your birth control at NIL” — CYP3A4 induction cuts oral-contraceptive efficacy.'],
    confusables: ['Modafinil vs armodafinil (its longer-acting R-enantiomer) vs classic stimulants (methylphenidate/amphetamine).'],
    classDifferentiators: 'Wakefulness agent (not an EPS drug) — treats excessive sleepiness. Its defining interaction is CYP3A4 induction reducing contraceptive efficacy.',
    examHooks: ['Woman on the pill started on modafinil for narcolepsy → counsel backup contraception (CYP3A4 induction).', 'First-line pharmacotherapy for excessive daytime sleepiness in narcolepsy? Modafinil.'],
    counsellingPoints: ['Take in the morning to avoid insomnia.', 'If on hormonal birth control, use an additional method during and for ~1 month after (reduced efficacy).', 'Stop and seek care if any rash develops.'],
    vignettes: [
      {
        stem: 'A 28-year-old woman with narcolepsy is started on modafinil. She uses a combined oral contraceptive as her only method of contraception. What is the most important counselling point?',
        options: [
          'The contraceptive will increase modafinil levels dangerously',
          'Modafinil may reduce the contraceptive’s efficacy — add a backup method',
          'She must stop the contraceptive entirely',
          'No interaction is expected',
        ],
        answer: 'Modafinil may reduce the contraceptive’s efficacy — add a backup method',
        explanation: 'Modafinil induces CYP3A4, lowering plasma levels of hormonal contraceptives and reducing their efficacy; patients should use an additional or alternative method during treatment and for about a month after stopping.',
        testedFact: 'Modafinil CYP3A4 induction ↓ contraceptive efficacy',
        source: { name: 'openFDA/DailyMed modafinil label — drug interactions (contraceptives)', origin: 'openfda' },
      },
    ],
    _prov: ADJUNCT_PROV,
  },

  armodafinil: {
    pronunciation: 'ar-moh-DAF-i-nil',
    moa: 'Wakefulness-promoting agent; the longer-acting R-(−)-enantiomer of modafinil, with the same incompletely understood mechanism (weak DAT inhibition + orexin/histamine/noradrenergic effects).',
    receptorProfile: 'Atypical (as modafinil); not a classic stimulant.',
    onsetOfEffect: 'Wakefulness within ~1–2 h; sustained plasma levels later in the day than modafinil.',
    halfLife: '~13–15 hours; being the single R-enantiomer, effective concentrations persist longer into the day than racemic modafinil.',
    metabolism: 'Hepatic; CYP3A4 substrate. Induces CYP3A4 (↓ contraceptive efficacy) and inhibits CYP2C19 — same interaction profile as modafinil.',
    approvedCanada: [],
    offLabel: ['(Same indications as modafinil where available: narcolepsy, OSA adjunct, shift-work disorder)'],
    approvedPopulations: 'Adults.',
    startingDose: '150 mg PO once daily in the morning (shift-work: ~1 h before shift).',
    titration: 'Usually 150–250 mg/day.',
    maxDose: '250 mg/day.',
    frequencyTiming: 'Once daily, morning.',
    commonSE: ['Headache', 'Nausea', 'Insomnia', 'Anxiety', 'Dry mouth', 'Dizziness'],
    seriousAE: ['Serious rash — SJS/TEN/DRESS (rare)', 'Psychiatric activation (anxiety, mania, psychosis)', 'Cardiovascular effects'],
    syndromes: ['Serious cutaneous hypersensitivity', 'Stimulant-like activation'],
    overdoseLethality: 'Overdose → agitation, insomnia, tachycardia, hypertension; lower toxicity than classic stimulants.',
    ongoingMonitoring: 'BP/HR; watch for rash and psychiatric symptoms.',
    majorDDI: ['Hormonal contraceptives — reduced efficacy (CYP3A4 induction; use backup)', 'CYP2C19 substrates rise', 'CYP3A4 substrates fall', 'Warfarin — monitor INR'],
    contraindicatedCombos: ['Prior modafinil/armodafinil hypersensitivity or rash'],
    pregnancy: 'Avoid; effective contraception advised.',
    geriatric: 'Reduce dose; slower clearance.',
    cardiac: 'Can raise HR/BP; avoid with recent MI/unstable angina.',
    pearls: [
      'US-only — for awareness (Nuvigil): the R-enantiomer of modafinil; NOT marketed in Canada (the pipeline flags Canadian availability itself).',
      'Once-daily like modafinil but sustains wakefulness longer into the day (single enantiomer); same CYP3A4-induction/contraceptive caveat.',
      'Controlled substance (Schedule IV in the US) with misuse potential.',
    ],
    mnemonics: ['“ARmodafinil = the R-enantiomer that Runs longer” — one enantiomer, longer daytime coverage.'],
    confusables: ['Armodafinil (R-enantiomer, US-only) vs modafinil (racemic, available in Canada).'],
    classDifferentiators: 'Enantiomer refinement of modafinil — longer effective daytime levels; US-only. Same wakefulness role and same contraceptive-efficacy interaction.',
    examHooks: ['How does armodafinil differ from modafinil? It is the purified longer-acting R-enantiomer (US-only).'],
    counsellingPoints: ['Take in the morning.', 'Use backup contraception if on hormonal birth control.', 'Stop and seek care if a rash develops.'],
    vignettes: [
      {
        stem: 'Armodafinil differs pharmacologically from modafinil primarily in which way?',
        options: [
          'It is a classic amphetamine-type stimulant',
          'It is the single R-(−)-enantiomer with longer-sustained daytime levels',
          'It has no effect on CYP3A4',
          'It is a dopamine antagonist',
        ],
        answer: 'It is the single R-(−)-enantiomer with longer-sustained daytime levels',
        explanation: 'Armodafinil is the R-enantiomer of racemic modafinil; its longer effective half-life sustains wakefulness later in the day. It shares modafinil’s CYP3A4-inducing (contraceptive-lowering) interaction. It is US-only.',
        testedFact: 'Armodafinil = R-enantiomer of modafinil',
        source: { name: 'openFDA/DailyMed armodafinil label — clinical pharmacology', origin: 'openfda' },
      },
    ],
    _prov: ADJUNCT_PROV,
  },

  tetrabenazine: {
    pronunciation: 'tet-ra-BEN-a-zeen',
    moa: 'Reversible VMAT2 (vesicular monoamine transporter type 2) inhibitor — blocks packaging of monoamines into presynaptic vesicles, depleting dopamine (and serotonin/norepinephrine) to reduce hyperkinetic movements.',
    receptorProfile: 'VMAT2 inhibition (presynaptic dopamine depletion); weak D2 affinity via metabolites.',
    onsetOfEffect: 'Chorea/dyskinesia improve over days–weeks with titration.',
    halfLife: 'Parent short; active dihydrotetrabenazine (HTBZ) metabolites (~4–8 h) drive the effect.',
    metabolism: 'Carbonyl reductase → active α- and β-HTBZ; further metabolized by CYP2D6 → reduce dose with CYP2D6 inhibitors and in poor metabolizers.',
    approvedCanada: ['Hyperkinetic movement disorders — Huntington chorea; hemiballismus; tardive dyskinesia; Tourette/tics (Nitoman label)'],
    offLabel: ['Tardive dyskinesia (where labelled elsewhere as a VMAT2 indication)'],
    approvedPopulations: 'Adults.',
    startingDose: '12.5 mg PO once–twice daily; titrate slowly.',
    titration: 'Increase by 12.5 mg every few days to effect/tolerability.',
    maxDose: 'Up to ~75–100 mg/day (lower with CYP2D6 inhibitors / poor metabolizers).',
    frequencyTiming: 'Divided doses (BID–TID); short-acting active metabolites.',
    renalHepaticAdjustment: 'Contraindicated in hepatic impairment (per US labelling).',
    commonSE: ['Sedation/somnolence', 'Depression', 'Parkinsonism (bradykinesia, rigidity)', 'Akathisia', 'Insomnia', 'Nausea'],
    seriousAE: ['DEPRESSION and SUICIDALITY', 'Neuroleptic malignant syndrome (rare)', 'QT prolongation', 'Drug-induced parkinsonism', 'Orthostatic hypotension'],
    syndromes: ['Dopamine-depletion depression/suicidality', 'Parkinsonism', 'QT prolongation', 'NMS (rare)'],
    overdoseLethality: 'Overdose → sedation, hypotension, sweating, tremor; QT effects — supportive care.',
    baselineWorkup: ['Screen for depression/suicidality', 'ECG (QT) if cardiac risk', 'CYP2D6 status if high-dose planned'],
    ongoingMonitoring: 'Depression/suicidality at each visit; parkinsonism/akathisia; QT if risk factors.',
    majorDDI: ['CYP2D6 inhibitors (fluoxetine, paroxetine, bupropion) — raise HTBZ levels (reduce dose)', 'Other QT-prolonging drugs — additive', 'Dopamine antagonists (antipsychotics) — additive parkinsonism/NMS risk', 'MAOIs — avoid'],
    contraindicatedCombos: ['Active depression / suicidality (untreated)', 'Hepatic impairment', 'MAOIs', 'Concurrent reserpine/other VMAT2 inhibitor'],
    pregnancy: 'Limited data; use only if clearly needed.',
    geriatric: 'Sensitive to sedation, parkinsonism, orthostasis, depression.',
    cardiac: 'QT prolongation — caution with other QT drugs / electrolyte abnormalities.',
    pearls: [
      'VMAT2 inhibitor that DEPLETES dopamine to treat hyperkinetic movements (Huntington chorea, tardive dyskinesia) — the mechanistic OPPOSITE of what causes drug-induced parkinsonism.',
      'Because it depletes dopamine it can CAUSE depression/suicidality and parkinsonism — screen mood and avoid in active depression.',
      'Canadian brand is Nitoman; CYP2D6 metabolizes the active HTBZ metabolites, so 2D6 inhibitors/poor metabolizers need dose reduction.',
    ],
    mnemonics: ['“TETRAbenazine TAKES away dopamine (VMAT2) → can take away mood too (depression).”'],
    confusables: ['Tetrabenazine (Canada: Nitoman) vs deutetrabenazine/valbenazine (US-only VMAT2 inhibitors) vs reserpine (older non-selective VMAT inhibitor).'],
    classDifferentiators: 'VMAT2 inhibitor for TARDIVE DYSKINESIA / Huntington chorea (dopamine depletion) — the correct answer for TD where anticholinergics are WRONG. Canada-available (Nitoman); its dopamine depletion risks depression/parkinsonism/QT.',
    examHooks: ['Persistent orofacial/lingual choreoathetoid movements (tardive dyskinesia) → VMAT2 inhibitor (tetrabenazine), NOT an anticholinergic.', 'Which movement-disorder drug can precipitate depression/suicidality by depleting dopamine? Tetrabenazine.'],
    counsellingPoints: ['Report low mood or any thoughts of self-harm immediately (dopamine depletion can worsen depression).', 'May cause drowsiness and slowed movements — avoid driving until you know your response.', 'Rise slowly (orthostatic dizziness).'],
    vignettes: [
      {
        stem: 'A patient on long-term antipsychotic therapy develops persistent involuntary lip-smacking, tongue protrusion and choreiform finger movements that continue despite lowering the antipsychotic. Which medication specifically treats this condition?',
        options: ['Benztropine', 'Propranolol', 'Tetrabenazine', 'Trihexyphenidyl'],
        answer: 'Tetrabenazine',
        explanation: 'This is tardive dyskinesia. VMAT2 inhibitors (tetrabenazine, and US-only valbenazine/deutetrabenazine) deplete presynaptic dopamine and are the specific treatment. Anticholinergics (benztropine, trihexyphenidyl) can WORSEN TD; propranolol is for akathisia.',
        testedFact: 'Tardive dyskinesia → VMAT2 inhibitor',
        source: { name: 'openFDA/DailyMed tetrabenazine label — indication (hyperkinetic movement disorder)', origin: 'openfda' },
      },
    ],
    _prov: ADJUNCT_PROV,
  },

  valbenazine: {
    pronunciation: 'val-BEN-a-zeen',
    moa: 'Selective VMAT2 inhibitor (a purified/prodrug relative of tetrabenazine); depletes presynaptic dopamine to reduce tardive-dyskinesia movements.',
    receptorProfile: 'VMAT2 inhibition; hydrolyzes to the active metabolite (the α-HTBZ isomer).',
    onsetOfEffect: 'TD improvement over weeks.',
    halfLife: '~15–22 hours (once-daily dosing).',
    metabolism: 'Hydrolysis to active metabolite; further via CYP3A4 (and CYP2D6). QT prolongation possible.',
    approvedCanada: [],
    offLabel: ['(US indication: tardive dyskinesia)'],
    approvedPopulations: 'Adults.',
    startingDose: '40 mg PO once daily.',
    titration: 'Increase to 80 mg once daily after ~1 week; 40 mg may be maintained if needed.',
    maxDose: '80 mg/day (lower with strong CYP3A4/2D6 issues).',
    frequencyTiming: 'Once daily (its key convenience advantage over tetrabenazine).',
    commonSE: ['Somnolence/sedation', 'Fatigue', 'Dry mouth', 'Balance/gait disturbance', 'Headache'],
    seriousAE: ['QT prolongation', 'Parkinsonism', 'Somnolence', 'Depression (class effect of dopamine depletion)'],
    syndromes: ['QT prolongation', 'Parkinsonism', 'Dopamine-depletion mood effects'],
    overdoseLethality: 'Limited data; expect sedation and QT effects — supportive care.',
    baselineWorkup: ['Consider ECG (QT) if cardiac risk'],
    ongoingMonitoring: 'Sedation, parkinsonism, mood; QT if risk factors.',
    majorDDI: ['Strong CYP3A4 inducers reduce efficacy; strong CYP3A4/2D6 inhibitors raise levels', 'Other QT-prolonging drugs — additive', 'MAOIs — avoid'],
    contraindicatedCombos: ['Congenital long-QT / arrhythmias', 'MAOIs'],
    pregnancy: 'Limited data; avoid unless clearly needed.',
    cardiac: 'QT prolongation — caution with QT drugs.',
    pearls: [
      'US-only — for awareness (Ingrezza): VMAT2 inhibitor approved for tardive dyskinesia; NOT marketed in Canada (pipeline flags availability).',
      'Key advantage over tetrabenazine: ONCE-DAILY dosing and generally better tolerability.',
      'Same class caveats: parkinsonism, somnolence, QT, and dopamine-depletion mood effects.',
    ],
    mnemonics: ['“VALbenazine = VALue of once-daily” — the convenient once-daily VMAT2 inhibitor for TD.'],
    confusables: ['Valbenazine vs deutetrabenazine (both US-only TD agents) vs tetrabenazine (Canada-available).'],
    classDifferentiators: 'Once-daily VMAT2 inhibitor for tardive dyskinesia; US-only. Simpler dosing than tetrabenazine; shares dopamine-depletion/QT profile.',
    examHooks: ['Which VMAT2 inhibitor for TD is dosed once daily? Valbenazine (US-only).'],
    counsellingPoints: ['Take once daily as prescribed.', 'Report drowsiness affecting driving.', 'Report palpitations/fainting (QT).'],
    vignettes: [
      {
        stem: 'Among the VMAT2 inhibitors used for tardive dyskinesia, which is characterized by once-daily dosing (though it is not marketed in Canada)?',
        options: ['Tetrabenazine', 'Valbenazine', 'Benztropine', 'Amantadine'],
        answer: 'Valbenazine',
        explanation: 'Valbenazine (US-only) is a VMAT2 inhibitor dosed once daily for tardive dyskinesia, offering simpler dosing than tetrabenazine (BID–TID). Benztropine and amantadine are not VMAT2 inhibitors.',
        testedFact: 'Valbenazine once-daily VMAT2 inhibitor for TD',
        source: { name: 'openFDA/DailyMed valbenazine label — dosage (once daily)', origin: 'openfda' },
      },
    ],
    _prov: ADJUNCT_PROV,
  },

  deutetrabenazine: {
    pronunciation: 'DOO-teh-tra-BEN-a-zeen',
    moa: 'Deuterated form of tetrabenazine — a VMAT2 inhibitor; carbon-deuterium bonds slow metabolism of the active HTBZ metabolites, giving steadier levels and twice-daily dosing.',
    receptorProfile: 'VMAT2 inhibition (presynaptic dopamine depletion), via active deuterated HTBZ metabolites.',
    onsetOfEffect: 'Chorea/TD improve over weeks with titration.',
    halfLife: 'Deuteration prolongs the active-metabolite half-life (~9–10 h) versus tetrabenazine → BID dosing with fewer peak-related effects.',
    metabolism: 'Carbonyl reductase to deuterated α-/β-HTBZ; CYP2D6 downstream (reduce dose with strong 2D6 inhibitors / poor metabolizers).',
    approvedCanada: [],
    offLabel: ['(US indications: tardive dyskinesia; chorea of Huntington disease)'],
    approvedPopulations: 'Adults.',
    startingDose: '6 mg PO once daily (Huntington chorea) / 12 mg/day divided (tardive dyskinesia) — titrate slowly.',
    titration: 'Increase weekly by 6 mg/day to effect.',
    maxDose: 'Up to ~48 mg/day (lower with strong CYP2D6 inhibitors / poor metabolizers).',
    frequencyTiming: 'Twice daily with food (deuteration allows BID vs tetrabenazine’s more frequent dosing).',
    commonSE: ['Somnolence', 'Fatigue', 'Diarrhea/dry mouth', 'Insomnia', 'Akathisia'],
    seriousAE: ['Depression/suicidality (class effect)', 'Parkinsonism', 'QT prolongation', 'NMS (rare)', 'Akathisia/restlessness'],
    syndromes: ['Dopamine-depletion depression/suicidality', 'Parkinsonism', 'QT prolongation'],
    overdoseLethality: 'Expect sedation, hypotension, QT effects — supportive care.',
    baselineWorkup: ['Screen depression/suicidality', 'ECG (QT) if cardiac risk'],
    ongoingMonitoring: 'Mood/suicidality, parkinsonism/akathisia, QT if risk factors.',
    majorDDI: ['CYP2D6 inhibitors raise active-metabolite levels (reduce dose)', 'Other QT-prolonging drugs — additive', 'Dopamine antagonists — additive parkinsonism/NMS risk', 'MAOIs — avoid'],
    contraindicatedCombos: ['Hepatic impairment', 'MAOIs', 'Concurrent tetrabenazine/valbenazine/reserpine', 'Active untreated depression/suicidality'],
    pregnancy: 'Limited data; avoid unless clearly needed.',
    cardiac: 'QT prolongation — caution with QT drugs / electrolyte abnormalities.',
    pearls: [
      'US-only — for awareness (Austedo): the DEUTERATED tetrabenazine — deuterium slows metabolism → smoother levels, BID dosing, and generally better tolerability than tetrabenazine.',
      'Approved (US) for BOTH tardive dyskinesia and Huntington chorea.',
      'Same class caveats: depression/suicidality, parkinsonism, QT (dopamine depletion).',
    ],
    mnemonics: ['“DEUTEtrabenazine = tetrabenazine with a DEUTERIUM Durability upgrade” — heavy hydrogen → slower metabolism, BID dosing.'],
    confusables: ['Deutetrabenazine (deuterated, US-only) vs tetrabenazine (Canada: Nitoman) vs valbenazine (once-daily, US-only).'],
    classDifferentiators: 'Deuterated VMAT2 inhibitor for TD/Huntington chorea; US-only. Smoother PK and better tolerability than tetrabenazine while sharing its dopamine-depletion/QT profile.',
    examHooks: ['How does deutetrabenazine improve on tetrabenazine? Deuteration slows metabolism → steadier levels, BID dosing, fewer peak effects (US-only).'],
    counsellingPoints: ['Take twice daily with food.', 'Report low mood or self-harm thoughts.', 'Report drowsiness affecting driving; report palpitations/fainting.'],
    vignettes: [
      {
        stem: 'Deutetrabenazine was developed to improve on tetrabenazine. What is the pharmacologic basis for its advantages?',
        options: [
          'It blocks dopamine receptors rather than depleting dopamine',
          'Deuterium substitution slows metabolism of the active metabolites, giving steadier levels and less frequent dosing',
          'It is an anticholinergic',
          'It has no risk of depression',
        ],
        answer: 'Deuterium substitution slows metabolism of the active metabolites, giving steadier levels and less frequent dosing',
        explanation: 'Deutetrabenazine is deuterated tetrabenazine; the stronger carbon–deuterium bonds slow metabolism of the active HTBZ metabolites, smoothing plasma levels and permitting twice-daily dosing with better tolerability. It still depletes dopamine (VMAT2) and can cause depression. It is US-only.',
        testedFact: 'Deutetrabenazine = deuterated tetrabenazine (slower metabolism)',
        source: { name: 'openFDA/DailyMed deutetrabenazine label — clinical pharmacology', origin: 'openfda' },
      },
    ],
    _prov: ADJUNCT_PROV,
  },

  amantadine: {
    pronunciation: 'a-MAN-ta-deen',
    moa: 'Dopaminergic + NMDA-receptor antagonist: enhances dopamine release, blocks dopamine reuptake, and antagonizes glutamate NMDA receptors (also has historical anti-influenza-A activity).',
    receptorProfile: 'NMDA antagonist + indirect dopaminergic; mild anticholinergic-like effects.',
    onsetOfEffect: 'Antiparkinsonian/dyskinesia benefit over days.',
    halfLife: '~10–17 hours (markedly prolonged in renal impairment and the elderly).',
    metabolism: 'Minimal hepatic metabolism — excreted largely UNCHANGED by the kidneys (renal dose adjustment required).',
    elimination: 'Renal (unchanged drug); accumulates in renal impairment.',
    approvedCanada: ['Parkinsonism (idiopathic and drug-induced)', 'Influenza A prophylaxis/treatment (historical)'],
    offLabel: ['Adjunct for tardive dyskinesia', 'Levodopa-induced dyskinesia', 'Fatigue (e.g., MS)'],
    approvedPopulations: 'Adults.',
    startingDose: '100 mg PO once daily.',
    titration: 'Increase to 100 mg BID after ~1 week if needed.',
    maxDose: '~300–400 mg/day (immediate-release); reduce in renal impairment.',
    frequencyTiming: 'Once–twice daily; avoid late evening dosing (insomnia).',
    renalHepaticAdjustment: 'REDUCE dose (and/or frequency) in renal impairment — renally cleared; toxicity/accumulation otherwise.',
    commonSE: ['Livedo reticularis (mottled skin)', 'Peripheral/ankle edema', 'Insomnia', 'Dizziness', 'Nausea', 'Dry mouth'],
    seriousAE: ['Hallucinations/confusion/psychosis (esp. elderly, high dose, renal impairment)', 'Suicidality', 'NMS-like syndrome on abrupt withdrawal', 'QT prolongation', 'Orthostatic hypotension'],
    syndromes: ['Livedo reticularis + ankle edema (signature)', 'Dopaminergic hallucinations/confusion', 'Withdrawal NMS-like syndrome'],
    overdoseLethality: 'Narrow margin in overdose — arrhythmia, seizures, hallucinations, anticholinergic-like toxicity; potentially fatal. Risk rises with renal impairment.',
    baselineWorkup: ['Renal function (dose depends on it)'],
    ongoingMonitoring: 'Renal function; mental status (hallucinations/confusion); skin (livedo) and edema; do not stop abruptly.',
    majorDDI: ['Other anticholinergics — additive confusion/anticholinergic effects', 'Other CNS stimulants — additive activation', 'QT-prolonging drugs — additive', 'Triamterene/hydrochlorothiazide, trimethoprim — reduce renal clearance (raise amantadine levels)'],
    contraindicatedCombos: ['Significant renal failure without dose adjustment (accumulation/toxicity)'],
    pregnancy: 'Limited data; use only if clearly needed.',
    geriatric: 'High risk of confusion/hallucinations and reduced renal clearance — lower dose; often preferred over anticholinergics for parkinsonism because it lacks their full anticholinergic burden.',
    renalHepatic: 'Renally excreted — the key adjustment. Accumulates and becomes neurotoxic if not reduced in renal impairment.',
    cardiac: 'Can prolong QT and cause orthostasis.',
    pearls: [
      'Dopaminergic + NMDA antagonist — used for DRUG-INDUCED PARKINSONISM (and as an adjunct for tardive dyskinesia/levodopa dyskinesia); an alternative to anticholinergics with LESS anticholinergic burden.',
      'Signature adverse effects: LIVEDO RETICULARIS and ANKLE EDEMA; also hallucinations/confusion (esp. elderly).',
      'Renally excreted UNCHANGED → MUST reduce dose in renal impairment; do NOT stop abruptly (NMS-like withdrawal).',
    ],
    mnemonics: ['“aMANtadine leaves a MANtled (livedo reticularis) skin and swollen ankles, and its clue is the KIDNEY (renal excretion).”'],
    confusables: ['Amantadine (dopaminergic/NMDA — parkinsonism, renally cleared) vs memantine (NMDA antagonist for Alzheimer dementia) vs anticholinergics.'],
    classDifferentiators: 'Not an anticholinergic and not a VMAT2 inhibitor: a dopaminergic/NMDA agent for DRUG-INDUCED PARKINSONISM (± TD adjunct). Renally cleared (renal dosing), with signature livedo reticularis/edema and hallucination risk.',
    examHooks: ['Drug-induced parkinsonism in an elderly patient where you want to AVOID anticholinergic burden → amantadine.', 'Mottled skin (livedo reticularis) + ankle edema on a parkinsonism drug → amantadine.'],
    counsellingPoints: ['Do not stop suddenly (risk of a serious withdrawal reaction).', 'Report new confusion, hallucinations, or mood changes.', 'A lace-like purple skin mottling (livedo) and ankle swelling can occur and are usually reversible.', 'Take earlier in the day to avoid insomnia.'],
    vignettes: [
      {
        stem: 'An elderly patient on an antipsychotic develops parkinsonism, but you want to avoid worsening their constipation and cognition with an anticholinergic. You also note they have mild renal impairment. Which agent is most appropriate, with dose adjustment?',
        options: ['Benztropine', 'Amantadine', 'Trihexyphenidyl', 'Tetrabenazine'],
        answer: 'Amantadine',
        explanation: 'Amantadine (dopaminergic + NMDA antagonist) treats drug-induced parkinsonism with less anticholinergic burden than benztropine/trihexyphenidyl — useful in the elderly. It is renally excreted, so the dose must be reduced in renal impairment to avoid confusion/hallucinations.',
        testedFact: 'Amantadine for parkinsonism; renal dosing; less anticholinergic burden',
        source: { name: 'openFDA/DailyMed amantadine label — dosing/renal + adverse effects', origin: 'openfda' },
      },
    ],
    _prov: ADJUNCT_PROV,
  },

  dexmedetomidine: {
    pronunciation: 'dex-MED-e-TOE-mi-deen',
    moa: 'Selective α2-adrenergic receptor agonist; reduces central sympathetic (noradrenergic) outflow to produce calming/sedation without significant respiratory depression.',
    receptorProfile: 'α2-adrenergic agonist (high α2:α1 selectivity).',
    onsetOfEffect: 'Sublingual/buccal film calms acute agitation within ~20–60 minutes.',
    halfLife: '~2–3 hours.',
    metabolism: 'Hepatic — glucuronidation and CYP-mediated (CYP2A6) oxidation.',
    approvedCanada: [],
    offLabel: ['(IV form used for procedural/ICU sedation; sublingual film is the psychiatric agitation product)'],
    approvedPopulations: 'Adults.',
    startingDose: 'Sublingual/buccal film 120 micrograms for acute agitation (lower in mild–moderate hepatic impairment / elderly); may re-dose per label.',
    titration: 'Repeat/step-down dosing per label based on agitation and vitals.',
    maxDose: 'Per label daily maximum for the sublingual film (limited repeat doses in 24 h).',
    frequencyTiming: 'PRN for acute agitation episodes (not maintenance therapy).',
    renalHepaticAdjustment: 'Lower dose in hepatic impairment.',
    commonSE: ['Somnolence/sedation', 'Hypotension', 'Bradycardia', 'Dry mouth', 'Orthostatic hypotension', 'Dizziness'],
    seriousAE: ['Hypotension/orthostatic hypotension (syncope)', 'Bradycardia', 'QT prolongation', 'Excessive sedation'],
    syndromes: ['α2-agonist hypotension/bradycardia', 'Sedation'],
    overdoseLethality: 'Overdose → profound hypotension, bradycardia, sedation; supportive care/monitoring.',
    baselineWorkup: ['Blood pressure and heart rate before dosing'],
    ongoingMonitoring: 'BP and HR after each dose (monitor for hypotension/bradycardia); orthostatic vitals; sedation level.',
    majorDDI: ['Other antihypertensives — additive hypotension/bradycardia', 'CNS depressants (benzodiazepines, opioids, alcohol) — additive sedation', 'Other bradycardic agents (β-blockers, digoxin) — additive bradycardia'],
    contraindicatedCombos: ['Significant hypotension/orthostasis; symptomatic bradycardia'],
    pregnancy: 'Limited data; use only if clearly needed.',
    geriatric: 'More sensitive to hypotension/bradycardia — reduce dose, monitor vitals.',
    cardiac: 'Hypotension and bradycardia are the defining hazards; can prolong QT.',
    pearls: [
      'US-only — for awareness (Igalmi): a sublingual/buccal α2-agonist FILM for ACUTE AGITATION in schizophrenia or bipolar I/II; NOT marketed in Canada (pipeline flags availability).',
      'Distinct from IM antipsychotics/benzodiazepines for agitation — non-dopaminergic, minimal respiratory depression, but requires BP/HR monitoring (hypotension/bradycardia/orthostasis).',
      'It calms without the EPS risk of antipsychotics — but sedation and cardiovascular depression are the trade-offs.',
    ],
    mnemonics: ['“DEXmedetomidine DECKS agitation via α2 (like clonidine’s cousin) — but watch the BP and pulse DROP.”'],
    confusables: ['Dexmedetomidine (α2 agonist for acute agitation, US-only) vs clonidine/guanfacine (α2 agonists) vs IM antipsychotics/benzodiazepines for agitation.'],
    classDifferentiators: 'Not an EPS or movement-disorder drug: an α2-agonist for ACUTE AGITATION (schizophrenia/bipolar), US-only. Non-dopaminergic calming (no EPS) but with hypotension/bradycardia as the key hazard.',
    examHooks: ['Sublingual film α2-agonist for acute agitation in schizophrenia/bipolar (US-only)? Dexmedetomidine.', 'What must you monitor after dosing dexmedetomidine for agitation? BP and heart rate (hypotension/bradycardia).'],
    counsellingPoints: ['Used for short-term acute agitation, not daily maintenance.', 'Expect drowsiness; blood pressure and pulse will be checked.', 'Rise slowly afterward (dizziness/fainting risk).'],
    vignettes: [
      {
        stem: 'A sublingual film formulation of an α2-adrenergic agonist is approved (in the US) for acute agitation in adults with schizophrenia or bipolar disorder. Which agent is this, and what is the main monitoring concern?',
        options: [
          'Haloperidol — monitor for EPS',
          'Dexmedetomidine — monitor blood pressure and heart rate',
          'Lorazepam — monitor for respiratory depression',
          'Tetrabenazine — monitor mood',
        ],
        answer: 'Dexmedetomidine — monitor blood pressure and heart rate',
        explanation: 'Sublingual dexmedetomidine (US-only) is an α2-agonist for acute agitation; because α2 agonism lowers sympathetic tone, hypotension and bradycardia (and orthostasis) are the key monitoring concerns. It is non-dopaminergic, so it avoids EPS.',
        testedFact: 'Dexmedetomidine α2-agonist for agitation; monitor BP/HR',
        source: { name: 'openFDA/DailyMed dexmedetomidine sublingual label — warnings (hypotension/bradycardia)', origin: 'openfda' },
      },
    ],
    _prov: ADJUNCT_PROV,
  },
};
