// authored/antipsy_novel.js — authored overlay for novel-mechanism antipsychotics / antipsychotic-adjacent agents.
//
// Mechanism/PK/dosing summaries + the pedagogical layer, grounded in established
// pharmacology and the fetched openFDA/monograph label sections. `_prov` declares which
// safety-critical fields the label text grounds; build.js attaches that source text and,
// where a field cannot be grounded, downgrades it to origin 'authored' + verifyFlag.
//
// Group theme: agents whose selling point is a NOVEL mechanism that departs from classic
// post-synaptic D2 blockade. Lumateperone (unusual 5-HT2A/D2/SERT balance, low metabolic/EPS
// burden). Xanomeline–trospium (M1/M4 muscarinic agonist — the first antipsychotic with NO
// direct D2 antagonism → no EPS/prolactin). Pimavanserin (selective 5-HT2A inverse agonist —
// again NO D2 activity — for Parkinson disease psychosis). All three are US-only at present —
// noted in a pearl for awareness; the pipeline flags Canadian availability itself.

const NOVEL_PROV = {
  startingDose: 'openfda', maxDose: 'openfda', seriousAE: 'openfda', syndromes: 'openfda',
  majorDDI: 'openfda', contraindicatedCombos: 'openfda', pregnancy: 'openfda',
  overdoseLethality: 'openfda',
};

export default {
  lumateperone: {
    pronunciation: 'loo-ma-TEP-er-one',
    moa: 'Novel-mechanism antipsychotic with a dose-dependent, multi-target profile: potent post-synaptic 5-HT2A antagonism, LOW/partial striatal D2 occupancy (pre-synaptic partial agonist + post-synaptic antagonist), and SERT inhibition. The high 5-HT2A:D2 ratio and low absolute D2 occupancy (~40% at therapeutic dose) explain its low EPS/prolactin burden versus classic D2 blockers.',
    receptorProfile: 'Very high 5-HT2A affinity ≫ D2; also modulates glutamate (indirect NMDA/AMPA via D1) and inhibits SERT. Minimal H1/M1/α1 activity at therapeutic dose → low sedation/metabolic signal.',
    onsetOfEffect: 'Antipsychotic effect over 1–2 weeks; full response weeks (as with other antipsychotics).',
    halfLife: 'Terminal ~13–18 hours (parent); given once daily.',
    timeToSteadyState: 'A few days with once-daily dosing.',
    metabolism: 'Extensive hepatic metabolism, predominantly CYP3A4 (also UGT, AKR, CYP2C8/1A2). A sensitive CYP3A4 substrate — strong 3A4 inhibitors/inducers markedly change exposure.',
    foodEffect: 'Give with food — food lowers peak concentration and improves tolerability.',
    approvedPopulations: 'Adults.',
    offLabel: ['Bipolar mania/mixed (under study)', 'Behavioural symptoms adjunct (investigational)'],
    startingDose: '42 mg PO once daily (no titration needed — start at the therapeutic dose).',
    titration: 'None — 42 mg is both the starting and target dose.',
    maxDose: '42 mg/day (single fixed therapeutic dose; higher doses have not shown added benefit).',
    frequencyTiming: 'Once daily, with food; timing flexible (often given in the evening).',
    renalHepaticAdjustment: 'Not recommended in moderate–severe hepatic impairment (Child-Pugh B/C) — exposure rises.',
    administrationNotes: 'Fixed-dose simplicity is a practical selling point; swallow capsule whole with food.',
    commonSE: ['Somnolence/sedation', 'Dry mouth', 'Dizziness', 'Nausea', 'Fatigue'],
    seriousAE: ['Increased mortality in elderly with dementia-related psychosis (class effect)', 'Neuroleptic malignant syndrome', 'Cerebrovascular events in elderly dementia', 'Metabolic changes (relatively low)', 'Leukopenia/neutropenia', 'Suicidality/mood monitoring'],
    syndromes: ['Neuroleptic malignant syndrome', 'Tardive dyskinesia (low risk)', 'Metabolic syndrome (low signal)'],
    overdoseLethality: 'Limited overdose data; supportive care. Sedation and cardiovascular monitoring; no specific antidote.',
    discontinuationSyndrome: 'No specific withdrawal syndrome described; watch for relapse of psychosis.',
    ongoingMonitoring: 'Standard antipsychotic monitoring: weight/metabolic panel, mental status; lower expected metabolic/EPS burden than most agents but still monitor.',
    majorDDI: ['Strong CYP3A4 inhibitors (e.g., ketoconazole, clarithromycin) — avoid/markedly raise levels', 'Strong/moderate CYP3A4 inducers (e.g., rifampin, carbamazepine) — reduce efficacy, avoid', 'UGT inhibitors — may raise exposure', 'Additive CNS depression with sedatives/alcohol'],
    contraindicatedCombos: ['Co-administration with strong CYP3A4 inducers (loss of efficacy)', 'Concomitant strong CYP3A4 inhibitors (per label caution/avoid)'],
    pregnancy: 'Third-trimester antipsychotic exposure risks EPS/withdrawal in the neonate (class effect); limited human data. Weigh maternal illness. Enrol in pregnancy registry where available.',
    lactation: 'Limited data; monitor infant for sedation/feeding.',
    pediatric: 'Not established in children/adolescents.',
    geriatric: 'Boxed-warning population (dementia-related psychosis) — increased mortality; use general antipsychotic caution.',
    renalHepatic: 'Avoid in moderate–severe hepatic impairment; no adjustment needed in renal impairment.',
    pearls: [
      'US-only — for awareness (Caplyta): approved for schizophrenia and bipolar I/II depression (mono or adjunct with lithium/valproate); not marketed in Canada.',
      'The mechanism is notable: a high 5-HT2A:D2 ratio with LOW absolute D2 occupancy (~40%) plus SERT inhibition gives an antipsychotic with unusually low EPS, low prolactin, and low metabolic/weight signal — distinct from classic potent D2 blockers.',
      'Fixed single dose (42 mg, with food, no titration) — practically simple.',
    ],
    mnemonics: ['"LUMA lights up serotonin, barely touches dopamine" — 5-HT2A ≫ D2, so few EPS and little prolactin.'],
    confusables: ['Lumateperone vs pimavanserin — both spare D2, but pimavanserin has NO D2 activity at all (pure 5-HT2A inverse agonist for PD psychosis), whereas lumateperone still has low/partial D2 activity and treats schizophrenia + bipolar depression.'],
    classDifferentiators: 'Among "atypicals," the lowest-metabolic/lowest-EPS profile by design; unique SERT inhibition + high 5-HT2A:D2 ratio; the only one approved across schizophrenia AND both bipolar I and II depression.',
    examHooks: ['Which novel antipsychotic combines potent 5-HT2A antagonism, low D2 occupancy, and SERT inhibition, with a low metabolic/EPS burden and approval for bipolar depression? (lumateperone)'],
    counsellingPoints: ['Take once daily with food.', 'Less likely to cause weight gain or movement side effects than many antipsychotics, but keep monitoring appointments.', 'Do not stop abruptly — discuss any changes.', 'Tell your prescriber about medications that affect the liver enzyme CYP3A4.'],
    vignettes: [
      {
        stem: 'A 34-year-old with schizophrenia has gained 12 kg and developed akathisia on prior antipsychotics. You consider lumateperone. Which pharmacological feature best explains its comparatively low weight-gain and EPS risk?',
        options: ['Potent H1 and 5-HT2C antagonism', 'High 5-HT2A affinity with low absolute striatal D2 occupancy', 'Full D2 agonism', 'Irreversible D2 blockade'],
        answer: 'High 5-HT2A affinity with low absolute striatal D2 occupancy',
        explanation: 'Lumateperone occupies D2 only ~40% at the therapeutic dose while potently antagonising 5-HT2A, and has minimal H1/5-HT2C activity, giving low EPS/prolactin and a low metabolic signal.',
        testedFact: 'Lumateperone 5-HT2A:D2 ratio and low D2 occupancy → low EPS/metabolic burden',
        source: { name: 'openFDA/DailyMed lumateperone (Caplyta) label — clinical pharmacology', origin: 'openfda' },
      },
    ],
    _prov: NOVEL_PROV,
  },

  xanomeline_trospium: {
    pronunciation: 'za-NOM-eh-leen / TROSS-pee-um',
    moa: 'First-in-class antipsychotic that works WITHOUT any direct D2 receptor blockade. Xanomeline is a muscarinic M1/M4 receptor agonist; M4 activation in the striatum indirectly dampens dopamine signalling and M1 activation modulates cortical/limbic circuits, producing antipsychotic effect upstream of the dopamine synapse. Trospium is a peripherally-restricted (does not meaningfully cross the blood–brain barrier) muscarinic antagonist added solely to blunt xanomeline\'s peripheral cholinergic side effects.',
    receptorProfile: 'Xanomeline: M1/M4 muscarinic agonist (some M2/M3/M5 activity). Trospium: non-selective peripheral muscarinic antagonist (quaternary amine → CNS-sparing). No D2, 5-HT2A, H1, or α1 blockade — the whole point is a non-dopaminergic mechanism.',
    onsetOfEffect: 'Antipsychotic separation from placebo within weeks in trials.',
    halfLife: 'Xanomeline ~1–2 hours; trospium ~8.5 hours — hence twice-daily dosing.',
    timeToSteadyState: 'Within about a week of stable BID dosing.',
    metabolism: 'Xanomeline is hepatically metabolised (oxidative). Trospium is minimally metabolised and largely renally excreted (active tubular secretion) — a source of interactions with other renally secreted drugs.',
    foodEffect: 'Take on an empty stomach (≥1 h before or ≥2 h after food) — food raises trospium exposure and can worsen anticholinergic effects.',
    approvedPopulations: 'Adults with schizophrenia.',
    startingDose: 'Xanomeline 50 mg / trospium 20 mg PO twice daily, then titrate over days.',
    titration: 'Increase stepwise (e.g., to 100/20 then 125/30 BID) as tolerated, based on the label schedule.',
    maxDose: 'Xanomeline 125 mg / trospium 30 mg PO twice daily.',
    frequencyTiming: 'Twice daily on an empty stomach.',
    renalHepaticAdjustment: 'Not recommended in moderate/severe hepatic impairment or moderate/severe renal impairment (both components accumulate).',
    administrationNotes: 'Empty-stomach BID dosing and stepwise titration are key to tolerability; the trospium component is what makes the peripheral cholinergic load manageable.',
    commonSE: ['Nausea/vomiting', 'Dyspepsia', 'Constipation', 'Dry mouth', 'Dizziness', 'Hypertension', 'Increased heart rate'],
    seriousAE: ['Urinary retention (anticholinergic)', 'Symptomatic bradycardia/syncope (cholinergic)', 'Anticholinergic effects incl. worsening narrow-angle glaucoma, ileus', 'Hepatic effects (transaminase elevations — monitor)', 'Increased blood pressure/heart rate'],
    syndromes: ['Cholinergic excess (GI/nausea, sweating, bradycardia)', 'Anticholinergic toxicity (peripheral — dry mouth, constipation, urinary retention)'],
    overdoseLethality: 'Overdose could produce mixed cholinergic (GI, bradycardia) and anticholinergic (retention, tachycardia, mydriasis) effects; supportive care, no specific antidote established.',
    discontinuationSyndrome: 'Cholinergic rebound possible on abrupt stop (as with other cholinergic/anticholinergic agents); watch for relapse.',
    baselineWorkup: ['Consider baseline LFTs (hepatic effects reported)', 'Assess for urinary retention risk, narrow-angle glaucoma, and GI motility disorders before starting'],
    ongoingMonitoring: 'Monitor heart rate/BP, GI tolerability, urinary symptoms, and LFTs. Notably, routine metabolic/prolactin/EPS monitoring concerns are lower because there is no D2 blockade — but do NOT ignore cholinergic/anticholinergic effects.',
    majorDDI: ['Other anticholinergics — additive peripheral antimuscarinic toxicity (retention, constipation, ileus)', 'Other cholinergic agents — additive GI/bradycardic effects', 'Drugs cleared by renal tubular secretion (e.g., metformin, digoxin, procainamide) — compete with trospium', 'Additive effects with agents that slow GI motility'],
    contraindicatedCombos: ['Clinically significant urinary retention, gastric retention, or uncontrolled narrow-angle glaucoma (per label — trospium component)'],
    pregnancy: 'Limited human data; weigh maternal illness. Anticholinergic/cholinergic effects on the neonate are theoretical — enrol in a pregnancy registry where available.',
    lactation: 'Limited data; monitor infant.',
    pediatric: 'Not established.',
    geriatric: 'Anticholinergic burden and orthostatic/cardiac effects warrant caution; note it lacks the dementia-mortality boxed warning framing of D2 antipsychotics, but safety in elderly psychosis is not established.',
    renalHepatic: 'Avoid in moderate/severe renal or hepatic impairment.',
    cardiac: 'Can raise heart rate and blood pressure and, via the cholinergic component, cause bradycardia/syncope — monitor.',
    pearls: [
      'US-only — for awareness (Cobenfy, formerly KarXT): first antipsychotic approved for schizophrenia that does NOT block dopamine receptors; not available in Canada.',
      'The mechanism is the headline: an M1/M4 muscarinic agonist (xanomeline) acts upstream of dopamine, so there is NO D2 blockade → essentially no EPS, no tardive dyskinesia risk from D2 blockade, and no prolactin elevation. The side-effect profile is cholinergic/anticholinergic, not dopaminergic/metabolic.',
      'Trospium is added purely as a peripheral muscarinic ANTAGONIST (CNS-sparing quaternary amine) to counter xanomeline\'s peripheral cholinergic effects (nausea, sweating, GI) without blunting the central antipsychotic action.',
    ],
    mnemonics: ['"KarXT = Karb (cholinergic) + Trospium (anti-cholinergic outside the brain)": central M1/M4 agonism does the work; peripheral antimuscarinic keeps the gut/bladder quiet.'],
    confusables: ['Xanomeline–trospium vs every other antipsychotic — it is the ONLY one with no dopamine-receptor activity; classic and atypical agents all block (or partially agonise) D2.'],
    classDifferentiators: 'Purely muscarinic (M1/M4 agonist) mechanism with no D2/5-HT2A blockade → no EPS, no TD-from-D2, no hyperprolactinemia, minimal metabolic/weight signal; side effects are cholinergic (nausea, GI, bradycardia) and peripheral anticholinergic (dry mouth, constipation, urinary retention).',
    examHooks: ['Which antipsychotic treats schizophrenia through M1/M4 muscarinic agonism with NO D2 blockade, paired with a peripheral anticholinergic to limit cholinergic side effects? (xanomeline–trospium)'],
    counsellingPoints: ['Take twice daily on an empty stomach (well before or after meals).', 'Nausea, constipation, dry mouth and stomach upset are common early and often improve — report severe vomiting, inability to urinate, or fainting.', 'This medicine does not usually cause the movement or prolactin side effects of older antipsychotics.', 'Do not stop suddenly; keep monitoring visits.'],
    vignettes: [
      {
        stem: 'A 29-year-old with schizophrenia cannot tolerate EPS or hyperprolactinemia on multiple dopamine-blocking antipsychotics. He is switched to xanomeline–trospium and improves without any movement side effects. Which mechanism explains the absence of EPS and prolactin elevation?',
        options: ['Selective D2 partial agonism', 'M1/M4 muscarinic agonism with no direct D2 receptor blockade', 'Potent 5-HT2A inverse agonism at D2 receptors', 'Irreversible D2 antagonism with rapid dissociation'],
        answer: 'M1/M4 muscarinic agonism with no direct D2 receptor blockade',
        explanation: 'Xanomeline acts as an M1/M4 agonist upstream of dopamine transmission; because it does not block D2 receptors, it does not cause the EPS or prolactin rise seen with dopamine antagonists. Trospium only blocks peripheral muscarinic receptors.',
        testedFact: 'Xanomeline–trospium non-dopaminergic (muscarinic) mechanism → no EPS/prolactin',
        source: { name: 'openFDA/DailyMed xanomeline–trospium (Cobenfy) label — mechanism of action', origin: 'openfda' },
      },
    ],
    _prov: NOVEL_PROV,
  },

  pimavanserin: {
    pronunciation: 'pim-a-VAN-ser-in',
    moa: 'Selective serotonin 5-HT2A receptor INVERSE AGONIST/antagonist (with some 5-HT2C activity) and NO dopamine (D2) receptor activity. By dampening 5-HT2A-mediated signalling rather than blocking dopamine, it treats hallucinations/delusions of Parkinson disease psychosis without worsening motor function — the key advantage over D2-blocking antipsychotics.',
    receptorProfile: 'High-affinity 5-HT2A inverse agonist; lower 5-HT2C activity; essentially no affinity for D2, muscarinic, histaminergic, or adrenergic receptors — hence no dopaminergic motor worsening and no anticholinergic/α1 burden.',
    onsetOfEffect: 'Improvement in psychotic symptoms over ~2–6 weeks.',
    halfLife: 'Long — parent ~57 hours and active metabolite (AC-279) ~200 hours; once-daily dosing, slow accumulation.',
    timeToSteadyState: 'Several weeks due to the long half-life.',
    metabolism: 'Hepatic, predominantly CYP3A4 (and 3A5) to an active metabolite; a CYP3A4 substrate — strong 3A4 inhibitors/inducers change exposure significantly.',
    foodEffect: 'May be taken with or without food.',
    approvedPopulations: 'Adults with Parkinson disease psychosis (hallucinations and delusions).',
    offLabel: ['Dementia-related psychosis (studied; not approved and carries the class mortality warning)'],
    startingDose: '34 mg PO once daily (no titration required).',
    titration: 'None — start and maintain at 34 mg once daily.',
    maxDose: '34 mg/day (reduce to 10 mg/day when used with a strong CYP3A4 inhibitor).',
    frequencyTiming: 'Once daily, with or without food.',
    renalHepaticAdjustment: 'Not recommended in severe hepatic impairment; no adjustment for mild–moderate renal impairment.',
    administrationNotes: 'Fixed dose; the main dose adjustment is halving (to 10 mg) with strong 3A4 inhibitors.',
    commonSE: ['Peripheral edema', 'Nausea', 'Confusional state', 'Hallucinations (paradoxical/persistent)', 'Constipation', 'Gait disturbance'],
    seriousAE: ['QT interval prolongation', 'Increased mortality in elderly with dementia-related psychosis (boxed class warning)', 'Confusion/worsening psychosis in some', 'Falls'],
    syndromes: ['QT prolongation', 'Confusional state in the elderly'],
    overdoseLethality: 'Overdose data limited; QT prolongation and CNS effects are the concerns — monitor ECG; no specific antidote.',
    discontinuationSyndrome: 'No defined withdrawal syndrome; psychosis may recur.',
    baselineWorkup: ['Consider baseline ECG/electrolytes if QT risk factors or on other QT-prolonging drugs'],
    ongoingMonitoring: 'Monitor for QT prolongation (ECG if risk factors), mental status/confusion, and effect on psychosis; watch Parkinson motor status (should not worsen).',
    majorDDI: ['Strong CYP3A4 inhibitors (e.g., ketoconazole, clarithromycin) — reduce pimavanserin to 10 mg/day', 'Strong CYP3A4 inducers (e.g., rifampin, carbamazepine) — reduce efficacy; avoid', 'Other QT-prolonging drugs (Class 1A/III antiarrhythmics, some antibiotics/antipsychotics) — additive QT risk', 'Additive CNS effects with other sedatives'],
    contraindicatedCombos: ['Combination with other QT-prolonging agents where risk is significant (per label caution)'],
    pregnancy: 'Limited human data; use only if benefit justifies risk. Note the population (older PD patients) makes pregnancy uncommon.',
    lactation: 'Limited data; decide considering benefit/relevance.',
    pediatric: 'Not established.',
    geriatric: 'Primary population; boxed warning for increased mortality in dementia-related psychosis — reserve for PD psychosis; watch confusion, falls, QT.',
    renalHepatic: 'Avoid in severe hepatic impairment.',
    cardiac: 'Dose-dependent QT prolongation — avoid/caution with other QT drugs and in congenital long-QT.',
    pearls: [
      'US-only — for awareness (Nuplazid): approved for hallucinations/delusions of Parkinson disease psychosis; not available in Canada.',
      'The mechanism is notable: a SELECTIVE 5-HT2A inverse agonist with NO D2 activity — so it controls psychosis without blocking dopamine, uniquely avoiding worsening of Parkinsonian motor symptoms (the reason typical/atypical D2 antipsychotics are problematic in PD).',
      'QT prolongation is the defining safety caution; carries the class boxed warning for increased mortality in elderly dementia-related psychosis (it is NOT approved for dementia psychosis).',
    ],
    mnemonics: ['"Pimavanserin = Parkinson\'s psychosis, Pure 5-HT2A, no dopamine" — three P\'s; spares motor function.'],
    confusables: ['Pimavanserin vs quetiapine/clozapine for PD psychosis — all avoid strong D2 blockade, but pimavanserin has NO D2 activity at all (pure 5-HT2A inverse agonist); quetiapine/clozapine are low-D2 atypicals still with off-target (sedation, metabolic, agranulocytosis for clozapine) effects.'],
    classDifferentiators: 'The only antipsychotic-class agent that is a selective 5-HT2A inverse agonist with zero dopaminergic activity, purpose-built for Parkinson disease psychosis; profile dominated by QT and the dementia-mortality boxed warning rather than EPS/metabolic effects.',
    examHooks: ['Which agent treats Parkinson disease psychosis via selective 5-HT2A inverse agonism without any D2 blockade (so it does not worsen motor symptoms)? (pimavanserin)'],
    counsellingPoints: ['Take once daily; it can take a few weeks to work.', 'It should not worsen your Parkinson movement symptoms.', 'Report fainting or palpitations (heart-rhythm effect).', 'Tell your prescriber about all medications, especially those affecting the liver enzyme CYP3A4 or the heart rhythm.'],
    vignettes: [
      {
        stem: 'A 74-year-old with Parkinson disease develops distressing visual hallucinations. Standard antipsychotics previously worsened his rigidity and bradykinesia. Which agent controls the psychosis while sparing motor function because it has no dopamine-receptor activity?',
        options: ['Haloperidol', 'Risperidone', 'Pimavanserin', 'Olanzapine'],
        answer: 'Pimavanserin',
        explanation: 'Pimavanserin is a selective 5-HT2A inverse agonist with no D2 activity, so it treats Parkinson disease psychosis without the dopamine blockade that worsens parkinsonism; the other options are D2 antagonists that worsen motor symptoms.',
        testedFact: 'Pimavanserin selective 5-HT2A inverse agonism / no D2 → treats PD psychosis without motor worsening',
        source: { name: 'openFDA/DailyMed pimavanserin (Nuplazid) label — indications/mechanism', origin: 'openfda' },
      },
    ],
    _prov: NOVEL_PROV,
  },
};
