// authored/benzo.js — authored overlay for the benzodiazepine class.
//
// Mechanism/PK/dosing summaries + the pedagogical layer, grounded in established
// pharmacology and the fetched openFDA/monograph label sections. `_prov` declares which
// safety-critical fields the label text grounds; build.js attaches that source text and,
// where a field cannot be grounded, downgrades it to origin 'authored' + verifyFlag.
// The pipeline supplies identity, DINs/brands, the Targeted Substance schedule, the boxed
// warning and contraindications from live sources — do NOT author those here.
//
// Benzodiazepine class theme: POSITIVE ALLOSTERIC MODULATION of GABA-A (bind the α/γ
// interface, ↑ FREQUENCY of Cl- channel opening in presence of GABA) → anxiolytic,
// sedative-hypnotic, anticonvulsant, muscle-relaxant, amnestic. The teaching axes are
// (1) HALF-LIFE CLASS (ultra-short/short/intermediate/long → onset, hangover, withdrawal
// severity, accumulation) and (2) METABOLISM — the "LOT" agents (Lorazepam, Oxazepam,
// Temazepam) are cleared by GLUCURONIDATION only (no oxidative CYP step, no active
// metabolites) so they are preferred in hepatic impairment and the elderly; the rest need
// hepatic CYP oxidation and several carry long-lived active metabolites that accumulate.
// HARMS: dependence/tolerance/withdrawal (withdrawal seizures on abrupt stop), sedation,
// falls + cognitive impairment in the elderly (Beers), anterograde amnesia, paradoxical
// disinhibition, and — the killer — RESPIRATORY DEPRESSION and DEATH when combined with
// opioids, alcohol, or other CNS depressants. Low lethality ALONE; high in combination.
// Flumazenil is the competitive GABA-A antagonist / reversal agent (can precipitate
// seizures in benzo-dependent or mixed TCA overdose — use cautiously).

const BENZO_PROV = {
  startingDose: 'openfda', maxDose: 'openfda', seriousAE: 'openfda', syndromes: 'openfda',
  majorDDI: 'openfda', contraindicatedCombos: 'openfda', pregnancy: 'openfda',
  overdoseLethality: 'openfda',
};

export default {
  lorazepam: {
    pronunciation: 'lor-AZ-uh-pam',
    moa: 'Benzodiazepine: positive allosteric modulator at GABA-A, increasing the frequency of chloride-channel opening → sedation, anxiolysis, anticonvulsant effect.',
    receptorProfile: 'Non-selective GABA-A benzodiazepine-site agonist.',
    onsetOfEffect: 'PO ~20–30 min; IV within 1–3 min; intermediate lipophilicity gives a slightly slower CNS onset than diazepam but a longer duration of clinical effect.',
    halfLife: '~10–20 h (short–intermediate class).',
    timeToSteadyState: '~2–3 days.',
    metabolism: 'GLUCURONIDATION (UGT) to an inactive glucuronide — NO oxidative CYP step. Unaffected by CYP inhibitors/inducers and largely preserved in liver disease.',
    activeMetabolites: 'None (inactive glucuronide only).',
    elimination: 'Renal (inactive conjugate).',
    approvedCanada: ['Anxiety', 'Insomnia due to anxiety', 'Preoperative sedation'],
    offLabel: ['Status epilepticus', 'Acute agitation', 'Alcohol withdrawal', 'Catatonia (lorazepam challenge)', 'Chemotherapy-induced/anticipatory nausea'],
    approvedPopulations: 'Adults; used across settings given IM/IV availability.',
    startingDose: '0.5–1 mg PO 2–3×/day for anxiety; 1–2 mg IV/IM for acute agitation or status epilepticus (repeat per protocol).',
    titration: 'Lowest effective dose for the shortest duration; increase gradually.',
    maxDose: 'Up to ~6–10 mg/day in divided doses for anxiety (lower in elderly).',
    frequencyTiming: 'BID–TID (intermediate half-life); can be given IM/IV, unlike most oral-only benzos.',
    renalHepaticAdjustment: 'Preferred benzodiazepine in hepatic impairment (glucuronidation preserved); IV formulation contains propylene glycol — watch for toxicity/lactic acidosis with high-dose infusions.',
    startStopCrossTaper: 'Taper gradually after regular use to avoid withdrawal (rebound anxiety, insomnia, seizures).',
    administrationNotes: 'One of the "LOT" liver-safe agents; reliable IM absorption makes it a workhorse for agitation and status epilepticus.',
    commonSE: ['Sedation', 'Dizziness', 'Ataxia/unsteadiness', 'Anterograde amnesia', 'Fatigue'],
    seriousAE: ['Respiratory depression (esp. with opioids/alcohol/IV)', 'Dependence and withdrawal (incl. seizures)', 'Falls/fractures in elderly', 'Paradoxical agitation/disinhibition', 'Propylene-glycol toxicity with prolonged high-dose IV'],
    syndromes: ['Dependence/withdrawal (withdrawal seizures)', 'Respiratory depression (with CNS depressants)', 'Falls/cognitive impairment (elderly)', 'Paradoxical disinhibition', 'Anterograde amnesia'],
    overdoseLethality: 'LOW when taken alone; HIGH risk of fatal respiratory depression when combined with opioids, alcohol, or other CNS depressants. Flumazenil reverses but may precipitate seizures.',
    discontinuationSyndrome: 'Withdrawal after regular use — rebound anxiety/insomnia, tremor, autonomic arousal, and (abrupt cessation) seizures; taper slowly.',
    ongoingMonitoring: 'Sedation, respiratory status (especially with opioids), signs of misuse/dependence, falls risk in elderly.',
    majorDDI: ['Opioids (additive respiratory depression — boxed-warning combination)', 'Alcohol and other CNS depressants', 'Clozapine (rare respiratory/cardiac arrest with parenteral benzodiazepines)', 'Sodium valproate (may raise lorazepam levels)'],
    contraindicatedCombos: ['Opioids (combine only when no alternative; lowest dose/shortest duration)', 'Alcohol/other CNS depressants', 'Use in severe respiratory insufficiency / untreated sleep apnea'],
    pregnancy: 'Avoid where possible; late-pregnancy/regular use risks neonatal sedation, hypotonia ("floppy infant") and withdrawal. Weigh against untreated maternal illness.',
    lactation: 'Small amounts in milk; monitor infant for sedation/poor feeding. Preferred benzos in lactation are shorter-acting agents without active metabolites.',
    geriatric: 'Beers-listed — avoid in older adults (falls, fractures, cognitive impairment, delirium). If unavoidable, this glucuronidated agent is often preferred over long-acting/active-metabolite benzos; use the lowest dose.',
    renalHepatic: 'Hepatically safer than CYP-metabolized benzos; no active metabolite to accumulate in renal impairment.',
    pearls: [
      'A "LOT" agent (Lorazepam/Oxazepam/Temazepam): glucuronidation only, no active metabolite — the benzo of choice in hepatic impairment and the elderly.',
      'Reliable IM/IV absorption → first-line for status epilepticus and acute agitation; IV drug of choice for benzodiazepine-treated status.',
      'Used as the "lorazepam challenge" in suspected catatonia.',
    ],
    mnemonics: ['"LOT" = Lorazepam, Oxazepam, Temazepam → glucuronidated, Liver-safe, no active metabolite.'],
    confusables: ['Lorazepam vs alprazolam — both short/intermediate anxiolytics, but lorazepam is glucuronidated (liver-safe, IM/IV) while alprazolam is CYP3A4 and higher-potency with worse interdose rebound.', 'Lorazepam vs clonazepam — clonazepam is long-acting.'],
    classDifferentiators: 'Short–intermediate half-life, glucuronidation (no CYP, no active metabolite), parenteral (IM/IV) availability — the versatile liver-safe workhorse.',
    examHooks: ['Which benzodiazepine is preferred in hepatic impairment/elderly and why? (lorazepam — glucuronidation, no active metabolite).', 'First-line benzodiazepine for status epilepticus? (IV lorazepam).'],
    counsellingPoints: ['Do not combine with alcohol or opioids — risk of fatal breathing suppression.', 'Do not stop suddenly after regular use — taper with your prescriber.', 'May impair driving and cause memory gaps.'],
    vignettes: [
      {
        stem: 'A 74-year-old with cirrhosis needs a benzodiazepine for severe alcohol-withdrawal agitation. Which agent is preferred because its clearance does not depend on hepatic oxidation?',
        options: ['Diazepam', 'Chlordiazepoxide', 'Lorazepam', 'Alprazolam'],
        answer: 'Lorazepam',
        explanation: 'Lorazepam (with oxazepam and temazepam — "LOT") is cleared by glucuronidation without a CYP oxidation step and has no active metabolite, so it is preferred in significant liver disease and the elderly, where oxidatively metabolized/long-acting benzos accumulate.',
        testedFact: 'Glucuronidated (LOT) benzodiazepines in hepatic impairment',
        source: { name: 'Standard psychopharmacology; openFDA/DailyMed lorazepam label — metabolism', origin: 'monograph' },
      },
    ],
    _prov: BENZO_PROV,
  },

  clonazepam: {
    pronunciation: 'kloh-NAZ-uh-pam',
    moa: 'Benzodiazepine: GABA-A positive allosteric modulator (↑ frequency of Cl- channel opening); high-potency, long-acting.',
    receptorProfile: 'Non-selective GABA-A benzodiazepine-site agonist.',
    onsetOfEffect: 'PO onset ~20–60 min; long duration of clinical effect.',
    halfLife: '~18–50 h (long class).',
    timeToSteadyState: '~5–7 days.',
    metabolism: 'Hepatic — nitro-reduction and CYP3A4 to inactive metabolites; acetylation.',
    activeMetabolites: 'None clinically significant.',
    approvedCanada: ['Seizure disorders (e.g., absence, myoclonic, Lennox-Gastaut)', 'Panic disorder'],
    offLabel: ['Anxiety disorders', 'Acute mania (adjunct)', 'REM sleep behaviour disorder', 'Restless legs', 'Akathisia'],
    approvedPopulations: 'Adults and children (epilepsy).',
    startingDose: '0.25–0.5 mg PO BID for panic; 0.5 mg TID for seizures.',
    titration: 'Increase every few days; long half-life allows once–twice daily dosing at steady state.',
    maxDose: 'Panic up to ~4 mg/day; seizures up to ~20 mg/day.',
    frequencyTiming: 'BID (long half-life gives smoother coverage than short-acting agents).',
    startStopCrossTaper: 'Taper slowly; sometimes used to cross-taper OFF shorter-acting benzos (e.g., alprazolam) because its longer half-life smooths withdrawal.',
    administrationNotes: 'Long half-life + high potency → steadier plasma levels and less interdose rebound than alprazolam.',
    commonSE: ['Sedation', 'Fatigue', 'Ataxia', 'Behavioural changes/irritability (esp. children)', 'Dizziness'],
    seriousAE: ['Respiratory depression (with opioids/alcohol)', 'Dependence and withdrawal (incl. seizures)', 'Falls in elderly', 'Paradoxical disinhibition', 'Hypersalivation/bronchial hypersecretion (infants)'],
    syndromes: ['Dependence/withdrawal (withdrawal seizures)', 'Respiratory depression (with CNS depressants)', 'Falls/cognitive impairment (elderly)', 'Paradoxical disinhibition'],
    overdoseLethality: 'LOW alone; HIGH with opioids/alcohol/other CNS depressants (respiratory depression).',
    discontinuationSyndrome: 'Withdrawal on abrupt stop (anxiety, insomnia, tremor, seizures); its long half-life makes withdrawal somewhat milder/more delayed than short-acting benzos — still taper.',
    ongoingMonitoring: 'Sedation, dependence, mood/behaviour (esp. children), falls in elderly, respiratory status with opioids.',
    majorDDI: ['Opioids (additive respiratory depression)', 'Alcohol/CNS depressants', 'Strong CYP3A4 inhibitors (may raise levels)', 'Enzyme-inducing anticonvulsants (may lower levels)'],
    contraindicatedCombos: ['Opioids (avoid; lowest dose/shortest duration if unavoidable)', 'Alcohol/other CNS depressants', 'Severe respiratory insufficiency / untreated sleep apnea'],
    pregnancy: 'Avoid where possible; regular late use → neonatal sedation/hypotonia/withdrawal; balance against seizure/panic control.',
    lactation: 'Passes into milk; monitor infant for sedation. Long half-life is a drawback in nursing.',
    geriatric: 'Beers — avoid; long half-life increases accumulation, sedation, and falls.',
    pearls: [
      'Long half-life + high potency → useful for panic disorder and as a cross-taper agent to withdraw patients off short-acting benzos like alprazolam.',
      'Both an anxiolytic and an anticonvulsant — one of the few benzos formally used long-term for epilepsy.',
      'Once at steady state, BID dosing gives steadier levels and less interdose rebound than alprazolam.',
    ],
    mnemonics: ['"cloNAZepam = the long, steady one" — smooths panic and helps taper off alprazolam.'],
    confusables: ['CLONAZEPAM (benzodiazepine) vs CLOZAPINE (atypical antipsychotic with agranulocytosis monitoring) — sound-alike, very different drugs.', 'Clonazepam vs clobazam — clobazam is a 1,5-benzodiazepine seizure adjunct.'],
    classDifferentiators: 'Long half-life, high potency, dual anxiolytic/anticonvulsant role, no significant active metabolite.',
    examHooks: ['High-potency long-acting benzo used for panic and as a cross-taper off alprazolam? (clonazepam).', 'Name the classic sound-alike confusable for clonazepam (clozapine).'],
    counsellingPoints: ['Do not stop abruptly.', 'Avoid alcohol/opioids.', 'Report worsening mood or unusual behaviour, especially in children.'],
    vignettes: [
      {
        stem: 'A patient on alprazolam 1 mg QID reports rebound anxiety hours after each dose and difficulty tapering. Which strategy best facilitates discontinuation?',
        options: ['Increase alprazolam frequency to 6×/day', 'Cross-taper to an equivalent dose of clonazepam, then taper', 'Switch abruptly to as-needed lorazepam', 'Add an opioid for anxiety'],
        answer: 'Cross-taper to an equivalent dose of clonazepam, then taper',
        explanation: 'Alprazolam’s short half-life causes interdose rebound and difficult withdrawal. Converting to a longer-acting benzodiazepine such as clonazepam produces steadier levels and allows a smoother, gradual taper.',
        testedFact: 'Long-acting benzo cross-taper to withdraw short-acting benzo',
        source: { name: 'Standard psychopharmacology; benzodiazepine tapering practice', origin: 'monograph' },
      },
    ],
    _prov: BENZO_PROV,
  },

  diazepam: {
    pronunciation: 'dy-AZ-uh-pam',
    moa: 'Benzodiazepine: GABA-A positive allosteric modulator (↑ Cl- channel opening frequency); highly lipophilic → very rapid CNS onset.',
    receptorProfile: 'Non-selective GABA-A benzodiazepine-site agonist.',
    onsetOfEffect: 'Very rapid (PO ~15 min; IV within 1–3 min) due to high lipophilicity, but redistributes quickly; long terminal accumulation via active metabolites.',
    halfLife: 'Parent ~20–50 h; active metabolite desmethyldiazepam (nordiazepam) up to ~200 h (LONG class — accumulates).',
    timeToSteadyState: 'Up to ~2 weeks because of long-lived active metabolites.',
    metabolism: 'Hepatic oxidation via CYP2C19 and CYP3A4 to ACTIVE metabolites (desmethyldiazepam → oxazepam, temazepam).',
    activeMetabolites: 'Desmethyldiazepam (nordiazepam, very long half-life), plus temazepam and oxazepam — accumulate, especially in the elderly.',
    approvedCanada: ['Anxiety', 'Skeletal muscle spasm', 'Seizure disorders (adjunct)', 'Alcohol withdrawal', 'Preoperative/procedural sedation'],
    offLabel: ['Status epilepticus (incl. rectal/IV)', 'Vertigo', 'Spasticity'],
    approvedPopulations: 'Adults and children.',
    startingDose: '2–10 mg PO 2–4×/day depending on indication; 5–10 mg IV for seizures/withdrawal per protocol.',
    titration: 'Titrate to effect; long metabolites mean effects build over days.',
    maxDose: 'Commonly up to ~40 mg/day PO in divided doses (higher in supervised withdrawal/seizure settings).',
    frequencyTiming: 'BID–QID; rectal and IV forms exist for seizures.',
    renalHepaticAdjustment: 'Avoid/reduce in hepatic impairment and elderly — active metabolites accumulate. A glucuronidated (LOT) benzo is safer there.',
    startStopCrossTaper: 'Its long half-life makes it a preferred agent for tapering/cross-tapering off shorter-acting benzos and for alcohol-withdrawal "self-tapering" regimens.',
    administrationNotes: 'Rapid onset + long tail: fast symptom relief but prolonged accumulation.',
    commonSE: ['Sedation', 'Fatigue', 'Ataxia', 'Muscle weakness', 'Dizziness'],
    seriousAE: ['Respiratory depression (with opioids/alcohol)', 'Dependence and withdrawal (incl. seizures)', 'Falls/oversedation in elderly (accumulation)', 'Paradoxical disinhibition'],
    syndromes: ['Dependence/withdrawal (withdrawal seizures)', 'Respiratory depression (with CNS depressants)', 'Accumulation/oversedation in elderly', 'Falls', 'Paradoxical disinhibition'],
    overdoseLethality: 'LOW alone; HIGH with opioids/alcohol/other CNS depressants (respiratory depression).',
    discontinuationSyndrome: 'Withdrawal on stopping; long half-life gives a slower, milder, self-tapering course — but seizures still possible after high-dose/long-term use.',
    ongoingMonitoring: 'Sedation, accumulation (esp. elderly/hepatic), respiratory status with opioids, dependence.',
    majorDDI: ['Opioids (additive respiratory depression)', 'Alcohol/CNS depressants', 'CYP2C19/3A4 inhibitors (e.g., omeprazole, fluvoxamine → raise levels)', 'CYP inducers (lower levels)'],
    contraindicatedCombos: ['Opioids (avoid; lowest dose/shortest duration if unavoidable)', 'Alcohol/other CNS depressants', 'Severe respiratory insufficiency / untreated sleep apnea', 'Myasthenia gravis / severe hepatic impairment (caution per label)'],
    pregnancy: 'Avoid where possible; late/regular use → neonatal hypotonia, sedation, withdrawal ("floppy infant").',
    lactation: 'Long-acting with active metabolites — accumulation in the infant possible; a shorter-acting benzo is preferred if one is needed.',
    geriatric: 'Beers — avoid; active metabolites (desmethyldiazepam) accumulate → prolonged sedation, falls, confusion.',
    renalHepatic: 'Metabolites accumulate in hepatic impairment and renal failure; avoid in favour of a LOT agent.',
    pearls: [
      'Long-acting via active metabolites (desmethyldiazepam ~200 h) → smooth, self-tapering course; classic for alcohol withdrawal and for tapering off shorter benzos.',
      'Very lipophilic → fast onset for muscle spasm/acute seizures, but a long accumulation tail.',
      'Accumulation in the elderly/hepatic patients is the key pitfall — opposite of the "LOT" agents.',
    ],
    mnemonics: ['"diazepam = Deep and Durable" — Desmethyldiazepam Drags on for Days (accumulates).'],
    confusables: ['Diazepam vs lorazepam — diazepam is long-acting with active metabolites (accumulates); lorazepam is glucuronidated and liver-safe.', 'Desmethyldiazepam is the shared active metabolite of diazepam, clorazepate, and chlordiazepoxide.'],
    classDifferentiators: 'Long half-life via long-lived active metabolites, rapid lipophilic onset, muscle-relaxant/anticonvulsant/withdrawal uses; accumulates in elderly/hepatic disease.',
    examHooks: ['Which benzodiazepine self-tapers due to its long-half-life active metabolite (desmethyldiazepam)? (diazepam).', 'Why avoid diazepam in the elderly? (active-metabolite accumulation → falls/sedation).'],
    counsellingPoints: ['Effects and drowsiness can build up over days.', 'Avoid alcohol/opioids.', 'Do not stop abruptly after regular use.'],
    vignettes: [
      {
        stem: 'A 30-year-old in alcohol withdrawal with normal liver function is treated with a symptom-triggered benzodiazepine regimen. Which agent’s long-acting active metabolite provides a smooth, "self-tapering" course?',
        options: ['Oxazepam', 'Lorazepam', 'Diazepam', 'Alprazolam'],
        answer: 'Diazepam',
        explanation: 'Diazepam is oxidized to desmethyldiazepam (nordiazepam), an active metabolite with a very long half-life, giving a self-tapering effect useful in alcohol withdrawal when hepatic function is preserved; in significant liver disease, glucuronidated lorazepam/oxazepam are preferred.',
        testedFact: 'Diazepam active metabolite (desmethyldiazepam) and self-taper',
        source: { name: 'Standard psychopharmacology; alcohol-withdrawal management', origin: 'monograph' },
      },
    ],
    _prov: BENZO_PROV,
  },

  alprazolam: {
    pronunciation: 'al-PRAY-zoh-lam',
    moa: 'Benzodiazepine: GABA-A positive allosteric modulator (↑ Cl- channel opening frequency); high potency.',
    receptorProfile: 'Non-selective GABA-A benzodiazepine-site agonist.',
    onsetOfEffect: 'Rapid PO onset (~20–30 min) — quick anxiolysis reinforces its high misuse/dependence potential.',
    halfLife: '~11–16 h (short class); XR blunts peaks/troughs.',
    timeToSteadyState: '~2–3 days.',
    metabolism: 'Hepatic CYP3A4 to largely inactive metabolites → many CYP3A4 interactions.',
    activeMetabolites: 'None clinically significant.',
    approvedCanada: ['Panic disorder', 'Anxiety'],
    offLabel: ['Generalized anxiety (short-term)'],
    approvedPopulations: 'Adults.',
    startingDose: '0.25–0.5 mg PO TID (immediate-release); lower in elderly.',
    titration: 'Increase cautiously; frequent dosing needed because of the short half-life.',
    maxDose: 'Panic disorder up to ~4–10 mg/day in divided doses (rarely justified; higher doses raise dependence risk).',
    frequencyTiming: 'TID–QID (IR) due to short half-life; once daily for XR. Interdose rebound anxiety is common with IR.',
    startStopCrossTaper: 'Notoriously hard to stop — taper very slowly or cross-taper to a longer-acting benzo (e.g., clonazepam) first.',
    administrationNotes: 'Short half-life + high potency + rapid onset → the benzo most associated with interdose rebound, dependence, and difficult withdrawal.',
    commonSE: ['Sedation', 'Fatigue', 'Cognitive slowing/amnesia', 'Ataxia', 'Interdose rebound anxiety'],
    seriousAE: ['Respiratory depression (with opioids/alcohol)', 'Dependence and difficult withdrawal (incl. seizures)', 'Rebound/interdose anxiety', 'Falls in elderly', 'Paradoxical disinhibition'],
    syndromes: ['Dependence/withdrawal (severe; withdrawal seizures)', 'Interdose rebound', 'Respiratory depression (with CNS depressants)', 'Falls', 'Paradoxical disinhibition'],
    overdoseLethality: 'LOW alone; HIGH with opioids/alcohol/other CNS depressants (respiratory depression).',
    discontinuationSyndrome: 'Among the worst — rebound anxiety, insomnia, tremor, seizures; short half-life makes abrupt withdrawal especially dangerous. Taper very slowly.',
    ongoingMonitoring: 'Dependence/escalation, interdose rebound, sedation, respiratory status with opioids, falls in elderly.',
    majorDDI: ['Opioids (additive respiratory depression)', 'Alcohol/CNS depressants', 'Strong CYP3A4 inhibitors (ketoconazole, itraconazole, ritonavir, clarithromycin, nefazodone → raise levels/toxicity)', 'CYP3A4 inducers (carbamazepine → lower levels)'],
    contraindicatedCombos: ['Opioids (avoid; lowest dose/shortest duration if unavoidable)', 'Alcohol/other CNS depressants', 'Strong CYP3A4 inhibitors (e.g., itraconazole, ketoconazole — contraindicated per label)', 'Severe respiratory insufficiency / untreated sleep apnea'],
    pregnancy: 'Avoid; late/regular use → neonatal sedation, hypotonia, withdrawal.',
    lactation: 'Passes into milk; monitor infant for sedation.',
    geriatric: 'Beers — avoid; sedation, falls, and cognitive impairment; high dependence potential.',
    pearls: [
      'Short half-life + high potency + fast onset → the benzo most linked to interdose rebound, dependence, and a difficult, dangerous taper.',
      'CYP3A4 substrate — strong 3A4 inhibitors (azoles, protease inhibitors, clarithromycin) markedly raise levels.',
      'To discontinue, consider cross-tapering to a longer-acting benzo (clonazepam) first.',
    ],
    mnemonics: ['"Alprazolam = Addictive, Abrupt-rebound" — short-acting, high-potency, hardest to stop.'],
    confusables: ['Alprazolam vs lorazepam — both short/intermediate anxiolytics; alprazolam is CYP3A4 (interactions) and higher-potency with worse rebound/dependence, whereas lorazepam is glucuronidated, liver-safe, and available IM/IV.'],
    classDifferentiators: 'Short half-life, high potency, rapid onset, CYP3A4 metabolism, worst interdose rebound/dependence of the anxiolytic benzos.',
    examHooks: ['Which benzodiazepine has the greatest interdose rebound and dependence potential, and why? (alprazolam — short half-life, high potency, rapid onset).', 'Which CYP mediates alprazolam metabolism? (CYP3A4).'],
    counsellingPoints: ['Take exactly as prescribed — do not escalate.', 'Never stop suddenly — seizures can occur; taper with your prescriber.', 'Avoid alcohol/opioids and grapefruit-type CYP3A4 interactions.'],
    vignettes: [
      {
        stem: 'A patient on alprazolam for panic disorder starts itraconazole for onychomycosis and becomes markedly sedated and ataxic. What is the mechanism?',
        options: ['Itraconazole displaces alprazolam from albumin', 'Itraconazole inhibits CYP3A4, raising alprazolam levels', 'Itraconazole induces glucuronidation of alprazolam', 'Additive serotonergic toxicity'],
        answer: 'Itraconazole inhibits CYP3A4, raising alprazolam levels',
        explanation: 'Alprazolam is metabolized by CYP3A4; strong 3A4 inhibitors (azole antifungals, macrolides, protease inhibitors, nefazodone) reduce its clearance and cause accumulation with excess sedation — a labelled interaction.',
        testedFact: 'Alprazolam CYP3A4 interaction',
        source: { name: 'openFDA/DailyMed alprazolam label — drug interactions (CYP3A4)', origin: 'openfda' },
      },
    ],
    _prov: BENZO_PROV,
  },

  oxazepam: {
    pronunciation: 'ox-AZ-uh-pam',
    moa: 'Benzodiazepine: GABA-A positive allosteric modulator (↑ Cl- channel opening frequency).',
    receptorProfile: 'Non-selective GABA-A benzodiazepine-site agonist.',
    onsetOfEffect: 'Slow onset (PO ~1–2 h) — least abuse-reinforcing kinetics of the benzos.',
    halfLife: '~5–15 h (short class).',
    timeToSteadyState: '~2–3 days.',
    metabolism: 'GLUCURONIDATION (UGT) only — NO oxidative CYP step; preserved in liver disease.',
    activeMetabolites: 'None (inactive glucuronide).',
    elimination: 'Renal (inactive conjugate).',
    approvedCanada: ['Anxiety', 'Anxiety associated with depression', 'Alcohol withdrawal (acute)'],
    offLabel: ['Insomnia'],
    approvedPopulations: 'Adults.',
    startingDose: '10–15 mg PO 3–4×/day for anxiety; 15–30 mg TID–QID in alcohol withdrawal.',
    titration: 'Titrate to symptom control; short half-life needs frequent dosing.',
    maxDose: 'Up to ~120 mg/day in divided doses (severe cases).',
    frequencyTiming: 'TID–QID (short half-life).',
    renalHepaticAdjustment: 'Preferred in hepatic impairment (glucuronidation preserved), like other "LOT" agents.',
    startStopCrossTaper: 'Taper after regular use; slow onset and short duration limit misuse but require frequent dosing.',
    administrationNotes: 'A "LOT" liver-safe agent; slow onset makes it comparatively low in abuse liability.',
    commonSE: ['Sedation', 'Dizziness', 'Ataxia', 'Headache', 'Fatigue'],
    seriousAE: ['Respiratory depression (with opioids/alcohol)', 'Dependence and withdrawal (incl. seizures)', 'Falls in elderly', 'Paradoxical disinhibition'],
    syndromes: ['Dependence/withdrawal (withdrawal seizures)', 'Respiratory depression (with CNS depressants)', 'Falls/cognitive impairment (elderly)', 'Paradoxical disinhibition'],
    overdoseLethality: 'LOW alone; HIGH with opioids/alcohol/other CNS depressants.',
    discontinuationSyndrome: 'Withdrawal after regular use (rebound anxiety/insomnia, seizures if abrupt); taper.',
    ongoingMonitoring: 'Sedation, dependence, respiratory status with opioids, falls in elderly.',
    majorDDI: ['Opioids (additive respiratory depression)', 'Alcohol/CNS depressants'],
    contraindicatedCombos: ['Opioids (avoid; lowest dose/shortest duration if unavoidable)', 'Alcohol/other CNS depressants', 'Severe respiratory insufficiency / untreated sleep apnea'],
    pregnancy: 'Avoid where possible; late/regular use → neonatal sedation/hypotonia/withdrawal.',
    lactation: 'Short-acting without active metabolite — comparatively preferred if a benzo is needed; monitor infant.',
    geriatric: 'Beers — avoid; but if a benzo is required, this glucuronidated short-acting agent is often preferred over long-acting/active-metabolite benzos.',
    renalHepatic: 'Liver-safe; no active metabolite to accumulate in renal impairment.',
    pearls: [
      'A "LOT" agent (glucuronidation only, no active metabolite) — liver- and elderly-preferred, used in alcohol withdrawal when hepatic function is impaired.',
      'Slow onset → low abuse-reinforcement relative to alprazolam/diazepam.',
      'Is itself an active metabolite of diazepam.',
    ],
    mnemonics: ['"LOT" = Lorazepam, Oxazepam, Temazepam → glucuronidated, liver-safe.'],
    confusables: ['Oxazepam vs temazepam — both glucuronidated LOT agents; temazepam is marketed as a hypnotic, oxazepam as an anxiolytic/withdrawal agent.'],
    classDifferentiators: 'Short half-life, glucuronidation (no CYP, no active metabolite), slow onset (low abuse liability) — liver-safe anxiolytic/withdrawal agent.',
    examHooks: ['Name the three glucuronidated, liver-safe benzodiazepines. (Lorazepam, Oxazepam, Temazepam — "LOT").'],
    counsellingPoints: ['Onset is gradual; take on schedule rather than expecting an instant effect.', 'Avoid alcohol/opioids.', 'Do not stop abruptly after regular use.'],
    vignettes: [
      {
        stem: 'Which of the following benzodiazepines shares with lorazepam and temazepam the property of being metabolized solely by glucuronidation (making it a preferred choice in cirrhosis)?',
        options: ['Diazepam', 'Chlordiazepoxide', 'Oxazepam', 'Clorazepate'],
        answer: 'Oxazepam',
        explanation: 'Oxazepam is one of the "LOT" benzodiazepines (Lorazepam, Oxazepam, Temazepam) cleared by glucuronidation without oxidative CYP metabolism and with no active metabolite, making it preferable in hepatic impairment and the elderly.',
        testedFact: 'Oxazepam glucuronidation / LOT',
        source: { name: 'Standard psychopharmacology; benzodiazepine metabolism', origin: 'monograph' },
      },
    ],
    _prov: BENZO_PROV,
  },

  temazepam: {
    pronunciation: 'teh-MAZ-uh-pam',
    moa: 'Benzodiazepine: GABA-A positive allosteric modulator (↑ Cl- channel opening frequency); marketed as a hypnotic.',
    receptorProfile: 'Non-selective GABA-A benzodiazepine-site agonist.',
    onsetOfEffect: 'PO onset ~30–60 min — timed for sleep onset/maintenance.',
    halfLife: '~8–15 h (intermediate class) — hypnotic duration with limited next-day hangover relative to long-acting agents.',
    timeToSteadyState: '~2–3 days.',
    metabolism: 'GLUCURONIDATION (UGT) only — NO oxidative CYP step; liver-safe.',
    activeMetabolites: 'None (inactive glucuronide).',
    elimination: 'Renal (inactive conjugate).',
    approvedCanada: ['Insomnia (short-term)'],
    offLabel: [],
    approvedPopulations: 'Adults.',
    startingDose: '15 mg PO at bedtime (7.5 mg in elderly/debilitated).',
    titration: 'Use the lowest effective dose for the shortest time.',
    maxDose: '30 mg at bedtime.',
    frequencyTiming: 'At bedtime; intermediate half-life aids sleep maintenance with modest morning residue.',
    renalHepaticAdjustment: 'Preferred in hepatic impairment (glucuronidation); reduce in elderly.',
    startStopCrossTaper: 'Taper after regular nightly use to avoid rebound insomnia.',
    administrationNotes: 'A "LOT" liver-safe hypnotic — the glucuronidated benzodiazepine sleep agent.',
    commonSE: ['Daytime drowsiness/residual sedation', 'Dizziness', 'Headache', 'Anterograde amnesia'],
    seriousAE: ['Respiratory depression (with opioids/alcohol)', 'Dependence and rebound insomnia', 'Complex sleep behaviours (sleep-driving)', 'Falls in elderly'],
    syndromes: ['Dependence/rebound insomnia', 'Respiratory depression (with CNS depressants)', 'Falls/cognitive impairment (elderly)', 'Complex sleep behaviours', 'Anterograde amnesia'],
    overdoseLethality: 'LOW alone; HIGH with opioids/alcohol/other CNS depressants.',
    discontinuationSyndrome: 'Rebound insomnia and anxiety after regular use; taper.',
    ongoingMonitoring: 'Residual daytime sedation, dependence, falls in elderly, respiratory status with opioids.',
    majorDDI: ['Opioids (additive respiratory depression)', 'Alcohol/CNS depressants'],
    contraindicatedCombos: ['Opioids (avoid; lowest dose/shortest duration if unavoidable)', 'Alcohol/other CNS depressants', 'Severe respiratory insufficiency / untreated sleep apnea'],
    pregnancy: 'Avoid; late use → neonatal sedation/hypotonia/withdrawal.',
    lactation: 'Monitor infant for sedation.',
    geriatric: 'Beers — avoid hypnotic benzos in older adults (falls, next-day impairment); if used, this glucuronidated agent is preferred and dose-reduced.',
    renalHepatic: 'Liver-safe; no active metabolite.',
    pearls: [
      'A "LOT" agent — glucuronidated, no active metabolite; the liver-safe benzodiazepine hypnotic.',
      'Intermediate half-life targets sleep maintenance with less accumulation than flurazepam/nitrazepam.',
      'Like other hypnotics, can cause complex sleep behaviours (sleep-driving) and anterograde amnesia.',
    ],
    mnemonics: ['"LOT" = Lorazepam, Oxazepam, Temazepam → glucuronidated, liver-safe (Temazepam = the sleep one).'],
    confusables: ['Temazepam vs triazolam — both hypnotics, but temazepam is intermediate/glucuronidated (liver-safe) whereas triazolam is ultra-short and CYP3A4 (many interactions, marked amnesia/rebound).'],
    classDifferentiators: 'Intermediate half-life, glucuronidation (no CYP, no active metabolite) — the liver-safe benzo hypnotic for sleep maintenance.',
    examHooks: ['Which benzodiazepine hypnotic is glucuronidated and therefore safer in liver disease? (temazepam — a "LOT" agent).'],
    counsellingPoints: ['Take right before bed; allow 7–8 hours for sleep to avoid next-day drowsiness.', 'Avoid alcohol/opioids.', 'Do not drive if drowsy; report any sleep-driving.'],
    vignettes: [
      {
        stem: 'A 68-year-old with compensated cirrhosis has short-term insomnia and you must briefly use a benzodiazepine hypnotic. Which agent avoids oxidative hepatic metabolism and long active metabolites?',
        options: ['Flurazepam', 'Nitrazepam', 'Temazepam', 'Triazolam'],
        answer: 'Temazepam',
        explanation: 'Temazepam is a "LOT" benzodiazepine cleared by glucuronidation with no active metabolite, so it avoids the accumulation seen with oxidatively metabolized/long-acting hypnotics (flurazepam, nitrazepam) in liver disease and the elderly.',
        testedFact: 'Temazepam glucuronidation (liver-safe hypnotic)',
        source: { name: 'Standard psychopharmacology; benzodiazepine hypnotic metabolism', origin: 'monograph' },
      },
    ],
    _prov: BENZO_PROV,
  },

  chlordiazepoxide: {
    pronunciation: 'klor-dy-az-eh-POX-ide',
    moa: 'Benzodiazepine: GABA-A positive allosteric modulator (↑ Cl- channel opening frequency); the classic long-acting alcohol-withdrawal agent.',
    receptorProfile: 'Non-selective GABA-A benzodiazepine-site agonist.',
    onsetOfEffect: 'PO onset ~1–2 h; long-lasting effect via active metabolites.',
    halfLife: 'Parent ~5–30 h, but active metabolites (desmethylchlordiazepoxide, demoxepam, desmethyldiazepam) extend effective duration to the LONG class.',
    timeToSteadyState: 'Up to ~1–2 weeks (long-lived active metabolites).',
    metabolism: 'Hepatic oxidation (CYP) to ACTIVE metabolites, including desmethyldiazepam.',
    activeMetabolites: 'Desmethylchlordiazepoxide, demoxepam, desmethyldiazepam (long-acting) — accumulate.',
    approvedCanada: ['Anxiety', 'Alcohol withdrawal', 'Preoperative apprehension'],
    offLabel: [],
    approvedPopulations: 'Adults.',
    startingDose: 'Alcohol withdrawal: 50–100 mg PO, repeated per protocol (symptom-triggered or fixed taper). Anxiety: 5–25 mg TID–QID.',
    titration: 'Titrate to withdrawal symptoms (e.g., CIWA); taper over days.',
    maxDose: 'Up to ~300 mg/day in divided doses (supervised withdrawal).',
    frequencyTiming: 'TID–QID or symptom-triggered; long metabolites give a self-tapering effect.',
    renalHepaticAdjustment: 'Avoid/reduce in significant hepatic impairment and elderly — active metabolites accumulate; prefer a LOT agent (lorazepam/oxazepam) there.',
    startStopCrossTaper: 'Long half-life supports a smooth fixed-dose alcohol-withdrawal taper.',
    administrationNotes: 'The prototypical fixed-schedule alcohol-withdrawal benzodiazepine.',
    commonSE: ['Sedation', 'Ataxia', 'Confusion (esp. elderly)', 'Fatigue', 'Dizziness'],
    seriousAE: ['Respiratory depression (with opioids/alcohol)', 'Dependence and withdrawal (incl. seizures)', 'Oversedation/accumulation in elderly', 'Paradoxical disinhibition'],
    syndromes: ['Dependence/withdrawal (withdrawal seizures)', 'Respiratory depression (with CNS depressants)', 'Accumulation/oversedation in elderly', 'Paradoxical disinhibition'],
    overdoseLethality: 'LOW alone; HIGH with opioids/alcohol/other CNS depressants.',
    discontinuationSyndrome: 'Withdrawal on stopping; long half-life gives a gentler, self-tapering course — still taper after high-dose use.',
    ongoingMonitoring: 'Withdrawal severity (CIWA), sedation/accumulation (esp. elderly/hepatic), respiratory status with opioids.',
    majorDDI: ['Opioids (additive respiratory depression)', 'Alcohol/CNS depressants', 'CYP inhibitors (raise levels)'],
    contraindicatedCombos: ['Opioids (avoid; lowest dose/shortest duration if unavoidable)', 'Alcohol/other CNS depressants', 'Severe respiratory insufficiency / untreated sleep apnea'],
    pregnancy: 'Avoid; late/regular use → neonatal sedation/hypotonia/withdrawal.',
    lactation: 'Long-acting with active metabolites — accumulation possible; a shorter agent is preferred.',
    geriatric: 'Beers — avoid; active-metabolite accumulation → prolonged sedation, confusion, falls. Use lorazepam/oxazepam instead for withdrawal in the elderly/hepatic patients.',
    renalHepatic: 'Active metabolites accumulate in hepatic/renal impairment — avoid there.',
    pearls: [
      'The classic long-acting alcohol-withdrawal benzo for a smooth fixed-dose taper (normal liver function).',
      'Multiple long-lived active metabolites (including desmethyldiazepam) → accumulation, especially in the elderly/hepatic disease.',
      'In cirrhosis or the frail elderly, switch to a "LOT" agent (lorazepam/oxazepam) for withdrawal.',
    ],
    mnemonics: ['"Chlordiazepoxide = Classic for the Cage/CIWA" — long-acting alcohol-withdrawal taper.'],
    confusables: ['Chlordiazepoxide vs clordiazepate/clorazepate — both feed into desmethyldiazepam; chlordiazepoxide is the older Librium withdrawal agent.'],
    classDifferentiators: 'Long half-life via multiple active metabolites; oxidatively metabolized; the prototypical alcohol-withdrawal taper agent — but accumulates in elderly/hepatic disease.',
    examHooks: ['Classic long-acting benzo for alcohol-withdrawal taper in patients with normal liver function? (chlordiazepoxide).', 'When would you switch it to lorazepam/oxazepam? (hepatic impairment / frail elderly).'],
    counsellingPoints: ['Take as scheduled during withdrawal; do not add alcohol.', 'Drowsiness may accumulate over days.', 'Do not stop abruptly.'],
    vignettes: [
      {
        stem: 'A 45-year-old with alcohol use disorder and normal liver function is admitted for withdrawal. Which benzodiazepine is the classic choice for a fixed-dose "self-tapering" regimen?',
        options: ['Chlordiazepoxide', 'Alprazolam', 'Triazolam', 'Midazolam'],
        answer: 'Chlordiazepoxide',
        explanation: 'Chlordiazepoxide (and diazepam) are long-acting via active metabolites, producing a smooth self-tapering course favoured for alcohol withdrawal when liver function is preserved; in hepatic impairment, glucuronidated lorazepam/oxazepam are used instead.',
        testedFact: 'Chlordiazepoxide in alcohol withdrawal',
        source: { name: 'Standard psychopharmacology; alcohol-withdrawal management', origin: 'monograph' },
      },
    ],
    _prov: BENZO_PROV,
  },

  midazolam: {
    pronunciation: 'mih-DAZ-oh-lam',
    moa: 'Benzodiazepine: GABA-A positive allosteric modulator (↑ Cl- channel opening frequency); water-soluble at low pH, highly lipophilic at physiologic pH → rapid CNS entry.',
    receptorProfile: 'Non-selective GABA-A benzodiazepine-site agonist.',
    onsetOfEffect: 'Very fast: IV ~1–3 min, IM ~5–15 min, intranasal/buccal minutes — brief duration.',
    halfLife: '~1.5–3 h (ULTRA-SHORT class).',
    timeToSteadyState: 'Rapid; usually given as single/procedural doses or infusion.',
    metabolism: 'Hepatic CYP3A4 to 1-hydroxymidazolam (then glucuronidated) → strong CYP3A4-interaction potential; clearance falls in critical illness/hepatic dysfunction.',
    activeMetabolites: '1-hydroxymidazolam (active; can accumulate with prolonged infusions or renal failure).',
    approvedCanada: ['Procedural/conscious sedation', 'Preoperative sedation/anxiolysis', 'Induction/maintenance of anesthesia', 'ICU sedation'],
    offLabel: ['Status epilepticus (IM/IV/intranasal/buccal)', 'Palliative sedation'],
    approvedPopulations: 'Adults and children (procedural).',
    startingDose: 'Procedural sedation: titrate small IV increments (e.g., 0.5–2 mg) to effect; seizures: 10 mg IM (or intranasal/buccal) per protocol.',
    titration: 'Titrate slowly to effect with continuous monitoring; effects potentiated by opioids.',
    maxDose: 'Setting-dependent; titrate to clinical endpoint under monitoring rather than a fixed ceiling.',
    frequencyTiming: 'Single doses or infusion; IV/IM/intranasal/buccal routes.',
    renalHepaticAdjustment: 'Active metabolite (1-OH-midazolam) accumulates in renal failure and prolonged infusions → delayed awakening; reduce in hepatic dysfunction/critical illness.',
    administrationNotes: 'Requires resuscitation-capable monitoring; intranasal/buccal/IM routes make it useful for seizures without IV access.',
    commonSE: ['Sedation', 'Amnesia (used therapeutically)', 'Hypotension', 'Hiccups', 'Injection-site effects'],
    seriousAE: ['Respiratory depression/apnea (dose-related; marked with opioids)', 'Airway obstruction', 'Hypotension', 'Paradoxical agitation', 'Delayed emergence (prolonged infusion/renal failure)'],
    syndromes: ['Respiratory depression/apnea (with opioids/procedural over-sedation)', 'Paradoxical disinhibition', 'Delayed emergence (metabolite accumulation)', 'Amnesia'],
    overdoseLethality: 'LOW alone but respiratory depression/apnea is dose-related and rapid; HIGH with opioids. Requires airway/monitoring capability; flumazenil available.',
    discontinuationSyndrome: 'Withdrawal after prolonged ICU infusions — taper the infusion.',
    ongoingMonitoring: 'Continuous respiratory rate/SpO2, blood pressure, level of sedation; capnography for deeper sedation.',
    majorDDI: ['Opioids (additive respiratory depression)', 'Strong CYP3A4 inhibitors (azoles, protease inhibitors, clarithromycin → raise levels/prolong sedation)', 'CYP3A4 inducers (lower levels)', 'Alcohol/CNS depressants'],
    contraindicatedCombos: ['Strong CYP3A4 inhibitors (e.g., oral midazolam with protease inhibitors/azoles — contraindicated per label)', 'Opioids without airway monitoring', 'Alcohol/other CNS depressants', 'Acute narrow-angle glaucoma (per label)'],
    pregnancy: 'Reserve for procedural/emergency indications; neonatal exposure risks sedation/respiratory depression.',
    lactation: 'Single procedural doses generally compatible; monitor infant after larger/repeated exposure.',
    geriatric: 'Highly sensitive to respiratory depression/hypotension — use markedly reduced, slowly titrated doses.',
    renalHepatic: 'Active metabolite accumulates in renal failure and with prolonged infusion; reduce/monitor.',
    pearls: [
      'Ultra-short acting, water-soluble → procedural sedation workhorse; IM/intranasal/buccal routes treat seizures without IV access.',
      'CYP3A4 substrate — strong inhibitors prolong sedation; 1-hydroxymidazolam accumulates in renal failure/long infusions → delayed awakening.',
      'Only give where airway management and monitoring are available; flumazenil reverses.',
    ],
    mnemonics: ['"Midazolam = Minutes" — ultra-short onset/offset for procedures.'],
    confusables: ['Midazolam vs lorazepam for status epilepticus — IM/intranasal midazolam is preferred when there is no IV access; IV lorazepam when access exists.'],
    classDifferentiators: 'Ultra-short half-life, CYP3A4 metabolism with an active renally-cleared metabolite, multiple parenteral routes — the procedural-sedation/anesthesia benzo.',
    examHooks: ['Benzodiazepine of choice for seizures when there is NO IV access? (IM or intranasal midazolam).', 'Why can ICU midazolam infusions cause delayed awakening in renal failure? (accumulation of active 1-hydroxymidazolam).'],
    counsellingPoints: ['You may not remember the procedure (expected amnesia).', 'Do not drive or make important decisions for 24 h.', 'Arrange an escort home.'],
    vignettes: [
      {
        stem: 'A child in the community has ongoing tonic-clonic seizures and no IV access. Which benzodiazepine and route is most appropriate as first-line?',
        options: ['IV lorazepam', 'Oral diazepam', 'Intramuscular/intranasal midazolam', 'Oral clonazepam'],
        answer: 'Intramuscular/intranasal midazolam',
        explanation: 'Without IV access, IM or intranasal/buccal midazolam has rapid absorption and reliably aborts seizures (RAMPART trial); IV lorazepam is first-line only when IV access exists.',
        testedFact: 'Midazolam (IM/intranasal) for status without IV access',
        source: { name: 'Status epilepticus guidelines; RAMPART evidence', origin: 'monograph' },
      },
    ],
    _prov: BENZO_PROV,
  },

  bromazepam: {
    pronunciation: 'broh-MAZ-uh-pam',
    moa: 'Benzodiazepine: GABA-A positive allosteric modulator (↑ Cl- channel opening frequency).',
    receptorProfile: 'Non-selective GABA-A benzodiazepine-site agonist.',
    onsetOfEffect: 'PO onset ~1–2 h.',
    halfLife: '~10–20 h (intermediate class).',
    timeToSteadyState: '~2–3 days.',
    metabolism: 'Hepatic oxidation (CYP) to metabolites (some minor activity).',
    activeMetabolites: 'Hydroxy-bromazepam (minor).',
    approvedCanada: ['Anxiety (short-term)'],
    offLabel: ['Insomnia associated with anxiety'],
    approvedPopulations: 'Adults.',
    startingDose: '6–18 mg/day PO in divided doses (lower in elderly); an available Canadian anxiolytic benzodiazepine.',
    titration: 'Lowest effective dose; titrate gradually.',
    maxDose: 'Up to ~30 mg/day in divided doses (severe cases; specialist settings).',
    frequencyTiming: 'BID–TID (intermediate half-life).',
    renalHepaticAdjustment: 'Reduce in hepatic impairment/elderly (oxidative metabolism).',
    startStopCrossTaper: 'Taper after regular use.',
    administrationNotes: 'A Canada/Europe-available anxiolytic benzodiazepine (not marketed in the US).',
    commonSE: ['Sedation', 'Dizziness', 'Ataxia', 'Fatigue'],
    seriousAE: ['Respiratory depression (with opioids/alcohol)', 'Dependence and withdrawal (incl. seizures)', 'Falls in elderly', 'Paradoxical disinhibition'],
    syndromes: ['Dependence/withdrawal (withdrawal seizures)', 'Respiratory depression (with CNS depressants)', 'Falls/cognitive impairment (elderly)', 'Paradoxical disinhibition'],
    overdoseLethality: 'LOW alone; HIGH with opioids/alcohol/other CNS depressants.',
    discontinuationSyndrome: 'Withdrawal after regular use; taper.',
    ongoingMonitoring: 'Sedation, dependence, respiratory status with opioids, falls in elderly.',
    majorDDI: ['Opioids (additive respiratory depression)', 'Alcohol/CNS depressants', 'CYP inhibitors (raise levels)'],
    contraindicatedCombos: ['Opioids (avoid; lowest dose/shortest duration if unavoidable)', 'Alcohol/other CNS depressants', 'Severe respiratory insufficiency / untreated sleep apnea'],
    pregnancy: 'Avoid; late/regular use → neonatal sedation/hypotonia/withdrawal.',
    lactation: 'Monitor infant for sedation.',
    geriatric: 'Beers — avoid; sedation and falls.',
    pearls: [
      'A Canadian/European anxiolytic benzodiazepine (not US-marketed) with an intermediate half-life.',
      'Behaves like a mid-range anxiolytic benzo — dependence/withdrawal cautions apply as for the class.',
    ],
    mnemonics: ['"Bromazepam = a Canadian anxiolytic benzo" — remember it is not on the US market.'],
    confusables: ['Bromazepam vs lorazepam — both intermediate anxiolytics; lorazepam is glucuronidated/IM-available while bromazepam is oxidatively metabolized and Canada/Europe-only.'],
    classDifferentiators: 'Intermediate half-life anxiolytic; oxidatively metabolized; Canada/Europe-available (US-unavailable).',
    examHooks: ['Which anxiolytic benzodiazepine is available in Canada/Europe but not the US? (bromazepam is one example).'],
    counsellingPoints: ['Avoid alcohol/opioids.', 'Short-term use only; do not stop abruptly.', 'May impair driving.'],
    vignettes: [
      {
        stem: 'A patient transferring care from Canada asks about "bromazepam," which their US pharmacy does not stock. Which statement is correct?',
        options: ['It is a long-acting antipsychotic', 'It is an anxiolytic benzodiazepine available in Canada but not marketed in the US', 'It is a glucuronidated agent preferred in cirrhosis', 'It is an SSRI'],
        answer: 'It is an anxiolytic benzodiazepine available in Canada but not marketed in the US',
        explanation: 'Bromazepam is an intermediate-acting anxiolytic benzodiazepine used in Canada and Europe but not marketed in the United States; class dependence/withdrawal and CNS-depressant cautions apply.',
        testedFact: 'Bromazepam Canadian availability/class',
        source: { name: 'Health Canada DPD; benzodiazepine class facts', origin: 'monograph' },
      },
    ],
    _prov: BENZO_PROV,
  },

  nitrazepam: {
    pronunciation: 'ny-TRAZ-uh-pam',
    moa: 'Benzodiazepine: GABA-A positive allosteric modulator (↑ Cl- channel opening frequency); long-acting hypnotic.',
    receptorProfile: 'Non-selective GABA-A benzodiazepine-site agonist.',
    onsetOfEffect: 'PO onset ~30–60 min; long duration → next-day residual sedation.',
    halfLife: '~16–40 h (long class).',
    timeToSteadyState: '~5–7 days.',
    metabolism: 'Hepatic nitro-reduction/acetylation to inactive metabolites.',
    activeMetabolites: 'None clinically significant (but long parent half-life).',
    approvedCanada: ['Insomnia (short-term)', 'Myoclonic seizures (incl. infantile spasms, adjunct)'],
    offLabel: [],
    approvedPopulations: 'Adults; children (some seizure syndromes).',
    startingDose: '5 mg PO at bedtime (2.5 mg in elderly).',
    titration: 'Lowest effective dose; short-term use.',
    maxDose: '~10 mg at bedtime.',
    frequencyTiming: 'At bedtime; long half-life causes next-day carryover.',
    renalHepaticAdjustment: 'Reduce in elderly/hepatic impairment (long half-life, carryover).',
    startStopCrossTaper: 'Taper after regular nightly use.',
    administrationNotes: 'A Canada/Europe-available long-acting hypnotic (not US-marketed).',
    commonSE: ['Next-day drowsiness/hangover', 'Dizziness', 'Ataxia', 'Headache'],
    seriousAE: ['Respiratory depression (with opioids/alcohol)', 'Dependence and rebound insomnia', 'Falls in elderly (carryover)', 'Paradoxical disinhibition', 'Bronchial hypersecretion (infants)'],
    syndromes: ['Dependence/rebound insomnia', 'Respiratory depression (with CNS depressants)', 'Falls/next-day impairment (elderly)', 'Paradoxical disinhibition'],
    overdoseLethality: 'LOW alone; HIGH with opioids/alcohol/other CNS depressants.',
    discontinuationSyndrome: 'Rebound insomnia/anxiety after regular use; taper.',
    ongoingMonitoring: 'Next-day sedation/falls, dependence, respiratory status with opioids.',
    majorDDI: ['Opioids (additive respiratory depression)', 'Alcohol/CNS depressants'],
    contraindicatedCombos: ['Opioids (avoid; lowest dose/shortest duration if unavoidable)', 'Alcohol/other CNS depressants', 'Severe respiratory insufficiency / untreated sleep apnea'],
    pregnancy: 'Avoid; late use → neonatal sedation/hypotonia/withdrawal.',
    lactation: 'Long-acting — infant accumulation possible; a shorter hypnotic preferred.',
    geriatric: 'Beers — avoid; long half-life → next-day impairment and falls in older adults.',
    pearls: [
      'Long-acting hypnotic (Canada/Europe, not US) → next-day hangover and falls, especially in the elderly.',
      'Contrast with the intermediate glucuronidated hypnotic temazepam, which accumulates less.',
    ],
    mnemonics: ['"Nitrazepam = Night-and-day" — long half-life leaves a next-day hangover.'],
    confusables: ['Nitrazepam vs temazepam — both benzo hypnotics; nitrazepam is long-acting (carryover) while temazepam is intermediate/glucuronidated (liver-safe, less carryover).'],
    classDifferentiators: 'Long half-life hypnotic; Canada/Europe-available (US-unavailable); notable next-day residual sedation.',
    examHooks: ['Which benzodiazepine hypnotic is long-acting with notable next-day sedation and is not US-marketed? (nitrazepam).'],
    counsellingPoints: ['Expect possible next-morning grogginess; caution driving.', 'Avoid alcohol/opioids.', 'Short-term use; taper when stopping.'],
    vignettes: [
      {
        stem: 'An 80-year-old on nightly nitrazepam presents with morning falls and daytime drowsiness. What property of the drug best explains this?',
        options: ['Ultra-short half-life causing rebound', 'Long half-life causing next-day carryover in the elderly', 'Glucuronidation with no active metabolite', 'Potent CYP3A4 inhibition'],
        answer: 'Long half-life causing next-day carryover in the elderly',
        explanation: 'Nitrazepam is long-acting; in older adults its prolonged half-life produces next-day residual sedation, unsteadiness, and falls — a reason it is avoided (Beers) and shorter agents are preferred.',
        testedFact: 'Nitrazepam long half-life / geriatric carryover',
        source: { name: 'Beers criteria; benzodiazepine hypnotic pharmacology', origin: 'monograph' },
      },
    ],
    _prov: BENZO_PROV,
  },

  clobazam: {
    pronunciation: 'KLOH-baz-am',
    moa: 'A 1,5-benzodiazepine: GABA-A positive allosteric modulator (↑ Cl- channel opening frequency). The 1,5 structure gives relatively more anticonvulsant/anxiolytic effect with comparatively less sedation than classic 1,4-benzodiazepines.',
    receptorProfile: 'GABA-A benzodiazepine-site agonist (1,5-benzodiazepine).',
    onsetOfEffect: 'PO onset within ~1–2 h; anticonvulsant benefit builds over days.',
    halfLife: 'Parent ~18 h; active metabolite N-desmethylclobazam ~40–80 h (LONG effective duration).',
    timeToSteadyState: '~1–2 weeks (long active metabolite).',
    metabolism: 'Hepatic CYP3A4 (and 2C19/2B6) to N-desmethylclobazam, which is cleared by CYP2C19 — so CYP2C19 poor metabolizers/inhibitors accumulate the active metabolite.',
    activeMetabolites: 'N-desmethylclobazam (active, long-lived; the main contributor at steady state).',
    approvedCanada: ['Epilepsy (adjunctive, incl. Lennox-Gastaut syndrome)', 'Anxiety (some indications)'],
    offLabel: ['Refractory focal seizures (adjunct)', 'Catamenial epilepsy'],
    approvedPopulations: 'Adults and children (seizures).',
    startingDose: 'Seizures: ~5–10 mg/day PO, titrate by weight; e.g., 5 mg/day (≤30 kg) or 10 mg/day (>30 kg).',
    titration: 'Increase gradually over weeks per weight/response.',
    maxDose: '~20–40 mg/day depending on weight.',
    frequencyTiming: 'Once or twice daily (long active metabolite).',
    renalHepaticAdjustment: 'Reduce in hepatic impairment; slower titration in CYP2C19 poor metabolizers (higher N-desmethylclobazam).',
    startStopCrossTaper: 'Taper to avoid withdrawal/seizure exacerbation.',
    administrationNotes: 'Less sedating than classic benzos at anticonvulsant doses — a niche epilepsy adjunct.',
    commonSE: ['Sedation (less than classic benzos)', 'Somnolence', 'Drooling/dysarthria (children)', 'Ataxia', 'Aggression/irritability'],
    seriousAE: ['Respiratory depression (with opioids/alcohol)', 'Serious skin reactions (Stevens-Johnson/TEN) — rare', 'Dependence and withdrawal', 'Tolerance to anticonvulsant effect'],
    syndromes: ['Dependence/withdrawal (seizure exacerbation on abrupt stop)', 'Respiratory depression (with CNS depressants)', 'Severe cutaneous reactions (rare)', 'Paradoxical disinhibition'],
    overdoseLethality: 'LOW alone; HIGH with opioids/alcohol/other CNS depressants.',
    discontinuationSyndrome: 'Withdrawal and seizure exacerbation if stopped abruptly; taper.',
    ongoingMonitoring: 'Seizure frequency, sedation, skin reactions early in therapy, respiratory status with opioids.',
    majorDDI: ['Opioids (additive respiratory depression)', 'Alcohol/CNS depressants', 'Strong CYP2C19 inhibitors (e.g., fluconazole, omeprazole → raise N-desmethylclobazam)', 'CYP3A4 inducers (may lower clobazam)', 'Clobazam can raise CYP2D6 substrates'],
    contraindicatedCombos: ['Opioids (avoid; lowest dose/shortest duration if unavoidable)', 'Alcohol/other CNS depressants', 'Severe respiratory insufficiency / untreated sleep apnea'],
    pregnancy: 'Balance seizure control against fetal risk; regular late use → neonatal sedation/withdrawal.',
    lactation: 'Long active metabolite — monitor infant for sedation/poor feeding.',
    geriatric: 'Beers — avoid where possible; if used for epilepsy, titrate slowly.',
    pearls: [
      'A 1,5-benzodiazepine → more selective anticonvulsant/anxiolytic action with less sedation than 1,4-benzodiazepines.',
      'Active metabolite N-desmethylclobazam (long half-life) is cleared by CYP2C19 — poor metabolizers/2C19 inhibitors accumulate it.',
      'Key niche: adjunct for Lennox-Gastaut syndrome and refractory epilepsy.',
    ],
    mnemonics: ['"cloBAZam = the 1,5 seizure benzo" — Lennox-gastaut adjunct, less sedation.'],
    confusables: ['Clobazam vs clonazepam — both anticonvulsant benzos; clobazam is a 1,5-benzodiazepine (LGS adjunct, less sedating) with a CYP2C19-cleared active metabolite, clonazepam is a 1,4-benzodiazepine.'],
    classDifferentiators: '1,5-benzodiazepine structure, long-acting active metabolite (CYP2C19-dependent), anticonvulsant-selective with less sedation — the Lennox-Gastaut adjunct.',
    examHooks: ['Which benzodiazepine is a 1,5-benzodiazepine used as an adjunct in Lennox-Gastaut syndrome? (clobazam).', 'Which CYP polymorphism affects clobazam’s active metabolite? (CYP2C19).'],
    counsellingPoints: ['Report any rash promptly (rare serious skin reactions).', 'Do not stop suddenly — seizures can worsen.', 'Avoid alcohol/opioids.'],
    vignettes: [
      {
        stem: 'A child with Lennox-Gastaut syndrome is started on clobazam. Poor clearance of which enzyme most increases exposure to its long-acting active metabolite N-desmethylclobazam?',
        options: ['CYP2D6', 'CYP1A2', 'CYP2C19', 'UGT1A1'],
        answer: 'CYP2C19',
        explanation: 'Clobazam’s active metabolite N-desmethylclobazam is eliminated by CYP2C19; poor metabolizers or CYP2C19 inhibitors accumulate the metabolite, increasing sedation and requiring slower titration.',
        testedFact: 'Clobazam active metabolite cleared by CYP2C19',
        source: { name: 'openFDA/DailyMed clobazam label — metabolism (CYP2C19)', origin: 'openfda' },
      },
    ],
    _prov: BENZO_PROV,
  },

  flurazepam: {
    pronunciation: 'flur-AZ-uh-pam',
    moa: 'Benzodiazepine: GABA-A positive allosteric modulator (↑ Cl- channel opening frequency); long-acting hypnotic via active metabolites.',
    receptorProfile: 'Non-selective GABA-A benzodiazepine-site agonist.',
    onsetOfEffect: 'PO onset ~30–60 min; effect prolonged by long-lived metabolites.',
    halfLife: 'Parent short, but active metabolite N-desalkylflurazepam ~40–250 h (LONG class — accumulates).',
    timeToSteadyState: 'Up to ~1–2 weeks (long active metabolite).',
    metabolism: 'Hepatic oxidation (CYP) to N-desalkylflurazepam (very long half-life).',
    activeMetabolites: 'N-desalkylflurazepam (active, very long-acting) — accumulates → next-day/2nd-day sedation.',
    approvedCanada: ['Insomnia (short-term)'],
    offLabel: [],
    approvedPopulations: 'Adults.',
    startingDose: '15 mg PO at bedtime (elderly).',
    titration: 'Lowest effective dose; short-term.',
    maxDose: '30 mg at bedtime.',
    frequencyTiming: 'At bedtime; sedation accumulates over successive nights.',
    renalHepaticAdjustment: 'Reduce/avoid in elderly/hepatic impairment — active metabolite accumulates.',
    startStopCrossTaper: 'Taper after regular use; long metabolite gives a gentler, self-tapering withdrawal.',
    administrationNotes: 'Classic example of hypnotic accumulation → next-day and cumulative sedation.',
    commonSE: ['Next-day/residual sedation (worsening over nights)', 'Dizziness', 'Ataxia', 'Headache'],
    seriousAE: ['Respiratory depression (with opioids/alcohol)', 'Cumulative oversedation (metabolite accumulation)', 'Falls in elderly', 'Dependence and rebound insomnia', 'Paradoxical disinhibition'],
    syndromes: ['Accumulation/next-day sedation', 'Dependence/rebound insomnia', 'Respiratory depression (with CNS depressants)', 'Falls (elderly)', 'Paradoxical disinhibition'],
    overdoseLethality: 'LOW alone; HIGH with opioids/alcohol/other CNS depressants.',
    discontinuationSyndrome: 'Rebound insomnia; long metabolite softens withdrawal but accumulation is the main issue.',
    ongoingMonitoring: 'Cumulative/next-day sedation, falls in elderly, dependence, respiratory status with opioids.',
    majorDDI: ['Opioids (additive respiratory depression)', 'Alcohol/CNS depressants', 'CYP inhibitors (raise levels)'],
    contraindicatedCombos: ['Opioids (avoid; lowest dose/shortest duration if unavoidable)', 'Alcohol/other CNS depressants', 'Severe respiratory insufficiency / untreated sleep apnea'],
    pregnancy: 'Avoid; late use → neonatal sedation/hypotonia/withdrawal.',
    lactation: 'Long-acting metabolite — infant accumulation possible; avoid/prefer a shorter hypnotic.',
    geriatric: 'Beers — avoid; the accumulating active metabolite makes next-day sedation and falls especially likely.',
    pearls: [
      'Long-acting hypnotic via N-desalkylflurazepam (up to ~250 h) → cumulative next-day sedation over successive nights — the classic "accumulating hypnotic".',
      'Contrast with temazepam (intermediate, glucuronidated, no active metabolite) for a cleaner hypnotic in the elderly/hepatic patients.',
    ],
    mnemonics: ['"Flurazepam = Forever" — the active metabolite lingers, so sedation accumulates.'],
    confusables: ['Flurazepam vs temazepam — flurazepam accumulates (long active metabolite), temazepam does not (intermediate, glucuronidated).'],
    classDifferentiators: 'Long-acting hypnotic driven by a very long active metabolite → cumulative next-day sedation; the opposite of the LOT hypnotic temazepam.',
    examHooks: ['Which hypnotic benzodiazepine accumulates over successive nights because of a long-lived active metabolite? (flurazepam — N-desalkylflurazepam).'],
    counsellingPoints: ['Grogginess can build up night after night — report it.', 'Avoid alcohol/opioids.', 'Short-term use; caution driving.'],
    vignettes: [
      {
        stem: 'After several nights of flurazepam, an elderly patient is progressively more sedated during the day. Which pharmacologic feature explains the cumulative effect?',
        options: ['Ultra-short half-life with rebound', 'Glucuronidation with no active metabolite', 'A very long-acting active metabolite (N-desalkylflurazepam)', 'Enzyme autoinduction'],
        answer: 'A very long-acting active metabolite (N-desalkylflurazepam)',
        explanation: 'Flurazepam is converted to N-desalkylflurazepam, whose extremely long half-life leads to accumulation with repeated nightly dosing, causing progressive daytime sedation — pronounced in the elderly.',
        testedFact: 'Flurazepam long-acting active metabolite accumulation',
        source: { name: 'Standard psychopharmacology; hypnotic benzodiazepine pharmacology', origin: 'monograph' },
      },
    ],
    _prov: BENZO_PROV,
  },

  triazolam: {
    pronunciation: 'try-AZ-oh-lam',
    moa: 'Benzodiazepine: GABA-A positive allosteric modulator (↑ Cl- channel opening frequency); ultra-short-acting hypnotic.',
    receptorProfile: 'Non-selective GABA-A benzodiazepine-site agonist.',
    onsetOfEffect: 'Fast PO onset (~15–30 min) for sleep induction; very brief effect.',
    halfLife: '~1.5–5.5 h (ULTRA-SHORT class).',
    timeToSteadyState: '~1–2 days.',
    metabolism: 'Hepatic CYP3A4 — extensive first-pass; strong 3A4 inhibitors dramatically raise levels (many labelled interactions/contraindications).',
    activeMetabolites: 'None clinically significant.',
    approvedCanada: ['Insomnia (short-term, sleep-onset)'],
    offLabel: [],
    approvedPopulations: 'Adults.',
    startingDose: '0.125–0.25 mg PO at bedtime (0.125 mg in elderly).',
    titration: 'Lowest effective dose; short-term only.',
    maxDose: '0.5 mg at bedtime (rarely; higher amnesia/rebound risk).',
    frequencyTiming: 'At bedtime, immediately before sleep; ultra-short duration minimizes next-day sedation but causes rebound.',
    renalHepaticAdjustment: 'Reduce in elderly; avoid with hepatic impairment plus CYP3A4 inhibitors.',
    startStopCrossTaper: 'Taper after regular use; expect rebound insomnia.',
    administrationNotes: 'Ultra-short half-life → minimal hangover but prominent anterograde amnesia, next-morning rebound anxiety, and CYP3A4-driven interactions.',
    commonSE: ['Anterograde amnesia (prominent)', 'Rebound insomnia/early-morning awakening', 'Dizziness', 'Headache'],
    seriousAE: ['Respiratory depression (with opioids/alcohol)', 'Complex sleep behaviours (sleep-driving)', 'Marked anterograde amnesia', 'Dependence and rebound', 'Paradoxical disinhibition'],
    syndromes: ['Anterograde amnesia', 'Rebound insomnia/anxiety', 'Respiratory depression (with CNS depressants)', 'Complex sleep behaviours', 'Dependence/withdrawal'],
    overdoseLethality: 'LOW alone; HIGH with opioids/alcohol/other CNS depressants; potentiated by CYP3A4 inhibitors.',
    discontinuationSyndrome: 'Rebound insomnia and daytime anxiety even after short use (ultra-short half-life); taper.',
    ongoingMonitoring: 'Amnesia/complex sleep behaviours, rebound symptoms, respiratory status with opioids, CYP3A4 co-medications.',
    majorDDI: ['Strong CYP3A4 inhibitors (ketoconazole, itraconazole, ritonavir/protease inhibitors, clarithromycin, nefazodone → CONTRAINDICATED — toxic levels)', 'Opioids (additive respiratory depression)', 'Alcohol/CNS depressants', 'Grapefruit juice (raises levels)'],
    contraindicatedCombos: ['Strong CYP3A4 inhibitors — ketoconazole, itraconazole, HIV protease inhibitors, nefazodone (CONTRAINDICATED per label)', 'Opioids (avoid)', 'Alcohol/other CNS depressants', 'Severe respiratory insufficiency / untreated sleep apnea'],
    pregnancy: 'Avoid; late use → neonatal sedation/withdrawal.',
    lactation: 'Monitor infant; short-acting but avoid if possible.',
    geriatric: 'Beers — avoid; amnesia, confusion, falls; use lowest dose (0.125 mg) only if unavoidable.',
    pearls: [
      'Ultra-short half-life → minimal next-day hangover BUT prominent anterograde amnesia and early-morning rebound insomnia/anxiety.',
      'CYP3A4 substrate with contraindicated strong-inhibitor combinations (azoles, protease inhibitors, nefazodone, clarithromycin, grapefruit).',
      'A classic "sleep-onset" hypnotic — no help for sleep-maintenance because it wears off quickly.',
    ],
    mnemonics: ['"Triazolam = Transient + Three-A-four" — ultra-short, amnestic, and a CYP3A4-contraindication magnet.'],
    confusables: ['Triazolam vs temazepam — triazolam is ultra-short/CYP3A4 (amnesia, rebound, many interactions); temazepam is intermediate/glucuronidated (liver-safe, fewer interactions).'],
    classDifferentiators: 'Ultra-short half-life, CYP3A4 metabolism with contraindicated strong-inhibitor combos, marked anterograde amnesia and rebound — the sleep-onset hypnotic.',
    examHooks: ['Which hypnotic benzodiazepine is contraindicated with strong CYP3A4 inhibitors and grapefruit? (triazolam).', 'Which benzo is most associated with anterograde amnesia and early-morning rebound? (triazolam).'],
    counsellingPoints: ['Take only when you can devote a full night to sleep.', 'Avoid grapefruit juice and tell prescribers about antifungals/antivirals (interactions).', 'Report memory gaps or sleep-driving; avoid alcohol/opioids.'],
    vignettes: [
      {
        stem: 'A patient taking ritonavir for HIV asks for triazolam to help sleep. Why is this combination contraindicated?',
        options: ['Additive serotonin toxicity', 'Ritonavir strongly inhibits CYP3A4, causing toxic triazolam accumulation', 'Triazolam induces ritonavir metabolism', 'Both are glucuronidated and compete for UGT'],
        answer: 'Ritonavir strongly inhibits CYP3A4, causing toxic triazolam accumulation',
        explanation: 'Triazolam is metabolized by CYP3A4; strong 3A4 inhibitors (ritonavir/other protease inhibitors, azole antifungals, nefazodone, clarithromycin) markedly increase levels and are contraindicated with triazolam per the label.',
        testedFact: 'Triazolam CYP3A4 contraindicated combos',
        source: { name: 'openFDA/DailyMed triazolam label — contraindications (CYP3A4)', origin: 'openfda' },
      },
    ],
    _prov: BENZO_PROV,
  },

  clorazepate: {
    pronunciation: 'klor-AZ-uh-payt',
    moa: 'Benzodiazepine PRODRUG: decarboxylated in acidic stomach to desmethyldiazepam (nordiazepam), a long-acting GABA-A positive allosteric modulator (↑ Cl- channel opening frequency).',
    receptorProfile: 'Acts via its active metabolite at the GABA-A benzodiazepine site.',
    onsetOfEffect: 'PO onset ~30–60 min (after gastric conversion to nordiazepam); long duration.',
    halfLife: 'Effective half-life is that of desmethyldiazepam (nordiazepam) — up to ~100–200 h (LONG class; accumulates).',
    timeToSteadyState: 'Up to ~2 weeks (long active metabolite).',
    metabolism: 'Prodrug → desmethyldiazepam (formed pre-systemically in the stomach), then hepatic oxidation to oxazepam (glucuronidated).',
    activeMetabolites: 'Desmethyldiazepam (nordiazepam, long-acting) — the active moiety; then oxazepam.',
    approvedCanada: ['Anxiety', 'Adjunct in partial seizures', 'Alcohol withdrawal'],
    offLabel: [],
    approvedPopulations: 'Adults.',
    startingDose: '7.5–15 mg PO 2–3×/day for anxiety (lower in elderly).',
    titration: 'Titrate gradually; long metabolite means effects build over days.',
    maxDose: 'Up to ~60 mg/day in divided doses.',
    frequencyTiming: 'BID–TID or once daily at steady state (long active metabolite).',
    renalHepaticAdjustment: 'Reduce/avoid in elderly/hepatic impairment — nordiazepam accumulates; a LOT agent is safer.',
    startStopCrossTaper: 'Long half-life supports a smooth self-taper; still taper after regular use.',
    administrationNotes: 'Requires gastric acid for conversion — antacids/achlorhydria may alter absorption.',
    commonSE: ['Sedation', 'Ataxia', 'Dizziness', 'Fatigue', 'Confusion (elderly)'],
    seriousAE: ['Respiratory depression (with opioids/alcohol)', 'Dependence and withdrawal (incl. seizures)', 'Accumulation/oversedation in elderly', 'Paradoxical disinhibition'],
    syndromes: ['Dependence/withdrawal (withdrawal seizures)', 'Respiratory depression (with CNS depressants)', 'Accumulation/oversedation in elderly', 'Paradoxical disinhibition'],
    overdoseLethality: 'LOW alone; HIGH with opioids/alcohol/other CNS depressants.',
    discontinuationSyndrome: 'Withdrawal on stopping; long half-life gives a gentler self-tapering course — still taper after high-dose/long use.',
    ongoingMonitoring: 'Sedation/accumulation (esp. elderly/hepatic), dependence, respiratory status with opioids.',
    majorDDI: ['Opioids (additive respiratory depression)', 'Alcohol/CNS depressants', 'CYP inhibitors (raise nordiazepam)', 'Antacids (may alter gastric conversion/absorption)'],
    contraindicatedCombos: ['Opioids (avoid; lowest dose/shortest duration if unavoidable)', 'Alcohol/other CNS depressants', 'Severe respiratory insufficiency / untreated sleep apnea'],
    pregnancy: 'Avoid; late/regular use → neonatal sedation/hypotonia/withdrawal.',
    lactation: 'Long-acting metabolite — infant accumulation possible; prefer a shorter agent.',
    geriatric: 'Beers — avoid; nordiazepam accumulation → sedation, confusion, falls.',
    renalHepatic: 'Active metabolite accumulates in hepatic/renal impairment — avoid there.',
    pearls: [
      'A prodrug converted in the acidic stomach to desmethyldiazepam (nordiazepam) — the same long-acting active metabolite shared with diazepam and chlordiazepoxide.',
      'Long half-life → self-tapering; but accumulates in the elderly/hepatic disease (avoid there, like diazepam).',
      'Gastric acid is needed for activation — antacids can reduce conversion.',
    ],
    mnemonics: ['"Clorazepate = the pro-drug that becomes Nordiazepam" — long-acting, like diazepam.'],
    confusables: ['Clorazepate vs clonazepam — sound-alike, but clorazepate is a long-acting prodrug of nordiazepam whereas clonazepam is a distinct high-potency long-acting agent.', 'Clorazepate vs chlordiazepoxide — both yield desmethyldiazepam.'],
    classDifferentiators: 'Long-acting benzodiazepine PRODRUG (→ nordiazepam); gastric-acid-activated; behaves like diazepam/chlordiazepoxide and accumulates in elderly/hepatic disease.',
    examHooks: ['Which benzodiazepine is a prodrug converted to desmethyldiazepam (nordiazepam) in the stomach? (clorazepate).'],
    counsellingPoints: ['Effects and drowsiness build over days.', 'Avoid alcohol/opioids.', 'Do not stop abruptly after regular use.'],
    vignettes: [
      {
        stem: 'Clorazepate is described as a "prodrug." Which active moiety is chiefly responsible for its long duration of action?',
        options: ['1-hydroxymidazolam', 'Desmethyldiazepam (nordiazepam)', 'N-desalkylflurazepam', 'Oxazepam glucuronide'],
        answer: 'Desmethyldiazepam (nordiazepam)',
        explanation: 'Clorazepate is decarboxylated in the stomach to desmethyldiazepam (nordiazepam), a long-acting active metabolite it shares with diazepam and chlordiazepoxide, accounting for its long half-life and accumulation in the elderly/hepatic disease.',
        testedFact: 'Clorazepate prodrug → nordiazepam',
        source: { name: 'Standard psychopharmacology; benzodiazepine metabolism', origin: 'monograph' },
      },
    ],
    _prov: BENZO_PROV,
  },
};
