// authored/dementia.js — authored overlay for cognitive enhancers (dementia).
//
// Mechanism/PK/dosing summaries + the pedagogical layer, grounded in established
// pharmacology and the fetched openFDA/monograph label sections. `_prov` declares which
// safety-critical fields the label text grounds; build.js attaches that source text and,
// where a field cannot be grounded, downgrades it to origin 'authored' + verifyFlag.
//
// Group theme: symptomatic anti-dementia agents. Three cholinesterase inhibitors
// (donepezil, rivastigmine, galantamine) RAISE synaptic acetylcholine → predictable
// CHOLINERGIC side effects: nausea/vomiting/diarrhea, bradycardia/syncope/heart block
// (caution with sick-sinus / AV block / other bradycardic drugs), increased gastric acid
// (peptic ulcer/GI-bleed risk), urinary urgency, muscle cramps, and vivid dreams. They give
// only MODEST symptomatic benefit and do NOT halt disease progression. Memantine is the
// odd one out — an NMDA-receptor antagonist with a DISTINCT mechanism and side-effect
// profile (dizziness, constipation, confusion; no cholinergic GI/brady effects), renally
// cleared, and added to an AChE-I in moderate–severe disease. Classic prescribing error:
// co-prescribing a strong ANTICHOLINERGIC (e.g., oxybutynin) with an AChE-I — the two have
// directly opposing actions and cancel each other out while worsening cognition.

const DEMENTIA_PROV = {
  startingDose: 'openfda', maxDose: 'openfda', seriousAE: 'openfda', syndromes: 'openfda',
  majorDDI: 'openfda', contraindicatedCombos: 'openfda', pregnancy: 'openfda',
  overdoseLethality: 'openfda',
};

export default {
  donepezil: {
    pronunciation: 'doh-NEP-uh-zil',
    moa: 'Reversible, centrally selective acetylcholinesterase (AChE) inhibitor → less breakdown of synaptic acetylcholine → enhanced cholinergic transmission in cortex/hippocampus. Symptomatic only; does not modify disease progression.',
    receptorProfile: 'Selective for AChE (piperidine); little butyrylcholinesterase or peripheral activity relative to central effect.',
    onsetOfEffect: 'Cognitive/functional benefit assessed over weeks; modest symptomatic effect, not disease-modifying.',
    halfLife: '~70 hours — the longest of the AChE inhibitors, allowing convenient once-daily dosing.',
    timeToSteadyState: '~2–3 weeks (long half-life).',
    metabolism: 'Hepatic CYP2D6 and CYP3A4, plus glucuronidation. Not a significant CYP inhibitor itself; strong 2D6/3A4 inhibitors raise its levels.',
    elimination: 'Renal (metabolites and some unchanged) and hepatic.',
    foodEffect: 'May be taken with or without food; bedtime dosing traditional.',
    approvedPopulations: 'Adults with mild, moderate, and severe Alzheimer disease.',
    offLabel: ['Lewy body dementia', 'Parkinson disease dementia', 'Vascular dementia'],
    startingDose: '5 mg PO once daily (often at bedtime).',
    titration: 'May increase to 10 mg/day after 4–6 weeks; a 23 mg/day formulation exists for moderate–severe disease (US).',
    maxDose: '10 mg/day (mild–moderate); 23 mg/day for moderate–severe (US high-dose tablet).',
    frequencyTiming: 'Once daily. If vivid dreams/nightmares occur with bedtime dosing, switch to the morning.',
    startStopCrossTaper: 'When switching between cholinesterase inhibitors, allow a washout appropriate to half-life; abrupt discontinuation can cause noticeable cognitive/behavioural decline.',
    administrationNotes: 'Longest half-life of the class → simplest (once-daily) dosing and the most forgiving of missed doses.',
    commonSE: ['Nausea', 'Vomiting', 'Diarrhea', 'Anorexia/weight loss', 'Insomnia and vivid dreams/nightmares', 'Muscle cramps', 'Bradycardia', 'Fatigue/dizziness'],
    seriousAE: ['Symptomatic bradycardia', 'Syncope', 'Heart block (sinoatrial/atrioventricular)', 'GI bleeding (increased gastric acid — peptic ulcer risk)', 'Seizures', 'Significant weight loss'],
    syndromes: ['Cholinergic excess (nausea/vomiting/diarrhea, bradycardia, salivation, urinary urgency)', 'Bradyarrhythmia/syncope', 'Vivid dreams/nightmares'],
    overdoseLethality: 'Overdose produces a cholinergic crisis (severe nausea/vomiting, salivation, sweating, bradycardia, hypotension, seizures, respiratory depression); atropine is the antidote.',
    baselineWorkup: ['Assess pulse/history of syncope or conduction disease before starting', 'Weight and GI/ulcer history'],
    ongoingMonitoring: 'Heart rate and syncope symptoms; weight and GI tolerance; cognitive/functional response to justify continuation.',
    majorDDI: ['Anticholinergics (oxybutynin, tolterodine, TCAs, first-gen antihistamines, benztropine) — OPPOSE the drug and worsen cognition', 'Beta-blockers, digoxin, non-dihydropyridine CCBs — additive bradycardia/AV block', 'Other cholinergic/cholinomimetic agents — additive cholinergic toxicity', 'NSAIDs — additive GI-bleed risk (increased gastric acid)', 'Succinylcholine — prolonged neuromuscular blockade', 'CYP2D6/3A4 inhibitors (paroxetine, fluoxetine, ketoconazole) raise donepezil levels'],
    contraindicatedCombos: ['Strong anticholinergics (pharmacodynamically self-defeating and worsen cognition)'],
    pregnancy: 'Rarely relevant (dementia population); limited data — use only if clearly needed.',
    geriatric: 'The target population — watch for bradycardia, syncope and falls, anorexia/weight loss, and vivid dreams; review the full medication list for anticholinergic burden.',
    cardiac: 'Vagotonic effect → bradycardia and syncope; caution with sick sinus syndrome or supraventricular conduction defects and with other rate-slowing drugs. QT prolongation has been reported.',
    pearls: [
      'Longest half-life AChE inhibitor → once daily and forgiving of a missed dose.',
      'Bedtime dosing can cause vivid dreams/nightmares — move to the morning if bothersome.',
      'Symptomatic benefit only — it does not stop Alzheimer progression; set expectations with families.',
      'Unexplained syncope in a treated patient warrants an ECG for bradycardia/heart block before attributing it to the dementia itself.',
    ],
    mnemonics: ['"doneP EZ-il = EASY once-daily" (longest half-life). Cholinergic excess = SLUDGE/DUMBELS — think the vagotonic Bradycardia when you dose it.'],
    confusables: ['Donepezil (AChE inhibitor) vs memantine (NMDA antagonist) — donepezil for mild–severe and causes cholinergic/GI/brady effects; memantine for moderate–severe with no cholinergic effects.', 'Donepezil vs galantamine — galantamine adds nicotinic modulation and is mild–moderate only.'],
    classDifferentiators: 'The default first-line AChE inhibitor across ALL stages of Alzheimer (mild through severe); longest half-life, purely AChE-selective, once daily.',
    examHooks: ['Which anti-dementia drug is approved across mild-to-severe Alzheimer and has the longest half-life? (donepezil)', 'A demented patient on donepezil develops syncope — next investigation? (ECG for bradycardia/AV block)'],
    counsellingPoints: ['Nausea/diarrhea and reduced appetite are common early and usually settle — take with food.', 'If you have vivid dreams, we can move the dose to the morning.', 'It helps symptoms modestly but does not cure or stop the disease.', 'Report fainting, dizziness or a very slow pulse.'],
    vignettes: [
      {
        stem: 'A 78-year-old woman with moderate Alzheimer disease on donepezil is prescribed oxybutynin by another clinic for urinary urgency. Over the next few weeks her family reports worse confusion. What is the BEST explanation?',
        options: [
          'Donepezil dose is too low and should be increased',
          'The anticholinergic oxybutynin pharmacodynamically opposes donepezil and worsens cognition',
          'This is expected progression of Alzheimer disease',
          'Oxybutynin has raised donepezil levels via CYP inhibition',
        ],
        answer: 'The anticholinergic oxybutynin pharmacodynamically opposes donepezil and worsens cognition',
        explanation: 'Cholinesterase inhibitors raise acetylcholine; anticholinergics block muscarinic receptors — directly opposing actions. Co-prescribing them is a classic error that blunts benefit and can worsen cognition. Use a non-anticholinergic option (e.g., mirabegron) for the bladder.',
        testedFact: 'AChE inhibitor + anticholinergic = opposing actions (prescribing error)',
        source: { name: 'Anticholinergic–cholinesterase-inhibitor deprescribing principle; product monograph', origin: 'monograph' },
      },
    ],
    _prov: DEMENTIA_PROV,
  },

  rivastigmine: {
    pronunciation: 'riv-uh-STIG-meen',
    moa: 'Pseudo-irreversible (carbamate) inhibitor of BOTH acetylcholinesterase AND butyrylcholinesterase → raises synaptic acetylcholine. Dual esterase inhibition is its distinguishing mechanism; symptomatic only.',
    receptorProfile: 'Inhibits AChE and butyrylcholinesterase; butyrylcholinesterase becomes more important as Alzheimer advances, a proposed rationale for the dual target.',
    onsetOfEffect: 'Symptomatic benefit assessed over weeks; not disease-modifying.',
    halfLife: 'Oral parent ~1.5 hours, but enzyme inhibition (pseudo-irreversible) lasts ~10 hours; the transdermal patch gives smooth, sustained levels over 24 h.',
    timeToSteadyState: 'Reached within days with steady dosing/patch.',
    metabolism: 'Minimal CYP involvement — hydrolysed by cholinesterases to a decarbamylated metabolite, then renally excreted. Few CYP-based drug interactions (a practical advantage).',
    elimination: 'Renal (metabolites); negligible unchanged drug.',
    foodEffect: 'Take oral doses WITH food to reduce GI upset; the patch bypasses first-pass GI exposure.',
    approvedPopulations: 'Adults with mild–moderate Alzheimer disease AND mild–moderate Parkinson disease dementia.',
    startingDose: 'Oral 1.5 mg PO BID; transdermal patch 4.6 mg/24 h once daily.',
    titration: 'Oral: increase by 1.5 mg BID at ≥2-week intervals as tolerated. Patch: step up to 9.5 mg/24 h after ≥4 weeks, then 13.3 mg/24 h.',
    maxDose: 'Oral 6 mg BID (12 mg/day); patch 13.3 mg/24 h.',
    frequencyTiming: 'Oral twice daily with food; patch once daily, rotating application sites.',
    renalHepaticAdjustment: 'Titrate cautiously in low body weight, renal or hepatic impairment (higher exposure, more GI/cholinergic effects).',
    startStopCrossTaper: 'If oral therapy is interrupted for more than ~3 days, RESTART at the lowest dose and re-titrate — resuming at the previous dose risks severe vomiting (with reports of esophageal rupture). The same re-titration caution applies to the patch.',
    administrationNotes: 'The transdermal patch is the signature feature: smoother plasma levels reduce nausea/vomiting and aid adherence.',
    commonSE: ['Nausea', 'Vomiting (prominent with oral, especially during titration)', 'Diarrhea', 'Anorexia/weight loss', 'Dizziness', 'Application-site erythema/pruritus (patch)'],
    seriousAE: ['Severe vomiting/dehydration (esp. on restarting without re-titration — esophageal rupture reported)', 'Symptomatic bradycardia and syncope', 'GI bleeding/peptic ulceration', 'Heart block'],
    syndromes: ['Cholinergic excess (GI-predominant)', 'Bradyarrhythmia/syncope', 'Severe re-titration vomiting syndrome'],
    overdoseLethality: 'Cholinergic crisis in overdose (severe GI symptoms, bradycardia, hypotension, seizures); atropine is the antidote. Accidental patch overuse (multiple patches) has caused serious toxicity.',
    baselineWorkup: ['Weight and GI tolerance', 'Pulse and history of conduction disease/syncope'],
    ongoingMonitoring: 'Weight and hydration/GI tolerance; heart rate; application-site skin checks (patch); confirm no patch stacking.',
    majorDDI: ['Anticholinergics — OPPOSE the drug and reduce efficacy', 'Beta-blockers/other bradycardic agents — additive bradycardia and syncope', 'Other cholinomimetics — additive cholinergic toxicity', 'Succinylcholine — prolonged neuromuscular blockade', 'NSAIDs — additive GI-bleed risk'],
    contraindicatedCombos: ['Strong anticholinergics (opposing pharmacology)'],
    pregnancy: 'Rarely relevant (dementia population); limited data — use only if clearly needed.',
    geriatric: 'Titrate slowly to limit nausea/vomiting and weight loss; the patch is often preferred in frail/low-weight patients for tolerability.',
    cardiac: 'Vagotonic → bradycardia and syncope; caution with sick sinus syndrome, conduction defects and other rate-slowing drugs.',
    pearls: [
      'The transdermal PATCH reduces GI side effects (smoother levels) and improves adherence versus oral dosing.',
      'The only cholinesterase inhibitor also approved for Parkinson disease dementia.',
      'Dual AChE + butyrylcholinesterase inhibition; metabolised by esterases (not CYP) → few CYP interactions.',
      'After an interruption >3 days, restart low and re-titrate — resuming the old dose risks severe vomiting.',
    ],
    mnemonics: ['"Rivastigmine RIDES a patch and RIVals in Parkinson" — patch = fewer GI SEs; approved for Parkinson disease dementia.'],
    confusables: ['Rivastigmine vs donepezil — rivastigmine is dual-esterase, twice-daily (or patch), and covers Parkinson dementia; donepezil is AChE-selective, once daily, all stages of Alzheimer.', 'Rivastigmine patch vs oral — same drug; patch has markedly fewer GI effects.'],
    classDifferentiators: 'Dual AChE + butyrylcholinesterase inhibitor; esterase-metabolised (few CYP interactions); available as a patch; the class member indicated for Parkinson disease dementia.',
    examHooks: ['Which cholinesterase inhibitor is approved for Parkinson disease dementia and comes as a patch? (rivastigmine)', 'Why re-titrate rivastigmine after a >3-day gap? (risk of severe vomiting/esophageal rupture)'],
    counsellingPoints: ['Take oral doses with food; nausea is worst during dose increases.', 'The patch causes less nausea — rotate sites and apply only ONE at a time.', 'If you miss several days, do not restart at the old dose — contact us to re-titrate.', 'Report severe/persistent vomiting, fainting, or a very slow pulse.'],
    vignettes: [
      {
        stem: 'A patient with Alzheimer disease stopped oral rivastigmine for 5 days during a hospital admission. On discharge, a nurse restarts the previous 4.5 mg BID dose and the patient develops severe, protracted vomiting. What is the key management principle that was violated?',
        options: [
          'Rivastigmine should never be restarted after any interruption',
          'After an interruption longer than 3 days, restart at the lowest dose and re-titrate',
          'The patient should have been switched to memantine',
          'Rivastigmine must always be given with an antiemetic',
        ],
        answer: 'After an interruption longer than 3 days, restart at the lowest dose and re-titrate',
        explanation: 'Cholinergic tolerance is lost after a few days off rivastigmine; resuming at the prior dose can cause severe vomiting (esophageal rupture has been reported). Restart at 1.5 mg BID and re-titrate.',
        testedFact: 'Rivastigmine re-titration after interruption',
        source: { name: 'openFDA/monograph rivastigmine label — dosage/administration (interruption)', origin: 'openfda' },
      },
    ],
    _prov: DEMENTIA_PROV,
  },

  galantamine: {
    pronunciation: 'guh-LAN-tuh-meen',
    moa: 'Competitive, reversible acetylcholinesterase inhibitor PLUS allosteric potentiation of nicotinic acetylcholine receptors — a dual cholinergic mechanism that further enhances acetylcholine signalling. Symptomatic only.',
    receptorProfile: 'AChE inhibition combined with positive allosteric modulation of nicotinic receptors (its distinguishing pharmacology).',
    onsetOfEffect: 'Symptomatic benefit assessed over weeks; not disease-modifying.',
    halfLife: '~7 hours.',
    timeToSteadyState: 'A few days.',
    metabolism: 'Hepatic CYP2D6 and CYP3A4, with renal excretion of drug/metabolites. Strong 2D6/3A4 inhibitors raise its levels.',
    elimination: 'Renal (partly unchanged) and hepatic.',
    foodEffect: 'Take WITH food (and maintain hydration) to reduce nausea and slow absorption.',
    approvedPopulations: 'Adults with mild–moderate Alzheimer disease.',
    offLabel: ['Vascular dementia (mixed AD/vascular)'],
    startingDose: 'Immediate-release 4 mg PO BID; extended-release 8 mg PO once daily in the morning.',
    titration: 'Increase to 8 mg BID (ER 16 mg/day) after ≥4 weeks, then to 12 mg BID (ER 24 mg/day) after a further ≥4 weeks as tolerated.',
    maxDose: '24 mg/day.',
    frequencyTiming: 'IR twice daily with food; ER once daily in the morning with food.',
    renalHepaticAdjustment: 'Avoid in severe renal impairment (CrCl <9 mL/min) and severe hepatic impairment (Child-Pugh C); reduce dose (≤16 mg/day) in moderate hepatic impairment.',
    administrationNotes: 'Maintain fluid intake during titration; slower titration reduces GI dropout.',
    commonSE: ['Nausea', 'Vomiting', 'Diarrhea', 'Anorexia/weight loss', 'Dizziness', 'Headache'],
    seriousAE: ['Symptomatic bradycardia and syncope', 'AV/heart block', 'Serious skin reactions (Stevens–Johnson syndrome, acute generalized exanthematous pustulosis — rare)', 'GI bleeding/peptic ulcer', 'Increased mortality signal when used for mild cognitive impairment (not an approved use)'],
    syndromes: ['Cholinergic excess', 'Bradyarrhythmia/syncope', 'Severe cutaneous reaction (rare)'],
    overdoseLethality: 'Cholinergic crisis in overdose (severe GI symptoms, bradycardia, hypotension, seizures, muscle weakness/respiratory compromise); atropine is the antidote.',
    baselineWorkup: ['Renal and hepatic function (dosing limits)', 'Pulse/history of syncope or conduction disease', 'Weight'],
    ongoingMonitoring: 'Heart rate and syncope; weight/GI tolerance; skin (discontinue at first sign of serious rash).',
    majorDDI: ['Anticholinergics — OPPOSE the drug and reduce efficacy', 'Beta-blockers/other bradycardic agents — additive bradycardia', 'CYP2D6/3A4 inhibitors (paroxetine, fluoxetine, ketoconazole, erythromycin) raise galantamine levels', 'Other cholinomimetics — additive toxicity', 'Succinylcholine — prolonged neuromuscular blockade', 'NSAIDs — GI-bleed risk'],
    contraindicatedCombos: ['Strong anticholinergics (opposing pharmacology)'],
    pregnancy: 'Rarely relevant (dementia population); limited data — use only if clearly needed.',
    geriatric: 'Titrate slowly with food; respect renal/hepatic dose ceilings; watch bradycardia, weight loss and falls.',
    renalHepatic: 'Contraindicated in severe renal or severe hepatic impairment; cap at 16 mg/day in moderate hepatic impairment.',
    cardiac: 'Vagotonic → bradycardia/syncope; caution with sick sinus syndrome, conduction defects and other rate-slowing drugs.',
    pearls: [
      'Dual mechanism: AChE inhibition PLUS nicotinic receptor allosteric potentiation.',
      'Approved for mild–moderate Alzheimer only (not severe disease).',
      'Respect renal/hepatic limits — avoid in severe impairment; take with food and fluids to limit nausea.',
      'An excess-mortality signal was seen in mild-cognitive-impairment trials — not an approved indication.',
    ],
    mnemonics: ['"GalantaMINE mines the NICOTINIC receptor too" — the dual AChE + nicotinic-modulator mechanism.'],
    confusables: ['Galantamine vs donepezil — galantamine adds nicotinic modulation, is twice-daily (or ER once-daily), and is mild–moderate only; donepezil is AChE-selective, once daily, all stages.', 'Galantamine vs guanfacine — similar-sounding but unrelated (guanfacine is an α2 agonist for ADHD).'],
    classDifferentiators: 'The AChE inhibitor with an ADDED nicotinic-receptor allosteric mechanism; restricted to mild–moderate Alzheimer; hard renal/hepatic dosing limits.',
    examHooks: ['Which cholinesterase inhibitor also allosterically modulates nicotinic receptors? (galantamine)', 'Which AChE inhibitor is contraindicated in severe renal/hepatic impairment? (galantamine)'],
    counsellingPoints: ['Take with meals and plenty of fluids; nausea is common when increasing the dose.', 'Report any spreading rash or blistering immediately.', 'Report fainting or a very slow pulse.', 'It eases symptoms modestly but does not stop the disease.'],
    vignettes: [
      {
        stem: 'You are choosing a cholinesterase inhibitor for a patient with mild Alzheimer disease and severe chronic kidney disease (eGFR 8 mL/min). Which agent is specifically CONTRAINDICATED in this setting?',
        options: ['Donepezil', 'Galantamine', 'Rivastigmine patch', 'Memantine'],
        answer: 'Galantamine',
        explanation: 'Galantamine is contraindicated in severe renal (CrCl <9 mL/min) and severe hepatic impairment because clearance falls and toxicity rises. Memantine is not a cholinesterase inhibitor (and is dose-reduced, not contraindicated, in renal impairment).',
        testedFact: 'Galantamine contraindicated in severe renal/hepatic impairment',
        source: { name: 'openFDA/monograph galantamine label — contraindications/use in impairment', origin: 'openfda' },
      },
    ],
    _prov: DEMENTIA_PROV,
  },

  memantine: {
    pronunciation: 'meh-MAN-teen',
    moa: 'Uncompetitive, low-to-moderate-affinity, open-channel NMDA-receptor antagonist. It blocks pathological tonic glutamate-driven Ca²⁺ influx (excitotoxicity) while its voltage-dependence and fast off-rate spare physiological synaptic transmission. A mechanism entirely DISTINCT from the cholinesterase inhibitors.',
    receptorProfile: 'NMDA-receptor channel blocker; also weak 5-HT3 and nicotinic antagonism. No cholinergic (AChE) activity — hence no cholinergic GI/bradycardic side-effect profile.',
    onsetOfEffect: 'Symptomatic benefit assessed over weeks; not disease-modifying.',
    halfLife: '~60–80 hours (long → once- or twice-daily dosing).',
    timeToSteadyState: '~1–2 weeks.',
    metabolism: 'Minimal hepatic metabolism — largely excreted UNCHANGED by the kidney (partly via active tubular secretion). Renal (not CYP/hepatic) handling is the key PK point. Alkaline urine markedly reduces clearance.',
    elimination: 'Renal; ~48% excreted unchanged. Clearance falls in renal impairment and with urinary alkalinisation.',
    foodEffect: 'May be taken with or without food.',
    approvedPopulations: 'Adults with moderate-to-severe Alzheimer disease.',
    offLabel: ['Adjunct to a cholinesterase inhibitor in moderate–severe disease', 'Vascular dementia (limited evidence)'],
    startingDose: '5 mg PO once daily (immediate-release); extended-release starts at 7 mg once daily.',
    titration: 'Increase by 5 mg/week to a target of 10 mg PO BID (IR) or 28 mg once daily (ER).',
    maxDose: '20 mg/day (immediate-release, 10 mg BID); 28 mg/day (extended-release).',
    frequencyTiming: 'IR twice daily once above 5 mg; ER once daily.',
    renalHepaticAdjustment: 'Reduce the target dose in severe renal impairment (CrCl ~5–29 mL/min) to 5 mg BID (10 mg/day, or ER 14 mg/day). No cholinergic constraints; hepatic adjustment not routinely required.',
    startStopCrossTaper: 'Can be combined with, or added on top of, an AChE inhibitor without a washout (different mechanism, non-overlapping toxicity).',
    administrationNotes: 'Titrate weekly to limit dizziness/confusion; the long half-life makes dosing forgiving.',
    commonSE: ['Dizziness', 'Headache', 'Constipation', 'Confusion', 'Somnolence', 'Hypertension'],
    seriousAE: ['Confusion/agitation (usually dose-related)', 'Seizures (rare)', 'Hypertension'],
    syndromes: ['CNS effects (dizziness, confusion, somnolence) — NOT cholinergic', 'No bradycardia/GI cholinergic syndrome (contrast with AChE inhibitors)'],
    overdoseLethality: 'Generally low toxicity; large ingestions have caused restlessness, psychosis, somnolence, and rarely seizures — largely supportive care.',
    ongoingMonitoring: 'Renal function (dose depends on it); cognitive/behavioural response; blood pressure. No routine cardiac or GI cholinergic monitoring needed.',
    majorDDI: ['Other NMDA antagonists (amantadine, ketamine, dextromethorphan) — avoid combination (additive CNS effects)', 'Urinary alkalinisers (carbonic anhydrase inhibitors e.g. acetazolamide, sodium bicarbonate) — reduce renal clearance → higher memantine levels', 'Drugs cleared by renal cationic transport (e.g., cimetidine, hydrochlorothiazide/triamterene) — potential competition', 'No significant CYP interactions'],
    contraindicatedCombos: ['Other NMDA-receptor antagonists (avoid combining)'],
    pregnancy: 'Rarely relevant (dementia population); limited data — use only if clearly needed.',
    geriatric: 'Well tolerated; adjust for renal function; a good choice when cholinergic GI/bradycardic effects are problematic. Add to an AChE inhibitor for moderate–severe disease.',
    renalHepatic: 'Renally cleared — reduce dose in severe renal impairment; urinary alkalinisation raises levels.',
    cardiac: 'No vagotonic bradycardia (not a cholinergic drug); can mildly raise blood pressure. A safer cardiac profile than the cholinesterase inhibitors in patients with conduction disease.',
    pearls: [
      'Different mechanism (NMDA antagonist) → can be COMBINED with an AChE inhibitor in moderate–severe Alzheimer.',
      'Renally excreted, largely UNCHANGED — dose-reduce in severe renal impairment (contrast the hepatically-metabolised AChE inhibitors).',
      'Well tolerated: no cholinergic GI/bradycardic effects; main issues are dizziness, constipation and confusion.',
      'Alkaline urine (e.g., carbonic anhydrase inhibitors, sodium bicarbonate) reduces clearance and raises levels.',
      'Reserved for MODERATE–SEVERE disease — not first-line for mild Alzheimer (unlike the AChE inhibitors).',
    ],
    mnemonics: ['"meMANtine = the odd MAN out" — NMDA (not cholinergic), moderate–severe, renally cleared, combines with an AChE-I.'],
    confusables: ['Memantine (NMDA antagonist, moderate–severe, renal, well tolerated) vs the cholinesterase inhibitors (cholinergic, GI/brady effects, hepatic).', 'Memantine vs amantadine — both NMDA-active; amantadine is antiviral/anti-parkinsonian and should not be co-prescribed with memantine.'],
    classDifferentiators: 'The ONLY NMDA-receptor antagonist here — distinct mechanism, distinct side effects (no cholinergic GI/brady), renally cleared, indicated for moderate–severe Alzheimer, and safely combined with a cholinesterase inhibitor.',
    examHooks: ['Which anti-dementia drug has a non-cholinergic (NMDA) mechanism and is added to an AChE inhibitor in moderate–severe disease? (memantine)', 'Which anti-dementia drug is renally cleared and dose-reduced in severe renal impairment? (memantine)'],
    counsellingPoints: ['It works differently from the other dementia drugs and can be taken alongside them.', 'Common effects are dizziness, constipation or mild confusion — tell us if they persist.', 'It does not cause the nausea/slow-pulse problems of the other class.', 'Dose depends on kidney function — let us know of any kidney problems.'],
    vignettes: [
      {
        stem: 'A patient with moderate-to-severe Alzheimer disease is already stable on donepezil but continues to decline. Which addition is mechanistically rational and safe to combine?',
        options: [
          'Add galantamine for a second cholinesterase inhibitor',
          'Add memantine, an NMDA-receptor antagonist',
          'Add oxybutynin for coexisting urinary urgency',
          'Add rivastigmine patch on top of donepezil',
        ],
        answer: 'Add memantine, an NMDA-receptor antagonist',
        explanation: 'Memantine has a distinct (glutamatergic NMDA) mechanism and non-overlapping toxicity, so it is combined with a cholinesterase inhibitor in moderate–severe disease. Stacking two cholinesterase inhibitors is not done, and an anticholinergic (oxybutynin) would oppose donepezil.',
        testedFact: 'Memantine + AChE inhibitor combination in moderate–severe Alzheimer',
        source: { name: 'openFDA/monograph memantine label; combination use in moderate–severe AD', origin: 'monograph' },
      },
    ],
    _prov: DEMENTIA_PROV,
  },
};
