// authored/fga.js — authored overlay for first-generation (typical) antipsychotics.
//
// Mechanism/PK/dosing summaries + the pedagogical layer, grounded in established
// pharmacology and the fetched openFDA/monograph label sections. `_prov` declares which
// safety-critical fields the label text grounds; build.js attaches that source text and,
// where a field cannot be grounded, downgrades it to origin 'authored' + verifyFlag.
//
// FGA class theme: high-affinity D2 blockade drives BOTH efficacy (positive symptoms) and
// the signature harms. Blocking mesolimbic D2 = antipsychotic; blocking nigrostriatal D2 =
// EPS (acute dystonia, akathisia, parkinsonism, tardive dyskinesia); blocking tuberoinfundibular
// D2 = hyperprolactinemia. Add NMS (idiosyncratic — fever, lead-pipe rigidity, autonomic
// instability, ↑CK, altered mental status) and QT prolongation. POTENCY axis is the master key:
// HIGH-potency (haloperidol, fluphenazine, pimozide, trifluoperazine) → more EPS, LESS
// sedation/anticholinergic/orthostasis; LOW-potency (chlorpromazine, methotrimeprazine) →
// more sedation/anticholinergic/orthostasis/weight, LESS EPS. Many are available as
// long-acting injectables (LAI/depot) — the pipeline supplies formulations; we note the depot
// clinically. All carry the class effect of increased mortality in elderly patients with
// dementia-related psychosis.

const FGA_PROV = {
  startingDose: 'openfda', maxDose: 'openfda', seriousAE: 'openfda', syndromes: 'openfda',
  majorDDI: 'openfda', contraindicatedCombos: 'openfda', pregnancy: 'openfda',
  overdoseLethality: 'openfda',
};

export default {
  haloperidol: {
    pronunciation: 'ha-loe-PER-i-dol',
    moa: 'High-potency butyrophenone; potent post-synaptic D2 receptor antagonist (mesolimbic → antipsychotic; nigrostriatal → EPS; tuberoinfundibular → ↑prolactin).',
    receptorProfile: 'Very high D2 affinity; minimal H1/M1 (little sedation or anticholinergic effect); modest α1. This "clean" off-target profile is why EPS dominate.',
    onsetOfEffect: 'Behavioural calming within hours (IM); antipsychotic effect over days–weeks.',
    halfLife: 'Oral ~14–37 h; decanoate LAI ~3 weeks.',
    metabolism: 'Hepatic — CYP3A4 (major) and CYP2D6; glucuronidation. Reduced to (less active) reduced-haloperidol.',
    startingDose: '0.5–5 mg PO; 2–5 mg IM for acute agitation.',
    titration: 'Adjust to response; lower and slower in elderly (start ~0.25–0.5 mg).',
    maxDose: 'Up to ~20 mg/day orally in schizophrenia (higher rarely used); minimize dose to limit EPS.',
    frequencyTiming: 'Oral once daily to BID–TID. Decanoate LAI given deep IM every 4 weeks (≈10–20× the oral daily dose).',
    startStopCrossTaper: 'Overlap oral coverage when initiating decanoate (delayed steady state). No serotonergic washout issues.',
    administrationNotes: 'IV haloperidol carries the highest torsades risk — if used, continuous ECG/telemetry; IM/PO preferred. Decanoate is a mainstay LAI for non-adherence.',
    commonSE: ['Akathisia', 'Acute dystonia', 'Drug-induced parkinsonism', 'Hyperprolactinemia (galactorrhea, amenorrhea)', 'Insomnia/restlessness'],
    seriousAE: ['Neuroleptic malignant syndrome', 'Tardive dyskinesia', 'QT prolongation / torsades (esp. IV)', 'Severe extrapyramidal reactions', 'Increased mortality in elderly patients with dementia-related psychosis'],
    syndromes: ['Extrapyramidal symptoms (dystonia/akathisia/parkinsonism)', 'Tardive dyskinesia', 'Neuroleptic malignant syndrome', 'QT prolongation', 'Hyperprolactinemia'],
    overdoseLethality: 'Less lethal than TCAs/MAOIs, but severe EPS, sedation, hypotension and QT prolongation/arrhythmia can occur; monitor ECG.',
    baselineWorkup: ['ECG (QT), especially with cardiac risk or IV use', 'Electrolytes (K/Mg)'],
    ongoingMonitoring: 'AIMS for tardive dyskinesia; watch for EPS/akathisia; ECG if IV or QT risk; prolactin if symptomatic.',
    majorDDI: ['CYP3A4/2D6 inhibitors raise levels', 'Other QT-prolonging drugs (additive torsades risk)', 'CNS depressants (additive sedation)', 'Anticholinergics (may mask/worsen TD, precipitate ileus)'],
    contraindicatedCombos: ['Other markedly QT-prolonging agents', 'Severe CNS depression'],
    pregnancy: 'Third-trimester exposure risks neonatal EPS/withdrawal; weigh untreated psychosis. Tie to monograph/CANMAT.',
    lactation: 'Excreted in milk; monitor infant for sedation/EPS.',
    geriatric: 'Increased mortality in elderly with dementia-related psychosis; start very low; falls, EPS, QT.',
    cardiac: 'Dose-dependent QT prolongation; IV route highest risk — telemetry.',
    pearls: [
      'The prototype HIGH-potency FGA: maximal EPS, minimal sedation/anticholinergic/orthostatic effect.',
      'Decanoate LAI every 4 weeks is a workhorse for non-adherence — overlap oral until steady state.',
      'IV haloperidol → torsades risk; QT monitoring is mandatory (many hospitals restrict IV use).',
    ],
    mnemonics: ['"HALO on top" — high-potency: high EPS, low sedation. Acute dystonia = the halo slips (fix with benztropine/diphenhydramine).'],
    confusables: ['Haloperidol (butyrophenone antipsychotic) vs droperidol (its short-acting cousin) — droperidol is the antiemetic/agitation agent with the QT warning.'],
    classDifferentiators: 'High-potency benchmark; most EPS, least sedation/anticholinergic; available as decanoate LAI; IV form is the QT worry.',
    examHooks: ['Young patient develops torticollis/oculogyric crisis hours after IM haloperidol — diagnosis and treatment? (acute dystonia → IM benztropine or diphenhydramine).'],
    counsellingPoints: ['Report muscle stiffness, restlessness, or abnormal movements early.', 'Do not stop abruptly.', 'Depot injection means fewer daily pills but steady blood levels build slowly.'],
    vignettes: [
      {
        stem: 'Four hours after receiving IM haloperidol for agitation, a 22-year-old man develops a sustained upward gaze and painful neck spasm. What is the most appropriate immediate treatment?',
        options: ['IV dantrolene', 'IM benztropine', 'Oral propranolol', 'Increase the haloperidol dose'],
        answer: 'IM benztropine',
        explanation: 'This is acute dystonia (oculogyric crisis + torticollis), an EPS most common with high-potency agents in young men early in treatment. First-line is an anticholinergic (benztropine) or diphenhydramine; dantrolene is for NMS, not dystonia.',
        testedFact: 'Acute dystonia management with high-potency FGAs',
        source: { name: 'openFDA/DailyMed haloperidol label — EPS; CANMAT/CPA schizophrenia', origin: 'openfda' },
      },
    ],
    _prov: FGA_PROV,
  },

  chlorpromazine: {
    pronunciation: 'klor-PROE-ma-zeen',
    moa: 'Low-potency aliphatic phenothiazine; D2 antagonist with broad off-target blockade (H1, M1, α1, 5-HT2).',
    receptorProfile: 'Moderate D2 affinity but strong H1 (sedation), M1 (anticholinergic) and α1 (orthostasis) antagonism — the low-potency signature.',
    onsetOfEffect: 'Sedation within hours; antipsychotic effect over days–weeks.',
    halfLife: '~16–30 h (many active metabolites).',
    metabolism: 'Extensive hepatic metabolism (CYP2D6, CYP1A2); numerous metabolites; CYP2D6 inhibitor.',
    startingDose: '25–50 mg PO (often TID); 25 mg IM for acute use.',
    titration: 'Increase gradually to effect; wide dose range.',
    maxDose: 'Up to ~800–1000 mg/day in resistant schizophrenia (much lower usual dosing).',
    frequencyTiming: 'Divided doses; larger portion at bedtime given sedation.',
    startStopCrossTaper: 'Taper to avoid cholinergic rebound and recurrence; watch orthostasis on uptitration.',
    administrationNotes: 'Historic prototype antipsychotic ("largactil"). Photosensitivity and orthostasis limit outpatient use.',
    commonSE: ['Marked sedation', 'Orthostatic hypotension', 'Anticholinergic effects (dry mouth, constipation, blurred vision, urinary retention)', 'Photosensitivity', 'Weight gain'],
    seriousAE: ['Neuroleptic malignant syndrome', 'Agranulocytosis', 'Cholestatic jaundice', 'QT prolongation', 'Tardive dyskinesia', 'Lowered seizure threshold', 'Increased mortality in elderly patients with dementia-related psychosis'],
    syndromes: ['Extrapyramidal symptoms (less than high-potency)', 'Tardive dyskinesia', 'Neuroleptic malignant syndrome', 'QT prolongation', 'Hyperprolactinemia', 'Anticholinergic burden'],
    overdoseLethality: 'Sedation, profound orthostatic hypotension, anticholinergic toxicity, QT prolongation/arrhythmia and seizures; supportive care with ECG monitoring.',
    baselineWorkup: ['ECG if cardiac risk', 'Baseline LFTs'],
    ongoingMonitoring: 'BP (orthostasis); AIMS for TD; LFTs if jaundice; watch anticholinergic load.',
    majorDDI: ['Other QT-prolonging drugs', 'CNS depressants (additive sedation)', 'Anticholinergics (additive)', 'Antihypertensives (additive hypotension)'],
    contraindicatedCombos: ['Other markedly QT-prolonging agents', 'Severe CNS depression'],
    pregnancy: 'Neonatal EPS/withdrawal with late exposure; weigh maternal illness.',
    lactation: 'Excreted in milk; sedation risk in infant.',
    geriatric: 'Poorly tolerated — orthostasis, falls, anticholinergic delirium; increased mortality in dementia.',
    cardiac: 'QT prolongation and orthostatic hypotension are prominent.',
    pearls: [
      'The prototype LOW-potency FGA: maximal sedation/anticholinergic/orthostasis, comparatively LESS EPS than high-potency agents.',
      'Photosensitivity is classic — counsel sun protection; long-term high dose can cause blue-grey skin and lens/corneal deposits.',
      'Cholestatic jaundice and lowered seizure threshold are distinctive phenothiazine hazards.',
    ],
    mnemonics: ['Low-potency = "the 3 S/anti" load: Sedation, Slumped BP (orthostasis), and antiCholinergic — chlorpromazine leads all three.'],
    confusables: ['Chlorpromazine (low-potency, sedating) vs trifluoperazine/fluphenazine (high-potency piperazine phenothiazines, EPS-heavy).'],
    classDifferentiators: 'Low-potency benchmark: sedating, hypotensive, anticholinergic, photosensitizing; less EPS but more autonomic/metabolic burden than haloperidol.',
    examHooks: ['Which classic antipsychotic causes photosensitivity, orthostasis and blue-grey skin discoloration? (chlorpromazine).'],
    counsellingPoints: ['Use sunscreen and protective clothing (photosensitivity).', 'Rise slowly to avoid dizziness/fainting.', 'Expect drowsiness, especially at first.'],
    vignettes: [
      {
        stem: 'A patient on long-term high-dose chlorpromazine reports skin that turns grey-blue in sun-exposed areas and easy sunburn. Which property of this drug best explains these findings?',
        options: ['High-potency D2 blockade', 'Photosensitizing low-potency phenothiazine effect', 'Serotonin syndrome', 'CYP1A2 induction'],
        answer: 'Photosensitizing low-potency phenothiazine effect',
        explanation: 'Chlorpromazine is the low-potency phenothiazine prototype: prominent photosensitivity, and with chronic high-dose use, slate-grey skin pigmentation and lens/corneal deposits. High-potency agents cause more EPS, not this dermatologic picture.',
        testedFact: 'Chlorpromazine photosensitivity / low-potency profile',
        source: { name: 'openFDA/DailyMed chlorpromazine label — adverse reactions/photosensitivity', origin: 'openfda' },
      },
    ],
    _prov: FGA_PROV,
  },

  loxapine: {
    pronunciation: 'LOX-a-peen',
    moa: 'Mid-potency dibenzoxazepine (structurally related to clozapine); D2 antagonist with 5-HT2A antagonism.',
    receptorProfile: 'Moderate D2 affinity; some 5-HT2A, H1 and M1 blockade — intermediate sedation/anticholinergic burden between low- and high-potency agents.',
    onsetOfEffect: 'Oral over days–weeks; inhaled formulation calms agitation within ~10 minutes.',
    halfLife: 'Oral ~4 h (biphasic; active metabolites longer, e.g., 8-hydroxyloxapine).',
    metabolism: 'Hepatic; metabolites include amoxapine and 7/8-hydroxyloxapine.',
    startingDose: '10 mg PO BID (oral); inhaled 10 mg as a single dose for acute agitation.',
    titration: 'Increase oral dose over days to response.',
    maxDose: 'Up to ~250 mg/day orally; inhaled limited to a single 10 mg dose per 24 h.',
    frequencyTiming: 'Oral BID–QID. Inhaled: one dose only, in a monitored healthcare setting.',
    administrationNotes: 'Inhaled loxapine (Adasuve) delivers rapid control of agitation but can cause bronchospasm — administer only where a short-acting bronchodilator and airway support are available; contraindicated in asthma/COPD/active bronchospasm.',
    commonSE: ['Sedation', 'EPS (akathisia, dystonia, parkinsonism)', 'Dizziness', 'Dysgeusia/throat irritation (inhaled)', 'Anticholinergic effects'],
    seriousAE: ['Neuroleptic malignant syndrome', 'Tardive dyskinesia', 'Bronchospasm (inhaled form)', 'QT prolongation', 'Lowered seizure threshold', 'Increased mortality in elderly patients with dementia-related psychosis'],
    syndromes: ['Extrapyramidal symptoms', 'Tardive dyskinesia', 'Neuroleptic malignant syndrome', 'QT prolongation', 'Hyperprolactinemia'],
    overdoseLethality: 'Sedation, EPS, hypotension and seizures possible; supportive care.',
    ongoingMonitoring: 'For inhaled use: assess for respiratory symptoms/bronchospasm after dose; AIMS for TD; EPS.',
    majorDDI: ['CNS depressants (additive sedation)', 'Other QT-prolonging drugs', 'Drugs lowering seizure threshold', 'Anticholinergics (additive)'],
    contraindicatedCombos: ['Inhaled form with asthma/COPD or acute bronchospasm'],
    pregnancy: 'Neonatal EPS/withdrawal risk with late exposure; weigh maternal illness.',
    lactation: 'Limited data; monitor infant.',
    geriatric: 'Increased mortality in dementia; sedation and EPS; caution.',
    cardiac: 'QT prolongation possible.',
    pearls: [
      'Mid-potency FGA — but the exam angle is the INHALED formulation for acute agitation (fast, single-dose, in-clinic only).',
      'Inhaled loxapine can cause bronchospasm — contraindicated in asthma/COPD; a rescue bronchodilator must be on hand.',
      'A dibenzoxazepine chemically related to clozapine; its metabolite amoxapine is an antidepressant.',
    ],
    mnemonics: ['"LOX you breathe in" — inhaled loxapine for agitation, but watch the LUNGS (bronchospasm).'],
    confusables: ['Loxapine (FGA, dibenzoxazepine) vs clozapine (SGA dibenzodiazepine, agranulocytosis) — similar skeleton, very different class/risk.'],
    classDifferentiators: 'Intermediate potency; unique inhaled route for rapid agitation control with a bronchospasm caveat.',
    examHooks: ['Which antipsychotic has an inhaled formulation for acute agitation, and what is its key contraindication? (loxapine; asthma/COPD — bronchospasm).'],
    counsellingPoints: ['Report wheeze/chest tightness after the inhaled dose immediately.', 'Inhaled dose is a one-time, in-clinic treatment.', 'Report abnormal movements or restlessness.'],
    vignettes: [
      {
        stem: 'An emergency department wants to use inhaled loxapine to rapidly settle an agitated patient. Which pre-existing condition makes this route contraindicated?',
        options: ['Hypertension', 'Asthma or COPD', 'Type 2 diabetes', 'Hypothyroidism'],
        answer: 'Asthma or COPD',
        explanation: 'Inhaled loxapine can precipitate bronchospasm; it is contraindicated in patients with asthma, COPD, or other conditions with bronchospasm, and must be given only where a bronchodilator and airway support are available.',
        testedFact: 'Inhaled loxapine bronchospasm contraindication',
        source: { name: 'openFDA/DailyMed loxapine (inhalation) label — boxed/contraindications', origin: 'openfda' },
      },
    ],
    _prov: FGA_PROV,
  },

  perphenazine: {
    pronunciation: 'per-FEN-a-zeen',
    moa: 'Mid-potency piperazine phenothiazine; D2 receptor antagonist.',
    receptorProfile: 'Moderate–high D2 affinity; intermediate H1/M1/α1 blockade — fewer autonomic effects than chlorpromazine, more EPS.',
    onsetOfEffect: 'Antipsychotic effect over days–weeks.',
    halfLife: '~9–12 h.',
    metabolism: 'Hepatic — CYP2D6 (major); poor metabolizers/2D6 inhibitors raise levels.',
    startingDose: '4–8 mg PO BID–TID.',
    titration: 'Increase to response; usual 12–24 mg/day.',
    maxDose: 'Up to ~64 mg/day.',
    frequencyTiming: 'BID–TID dosing.',
    administrationNotes: 'The FGA comparator in the CATIE effectiveness trial — performed comparably to several SGAs at much lower cost.',
    commonSE: ['EPS (akathisia, parkinsonism, dystonia)', 'Moderate sedation', 'Hyperprolactinemia', 'Orthostasis (mild–moderate)', 'Anticholinergic effects (mild)'],
    seriousAE: ['Neuroleptic malignant syndrome', 'Tardive dyskinesia', 'QT prolongation', 'Agranulocytosis (rare)', 'Increased mortality in elderly patients with dementia-related psychosis'],
    syndromes: ['Extrapyramidal symptoms', 'Tardive dyskinesia', 'Neuroleptic malignant syndrome', 'QT prolongation', 'Hyperprolactinemia'],
    overdoseLethality: 'Sedation, EPS, hypotension, QT prolongation; supportive care.',
    ongoingMonitoring: 'AIMS for TD; EPS; prolactin if symptomatic.',
    majorDDI: ['CYP2D6 inhibitors (paroxetine, fluoxetine, bupropion) raise levels', 'Other QT-prolonging drugs', 'CNS depressants'],
    contraindicatedCombos: ['Other markedly QT-prolonging agents', 'Severe CNS depression'],
    pregnancy: 'Neonatal EPS/withdrawal with late exposure; weigh maternal illness.',
    lactation: 'Excreted in milk; monitor infant.',
    geriatric: 'Increased mortality in dementia; EPS and orthostasis; caution.',
    pearls: [
      'The CATIE trial FGA — mid-potency perphenazine was roughly as effective as several SGAs and highly cost-effective, challenging assumptions that newer = better.',
      'Sits between chlorpromazine and haloperidol: moderate EPS, moderate sedation/autonomic effects.',
      'CYP2D6-metabolized — interactions with 2D6 inhibitors matter.',
    ],
    mnemonics: ['"PERphenazine = the PERformer in CATIE" — the mid-potency FGA that held its own against SGAs.'],
    confusables: ['Perphenazine (antipsychotic) is combined with amitriptyline in older fixed-dose products — don\'t confuse the combo with monotherapy.'],
    classDifferentiators: 'Mid-potency piperazine phenothiazine; the CATIE FGA benchmark; balanced side-effect profile.',
    examHooks: ['Which FGA served as the first-generation comparator in CATIE and performed comparably to SGAs? (perphenazine).'],
    counsellingPoints: ['Report abnormal movements or restlessness.', 'Effect builds over weeks.', 'Rise slowly if lightheaded.'],
    vignettes: [
      {
        stem: 'In the CATIE schizophrenia effectiveness trial, one first-generation antipsychotic was compared with several second-generation agents and proved similarly effective and more cost-effective. Which drug was it?',
        options: ['Haloperidol', 'Perphenazine', 'Chlorpromazine', 'Fluphenazine'],
        answer: 'Perphenazine',
        explanation: 'CATIE used mid-potency perphenazine as its FGA comparator; outcomes were broadly comparable to several SGAs (except olanzapine on some measures) at lower cost, an important health-economics teaching point.',
        testedFact: 'Perphenazine as the CATIE FGA comparator',
        source: { name: 'CATIE (Lieberman et al., NEJM 2005); CANMAT/CPA schizophrenia', origin: 'canmat' },
      },
    ],
    _prov: FGA_PROV,
  },

  fluphenazine: {
    pronunciation: 'floo-FEN-a-zeen',
    moa: 'High-potency piperazine phenothiazine; potent D2 receptor antagonist.',
    receptorProfile: 'Very high D2 affinity; low H1/M1 (little sedation/anticholinergic), some α1 — EPS-predominant profile like haloperidol.',
    onsetOfEffect: 'Antipsychotic effect over days–weeks.',
    halfLife: 'Oral ~15 h; decanoate LAI ~7–10 days (up to ~14).',
    metabolism: 'Hepatic — CYP2D6.',
    startingDose: '2.5–10 mg/day PO in divided doses.',
    titration: 'Adjust to response; use lowest effective dose to limit EPS.',
    maxDose: 'Up to ~20–40 mg/day orally (usual much lower).',
    frequencyTiming: 'Oral divided daily. Decanoate LAI deep IM every 2–3 weeks.',
    startStopCrossTaper: 'Overlap oral coverage when starting decanoate until steady state.',
    administrationNotes: 'Decanoate depot is a classic maintenance LAI for non-adherence; shorter dosing interval than haloperidol decanoate.',
    commonSE: ['Akathisia', 'Acute dystonia', 'Parkinsonism', 'Hyperprolactinemia', 'Insomnia/restlessness'],
    seriousAE: ['Neuroleptic malignant syndrome', 'Tardive dyskinesia', 'QT prolongation', 'Severe EPS', 'Increased mortality in elderly patients with dementia-related psychosis'],
    syndromes: ['Extrapyramidal symptoms', 'Tardive dyskinesia', 'Neuroleptic malignant syndrome', 'QT prolongation', 'Hyperprolactinemia'],
    overdoseLethality: 'Severe EPS, sedation, hypotension, QT prolongation; supportive care.',
    ongoingMonitoring: 'AIMS for TD; EPS/akathisia; prolactin if symptomatic.',
    majorDDI: ['CYP2D6 inhibitors raise levels', 'Other QT-prolonging drugs', 'CNS depressants', 'Anticholinergics (additive)'],
    contraindicatedCombos: ['Other markedly QT-prolonging agents', 'Severe CNS depression'],
    pregnancy: 'Neonatal EPS/withdrawal with late exposure; weigh maternal illness.',
    lactation: 'Excreted in milk; monitor infant.',
    geriatric: 'Increased mortality in dementia; EPS-prone; caution.',
    cardiac: 'QT prolongation possible.',
    pearls: [
      'High-potency like haloperidol: lots of EPS, little sedation/anticholinergic effect.',
      'Decanoate LAI dosed every 2–3 weeks (a shorter interval than haloperidol decanoate\'s 4 weeks) — a common maintenance choice for non-adherence.',
      'Piperazine phenothiazines (fluphenazine, trifluoperazine) are the high-potency members of that family.',
    ],
    mnemonics: ['"Fluphenazine & haloperidol = high-potency depot duo" — both EPS-heavy LAIs; fluphenazine q2–3 wk vs haloperidol q4 wk.'],
    confusables: ['Fluphenazine (high-potency antipsychotic) vs fluoxetine (SSRI) vs fluvoxamine (SSRI) — all "flu-", different classes.'],
    classDifferentiators: 'High-potency phenothiazine with a shorter-interval decanoate LAI; EPS-heavy, low sedation.',
    examHooks: ['Which two FGAs are the classic decanoate long-acting injectables, and how do their intervals differ? (fluphenazine ~q2–3 wk; haloperidol ~q4 wk).'],
    counsellingPoints: ['Report muscle stiffness, tremor, restlessness, or abnormal movements.', 'Depot injection gives steady levels — attend scheduled injections.', 'Do not stop abruptly.'],
    vignettes: [
      {
        stem: 'A patient with schizophrenia repeatedly stops oral medication. You choose a high-potency FGA decanoate long-acting injectable. Which agent, and what should you do during initiation?',
        options: ['Chlorpromazine — no oral overlap needed', 'Fluphenazine decanoate — overlap oral coverage until steady state', 'Clozapine — start at full dose', 'Loxapine inhaled — repeat daily'],
        answer: 'Fluphenazine decanoate — overlap oral coverage until steady state',
        explanation: 'Fluphenazine decanoate is a high-potency FGA LAI dosed roughly every 2–3 weeks; because depot levels rise slowly, oral coverage is overlapped during initiation. Chlorpromazine (low-potency) is not a standard depot; clozapine and inhaled loxapine do not fit.',
        testedFact: 'Fluphenazine decanoate LAI initiation/oral overlap',
        source: { name: 'openFDA/DailyMed fluphenazine decanoate monograph; CANMAT/CPA schizophrenia', origin: 'monograph' },
      },
    ],
    _prov: FGA_PROV,
  },

  zuclopenthixol: {
    pronunciation: 'zoo-kloe-pen-THIX-ol',
    moa: 'Thioxanthene (Canada/Europe; not marketed in the US); D1 and D2 receptor antagonist.',
    receptorProfile: 'High D2 affinity with additional α1 and H1 blockade — moderately sedating for a higher-potency agent.',
    onsetOfEffect: 'Acetate (Acuphase) sedating within hours, effect over ~2–3 days; oral/depot over days–weeks.',
    halfLife: 'Oral ~20 h; decanoate depot ~19 days.',
    metabolism: 'Hepatic — CYP2D6 and CYP3A4.',
    startingDose: 'Oral ~10–50 mg/day; acetate (Acuphase) 50–150 mg IM per episode.',
    titration: 'Adjust to response; acetate repeated no more often than every 2–3 days.',
    maxDose: 'Oral up to ~150 mg/day; limit cumulative acetate per treatment course per monograph.',
    frequencyTiming: 'Three distinct forms: oral (dihydrochloride), acetate/"Acuphase" (short-acting IM, effect ~72 h, for acute disturbance), and decanoate depot (deep IM every 2–4 weeks).',
    administrationNotes: 'Acuphase (acetate) is a Canadian tool for the acutely agitated/psychotic patient — one injection covers ~2–3 days, bridging to oral or depot. Do not use acetate for maintenance.',
    commonSE: ['Sedation', 'EPS (akathisia, dystonia, parkinsonism)', 'Hyperprolactinemia', 'Orthostasis', 'Dry mouth'],
    seriousAE: ['Neuroleptic malignant syndrome', 'Tardive dyskinesia', 'QT prolongation', 'Severe EPS', 'Increased mortality in elderly patients with dementia-related psychosis'],
    syndromes: ['Extrapyramidal symptoms', 'Tardive dyskinesia', 'Neuroleptic malignant syndrome', 'QT prolongation', 'Hyperprolactinemia'],
    overdoseLethality: 'Sedation, EPS, hypotension, QT prolongation; supportive care. Acetate\'s prolonged action complicates overdose.',
    ongoingMonitoring: 'AIMS for TD; EPS; sedation; BP.',
    majorDDI: ['CYP2D6/3A4 inhibitors raise levels', 'Other QT-prolonging drugs', 'CNS depressants (additive sedation)'],
    contraindicatedCombos: ['Other markedly QT-prolonging agents', 'Severe CNS depression'],
    pregnancy: 'Neonatal EPS/withdrawal with late exposure; weigh maternal illness.',
    lactation: 'Excreted in milk; monitor infant.',
    geriatric: 'Increased mortality in dementia; sedation/EPS/orthostasis; caution.',
    pearls: [
      'Canada-specific thioxanthene with THREE esters: oral, acetate (Acuphase, short-acting IM ~72 h for acute disturbance), and decanoate depot (q2–4 wk).',
      'Acuphase is for acute management only — a single injection bridges ~2–3 days; it is NOT a maintenance depot.',
      'Somewhat more sedating than pure high-potency agents due to α1/H1 blockade.',
    ],
    mnemonics: ['"AcuPHASE = acute phase" — zuclopenthixol acetate covers the acute 72-hour phase, then switch to oral/depot.'],
    confusables: ['Zuclopenthixol ACETATE (Acuphase, short-acting) vs DECANOATE (maintenance depot) — same molecule, opposite purposes.'],
    classDifferentiators: 'Canadian thioxanthene notable for the short-acting acetate (Acuphase) niche in acute psychosis, plus a maintenance decanoate depot.',
    examHooks: ['A single IM antipsychotic that covers ~2–3 days of acute psychotic agitation in Canada? (zuclopenthixol acetate / Acuphase).'],
    counsellingPoints: ['The Acuphase injection works for a few days as a bridge.', 'Report stiffness, restlessness, or abnormal movements.', 'Attend scheduled depot injections for maintenance.'],
    vignettes: [
      {
        stem: 'An acutely psychotic, agitated inpatient needs parenteral coverage lasting a couple of days while an oral regimen is established. Which Canadian formulation is designed for this "acute phase" bridge?',
        options: ['Zuclopenthixol acetate (Acuphase)', 'Zuclopenthixol decanoate', 'Fluphenazine decanoate', 'Haloperidol decanoate'],
        answer: 'Zuclopenthixol acetate (Acuphase)',
        explanation: 'Zuclopenthixol acetate (Acuphase) is a short-acting IM ester whose effect lasts about 2–3 days — used to bridge the acute phase, not for maintenance. The decanoate esters are the long-acting maintenance depots.',
        testedFact: 'Zuclopenthixol acetate (Acuphase) acute-phase role',
        source: { name: 'Zuclopenthixol (Clopixol) product monograph — Health Canada', origin: 'monograph' },
      },
    ],
    _prov: FGA_PROV,
  },

  flupenthixol: {
    pronunciation: 'floo-pen-THIX-ol',
    moa: 'Thioxanthene (Canada/Europe; not marketed in the US); D1 and D2 receptor antagonist.',
    receptorProfile: 'High D2 affinity; at LOW doses a mild activating/antidepressant effect is described; higher doses are antipsychotic.',
    onsetOfEffect: 'Antipsychotic effect over days–weeks; depot maintenance.',
    halfLife: 'Oral ~35 h; decanoate depot ~3 weeks.',
    metabolism: 'Hepatic — CYP2D6 and sulfoxidation.',
    startingDose: 'Oral ~1 mg/day (low-dose) up to a few mg/day for psychosis.',
    titration: 'Adjust to response; keep low to limit EPS.',
    maxDose: 'Oral up to ~12 mg/day (usual lower); depot per monograph.',
    frequencyTiming: 'Oral daily; decanoate depot deep IM every 2–3 weeks (up to ~4).',
    startStopCrossTaper: 'Overlap oral coverage when initiating depot.',
    administrationNotes: 'Canada-specific thioxanthene available as both oral tablets and a decanoate depot for maintenance; low-dose oral flupenthixol has historically been used for depression/anxiety.',
    commonSE: ['EPS (akathisia, dystonia, parkinsonism)', 'Restlessness/activation (low dose)', 'Hyperprolactinemia', 'Insomnia', 'Mild sedation'],
    seriousAE: ['Neuroleptic malignant syndrome', 'Tardive dyskinesia', 'QT prolongation', 'Severe EPS', 'Increased mortality in elderly patients with dementia-related psychosis'],
    syndromes: ['Extrapyramidal symptoms', 'Tardive dyskinesia', 'Neuroleptic malignant syndrome', 'QT prolongation', 'Hyperprolactinemia'],
    overdoseLethality: 'EPS, sedation, hypotension, QT prolongation; supportive care.',
    ongoingMonitoring: 'AIMS for TD; EPS/akathisia; prolactin if symptomatic.',
    majorDDI: ['CYP2D6 inhibitors raise levels', 'Other QT-prolonging drugs', 'CNS depressants'],
    contraindicatedCombos: ['Other markedly QT-prolonging agents', 'Severe CNS depression'],
    pregnancy: 'Neonatal EPS/withdrawal with late exposure; weigh maternal illness.',
    lactation: 'Excreted in milk; monitor infant.',
    geriatric: 'Increased mortality in dementia; EPS; caution.',
    pearls: [
      'Canada-specific thioxanthene with an oral form and a decanoate depot (q2–3 wk maintenance).',
      'Distinctively, LOW-dose flupenthixol can be activating/mildly antidepressant, while higher doses are antipsychotic.',
      'Its sibling zuclopenthixol adds the short-acting Acuphase; flupenthixol is oral + depot only.',
    ],
    mnemonics: ['Two Canadian thioxanthenes: fluPENTHIXol and zucloPENTHIXol — "-penthixol" = thioxanthene depot family.'],
    confusables: ['Flupenthixol vs zuclopenthixol — both Canadian thioxanthene depots; only zuclopenthixol has the short-acting acetate (Acuphase).'],
    classDifferentiators: 'Canadian thioxanthene; oral + decanoate depot; low-dose activating/antidepressant quirk distinguishes it.',
    examHooks: ['Name the two Canadian thioxanthene antipsychotics available as depots. (flupenthixol and zuclopenthixol).'],
    counsellingPoints: ['Report restlessness, stiffness, or abnormal movements.', 'Attend scheduled depot injections.', 'Effect builds over weeks.'],
    vignettes: [
      {
        stem: 'Which pair of first-generation antipsychotics are thioxanthenes available in Canada as long-acting decanoate depots but not marketed in the United States?',
        options: ['Haloperidol and fluphenazine', 'Flupenthixol and zuclopenthixol', 'Chlorpromazine and thioridazine', 'Perphenazine and trifluoperazine'],
        answer: 'Flupenthixol and zuclopenthixol',
        explanation: 'Flupenthixol and zuclopenthixol are thioxanthenes used in Canada/Europe (not the US), both available as decanoate depots. Haloperidol/fluphenazine are butyrophenone/phenothiazine depots available in the US.',
        testedFact: 'Canadian thioxanthene depots',
        source: { name: 'Flupentixol (Fluanxol) product monograph — Health Canada', origin: 'monograph' },
      },
    ],
    _prov: FGA_PROV,
  },

  pimozide: {
    pronunciation: 'PIM-oh-zide',
    moa: 'Diphenylbutylpiperidine; potent, selective D2 receptor antagonist (also blocks cardiac calcium channels → QT prolongation).',
    receptorProfile: 'High D2 affinity; low sedation/anticholinergic; the defining feature is marked, dose-dependent QT prolongation.',
    onsetOfEffect: 'Antipsychotic/anti-tic effect over days–weeks.',
    halfLife: 'Long — ~55 h.',
    metabolism: 'Hepatic — CYP3A4 (major) and CYP2D6. Strong inhibitors of either markedly raise levels and QT risk.',
    startingDose: 'Tourette: 1–2 mg/day (0.05 mg/kg in children), often at bedtime.',
    titration: 'Increase slowly every few days with ECG surveillance.',
    maxDose: 'Tourette: up to ~10 mg/day (or 0.2 mg/kg); use the lowest effective dose.',
    frequencyTiming: 'Once daily (long half-life); ECG before and during dose increases.',
    administrationNotes: 'Reserved largely for Tourette syndrome when other agents fail. Baseline and follow-up ECGs are mandatory; avoid with QT-prolonging or CYP3A4/2D6-inhibiting drugs and grapefruit juice.',
    commonSE: ['EPS (akathisia, dystonia, parkinsonism)', 'Sedation', 'Hyperprolactinemia', 'ECG changes (QT prolongation)', 'Dry mouth'],
    seriousAE: ['QT prolongation / torsades de pointes (sudden death reported)', 'Neuroleptic malignant syndrome', 'Tardive dyskinesia', 'Severe EPS', 'Increased mortality in elderly patients with dementia-related psychosis'],
    syndromes: ['QT prolongation', 'Extrapyramidal symptoms', 'Tardive dyskinesia', 'Neuroleptic malignant syndrome', 'Hyperprolactinemia'],
    overdoseLethality: 'Higher arrhythmia risk than most FGAs — QT prolongation/torsades; continuous ECG monitoring in overdose.',
    baselineWorkup: ['ECG (QTc)', 'Electrolytes (K/Mg)', 'Review concomitant QT drugs and CYP3A4/2D6 inhibitors'],
    ongoingMonitoring: 'Serial ECGs with dose changes; electrolytes; AIMS for TD.',
    majorDDI: ['CYP3A4 inhibitors — macrolides (clarithromycin/erythromycin), azole antifungals, protease inhibitors, grapefruit juice (CONTRAINDICATED)', 'CYP2D6 inhibitors (fluoxetine, paroxetine)', 'Other QT-prolonging drugs (CONTRAINDICATED)'],
    contraindicatedCombos: ['CYP3A4 inhibitors (macrolides, azoles, protease inhibitors)', 'Other QT-prolonging agents', 'Grapefruit juice'],
    pregnancy: 'Limited data; weigh maternal illness; neonatal EPS with late exposure.',
    lactation: 'Excreted in milk; monitor infant.',
    geriatric: 'Increased mortality in dementia; QT and EPS risk; caution.',
    cardiac: 'The high-QT FGA — dose-dependent QT prolongation with torsades/sudden death; ECG-driven dosing.',
    pearls: [
      'The QT champion among FGAs — dose-dependent QT prolongation with torsades; ECG monitoring is mandatory.',
      'CYP3A4-dependent metabolism makes macrolides, azole antifungals, protease inhibitors and grapefruit juice CONTRAINDICATED (levels + QT rise).',
      'Niche indication: Tourette syndrome refractory to other agents (a diphenylbutylpiperidine).',
    ],
    mnemonics: ['"PIMozide = Prolongs the QT, Interacts via 3A4, Manages tics."'],
    confusables: ['Pimozide vs primidone (anticonvulsant) — similar names, unrelated drugs.'],
    classDifferentiators: 'Diphenylbutylpiperidine with the strongest QT signal and the most restrictive CYP3A4/2D6 interaction list; Tourette niche.',
    examHooks: ['Which antipsychotic is contraindicated with clarithromycin because of QT prolongation via CYP3A4 inhibition? (pimozide).'],
    counsellingPoints: ['Avoid grapefruit juice.', 'Tell every prescriber you take pimozide (antibiotic/antifungal interactions).', 'Report fainting or palpitations; keep scheduled ECGs.'],
    vignettes: [
      {
        stem: 'A patient with Tourette syndrome on pimozide is prescribed clarithromycin for a chest infection. Why is this combination contraindicated?',
        options: ['Clarithromycin induces CYP3A4, lowering pimozide efficacy', 'Clarithromycin inhibits CYP3A4, raising pimozide levels and QT/torsades risk', 'It precipitates serotonin syndrome', 'It causes agranulocytosis'],
        answer: 'Clarithromycin inhibits CYP3A4, raising pimozide levels and QT/torsades risk',
        explanation: 'Pimozide is metabolized by CYP3A4 and prolongs QT dose-dependently. CYP3A4 inhibitors (macrolides, azoles, protease inhibitors, grapefruit) raise pimozide levels, increasing the risk of torsades — hence the contraindication.',
        testedFact: 'Pimozide CYP3A4 interaction + QT',
        source: { name: 'openFDA/DailyMed pimozide label — contraindications/CYP3A4/QT', origin: 'openfda' },
      },
    ],
    _prov: FGA_PROV,
  },

  methotrimeprazine: {
    pronunciation: 'meth-oh-trye-MEP-ra-zeen',
    moa: 'Low-potency phenothiazine (a.k.a. levomepromazine); D2 antagonist with broad H1/M1/α1 and 5-HT2 blockade; intrinsic analgesic and antiemetic activity.',
    receptorProfile: 'Strong H1 (very sedating), α1 (marked orthostasis) and M1 (anticholinergic); potent antiemetic and analgesic — used well beyond psychosis.',
    onsetOfEffect: 'Sedation/analgesia/antiemesis within hours.',
    halfLife: '~15–30 h.',
    metabolism: 'Hepatic (demethylation, sulfoxidation, glucuronidation).',
    startingDose: 'Palliative: low doses (e.g., 6.25–12.5 mg) for nausea/agitation; analgesic/sedative dosing individualized.',
    titration: 'Titrate to symptom control; watch orthostasis and sedation.',
    maxDose: 'Wide range; higher antipsychotic doses limited by sedation/hypotension.',
    frequencyTiming: 'Oral or SC/IM; often at bedtime or by continuous SC infusion in palliative care.',
    administrationNotes: 'A palliative-care staple — combines sedation, analgesia and antiemesis; frequently given subcutaneously for terminal restlessness, nausea and pain.',
    commonSE: ['Profound sedation', 'Orthostatic hypotension (marked)', 'Anticholinergic effects', 'Weight gain', 'Injection-site reactions (SC)'],
    seriousAE: ['Neuroleptic malignant syndrome', 'Severe hypotension', 'QT prolongation', 'Tardive dyskinesia', 'Agranulocytosis (rare)', 'Increased mortality in elderly patients with dementia-related psychosis'],
    syndromes: ['Extrapyramidal symptoms (less than high-potency)', 'Tardive dyskinesia', 'Neuroleptic malignant syndrome', 'QT prolongation', 'Anticholinergic burden'],
    overdoseLethality: 'Profound sedation and hypotension, anticholinergic toxicity, QT prolongation; supportive care.',
    ongoingMonitoring: 'BP (orthostasis); sedation; AIMS for TD; in palliative use, symptom control vs oversedation.',
    majorDDI: ['CNS depressants/opioids (additive sedation — often intended in palliative care)', 'Antihypertensives (additive hypotension)', 'Other QT-prolonging drugs', 'Anticholinergics (additive)'],
    contraindicatedCombos: ['Other markedly QT-prolonging agents', 'Severe CNS depression'],
    pregnancy: 'Weigh maternal illness; neonatal EPS/sedation with late exposure.',
    lactation: 'Excreted in milk; sedation risk in infant.',
    geriatric: 'Very sedating and hypotensive — high fall/delirium risk; increased mortality in dementia.',
    cardiac: 'Marked orthostatic hypotension and QT prolongation.',
    pearls: [
      'Canada-specific low-potency phenothiazine (levomepromazine) — VERY sedating, with genuine analgesic and antiemetic properties.',
      'A palliative-care workhorse: given (often subcutaneously) for terminal agitation, intractable nausea and pain.',
      'Marked orthostatic hypotension and sedation are the dose-limiting effects; EPS are comparatively mild (low-potency).',
    ],
    mnemonics: ['"MethoTRIMEPRAZINE = the palliative TRIPLE" — Tranquillizes, Treats pain, and Tames nausea.'],
    confusables: ['Methotrimeprazine (levomepromazine, phenothiazine) vs methotrexate — sound-alike, entirely different drugs.'],
    classDifferentiators: 'Low-potency phenothiazine unique for combined sedative + analgesic + antiemetic use in palliative care; heavy orthostasis/sedation, mild EPS.',
    examHooks: ['Which Canadian low-potency phenothiazine is prized in palliative care for combined sedation, analgesia and antiemesis? (methotrimeprazine/levomepromazine).'],
    counsellingPoints: ['Expect significant drowsiness.', 'Rise slowly — risk of fainting.', 'Report muscle stiffness or abnormal movements.'],
    vignettes: [
      {
        stem: 'A palliative-care patient has terminal restlessness, intractable nausea and pain. The team selects a low-potency phenothiazine with sedative, antiemetic AND analgesic properties, often given subcutaneously. Which drug is it?',
        options: ['Haloperidol', 'Methotrimeprazine (levomepromazine)', 'Fluphenazine', 'Pimozide'],
        answer: 'Methotrimeprazine (levomepromazine)',
        explanation: 'Methotrimeprazine is a low-potency phenothiazine with marked sedation plus intrinsic analgesic and antiemetic activity, making it a palliative-care staple (frequently SC). High-potency agents (haloperidol, fluphenazine, pimozide) lack this analgesic profile and cause more EPS.',
        testedFact: 'Methotrimeprazine in palliative care (sedation/analgesia/antiemesis)',
        source: { name: 'Methotrimeprazine (Nozinan) product monograph — Health Canada', origin: 'monograph' },
      },
    ],
    _prov: FGA_PROV,
  },

  trifluoperazine: {
    pronunciation: 'trye-floo-oh-PER-a-zeen',
    moa: 'High-potency piperazine phenothiazine; potent D2 receptor antagonist.',
    receptorProfile: 'High D2 affinity; low H1/M1 (little sedation/anticholinergic) — EPS-predominant like other high-potency agents.',
    onsetOfEffect: 'Antipsychotic effect over days–weeks.',
    halfLife: '~10–20 h.',
    metabolism: 'Hepatic; phenothiazine oxidation/glucuronidation.',
    startingDose: '2–5 mg PO BID.',
    titration: 'Increase to response; usual 15–20 mg/day.',
    maxDose: 'Up to ~40 mg/day.',
    frequencyTiming: 'BID dosing.',
    administrationNotes: 'A high-potency piperazine phenothiazine; historically also used short-term for severe anxiety at low dose (now uncommon).',
    commonSE: ['EPS (akathisia, dystonia, parkinsonism)', 'Restlessness/insomnia', 'Hyperprolactinemia', 'Mild orthostasis', 'Dry mouth (mild)'],
    seriousAE: ['Neuroleptic malignant syndrome', 'Tardive dyskinesia', 'QT prolongation', 'Severe EPS', 'Increased mortality in elderly patients with dementia-related psychosis'],
    syndromes: ['Extrapyramidal symptoms', 'Tardive dyskinesia', 'Neuroleptic malignant syndrome', 'QT prolongation', 'Hyperprolactinemia'],
    overdoseLethality: 'EPS, sedation, hypotension, QT prolongation; supportive care.',
    ongoingMonitoring: 'AIMS for TD; EPS/akathisia; prolactin if symptomatic.',
    majorDDI: ['Other QT-prolonging drugs', 'CNS depressants', 'Anticholinergics (additive)'],
    contraindicatedCombos: ['Other markedly QT-prolonging agents', 'Severe CNS depression'],
    pregnancy: 'Neonatal EPS/withdrawal with late exposure; weigh maternal illness.',
    lactation: 'Excreted in milk; monitor infant.',
    geriatric: 'Increased mortality in dementia; EPS-prone; caution.',
    cardiac: 'QT prolongation possible.',
    pearls: [
      'High-potency piperazine phenothiazine: EPS-heavy, low sedation/anticholinergic — profile resembles haloperidol/fluphenazine.',
      'Contrast with chlorpromazine (same phenothiazine family, but low-potency and sedating): potency, not chemistry, predicts the side-effect pattern.',
      'Older low-dose use for severe anxiety is now uncommon.',
    ],
    mnemonics: ['"triFLUOPERazine = high-potency phenothiazine" — the piperazine phenothiazines (tri-, fluphen-, perphen-) trend higher potency/more EPS.'],
    confusables: ['Trifluoperazine (high-potency, EPS) vs chlorpromazine (low-potency, sedating) — same phenothiazine class, opposite side-effect profiles.'],
    classDifferentiators: 'High-potency phenothiazine; EPS-predominant, minimal sedation — the "phenothiazine that behaves like haloperidol."',
    examHooks: ['Two phenothiazines: one sedating/hypotensive, one EPS-heavy. Which is high-potency? (trifluoperazine vs chlorpromazine → trifluoperazine).'],
    counsellingPoints: ['Report tremor, stiffness, restlessness, or abnormal movements.', 'Effect builds over weeks.', 'Do not stop abruptly.'],
    vignettes: [
      {
        stem: 'Two phenothiazines are compared: chlorpromazine and trifluoperazine. Which statement about trifluoperazine is correct?',
        options: ['It is low-potency and highly sedating', 'It is high-potency with more EPS and less sedation than chlorpromazine', 'It causes more orthostatic hypotension than chlorpromazine', 'It has strong anticholinergic effects'],
        answer: 'It is high-potency with more EPS and less sedation than chlorpromazine',
        explanation: 'Trifluoperazine is a high-potency piperazine phenothiazine: more EPS/hyperprolactinemia but less sedation, orthostasis and anticholinergic effect than the low-potency chlorpromazine. Potency (D2 affinity), not the shared phenothiazine chemistry, drives the side-effect pattern.',
        testedFact: 'High- vs low-potency phenothiazine side-effect trade-off',
        source: { name: 'openFDA/DailyMed trifluoperazine label; CANMAT/CPA schizophrenia', origin: 'openfda' },
      },
    ],
    _prov: FGA_PROV,
  },

  prochlorperazine: {
    pronunciation: 'proe-klor-PER-a-zeen',
    moa: 'Piperazine phenothiazine used mainly as an ANTIEMETIC/anti-vertigo agent; D2 antagonism (chemoreceptor trigger zone) more than antipsychotic use.',
    receptorProfile: 'D2 antagonist (CTZ + vestibular pathways); some H1/M1 — but the clinical role is antiemesis, not psychosis.',
    onsetOfEffect: 'Antiemetic effect within ~30–60 min (oral/IM); faster IV.',
    halfLife: '~6–8 h.',
    metabolism: 'Hepatic (CYP2D6 and others).',
    startingDose: 'Nausea/vomiting: 5–10 mg PO TID–QID or IM; vertigo similar.',
    titration: 'Use short-term at the lowest effective antiemetic dose.',
    maxDose: 'Antiemetic use typically ≤40 mg/day; higher antipsychotic dosing is largely historical.',
    frequencyTiming: 'PO/IM/PR (suppository); IV in some settings (dystonia/hypotension risk).',
    administrationNotes: 'Primarily an antiemetic/anti-vertigo drug (Stemetil). Acute dystonic reactions — even after a single antiemetic dose — are a classic hazard, especially in young women.',
    commonSE: ['Sedation (mild)', 'Akathisia/restlessness', 'Acute dystonia (notable)', 'Orthostasis', 'Dry mouth'],
    seriousAE: ['Acute dystonic reaction', 'Neuroleptic malignant syndrome', 'Tardive dyskinesia (with prolonged use)', 'QT prolongation', 'Increased mortality in elderly patients with dementia-related psychosis'],
    syndromes: ['Acute dystonia', 'Extrapyramidal symptoms', 'Tardive dyskinesia', 'Neuroleptic malignant syndrome', 'QT prolongation'],
    overdoseLethality: 'EPS/dystonia, sedation, hypotension, QT prolongation; supportive care with anticholinergic for dystonia.',
    ongoingMonitoring: 'Watch for acute dystonia after dosing; AIMS if prolonged use.',
    majorDDI: ['Other QT-prolonging drugs', 'CNS depressants', 'Other dopamine antagonists (additive EPS)'],
    contraindicatedCombos: ['Other markedly QT-prolonging agents', 'Severe CNS depression'],
    pregnancy: 'Sometimes used for hyperemesis; weigh benefit/risk; late exposure → neonatal EPS.',
    lactation: 'Excreted in milk; monitor infant.',
    geriatric: 'EPS and orthostasis; increased mortality in dementia; short-term antiemetic use only.',
    cardiac: 'QT prolongation possible.',
    pearls: [
      'Used mainly as an ANTIEMETIC / anti-vertigo agent (not primarily for psychosis) — but it is still a dopamine-blocking phenothiazine.',
      'Acute dystonia can occur even after a single antiemetic dose, classically in young women — treat with an anticholinergic (benztropine) or diphenhydramine.',
      'A good reminder that "antiemetic" dopamine blockers (also metoclopramide) carry EPS/TD risk.',
    ],
    mnemonics: ['"proCHLORPERazine → puke + spinning" (nausea/vertigo), but it can lock the neck (dystonia).'],
    confusables: ['Prochlorperazine (antiemetic phenothiazine) vs chlorpromazine (antipsychotic) vs perphenazine — easily confused "-perazine/-promazine" names.'],
    classDifferentiators: 'Phenothiazine whose main clinical use is antiemesis/vertigo; the exam angle is acute dystonia from a "just an antiemetic" dose.',
    examHooks: ['A young woman gets neck spasm and eye rolling after IV prochlorperazine for nausea — cause and treatment? (acute dystonia → benztropine/diphenhydramine).'],
    counsellingPoints: ['Seek care for sudden muscle spasms of the neck/eyes/tongue.', 'Use short-term for nausea/vertigo.', 'May cause drowsiness and dizziness.'],
    vignettes: [
      {
        stem: 'A 19-year-old woman given IV prochlorperazine for migraine-associated nausea develops involuntary neck twisting and an upward eye deviation 30 minutes later. What is the best immediate treatment?',
        options: ['IV diphenhydramine (or benztropine)', 'IV lorazepam only', 'IV dantrolene', 'Stop all fluids and observe'],
        answer: 'IV diphenhydramine (or benztropine)',
        explanation: 'This is an acute dystonic reaction — a well-known EPS from dopamine-blocking antiemetics like prochlorperazine, most common in young patients (especially women). Treatment is an anticholinergic (benztropine) or diphenhydramine; dantrolene is for NMS.',
        testedFact: 'Acute dystonia from antiemetic prochlorperazine',
        source: { name: 'openFDA/DailyMed prochlorperazine label — EPS/dystonia', origin: 'openfda' },
      },
    ],
    _prov: FGA_PROV,
  },

  pipotiazine: {
    pronunciation: 'pip-oh-TYE-a-zeen',
    moa: 'Piperidine phenothiazine (Canada-specific; a.k.a. pipotiazine palmitate); D2 receptor antagonist available as a long-acting injectable.',
    receptorProfile: 'Moderate–high D2 affinity with some H1/α1 blockade; used essentially only as a maintenance depot.',
    onsetOfEffect: 'Maintenance antipsychotic effect over weeks; depot pharmacokinetics.',
    halfLife: 'Palmitate depot: sustained release over ~3–4 weeks.',
    metabolism: 'Hepatic.',
    startingDose: 'Palmitate LAI: individualized (e.g., ~25–50 mg IM test dose), titrated per response.',
    titration: 'Adjust dose/interval to response and tolerability.',
    maxDose: 'Per monograph (commonly up to ~200 mg per injection interval).',
    frequencyTiming: 'Deep IM palmitate depot approximately every 4 weeks.',
    administrationNotes: 'Canada-specific palmitate long-acting injectable (Piportil L4) for maintenance of schizophrenia; the palmitate ester gives roughly monthly dosing. Establish tolerability (ideally with an oral phenothiazine) before committing to depot.',
    commonSE: ['EPS (akathisia, dystonia, parkinsonism)', 'Sedation', 'Hyperprolactinemia', 'Orthostasis', 'Injection-site reactions'],
    seriousAE: ['Neuroleptic malignant syndrome', 'Tardive dyskinesia', 'QT prolongation', 'Severe EPS', 'Increased mortality in elderly patients with dementia-related psychosis'],
    syndromes: ['Extrapyramidal symptoms', 'Tardive dyskinesia', 'Neuroleptic malignant syndrome', 'QT prolongation', 'Hyperprolactinemia'],
    overdoseLethality: 'EPS, sedation, hypotension, QT prolongation; prolonged depot action complicates management.',
    ongoingMonitoring: 'AIMS for TD; EPS; adherence to injection schedule; BP.',
    majorDDI: ['Other QT-prolonging drugs', 'CNS depressants', 'Anticholinergics (additive)'],
    contraindicatedCombos: ['Other markedly QT-prolonging agents', 'Severe CNS depression'],
    pregnancy: 'Neonatal EPS/withdrawal with late exposure; weigh maternal illness.',
    lactation: 'Excreted in milk; monitor infant.',
    geriatric: 'Increased mortality in dementia; EPS/orthostasis; the fixed depot is hard to reverse — caution.',
    pearls: [
      'Canada-specific PALMITATE long-acting injectable (Piportil L4) — roughly MONTHLY (q4-week) IM maintenance dosing.',
      'Distinguish the depot esters: decanoates (haloperidol, fluphenazine, zuclopenthixol, flupenthixol) vs pipotiazine PALMITATE.',
      'Used essentially only as a maintenance depot — establish tolerability first, since depot effects can\'t be quickly withdrawn.',
    ],
    mnemonics: ['"PIPOtiazine PALMitate = a PALMful once a month" — the ~q4-week Canadian phenothiazine depot.'],
    confusables: ['Pipotiazine PALMITATE vs the DECANOATE depots (haloperidol/fluphenazine/thioxanthenes) — different ester, similar monthly-ish depot concept.'],
    classDifferentiators: 'Canadian phenothiazine notable specifically as a palmitate-ester LAI dosed about every 4 weeks.',
    examHooks: ['Which Canadian FGA depot uses a PALMITATE ester (vs the more common decanoate)? (pipotiazine).'],
    counsellingPoints: ['Attend scheduled monthly injections.', 'Report stiffness, restlessness, or abnormal movements.', 'Depot levels persist for weeks after each dose.'],
    vignettes: [
      {
        stem: 'A stable patient with schizophrenia and poor oral adherence is switched to a Canadian long-acting injectable dosed about every four weeks that uses a palmitate ester. Which agent is this?',
        options: ['Haloperidol decanoate', 'Fluphenazine decanoate', 'Pipotiazine palmitate', 'Zuclopenthixol acetate'],
        answer: 'Pipotiazine palmitate',
        explanation: 'Pipotiazine palmitate (Piportil L4) is a Canada-specific phenothiazine LAI given roughly every 4 weeks; uniquely among the FGA depots here it uses a palmitate ester rather than a decanoate. Zuclopenthixol acetate is short-acting (acute phase), not maintenance.',
        testedFact: 'Pipotiazine palmitate LAI (ester + interval)',
        source: { name: 'Pipotiazine palmitate (Piportil L4) product monograph — Health Canada', origin: 'monograph' },
      },
    ],
    _prov: FGA_PROV,
  },

  droperidol: {
    pronunciation: 'droe-PER-i-dol',
    moa: 'Butyrophenone (haloperidol\'s short-acting cousin); potent D2 receptor antagonist used for agitation and as an antiemetic (PONV).',
    receptorProfile: 'High D2 affinity; some α1 blockade (hypotension); the defining safety issue is dose-dependent QT prolongation.',
    onsetOfEffect: 'Rapid — sedation/antiemesis within minutes (IM/IV).',
    halfLife: 'Short — ~2 h.',
    metabolism: 'Hepatic — CYP3A4.',
    startingDose: 'Agitation: 2.5–5 mg IM/IV; antiemetic (PONV): 0.625–1.25 mg IV.',
    titration: 'Additional small doses to effect; use lowest effective dose given QT risk.',
    maxDose: 'Use the minimum effective dose; higher doses amplify QT risk.',
    frequencyTiming: 'IM/IV in monitored settings; ECG recommended around use.',
    administrationNotes: 'Fast-acting for acute agitation and PONV, but carries a prominent QT-prolongation/torsades warning — assess QT risk and monitor ECG; correct K/Mg first.',
    commonSE: ['Sedation', 'Hypotension', 'Akathisia/restlessness', 'Acute dystonia', 'Dizziness'],
    seriousAE: ['QT prolongation / torsades de pointes (including at low antiemetic doses)', 'Neuroleptic malignant syndrome', 'Acute dystonia', 'Tardive dyskinesia (rare, short-term use)', 'Increased mortality in elderly patients with dementia-related psychosis'],
    syndromes: ['QT prolongation', 'Extrapyramidal symptoms (dystonia/akathisia)', 'Neuroleptic malignant syndrome', 'Hyperprolactinemia'],
    overdoseLethality: 'Main danger is QT prolongation/torsades and hypotension/sedation; continuous ECG monitoring.',
    baselineWorkup: ['ECG (QTc) before/around use where feasible', 'Electrolytes (K/Mg)'],
    ongoingMonitoring: 'ECG/telemetry after dosing where indicated; BP; watch for dystonia/akathisia.',
    majorDDI: ['Other QT-prolonging drugs (additive torsades risk)', 'CYP3A4 inhibitors (raise levels)', 'CNS depressants (additive sedation/hypotension)'],
    contraindicatedCombos: ['Known QT prolongation / other markedly QT-prolonging agents', 'Uncorrected hypokalemia/hypomagnesemia'],
    pregnancy: 'Limited data; weigh benefit/risk; used short-term for PONV.',
    lactation: 'Limited data; caution with sedation.',
    geriatric: 'Increased mortality in dementia; QT and hypotension; caution.',
    cardiac: 'Dose-dependent QT prolongation with torsades — the defining caution, even at antiemetic doses; ECG and electrolyte correction.',
    pearls: [
      'Haloperidol\'s short-acting butyrophenone cousin — fast onset for acute agitation and a potent antiemetic (PONV).',
      'Carries a prominent QT-prolongation/torsades warning (even at low antiemetic doses) — assess QT risk, correct K/Mg, monitor ECG.',
      'Short half-life (~2 h) makes it useful for rapid, titratable control.',
    ],
    mnemonics: ['"DROPeridol can DROP the heart into torsades" — QT is the headline risk.'],
    confusables: ['Droperidol vs haloperidol — same butyrophenone family; droperidol is the short-acting agitation/antiemetic agent with the QT warning.'],
    classDifferentiators: 'Short-acting butyrophenone for acute agitation/antiemesis; QT prolongation is the dominant safety concern.',
    examHooks: ['Which butyrophenone antiemetic/agitation agent carries a torsades warning even at low doses and prompts ECG monitoring? (droperidol).'],
    counsellingPoints: ['Report palpitations or fainting.', 'ECG monitoring may be used around your dose.', 'May cause drowsiness and dizziness.'],
    vignettes: [
      {
        stem: 'Before giving droperidol to an agitated patient, which intervention most reduces the risk of its most feared adverse effect?',
        options: ['Pre-treat with an antihistamine', 'Check and correct serum potassium and magnesium and review the QT interval', 'Give with food', 'Add a benzodiazepine to prevent EPS'],
        answer: 'Check and correct serum potassium and magnesium and review the QT interval',
        explanation: 'Droperidol\'s signature risk is dose-dependent QT prolongation/torsades. Correcting hypokalemia/hypomagnesemia, reviewing baseline QT, and avoiding other QT-prolonging drugs mitigate this; ECG monitoring is advised.',
        testedFact: 'Droperidol QT prolongation risk mitigation',
        source: { name: 'openFDA/DailyMed droperidol label — QT/warnings', origin: 'openfda' },
      },
    ],
    _prov: FGA_PROV,
  },
};
