// authored/hypnotic_anxio.js — authored overlay for non-benzodiazepine anxiolytics/hypnotics.
//
// Mechanism/PK/dosing summaries + the pedagogical layer, grounded in established
// pharmacology and the fetched openFDA/monograph label sections. `_prov` declares which
// safety-critical fields the label text grounds; build.js attaches that source text and,
// where a field cannot be grounded, downgrades it to origin 'authored' + verifyFlag.
//
// CLASS THEME — "alternatives to benzodiazepines":
//   • Z-drugs (zopiclone, zolpidem) act at the SAME benzodiazepine site on GABA-A →
//     they still cause complex sleep behaviours, next-day impairment, and DEPENDENCE.
//   • Buspirone (5-HT1A), the orexin antagonists/DORAs (lemborexant, daridorexant),
//     the melatonergics (melatonin, ramelteon), and hydroxyzine (H1) are the
//     NON-dependence-forming alternatives — no GABA/benzo-site activity.
//   • Barbiturates (phenobarbital) are the dangerous OUTLIER: they prolong the DURATION
//     of Cl- channel opening (vs benzo FREQUENCY), have NO ceiling effect, are potent CYP
//     inducers, cause respiratory depression, and are LETHAL in overdose — the sharp
//     contrast to the relatively overdose-safe benzodiazepines.

const HYP_PROV = {
  startingDose: 'openfda', maxDose: 'openfda', seriousAE: 'openfda', syndromes: 'openfda',
  majorDDI: 'openfda', contraindicatedCombos: 'openfda', pregnancy: 'openfda',
  overdoseLethality: 'openfda',
};

export default {
  zopiclone: {
    pronunciation: 'ZOH-pih-klone',
    moa: 'Non-benzodiazepine cyclopyrrolone (Z-drug). Positive allosteric modulator at the benzodiazepine binding site of the GABA-A receptor → enhances GABA-mediated Cl- influx (increases channel-opening FREQUENCY, like benzodiazepines).',
    receptorProfile: 'Acts at the GABA-A benzodiazepine (omega) site; broader subunit action than zolpidem, so it retains some anxiolytic/myorelaxant effect. Reversible with flumazenil.',
    onsetOfEffect: 'Rapid — sleep onset within ~30 minutes.',
    halfLife: '~5 hours (short; prolonged to ~7–9 h in the elderly/hepatic impairment).',
    timeToSteadyState: '~1–2 days.',
    metabolism: 'Hepatic CYP3A4 (major) and CYP2C8; inactive/weakly active metabolites renally excreted.',
    foodEffect: 'A heavy meal can delay onset — take on an empty stomach at bedtime.',
    approvedCanada: ['Short-term treatment of insomnia'],
    offLabel: [],
    approvedPopulations: 'Adults; short-term use (generally ≤7–14 days).',
    startingDose: '5 mg PO at bedtime (3.75 mg in the elderly/debilitated/hepatic impairment).',
    titration: 'Use the lowest effective dose for the shortest time; reassess need beyond 7–14 days.',
    maxDose: '7.5 mg/day (5 mg/day in the elderly, debilitated, or hepatic impairment).',
    frequencyTiming: 'Once at bedtime, only when a full night (7–8 h) of sleep is possible.',
    renalHepaticAdjustment: 'Reduce dose in hepatic impairment; caution in renal impairment.',
    startStopCrossTaper: 'Taper if used regularly beyond a few weeks to limit rebound insomnia/withdrawal.',
    administrationNotes: 'Intended for short-term/intermittent use; the Canadian Z-drug standard (eszopiclone, its US S-enantiomer, is not the Canadian product).',
    commonSE: ['Metallic/bitter taste (signature)', 'Dry mouth', 'Drowsiness/next-day sedation', 'Headache', 'Dizziness'],
    seriousAE: ['Complex sleep behaviours (sleep-driving, sleep-eating, sleep-walking)', 'Next-day psychomotor/driving impairment', 'Anterograde amnesia', 'Tolerance and dependence', 'Respiratory depression with other CNS depressants', 'Paradoxical agitation'],
    syndromes: ['Complex sleep behaviours', 'Sedative-hypnotic dependence/withdrawal', 'Next-day impairment', 'Rebound insomnia'],
    overdoseLethality: 'Low when taken alone; danger is additive CNS/respiratory depression with alcohol, opioids or benzodiazepines. Flumazenil reverses (Z-drugs bind the benzodiazepine site).',
    discontinuationSyndrome: 'Rebound insomnia and, after prolonged use, a benzodiazepine-like withdrawal (anxiety, tremor, rarely seizures) — taper.',
    ongoingMonitoring: 'Reassess ongoing need; screen for dependence, next-day sedation, and complex sleep behaviours.',
    majorDDI: ['CNS depressants (alcohol, opioids, benzodiazepines) — additive sedation/respiratory depression', 'Strong CYP3A4 inhibitors (clarithromycin, ketoconazole, ritonavir) raise levels', 'CYP3A4 inducers (rifampin, carbamazepine) lower levels'],
    contraindicatedCombos: ['Concomitant opioids without close monitoring (respiratory depression)'],
    pregnancy: 'Limited data; avoid where possible, especially late pregnancy (neonatal sedation/withdrawal). Weigh against untreated insomnia.',
    lactation: 'Excreted in breast milk — generally avoid or monitor the infant for sedation.',
    geriatric: 'Use the reduced dose; falls, confusion, and next-day sedation are the key risks.',
    pearls: [
      'The metallic/bitter after-taste is the classic, near-pathognomonic clue that a Z-drug is zopiclone.',
      'Acts at the SAME GABA-A benzodiazepine site as benzodiazepines — so it still causes complex sleep behaviours, dependence, and is reversible with flumazenil (it is NOT a "non-addictive" sleep aid).',
      'The Canadian Z-drug standard for insomnia; intended for short-term use only.',
    ],
    mnemonics: ['"ZOPICLONE = Z-drug with the metallic taste in your mouth."'],
    confusables: ['Zopiclone vs zolpidem — both Z-drugs at the benzo site, but zopiclone = metallic taste + broader action; zolpidem = α1-selective, sex-specific dosing.'],
    classDifferentiators: 'Cyclopyrrolone Z-drug; broader GABA-A action than zolpidem (retains mild anxiolysis); signature metallic taste; still dependence-forming and benzo-site active.',
    examHooks: ['Which hypnotic characteristically leaves a metallic/bitter taste? (zopiclone)', 'Are Z-drugs reversible with flumazenil? (yes — they bind the benzodiazepine site)'],
    counsellingPoints: ['Take only when you can sleep a full 7–8 hours.', 'You may notice a bitter/metallic taste.', 'Do not combine with alcohol.', 'Rare sleep-driving/eating without memory — stop and report it.'],
    vignettes: [
      {
        stem: 'A 40-year-old on a Z-drug for insomnia complains of a persistent metallic, bitter taste each morning and asks if the pill is "toxic." Which agent is he most likely taking?',
        options: ['Zolpidem', 'Zopiclone', 'Melatonin', 'Buspirone'],
        answer: 'Zopiclone',
        explanation: 'A metallic/bitter dysgeusia is the signature adverse effect of zopiclone and distinguishes it from zolpidem and the non-GABAergic agents.',
        testedFact: 'Zopiclone metallic taste',
        source: { name: 'openFDA/monograph zopiclone label — adverse effects', origin: 'monograph' },
      },
    ],
    _prov: HYP_PROV,
  },

  zolpidem: {
    pronunciation: 'zole-PIH-dem',
    moa: 'Non-benzodiazepine imidazopyridine (Z-drug). Positive allosteric modulator at the GABA-A benzodiazepine site, PREFERENTIALLY the α1 (omega-1/BZ1) subunit → predominantly sedative-hypnotic with little anxiolytic, myorelaxant, or anticonvulsant effect.',
    receptorProfile: 'α1-selective GABA-A benzodiazepine-site modulation; reversible with flumazenil.',
    onsetOfEffect: 'Rapid — sleep onset ~30 minutes (sublingual/Sublinox faster).',
    halfLife: '~2.5–3 hours (very short).',
    timeToSteadyState: '~1 day.',
    metabolism: 'Hepatic CYP3A4 (major), with CYP2C9/1A2 contributions; inactive metabolites.',
    foodEffect: 'Food delays absorption/onset — take on an empty stomach at bedtime.',
    approvedCanada: ['Short-term treatment of insomnia (Sublinox — sublingual)'],
    offLabel: [],
    approvedPopulations: 'Adults; short-term use.',
    startingDose: '5 mg SL at bedtime (women and the elderly start at 5 mg; men may use 5–10 mg).',
    titration: 'Use the lowest effective dose; reassess need.',
    maxDose: '10 mg/day.',
    frequencyTiming: 'Once at bedtime immediately before lying down, only with ≥7–8 h available for sleep.',
    renalHepaticAdjustment: 'Reduce in hepatic impairment.',
    startStopCrossTaper: 'Taper if used regularly; expect rebound insomnia after stopping.',
    administrationNotes: 'Lower doses in women because slower clearance produces higher next-morning levels and greater impairment.',
    commonSE: ['Drowsiness/next-day somnolence', 'Dizziness', 'Headache', 'Diarrhea', 'Dry mouth'],
    seriousAE: ['Complex sleep behaviours (sleep-driving, sleep-eating) — boxed/serious warning class effect', 'Anterograde amnesia', 'Next-day psychomotor/driving impairment', 'Dependence/tolerance', 'Respiratory depression with CNS depressants'],
    syndromes: ['Complex sleep behaviours', 'Sedative-hypnotic dependence/withdrawal', 'Next-day impairment', 'Rebound insomnia'],
    overdoseLethality: 'Low alone; risk is additive respiratory depression with alcohol/opioids/other CNS depressants. Flumazenil reverses.',
    discontinuationSyndrome: 'Rebound insomnia; benzodiazepine-like withdrawal after prolonged/high use — taper.',
    ongoingMonitoring: 'Reassess need; screen for next-day sedation, complex sleep behaviours, and dependence.',
    majorDDI: ['CNS depressants (alcohol, opioids, benzodiazepines) — additive', 'Strong CYP3A4 inhibitors (ketoconazole, ritonavir) raise levels', 'CYP3A4 inducers (rifampin) lower levels'],
    contraindicatedCombos: ['Concomitant opioids without close monitoring (respiratory depression)'],
    pregnancy: 'Limited data; avoid where possible, especially near term (neonatal sedation).',
    lactation: 'Small amounts in breast milk; monitor the infant for sedation.',
    geriatric: 'Use 5 mg; falls, confusion, and next-day sedation are the main risks.',
    pearls: [
      'Sex-specific dosing: women and the elderly get the LOWER dose because of slower clearance and higher next-morning drug levels.',
      'Most α1-selective of the Z-drugs → mostly hypnotic, minimal anxiolytic/muscle-relaxant effect.',
      'Complex sleep behaviours (sleep-driving, sleep-eating) are a boxed/serious warning class effect of the Z-drugs — the Canadian product is Sublinox (sublingual).',
    ],
    mnemonics: ['"ZolpiDEM → DEMoiselle dose" — women get the lower dose (5 mg).'],
    confusables: ['Zolpidem vs zopiclone — both Z-drugs at the benzo site; zolpidem = α1-selective + sex-specific dosing, zopiclone = metallic taste + broader action.'],
    classDifferentiators: 'Imidazopyridine Z-drug; most α1-selective (purely hypnotic); very short half-life; sex-specific dosing; complex sleep behaviours warning.',
    examHooks: ['Which hypnotic has sex-specific dosing (lower in women)? (zolpidem)', 'Which receptor subunit does zolpidem prefer? (GABA-A α1)'],
    counsellingPoints: ['Take right before bed with a full night ahead.', 'Do not combine with alcohol.', 'Rare sleep-driving/eating without memory — stop the drug and report it.'],
    vignettes: [
      {
        stem: 'A woman and a man of the same age and weight are both prescribed zolpidem for insomnia. Why is the recommended starting dose lower for the woman?',
        options: ['Higher renal clearance in women', 'Slower zolpidem clearance in women raises next-morning levels and impairment', 'Women metabolize it faster via CYP2D6', 'Women have a larger volume of distribution'],
        answer: 'Slower zolpidem clearance in women raises next-morning levels and impairment',
        explanation: 'Women clear zolpidem more slowly, producing higher morning blood levels and greater next-day psychomotor/driving impairment, so guidance recommends a lower dose in women.',
        testedFact: 'Zolpidem sex-specific dosing',
        source: { name: 'openFDA/DailyMed zolpidem label — dosage & warnings', origin: 'openfda' },
      },
    ],
    _prov: HYP_PROV,
  },

  buspirone: {
    pronunciation: 'byoo-SPY-rone',
    moa: '5-HT1A receptor PARTIAL agonist (presynaptic autoreceptor agonist / postsynaptic partial agonist); modest dopamine D2 activity. Anxiolysis WITHOUT any GABA-A/benzodiazepine activity.',
    receptorProfile: '5-HT1A partial agonist; some D2 affinity. No GABAergic, sedating, muscle-relaxant, or anticonvulsant effect.',
    onsetOfEffect: 'DELAYED — anxiolytic effect builds over 1–2 weeks, full effect ~4 weeks. NOT effective PRN / for acute anxiety.',
    halfLife: '~2–3 hours (short → dosed BID–TID).',
    timeToSteadyState: '~1–2 days (but clinical effect lags by weeks).',
    metabolism: 'Hepatic CYP3A4; active metabolite 1-PP (weak). Extensive first-pass metabolism.',
    activeMetabolites: '1-pyrimidinylpiperazine (1-PP) — weakly active.',
    foodEffect: 'Food increases bioavailability (slows first-pass) — take consistently with respect to food.',
    approvedCanada: ['Generalized anxiety disorder'],
    offLabel: ['Adjunct/augmentation of antidepressants', 'SSRI-induced sexual dysfunction'],
    approvedPopulations: 'Adults.',
    startingDose: '7.5 mg PO BID.',
    titration: 'Increase by 5 mg/day every 2–3 days as tolerated; usual 20–30 mg/day divided.',
    maxDose: '60 mg/day in divided doses.',
    frequencyTiming: 'BID–TID, consistently with or without food.',
    startStopCrossTaper: 'No taper needed (no dependence); it cannot cover benzodiazepine withdrawal (no cross-tolerance).',
    administrationNotes: 'Set expectations: it is a scheduled daily medication, not a "when anxious" pill, and takes ~2 weeks to work.',
    commonSE: ['Dizziness', 'Nausea', 'Headache', 'Lightheadedness', 'Nervousness'],
    seriousAE: ['Serotonin syndrome (with other serotonergics/MAOIs)', 'Rare restlessness/akathisia-like symptoms'],
    syndromes: ['Serotonin syndrome (in combination)'],
    overdoseLethality: 'Low — wide therapeutic margin; generally benign in isolated overdose.',
    discontinuationSyndrome: 'None expected — no physiologic dependence or withdrawal.',
    ongoingMonitoring: 'Assess anxiety response at 2–4 weeks; reinforce daily (non-PRN) use.',
    majorDDI: ['MAOIs (contraindicated — hypertension/serotonin syndrome)', 'Strong CYP3A4 inhibitors (grapefruit juice, ketoconazole, erythromycin, ritonavir) raise levels — reduce dose', 'CYP3A4 inducers (rifampin, carbamazepine) lower levels', 'Other serotonergics (serotonin syndrome)'],
    contraindicatedCombos: ['MAOIs (within 14 days)'],
    maoiWashout: '14 days between buspirone and an MAOI.',
    pregnancy: 'Limited human data; generally considered relatively low-risk but reserve for when benefits outweigh unknowns.',
    lactation: 'Limited data; use with caution.',
    geriatric: 'Well tolerated (non-sedating, no falls-from-sedation risk); watch dizziness.',
    pearls: [
      'No dependence, no abuse potential, non-sedating, minimal sexual dysfunction — the anxiolytic of choice for GAD in patients with a substance-use history.',
      'Takes ~2 weeks to work and must be taken daily — useless PRN, and it will NOT relieve or cover benzodiazepine withdrawal (no cross-tolerance).',
      'Grapefruit juice (CYP3A4) markedly raises buspirone levels.',
    ],
    mnemonics: ['"You wait for the BUS(pirone)" — takes ~2 weeks, no immediate relief, no dependence.'],
    confusables: ['Buspirone vs bupropion — sound-alike but unrelated: BUSpirone = 5-HT1A anxiolytic (GAD); buPROPion = NDRI antidepressant/smoking-cessation agent that LOWERS the seizure threshold.'],
    classDifferentiators: 'The only 5-HT1A partial-agonist anxiolytic; non-GABAergic, non-sedating, non-dependence-forming, delayed onset, strictly scheduled (not PRN).',
    examHooks: ['Anxiolytic with no dependence and no cross-tolerance with benzos, that takes ~2 weeks? (buspirone)', 'Which anxiolytic is ineffective PRN? (buspirone)'],
    counsellingPoints: ['Take every day — it is not an as-needed pill.', 'Expect ~2 weeks before you feel benefit.', 'Avoid grapefruit juice.', 'It will not relieve benzodiazepine withdrawal.'],
    vignettes: [
      {
        stem: 'A 34-year-old with GAD and a history of alcohol use disorder needs an anxiolytic without abuse potential. He is started on buspirone but returns in 3 days frustrated it "does nothing" when he takes it during panic. What is the best explanation?',
        options: ['The dose is subtherapeutic and should be doubled today', 'Buspirone has a delayed onset (~2 weeks) and is not effective taken PRN', 'He has developed tolerance already', 'Buspirone requires benzodiazepine co-administration to work'],
        answer: 'Buspirone has a delayed onset (~2 weeks) and is not effective taken PRN',
        explanation: 'Buspirone is a 5-HT1A partial agonist with anxiolysis that develops over ~1–2 weeks of daily dosing; it provides no acute relief and is not used PRN. Its lack of dependence makes it well suited to patients with substance-use histories.',
        testedFact: 'Buspirone delayed onset / non-PRN',
        source: { name: 'CANMAT/CPA anxiety guidelines; buspirone monograph', origin: 'canmat' },
      },
    ],
    _prov: HYP_PROV,
  },

  hydroxyzine: {
    pronunciation: 'hy-DROX-uh-zeen',
    moa: 'First-generation (piperazine) H1-antihistamine. Anxiolytic/sedative via central H1 antagonism; also antimuscarinic and some 5-HT2 antagonism. No GABA/benzodiazepine activity.',
    receptorProfile: 'H1 antagonist (central + peripheral), antimuscarinic, mild 5-HT2 antagonism.',
    onsetOfEffect: 'Rapid — anxiolysis/sedation within ~30–60 minutes, so it CAN be used PRN.',
    halfLife: '~20 hours in adults (longer, ~29 h, in the elderly).',
    metabolism: 'Hepatic; the major metabolite cetirizine is itself an active (marketed) antihistamine.',
    activeMetabolites: 'Cetirizine (active).',
    approvedCanada: ['Anxiety/tension', 'Pruritus (antihistaminic)', 'Sedation (pre/post-operative)'],
    offLabel: ['Insomnia', 'Adjunct for nausea'],
    approvedPopulations: 'Adults and children.',
    startingDose: 'Anxiety 25–50 mg PO TID–QID; pruritus 25 mg PO TID–QID.',
    titration: 'Titrate to effect within the daily maximum; often used PRN.',
    maxDose: 'Up to ~100 mg/day for anxiety (use the lowest effective dose; higher risk of anticholinergic/QT effects above this).',
    frequencyTiming: 'TID–QID or PRN; a bedtime dose exploits its sedation.',
    renalHepaticAdjustment: 'Reduce dose/frequency in hepatic or renal impairment.',
    startStopCrossTaper: 'No taper needed — no dependence or withdrawal.',
    administrationNotes: 'A non-dependence-forming PRN option; useful when abuse potential is a concern.',
    commonSE: ['Sedation/drowsiness', 'Dry mouth', 'Anticholinergic effects (constipation, blurred vision, urinary retention)', 'Dizziness'],
    seriousAE: ['QT prolongation / torsades (dose-related)', 'Anticholinergic toxicity (esp. elderly)', 'Seizures at high dose', 'Paradoxical excitation'],
    syndromes: ['QT prolongation', 'Anticholinergic burden'],
    overdoseLethality: 'Low–moderate; anticholinergic toxidrome and QT prolongation in large ingestions.',
    discontinuationSyndrome: 'None — no physiologic dependence.',
    baselineWorkup: ['Consider ECG if cardiac risk factors, electrolyte abnormalities, or other QT-prolonging drugs, especially at higher doses'],
    ongoingMonitoring: 'Watch anticholinergic load and sedation in the elderly; QT if combined with other QT-prolonging agents.',
    majorDDI: ['CNS depressants (alcohol, opioids, benzodiazepines) — additive sedation', 'Other QT-prolonging drugs (additive)', 'Anticholinergics (additive burden)', 'MAOIs (enhanced anticholinergic/CNS effects)'],
    contraindicatedCombos: ['Other QT-prolonging drugs at high dose (additive torsades risk)'],
    pregnancy: 'Avoid in early pregnancy and near term (neonatal effects); use only if clearly needed.',
    lactation: 'Antihistamines pass into milk and may sedate the infant / reduce supply — use with caution.',
    geriatric: 'Anticholinergic and sedating — on Beers-type caution lists; risk of falls, confusion, urinary retention.',
    cardiac: 'Dose-related QT prolongation — caution with QT risk factors or other QT drugs.',
    pearls: [
      'An antihistamine used as a non-dependence-forming anxiolytic — good PRN option when abuse potential is a concern (e.g., substance-use history).',
      'Watch two things at higher doses: anticholinergic burden (esp. elderly) and dose-related QT prolongation.',
      'Its active metabolite, cetirizine, is itself a marketed second-generation antihistamine.',
    ],
    mnemonics: ['"Hydroxyzine — the antiHISTAMINE that calms and itches less; no addiction, but dry + QT."'],
    confusables: ['Hydroxyzine vs hydralazine (antihypertensive) vs hydroxychloroquine — sound-alike, unrelated drugs.'],
    classDifferentiators: 'H1-antihistamine anxiolytic; rapid/PRN and non-dependence-forming (unlike Z-drugs/benzos), but anticholinergic and QT-prolonging (unlike buspirone/melatonergics).',
    examHooks: ['Non-addictive anxiolytic usable PRN with anticholinergic + QT cautions? (hydroxyzine)'],
    counsellingPoints: ['May cause drowsiness — avoid driving until you know your response.', 'Do not combine with alcohol.', 'Dry mouth/constipation are common; report palpitations or fainting.'],
    vignettes: [
      {
        stem: 'A 45-year-old with GAD and active opioid use disorder needs short-term anxiolysis without dependence potential, usable as needed. Which agent best fits?',
        options: ['Lorazepam', 'Hydroxyzine', 'Zopiclone', 'Phenobarbital'],
        answer: 'Hydroxyzine',
        explanation: 'Hydroxyzine is a rapidly acting H1-antihistamine anxiolytic with no abuse/dependence potential, appropriate PRN in patients where controlled sedative-hypnotics are undesirable; watch anticholinergic effects and QT at higher doses.',
        testedFact: 'Hydroxyzine as non-dependence PRN anxiolytic',
        source: { name: 'openFDA/DailyMed hydroxyzine label — indications', origin: 'openfda' },
      },
    ],
    _prov: HYP_PROV,
  },

  lemborexant: {
    pronunciation: 'lem-bor-EX-ant',
    moa: 'Dual Orexin Receptor Antagonist (DORA) — competitively blocks OX1R and OX2R, reducing orexin-A/B wake-promoting signalling → promotes sleep onset AND maintenance. No GABA/benzodiazepine activity.',
    receptorProfile: 'OX1R/OX2R antagonist; no meaningful GABAergic, histaminergic, or monoaminergic action.',
    onsetOfEffect: 'Rapid — reduces sleep latency the same night.',
    halfLife: '~17–19 hours.',
    metabolism: 'Hepatic CYP3A4 (major, some 3A5).',
    approvedCanada: ['Insomnia (sleep onset and/or maintenance)'],
    offLabel: [],
    approvedPopulations: 'Adults.',
    startingDose: '5 mg PO immediately before bedtime.',
    titration: 'May increase to 10 mg based on response/tolerability.',
    maxDose: '10 mg/day.',
    frequencyTiming: 'Once nightly, with ≥7 h remaining in bed; onset delayed if taken with/soon after food.',
    renalHepaticAdjustment: 'Max 5 mg in moderate hepatic impairment; avoid in severe hepatic impairment.',
    startStopCrossTaper: 'No taper required — minimal rebound/withdrawal.',
    administrationNotes: 'Take on an empty stomach for fastest onset.',
    commonSE: ['Somnolence/next-day sleepiness', 'Headache', 'Fatigue', 'Abnormal dreams'],
    seriousAE: ['Next-day driving/psychomotor impairment (dose-related, greater at 10 mg)', 'Sleep paralysis', 'Cataplexy-like hypnagogic muscle weakness', 'Complex sleep behaviours', 'Worsening depression/suicidal ideation'],
    syndromes: ['Next-day impairment', 'Sleep paralysis / hypnagogic phenomena', 'Complex sleep behaviours'],
    overdoseLethality: 'Low; excessive somnolence expected. Much less dangerous than barbiturates; no specific antidote.',
    discontinuationSyndrome: 'Minimal — no significant physiologic dependence or rebound.',
    ongoingMonitoring: 'Assess next-day somnolence (especially at 10 mg) and driving safety; screen for depression.',
    majorDDI: ['Strong/moderate CYP3A4 inhibitors — avoid or reduce dose', 'CYP3A4 inducers reduce efficacy', 'CNS depressants/alcohol — additive somnolence'],
    contraindicatedCombos: [],
    pregnancy: 'Limited data; use only if clearly needed.',
    lactation: 'Limited data; caution.',
    geriatric: 'Next-day somnolence and falls are the main concern; use 5 mg.',
    pearls: [
      'Orexin antagonists (DORAs) are non-dependence-forming and promote both sleep onset and maintenance — a mechanistically distinct alternative to benzo-site Z-drugs.',
      'Next-day somnolence is dose-related and greater at 10 mg — counsel about driving.',
      'CYP3A4-dependent — avoid with strong CYP3A4 inhibitors.',
    ],
    mnemonics: ['"OREXIN keeps you awake → block it (DORA) to sleep."'],
    confusables: ['Lemborexant vs daridorexant — both DORAs; lemborexant has the LONGER half-life (~17–19 h) → more next-day somnolence than daridorexant.'],
    classDifferentiators: 'DORA (orexin antagonist) — longer half-life than daridorexant; non-dependence-forming; sleep onset + maintenance; next-day somnolence at higher dose.',
    examHooks: ['Which sleep drug class blocks orexin receptors? (DORAs — lemborexant, daridorexant)'],
    counsellingPoints: ['Take right before bed with ≥7 h to sleep.', 'Take on an empty stomach for fastest effect.', 'You may feel next-day drowsiness — be cautious driving.', 'Report dream-enactment, sleep paralysis, or brief muscle weakness.'],
    vignettes: [
      {
        stem: 'A 58-year-old with sleep-onset AND maintenance insomnia, and a history of sedative misuse, needs a non-dependence-forming hypnotic. Which mechanism is most appropriate?',
        options: ['GABA-A benzodiazepine-site agonist', 'Dual orexin receptor antagonist', 'Barbiturate', 'H1 antihistamine'],
        answer: 'Dual orexin receptor antagonist',
        explanation: 'DORAs such as lemborexant block wake-promoting orexin signalling, improving both sleep onset and maintenance without the dependence liability of benzo-site agents — favourable when abuse potential is a concern.',
        testedFact: 'DORA mechanism / non-dependence',
        source: { name: 'openFDA/DailyMed lemborexant label — mechanism/indications', origin: 'openfda' },
      },
    ],
    _prov: HYP_PROV,
  },

  daridorexant: {
    pronunciation: 'dah-ree-do-REX-ant',
    moa: 'Dual Orexin Receptor Antagonist (DORA) — blocks OX1R and OX2R, reducing orexin wake drive to promote sleep onset and maintenance. No GABA/benzodiazepine activity.',
    receptorProfile: 'OX1R/OX2R antagonist.',
    onsetOfEffect: 'Rapid — reduces sleep latency the night of dosing.',
    halfLife: '~8 hours (shorter than lemborexant → designed to minimize next-day residual effects).',
    metabolism: 'Hepatic CYP3A4 (major).',
    approvedCanada: ['Insomnia (sleep onset and/or maintenance)'],
    offLabel: [],
    approvedPopulations: 'Adults.',
    startingDose: '25 mg PO ~30 minutes before bedtime.',
    titration: 'May increase to 50 mg based on response/tolerability.',
    maxDose: '50 mg/day.',
    frequencyTiming: 'Once nightly with ≥7 h remaining in bed; onset delayed if taken with food.',
    renalHepaticAdjustment: 'Max 25 mg in moderate hepatic impairment; avoid in severe hepatic impairment.',
    startStopCrossTaper: 'No taper required — minimal rebound/withdrawal.',
    administrationNotes: 'Its shorter half-life is the selling point versus lemborexant for daytime function.',
    commonSE: ['Headache', 'Somnolence/fatigue', 'Dizziness', 'Nausea'],
    seriousAE: ['Next-day impairment (less than longer-acting agents)', 'Sleep paralysis', 'Cataplexy-like hypnagogic muscle weakness', 'Complex sleep behaviours', 'Worsening depression/suicidal ideation'],
    syndromes: ['Sleep paralysis / hypnagogic phenomena', 'Complex sleep behaviours'],
    overdoseLethality: 'Low; excessive somnolence expected; no specific antidote.',
    discontinuationSyndrome: 'Minimal — no significant physiologic dependence or rebound.',
    ongoingMonitoring: 'Assess residual daytime somnolence (less than other hypnotics) and mood.',
    majorDDI: ['Strong/moderate CYP3A4 inhibitors — avoid (raise exposure)', 'CYP3A4 inducers reduce efficacy', 'CNS depressants/alcohol — additive somnolence'],
    contraindicatedCombos: [],
    pregnancy: 'Limited data; use only if clearly needed.',
    lactation: 'Limited data; caution.',
    geriatric: 'Shorter half-life is advantageous; still start 25 mg and watch falls.',
    pearls: [
      'A DORA like lemborexant, but with a SHORTER half-life (~8 h) → engineered for less next-day impairment.',
      'Non-dependence-forming orexin antagonist — a benzo-free option for both sleep onset and maintenance.',
      'CYP3A4-dependent — avoid strong CYP3A4 inhibitors.',
    ],
    mnemonics: ['"DARIdorexant = DAYtime-friendlier DORA (shorter half-life)."'],
    confusables: ['Daridorexant vs lemborexant — same DORA class; daridorexant is the SHORTER-acting one (less next-day carryover).'],
    classDifferentiators: 'DORA with the shortest half-life of the marketed orexin antagonists → least next-day impairment; non-dependence-forming.',
    examHooks: ['Which orexin antagonist has the shortest half-life / least next-day impairment? (daridorexant)'],
    counsellingPoints: ['Take ~30 min before bed with ≥7 h to sleep.', 'Take on an empty stomach for faster onset.', 'Less next-day grogginess than older hypnotics, but still use care driving.', 'Report dream-enactment or brief muscle weakness.'],
    vignettes: [
      {
        stem: 'Two orexin antagonists are compared for a patient who reports next-morning grogginess. Which agent has the shorter half-life and is preferred to minimize next-day residual sedation?',
        options: ['Lemborexant', 'Daridorexant', 'Zopiclone', 'Ramelteon'],
        answer: 'Daridorexant',
        explanation: 'Daridorexant (~8 h half-life) is shorter-acting than lemborexant (~17–19 h) and was developed specifically to reduce next-day impairment while still treating sleep onset and maintenance.',
        testedFact: 'Daridorexant shorter half-life / less next-day impairment',
        source: { name: 'openFDA/DailyMed daridorexant label — clinical pharmacology', origin: 'openfda' },
      },
    ],
    _prov: HYP_PROV,
  },

  melatonin: {
    pronunciation: 'mel-uh-TOH-nin',
    moa: 'Endogenous pineal hormone; agonist at MT1 (attenuates the wake-promoting/alerting signal → sleep onset) and MT2 (circadian phase-shifting) receptors.',
    receptorProfile: 'MT1/MT2 agonist; no GABA/benzodiazepine activity.',
    onsetOfEffect: 'Immediate-release ~30–60 min for a hypnotic effect; circadian phase-shifting depends on TIMING relative to the body clock, not dose.',
    halfLife: '~30–60 minutes (immediate-release; prolonged-release formulations last longer).',
    metabolism: 'Hepatic CYP1A2 (major) → 6-hydroxymelatonin.',
    approvedCanada: ['Sold OTC as a Natural Health Product (NPN, not a DIN) in Canada'],
    offLabel: ['Delayed sleep-phase / circadian rhythm disorders', 'Jet lag', 'Shift-work sleep disturbance', 'Sleep onset in ASD/ADHD', 'Delirium prevention (adjunct)', 'REM sleep behaviour disorder (adjunct)'],
    approvedPopulations: 'Adults and children (over-the-counter).',
    startingDose: 'Circadian/phase-shifting 0.5–1 mg timed to the desired shift; hypnotic 2–5 mg at bedtime.',
    titration: 'Use the lowest effective dose; correct timing matters more than a higher dose.',
    maxDose: 'Commonly up to ~5–10 mg; higher doses rarely add benefit.',
    frequencyTiming: 'For circadian disorders, timing (e.g., early evening for delayed sleep phase) is the key variable.',
    startStopCrossTaper: 'No taper — no dependence.',
    administrationNotes: 'OTC status means variable product quality; counsel patients to choose a reputable NPN-labelled product.',
    commonSE: ['Daytime drowsiness', 'Headache', 'Dizziness', 'Vivid dreams (occasional)'],
    seriousAE: ['Rare — very wide safety margin'],
    syndromes: [],
    overdoseLethality: 'Very low — one of the safest sleep aids; excess causes drowsiness.',
    discontinuationSyndrome: 'None — no dependence or withdrawal.',
    ongoingMonitoring: 'Minimal; reassess whether timing/sleep hygiene is addressing the circadian problem.',
    majorDDI: ['Fluvoxamine (potent CYP1A2 inhibitor) markedly RAISES melatonin levels', 'Other CYP1A2 inhibitors (ciprofloxacin) raise levels; smoking (CYP1A2 induction) lowers them', 'CNS depressants — additive drowsiness', 'Possible potentiation of anticoagulants/antiplatelets (monitor)'],
    contraindicatedCombos: [],
    pregnancy: 'Data limited; generally avoided/not recommended routinely in pregnancy given limited evidence.',
    lactation: 'Limited data; generally cautious.',
    geriatric: 'Endogenous melatonin declines with age; low doses can help sleep onset with minimal risk.',
    pearls: [
      'In Canada melatonin is sold OTC as a Natural Health Product with an NPN (Natural Product Number), NOT a DIN — a distinguishing Canadian regulatory nuance.',
      'For circadian rhythm disorders, the TIMING of the dose (relative to the body clock) matters more than the amount — low doses (0.5–1 mg) are used for phase-shifting.',
      'Fluvoxamine (potent CYP1A2 inhibitor) dramatically increases melatonin exposure — the same CYP1A2 pathway that makes fluvoxamine dangerous with ramelteon.',
    ],
    mnemonics: ['"MelatoNiN = NPN, Not a DIN" — OTC natural health product in Canada.'],
    confusables: ['Melatonin (endogenous hormone, OTC/NPN) vs ramelteon (synthetic MT1/MT2 agonist, prescription, US-only).'],
    classDifferentiators: 'Endogenous melatonergic agonist; OTC/NPN in Canada; best for circadian/timing problems; extremely safe; no dependence.',
    examHooks: ['What regulatory number does OTC melatonin carry in Canada? (NPN, not DIN)', 'Which drug interaction sharply raises melatonin levels? (fluvoxamine — CYP1A2)'],
    counsellingPoints: ['For jet lag / delayed sleep phase, timing matters more than dose.', 'Choose a reputable NPN-labelled product.', 'It is not a sedative "knockout" pill — it nudges your body clock.', 'Tell your doctor if you take fluvoxamine.'],
    vignettes: [
      {
        stem: 'A patient asks why the melatonin they buy in a Canadian pharmacy has an "NPN" on the bottle rather than a DIN like their other prescriptions. What does this reflect?',
        options: ['It is a controlled substance', 'It is regulated as a Natural Health Product, sold over-the-counter', 'It has no proven mechanism', 'It requires a prescription in Canada'],
        answer: 'It is regulated as a Natural Health Product, sold over-the-counter',
        explanation: 'In Canada melatonin is marketed OTC as a Natural Health Product and carries a Natural Product Number (NPN), not a Drug Identification Number (DIN) — a Canadian regulatory distinction.',
        testedFact: 'Melatonin NPN (OTC) in Canada',
        source: { name: 'Health Canada Natural Health Products Regulations', origin: 'monograph' },
      },
    ],
    _prov: HYP_PROV,
  },

  ramelteon: {
    pronunciation: 'ram-EL-tee-on',
    moa: 'Selective, high-affinity melatonin MT1/MT2 receptor agonist — a pharmaceutical melatonergic. Promotes sleep ONSET without GABA/benzodiazepine activity.',
    receptorProfile: 'MT1/MT2 agonist; no appreciable affinity for GABA, dopamine, or opioid receptors.',
    onsetOfEffect: 'Rapid — reduces sleep latency the night of dosing.',
    halfLife: '~1–2.6 hours; active metabolite M-II somewhat longer (~2–5 h).',
    metabolism: 'Extensive hepatic first-pass via CYP1A2 (major) → this is the key interaction pathway.',
    activeMetabolites: 'M-II (contributes to activity).',
    approvedCanada: ['Not marketed in Canada — US-only (for awareness)'],
    offLabel: [],
    approvedPopulations: 'Adults (US indication: insomnia characterized by difficulty with sleep onset).',
    startingDose: '8 mg PO within 30 minutes of bedtime.',
    titration: 'No dose titration — 8 mg is the fixed dose.',
    maxDose: '8 mg/day.',
    frequencyTiming: 'Once nightly; do not take with or immediately after a high-fat meal (delays absorption).',
    renalHepaticAdjustment: 'Avoid in severe hepatic impairment.',
    startStopCrossTaper: 'No taper — no dependence.',
    administrationNotes: 'Notable as a hypnotic that is NOT a controlled substance (no abuse potential).',
    commonSE: ['Somnolence', 'Dizziness', 'Fatigue', 'Headache'],
    seriousAE: ['Endocrine effects (increased prolactin, decreased testosterone) with chronic use', 'Worsening depression/suicidal ideation', 'Complex sleep behaviours (rare)'],
    syndromes: ['Hyperprolactinemia (chronic use)'],
    overdoseLethality: 'Low; excessive somnolence; no dependence.',
    discontinuationSyndrome: 'None — no physiologic dependence.',
    ongoingMonitoring: 'If chronic, ask about menstrual/libido/galactorrhea changes (prolactin); reassess sleep.',
    majorDDI: ['Fluvoxamine — CONTRAINDICATED (potent CYP1A2 inhibitor raises ramelteon exposure ~100-fold+)', 'Other strong CYP1A2 inhibitors (ciprofloxacin) — caution', 'Alcohol/CNS depressants — additive', 'CYP1A2 inducers (rifampin, smoking) reduce efficacy'],
    contraindicatedCombos: ['Fluvoxamine (potent CYP1A2 inhibitor)'],
    pregnancy: 'Limited data; use only if clearly needed.',
    lactation: 'Limited data; caution.',
    geriatric: 'Well tolerated; a non-controlled option for sleep-onset insomnia in the elderly.',
    pearls: [
      'US-only (not marketed in Canada) — included for awareness/contrast with OTC melatonin.',
      'A hypnotic with NO abuse potential — it is NOT a controlled substance, unlike Z-drugs and benzodiazepines.',
      'Fluvoxamine is CONTRAINDICATED: as a potent CYP1A2 inhibitor it raises ramelteon exposure enormously — the signature ramelteon interaction.',
    ],
    mnemonics: ['"RAMelteon + fluvoxaMINE = RAM into a wall" — CYP1A2 contraindication (huge level rise).'],
    confusables: ['Ramelteon (Rx melatonergic, US-only, MT1/MT2) vs melatonin (OTC/NPN hormone) vs the DORAs (orexin antagonists).'],
    classDifferentiators: 'Synthetic MT1/MT2 agonist; sleep-ONSET insomnia; non-controlled/non-dependence; defined by the CYP1A2 (fluvoxamine) contraindication; US-only.',
    examHooks: ['Which sleep drug is contraindicated with fluvoxamine because of CYP1A2? (ramelteon)', 'Which hypnotic is not a controlled substance? (ramelteon / melatonergics)'],
    counsellingPoints: ['Take within 30 min of bedtime.', 'Avoid a high-fat meal just before dosing.', 'Tell your prescriber if you take fluvoxamine (must not combine).'],
    vignettes: [
      {
        stem: 'A patient in the US on fluvoxamine for OCD requests ramelteon for sleep-onset insomnia. Why is this combination contraindicated?',
        options: ['Additive serotonin syndrome risk', 'Fluvoxamine potently inhibits CYP1A2, massively increasing ramelteon exposure', 'Both prolong the QT interval', 'Ramelteon induces fluvoxamine metabolism, causing OCD relapse'],
        answer: 'Fluvoxamine potently inhibits CYP1A2, massively increasing ramelteon exposure',
        explanation: 'Ramelteon is cleared mainly by CYP1A2. Fluvoxamine is a potent CYP1A2 inhibitor and increases ramelteon exposure many-fold, so the combination is contraindicated.',
        testedFact: 'Ramelteon + fluvoxamine CYP1A2 contraindication',
        source: { name: 'openFDA/DailyMed ramelteon label — contraindications/drug interactions', origin: 'openfda' },
      },
    ],
    _prov: HYP_PROV,
  },

  phenobarbital: {
    pronunciation: 'fee-noh-BAR-bih-tal',
    moa: 'Long-acting barbiturate; positive allosteric modulator at a distinct site on the GABA-A receptor → increases the DURATION of Cl- channel opening (contrast benzodiazepines, which increase FREQUENCY). At high concentrations it opens the Cl- channel directly, independent of GABA → NO ceiling effect → profound CNS/respiratory depression.',
    receptorProfile: 'GABA-A barbiturate site (prolongs opening; GABA-independent channel opening at high dose); also weak glutamate (AMPA/kainate) antagonism.',
    onsetOfEffect: 'Oral onset ~30–60 min; IV loading acts within minutes (status epilepticus).',
    halfLife: 'Very LONG — ~53–118 hours (~2–5 days).',
    timeToSteadyState: '~2–3 weeks (long half-life).',
    metabolism: 'Hepatic CYP2C9 (and 2C19/2E1); a POTENT broad-spectrum enzyme INDUCER (CYP3A4, 2C, 1A2, UGT) — it induces its own and many other drugs’ metabolism (autoinduction).',
    elimination: 'Partly renal as unchanged drug; excretion enhanced by alkaline urine (weak acid).',
    proteinBinding: '~45–50%.',
    approvedCanada: ['Seizure disorders (incl. status epilepticus, neonatal seizures)', 'Sedation (largely historical)'],
    offLabel: ['Alcohol/sedative-hypnotic withdrawal (protocolized)', 'Refractory benzodiazepine withdrawal'],
    approvedPopulations: 'Adults and children (including neonates).',
    startingDose: 'Anticonvulsant maintenance ~1–3 mg/kg/day (often 60–200 mg/day in adults); status epilepticus loading ~15–20 mg/kg IV. Guided by levels/response.',
    titration: 'Titrate slowly to effect/serum level given the long half-life; adjust for the narrow therapeutic index.',
    maxDose: 'Highly indication-dependent and level-guided (target serum ~65–172 µmol/L / ~15–40 µg/mL); avoid rates/doses causing respiratory depression.',
    frequencyTiming: 'Once or twice daily (long half-life allows once-daily maintenance).',
    renalHepaticAdjustment: 'Reduce in hepatic impairment; accumulation risk in renal impairment.',
    startStopCrossTaper: 'NEVER stop abruptly — taper slowly; abrupt withdrawal can cause seizures and a potentially fatal withdrawal syndrome.',
    administrationNotes: 'Narrow therapeutic index — the dangerous outlier of this class.',
    commonSE: ['Sedation/drowsiness', 'Cognitive slowing', 'Ataxia', 'Nystagmus', '"Hangover"/next-day grogginess', 'Paradoxical excitation (children/elderly)'],
    seriousAE: ['Respiratory depression', 'Dependence and tolerance', 'Severe withdrawal (seizures, delirium — potentially fatal)', 'Stevens-Johnson syndrome / DRESS', 'Osteomalacia (chronic — vitamin D metabolism)', 'Megaloblastic anemia (folate)'],
    syndromes: ['Barbiturate intoxication (CNS/respiratory depression)', 'Barbiturate withdrawal (seizures/delirium)', 'Enzyme-induction cascade', 'Physical dependence'],
    overdoseLethality: 'HIGH — narrow therapeutic index, NO ceiling effect, profound respiratory depression; historically a common lethal overdose. Management is supportive (airway/ventilation) with activated charcoal (multi-dose) and urinary alkalinization; flumazenil does NOT reverse barbiturates. This is the sharp contrast to overdose-safe benzodiazepines.',
    discontinuationSyndrome: 'Serious barbiturate withdrawal (anxiety, tremor, seizures, delirium) that can be fatal — always taper.',
    baselineWorkup: ['CBC (megaloblastic anemia risk)', 'Liver function', 'Review of all concurrent medications for induction interactions'],
    ongoingMonitoring: 'Serum phenobarbital level (target ~65–172 µmol/L), sedation/respiratory status, CBC, and vitamin D/bone health with chronic use; watch for induced failure of interacting drugs.',
    majorDDI: ['Potent CYP INDUCER → lowers levels/efficacy of warfarin (INR falls), oral contraceptives (CONTRACEPTIVE FAILURE), corticosteroids, many anticonvulsants, direct-acting antivirals, immunosuppressants, and others', 'Additive CNS/respiratory depression with alcohol, opioids, and benzodiazepines', 'Valproate raises phenobarbital levels (inhibits its metabolism)'],
    contraindicatedCombos: ['Concomitant opioids/other CNS depressants without close monitoring (fatal respiratory depression)'],
    pregnancy: 'Teratogenic risk (congenital malformations) and neonatal withdrawal/bleeding (vitamin K); use only when clearly necessary for seizure control with specialist input.',
    lactation: 'Excreted in milk — can sedate the infant; monitor closely.',
    geriatric: 'Paradoxical excitation, falls, cognitive impairment, and drug-interaction burden — generally avoid.',
    pearls: [
      'Barbiturates increase the DURATION of Cl- channel opening (benzodiazepines increase FREQUENCY); at high dose barbiturates open the channel directly with NO ceiling effect → lethal overdose.',
      'Potent broad CYP inducer → the classic cause of oral-contraceptive failure and falling warfarin/INR — a high-yield interaction contrast with benzodiazepines.',
      'Flumazenil does NOT reverse barbiturate overdose (it is not a benzo-site drug); management is airway support, multi-dose charcoal, and urinary alkalinization.',
      'The dangerous OUTLIER of the anxiolytic/hypnotic families: narrow therapeutic index, respiratory depression, high overdose lethality, severe (potentially fatal) withdrawal.',
    ],
    mnemonics: [
      '"BarbiDURATE vs BenzoFREQ" — Barbiturates prolong DURATION of Cl- opening; Benzos increase FREQUENCY.',
      '"Barbiturates have NO ceiling → they can kill" (vs benzos, which have a ceiling and are overdose-safer).',
    ],
    confusables: [
      'Phenobarbital (barbiturate — enzyme INDUCER, GABA duration) vs a benzodiazepine (GABA frequency, overdose-safe, flumazenil-reversible).',
      'Phenobarbital vs pentobarbital — both barbiturates; pentobarbital is short-acting (anesthesia/ICP), phenobarbital is long-acting (seizures/withdrawal).',
    ],
    classDifferentiators: 'The barbiturate outlier: prolongs Cl- channel DURATION with no ceiling effect, potent CYP inducer, high overdose lethality and dangerous withdrawal, long half-life — everything the non-benzo alternatives are chosen to AVOID.',
    examHooks: [
      'Barbiturate vs benzodiazepine at GABA-A: duration vs frequency of Cl- channel opening?',
      'Why is phenobarbital overdose more lethal than benzodiazepine overdose? (no ceiling effect → respiratory depression; flumazenil does not help)',
      'Which sedative is a potent enzyme inducer causing oral-contraceptive failure? (phenobarbital)',
    ],
    counsellingPoints: [
      'Never stop suddenly — withdrawal can cause seizures.',
      'Use a non-hormonal or backup contraceptive — this drug can make the pill fail.',
      'Do not combine with alcohol or opioids — dangerous breathing suppression.',
      'Report rash promptly (serious skin reactions).',
    ],
    vignettes: [
      {
        stem: 'On a board question, how do barbiturates such as phenobarbital differ from benzodiazepines at the GABA-A receptor, and why does this matter clinically in overdose?',
        options: [
          'Barbiturates increase FREQUENCY of Cl- channel opening; they are safer in overdose',
          'Barbiturates increase the DURATION of Cl- channel opening and have no ceiling effect, making overdose more lethal',
          'Barbiturates block Cl- channels, so they cause seizures in overdose',
          'Barbiturates act only on glutamate receptors, so flumazenil reverses them',
        ],
        answer: 'Barbiturates increase the DURATION of Cl- channel opening and have no ceiling effect, making overdose more lethal',
        explanation: 'Barbiturates prolong Cl- channel opening duration and, at high concentrations, open the channel independent of GABA — there is no ceiling effect, so respiratory depression and death occur more readily than with benzodiazepines (which increase opening frequency, have a ceiling, and are reversible with flumazenil).',
        testedFact: 'Barbiturate duration/no-ceiling vs benzo frequency',
        source: { name: 'openFDA/DailyMed phenobarbital label — clinical pharmacology; standard pharmacology', origin: 'openfda' },
      },
      {
        stem: 'A woman on combined oral contraceptives is started on phenobarbital for epilepsy and later presents pregnant. What is the most likely mechanism of contraceptive failure?',
        options: [
          'Phenobarbital inhibits CYP3A4, raising estrogen levels',
          'Phenobarbital is a potent CYP enzyme inducer that accelerates metabolism of the contraceptive hormones',
          'Phenobarbital displaces the hormones from protein binding',
          'Phenobarbital reduces gut absorption of the pill',
        ],
        answer: 'Phenobarbital is a potent CYP enzyme inducer that accelerates metabolism of the contraceptive hormones',
        explanation: 'Phenobarbital is a potent broad-spectrum CYP inducer, increasing metabolism of estrogen/progestin and lowering their levels — a classic cause of oral-contraceptive failure (it likewise lowers warfarin/INR).',
        testedFact: 'Phenobarbital enzyme induction → OCP failure',
        source: { name: 'openFDA/DailyMed phenobarbital label — drug interactions', origin: 'openfda' },
      },
    ],
    _prov: HYP_PROV,
  },
};
