// authored/maoi.js — authored overlay for the MAOI class.
//
// Mechanism/PK/dosing summaries + the pedagogical layer, grounded in established
// pharmacology and the fetched openFDA/monograph label sections. `_prov` declares which
// safety-critical fields the label text grounds; build.js attaches that source text and,
// where a field cannot be grounded, downgrades it to origin 'authored' + verifyFlag.
//
// MAOI class theme: block monoamine oxidase → raise NE/5-HT/DA. TWO lethal interactions:
//   (1) TYRAMINE → hypertensive crisis (aged cheese, cured/smoked meat, fermented soy,
//       tap/draught beer, Marmite/Vegemite, fava beans) with IRREVERSIBLE MAOIs. Tyramine is
//       normally destroyed by gut/hepatic MAO-A; block it and tyramine floods the circulation,
//       displacing stored NE → surge in BP.
//   (2) SEROTONIN SYNDROME with any serotonergic (SSRI/SNRI/TCA, tramadol, meperidine,
//       linezolid, dextromethorphan, triptans, St John's wort).
// Require a 14-day washout EACH WAY (5 weeks after fluoxetine). Overdose is dangerous
// (delayed hyperthermia + cardiovascular collapse). Contrast: irreversible MAOIs (strict diet)
// vs moclobemide (RIMA — reversible, minimal diet, short washout) vs low-dose/patch selegiline
// (MAO-B selective / first-pass-sparing → skips the diet).

const MAOI_PROV = {
  startingDose: 'openfda', maxDose: 'openfda', seriousAE: 'openfda', syndromes: 'openfda',
  majorDDI: 'openfda', contraindicatedCombos: 'openfda', pregnancy: 'openfda',
  overdoseLethality: 'openfda',
};

export default {
  phenelzine: {
    pronunciation: 'FEN-el-zeen',
    moa: 'Irreversible, non-selective monoamine oxidase inhibitor (MAO-A and MAO-B) → raises NE, 5-HT, dopamine. Hydrazine structure.',
    receptorProfile: 'No direct receptor affinity; effect is enzymatic (blocks monoamine breakdown). Depletes pyridoxine (vitamin B6) as a hydrazine.',
    onsetOfEffect: 'Antidepressant effect over 2–4 wk; full enzyme inhibition builds over days.',
    halfLife: 'Parent drug short (~1.5–4 h), but effect lasts ~2 weeks because inhibition is IRREVERSIBLE — activity returns only as new MAO is synthesized.',
    metabolism: 'Hepatic; acetylation and oxidation (hydrazine metabolites). Not a major CYP inhibitor, but PD interactions dominate.',
    foodEffect: 'Take with food if GI upset; the critical issue is tyramine content, not absorption.',
    approvedCanada: ['Major depressive disorder (esp. atypical/treatment-resistant)'],
    offLabel: ['Panic disorder', 'Social anxiety disorder', 'Atypical depression'],
    approvedPopulations: 'Adults.',
    startingDose: '15 mg PO three times daily.',
    titration: 'Increase to 60–90 mg/day over weeks based on response and tolerability.',
    maxDose: '90 mg/day.',
    frequencyTiming: 'Divided doses (BID–TID); can be sedating.',
    startStopCrossTaper: 'Requires a 14-day MAOI washout each way when switching to/from serotonergics (5 weeks after fluoxetine). Allow ~2 weeks for MAO regeneration after stopping before dietary/drug restrictions lift.',
    administrationNotes: 'More sedating and anxiolytic than tranylcypromine; historically favoured for atypical depression with anxiety.',
    commonSE: ['Orthostatic hypotension', 'Weight gain', 'Insomnia', 'Sexual dysfunction', 'Edema', 'Anticholinergic effects (dry mouth, constipation)'],
    seriousAE: ['Hypertensive crisis (tyramine or sympathomimetics)', 'Serotonin syndrome', 'Hepatotoxicity (hydrazine)', 'Pyridoxine (B6) deficiency → peripheral neuropathy'],
    syndromes: ['Hypertensive crisis (tyramine reaction)', 'Serotonin syndrome', 'Orthostatic hypotension'],
    overdoseLethality: 'Dangerous in overdose — delayed (up to 12–24 h) onset of agitation, hyperthermia, autonomic instability and cardiovascular collapse; narrow margin. High lethality relative to SSRIs.',
    discontinuationSyndrome: 'Abrupt withdrawal can cause agitation, vivid dreams and (rarely) psychosis; taper.',
    ongoingMonitoring: 'Blood pressure (supine and standing); watch for occipital headache signalling hypertensive crisis; mood/suicidality. Consider pyridoxine if neuropathic symptoms.',
    majorDDI: ['Serotonergics — SSRIs/SNRIs/TCAs, tramadol, meperidine, linezolid, dextromethorphan, triptans, St John\'s wort (serotonin syndrome)', 'Sympathomimetics — pseudoephedrine, phenylephrine, amphetamines, cocaine (hypertensive crisis)', 'Other MAOIs', 'Buspirone, tapentadol'],
    contraindicatedCombos: ['Any serotonergic antidepressant (SSRI/SNRI/TCA)', 'Meperidine (pethidine) — can be fatal', 'Linezolid, methylene blue', 'Dextromethorphan, tramadol', 'Sympathomimetics / decongestants', 'Other MAOIs / RIMA'],
    maoiWashout: 'Stop other MAOI/serotonergic ≥14 days before starting phenelzine; stop phenelzine ≥14 days before starting a serotonergic (5 weeks after fluoxetine).',
    foodInteractions: 'STRICT low-tyramine diet required. Avoid aged/matured cheese, cured or smoked/fermented meats, fermented soy (soy sauce, miso, tofu left out), sauerkraut, tap/draught beer, broad (fava) bean pods, overripe fruit, and yeast/meat extracts (Marmite, Vegemite, Oxo). Tyramine + MAOI → hypertensive crisis.',
    pregnancy: 'Generally avoided; limited data and risk of hypertensive reactions. Weigh against untreated illness (CANMAT perinatal 2024).',
    lactation: 'Limited data; generally avoided.',
    geriatric: 'Orthostatic hypotension and falls risk; dietary adherence harder — use caution.',
    pearls: [
      'Hydrazine MAOI → can deplete pyridoxine (B6) causing peripheral neuropathy, and carries hepatotoxicity risk.',
      'More sedating/anxiolytic than tranylcypromine — historically the MAOI for atypical/anxious depression.',
      'Irreversible: dietary and drug restrictions persist ~2 weeks after stopping while new MAO is made.',
    ],
    mnemonics: ['Tyramine crisis foods = "the 3 C\'s + beer": Cheese (aged), Cured meats, Chianti/fermented, plus tap beer & Marmite.'],
    confusables: ['Phenelzine (MAOI antidepressant) vs phenytoin (anticonvulsant) vs phentermine (sympathomimetic — dangerous WITH an MAOI).'],
    classDifferentiators: 'The sedating, anxiolytic hydrazine MAOI; unique risks of B6 depletion/neuropathy and hepatotoxicity.',
    examHooks: ['Which MAOI is a hydrazine linked to pyridoxine (B6) deficiency and hepatotoxicity? (phenelzine)', 'Occipital headache + hypertension on an MAOI → tyramine crisis.'],
    counsellingPoints: [
      'Follow the low-tyramine diet strictly — no aged cheese, cured/fermented meats, fermented soy, tap beer, Marmite; continue for 2 weeks after stopping.',
      'A severe throbbing (usually occipital) headache, palpitations or chest pain means possible hypertensive crisis — seek emergency care.',
      'Do not take any new medication (including OTC cold/decongestant remedies, dextromethorphan, tramadol) without pharmacist/physician check.',
      'Rise slowly to avoid dizziness (orthostatic hypotension).',
    ],
    vignettes: [
      {
        stem: 'A 47-year-old on phenelzine for atypical depression eats an aged-cheddar and salami platter with a draught beer at a party. Two hours later he presents with a severe throbbing occipital headache, BP 220/125, diaphoresis and palpitations. What is the mechanism?',
        options: [
          'Serotonin syndrome from excess synaptic serotonin',
          'Tyramine-induced release of stored noradrenaline causing a hypertensive crisis',
          'Anticholinergic toxicity',
          'Withdrawal-emergent autonomic instability',
        ],
        answer: 'Tyramine-induced release of stored noradrenaline causing a hypertensive crisis',
        explanation: 'Aged cheese, cured meats and tap beer are high in tyramine. With gut/hepatic MAO-A irreversibly blocked, ingested tyramine is not degraded, floods the circulation and displaces noradrenaline from nerve terminals → abrupt severe hypertension ("cheese reaction").',
        testedFact: 'Tyramine hypertensive crisis with irreversible MAOIs',
        source: { name: 'openFDA/DailyMed phenelzine label — warnings (hypertensive crises)', origin: 'openfda' },
      },
    ],
    _prov: MAOI_PROV,
  },

  tranylcypromine: {
    pronunciation: 'tran-il-SIP-roh-meen',
    moa: 'Irreversible, non-selective monoamine oxidase inhibitor (MAO-A and MAO-B). Amphetamine-like structure → activating, mildly stimulant.',
    receptorProfile: 'Structurally related to amphetamine; some direct catecholamine-releasing/reuptake effect adds to the enzymatic (MAO) mechanism.',
    onsetOfEffect: 'Often faster/more activating than phenelzine; antidepressant effect over 1–3 wk.',
    halfLife: 'Parent drug very short (~1.5–3 h), but effect lasts ~1–2 weeks because inhibition is IRREVERSIBLE.',
    metabolism: 'Hepatic. PD (not CYP) interactions dominate the risk profile.',
    foodEffect: 'Take earlier in the day to limit insomnia; tyramine content is the critical dietary issue.',
    approvedCanada: ['Major depressive disorder (treatment-resistant)'],
    offLabel: ['Atypical depression', 'Anxiety disorders'],
    approvedPopulations: 'Adults.',
    startingDose: '10 mg PO twice daily.',
    titration: 'Increase gradually; usual 30 mg/day, up to 60 mg/day if needed.',
    maxDose: '60 mg/day.',
    frequencyTiming: 'Divided doses, earlier in the day (activating — dosing late causes insomnia).',
    startStopCrossTaper: '14-day MAOI washout each way vs serotonergics (5 weeks after fluoxetine); ~2 weeks for MAO regeneration after stopping.',
    administrationNotes: 'Activating/stimulant profile; amphetamine-like structure means some dependence/abuse potential has been reported.',
    commonSE: ['Insomnia (activating)', 'Orthostatic hypotension', 'Agitation/anxiety', 'Sexual dysfunction', 'Less weight gain than phenelzine'],
    seriousAE: ['Hypertensive crisis (tyramine or sympathomimetics)', 'Serotonin syndrome', 'Dependence/abuse potential (amphetamine-like)'],
    syndromes: ['Hypertensive crisis (tyramine reaction)', 'Serotonin syndrome', 'Orthostatic hypotension'],
    overdoseLethality: 'Dangerous in overdose — delayed hyperthermia, agitation, seizures, autonomic instability and cardiovascular collapse; high lethality relative to SSRIs.',
    discontinuationSyndrome: 'Rebound agitation/insomnia possible on abrupt stop; taper.',
    ongoingMonitoring: 'Blood pressure (supine/standing); occipital headache as a crisis warning; sleep and activation; mood/suicidality.',
    majorDDI: ['Serotonergics — SSRIs/SNRIs/TCAs, tramadol, meperidine, linezolid, dextromethorphan, triptans, St John\'s wort (serotonin syndrome)', 'Sympathomimetics — pseudoephedrine, phenylephrine, amphetamines, cocaine (hypertensive crisis)', 'Other MAOIs / RIMA', 'Buspirone'],
    contraindicatedCombos: ['Any serotonergic antidepressant (SSRI/SNRI/TCA)', 'Meperidine (pethidine) — can be fatal', 'Linezolid, methylene blue', 'Dextromethorphan, tramadol', 'Sympathomimetics / decongestants', 'Other MAOIs / RIMA'],
    maoiWashout: 'Stop other MAOI/serotonergic ≥14 days before starting tranylcypromine; stop tranylcypromine ≥14 days before a serotonergic (5 weeks after fluoxetine).',
    foodInteractions: 'STRICT low-tyramine diet required (identical to phenelzine): avoid aged cheese, cured/smoked/fermented meats, fermented soy (soy sauce, miso), sauerkraut, tap/draught beer, broad (fava) beans, and yeast/meat extracts (Marmite, Vegemite). Tyramine + MAOI → hypertensive crisis.',
    pregnancy: 'Generally avoided; limited data and hypertensive-reaction risk. Weigh untreated illness (CANMAT perinatal 2024).',
    lactation: 'Limited data; generally avoided.',
    geriatric: 'Activation, insomnia and orthostatic hypotension; caution.',
    pearls: [
      'Amphetamine-like structure → the ACTIVATING MAOI (insomnia, dose early); some abuse potential.',
      'Contrast with phenelzine: tranylcypromine = activating/less weight gain; phenelzine = sedating/more weight gain.',
      'Same strict tyramine diet and 14-day washout rules as all irreversible MAOIs.',
    ],
    mnemonics: ['"tranylcyproMINE = amphetaMINE-like" → activating, causes insomnia, has abuse potential.'],
    confusables: ['Tranylcypromine vs trimipramine (a TCA) — similar-looking names, different classes.'],
    classDifferentiators: 'The activating, amphetamine-like irreversible MAOI; less weight gain than phenelzine but more insomnia and some dependence risk.',
    examHooks: ['Which MAOI is amphetamine-like and most activating (causes insomnia, dose in the morning)? (tranylcypromine)'],
    counsellingPoints: [
      'Take earlier in the day to avoid insomnia.',
      'Same strict low-tyramine diet as other MAOIs; continue ~2 weeks after stopping.',
      'Avoid all decongestants, stimulants, dextromethorphan, tramadol and other antidepressants unless cleared.',
      'A sudden severe headache with high blood pressure is an emergency (hypertensive crisis).',
    ],
    vignettes: [
      {
        stem: 'A 34-year-old with treatment-resistant depression on tranylcypromine is given meperidine (pethidine) in the ED for renal colic. Within an hour she develops agitation, hyperthermia (40°C), diaphoresis, tremor, hyperreflexia and inducible clonus. What is the diagnosis and the offending mechanism?',
        options: [
          'Neuroleptic malignant syndrome from dopamine blockade',
          'Serotonin syndrome from an MAOI + meperidine (serotonergic) combination',
          'Malignant hyperthermia',
          'Anticholinergic toxidrome',
        ],
        answer: 'Serotonin syndrome from an MAOI + meperidine (serotonergic) combination',
        explanation: 'Meperidine has serotonergic activity and is contraindicated with MAOIs. Clonus/hyperreflexia, hyperthermia and autonomic instability point to serotonin syndrome, not NMS (which is bradykinesic/rigid). Use a non-serotonergic analgesic (e.g., morphine) in MAOI patients.',
        testedFact: 'MAOI + meperidine → serotonin syndrome (contraindicated)',
        source: { name: 'openFDA/DailyMed tranylcypromine label — contraindications (meperidine/serotonergics)', origin: 'openfda' },
      },
    ],
    _prov: MAOI_PROV,
  },

  moclobemide: {
    pronunciation: 'moh-KLOH-buh-mide',
    moa: 'Reversible Inhibitor of MAO-A (RIMA) — selectively and reversibly inhibits MAO-A, raising 5-HT, NE and dopamine. Canada-available (not marketed in the US).',
    receptorProfile: 'No significant direct receptor binding; reversibility means dietary tyramine can competitively DISPLACE it from MAO-A, greatly limiting the "cheese reaction".',
    onsetOfEffect: 'Antidepressant effect over 1–3 wk.',
    halfLife: 'Short (~1–3 h) — a key reason its washout is much shorter than irreversible MAOIs.',
    metabolism: 'Hepatic, largely via CYP2C19 (some 2D6). Moderate inhibitor of CYP2D6/2C19 — levels rise with 2C19 inhibitors (e.g., cimetidine → halve the dose).',
    foodEffect: 'Take AFTER meals — food (and taking it post-prandially) further reduces any tyramine pressor effect.',
    approvedCanada: ['Major depressive disorder', 'Social anxiety disorder'],
    offLabel: ['Atypical depression', 'Dysthymia'],
    approvedPopulations: 'Adults.',
    startingDose: '300 mg/day PO in divided doses (e.g., 150 mg BID) after meals.',
    titration: 'Increase after ~1 week as needed to a maximum of 600 mg/day.',
    maxDose: '600 mg/day.',
    frequencyTiming: 'BID–TID with/after meals.',
    startStopCrossTaper: 'Short washout: because it is reversible with a short half-life, moclobemide clears within ~24 h — but still allow adequate washout when switching from an irreversible MAOI (~2 wk) or from an SSRI/SNRI (~1 wk; 5 wk after fluoxetine) to avoid serotonin syndrome.',
    administrationNotes: 'The Canadian "safer MAOI" — reversibility markedly lowers hypertensive-crisis risk versus phenelzine/tranylcypromine.',
    commonSE: ['Insomnia', 'Nausea', 'Dizziness', 'Headache', 'Dry mouth', 'Less orthostatic hypotension / weight gain than irreversible MAOIs'],
    seriousAE: ['Serotonin syndrome (with serotonergics)', 'Hypertensive reaction (much lower risk; possible only with very large tyramine loads or overdose)'],
    syndromes: ['Serotonin syndrome', 'Hypertensive reaction (low risk)'],
    overdoseLethality: 'Generally safer in isolated overdose than irreversible MAOIs, but combined overdose with a serotonergic (esp. SSRI/citalopram) can cause fatal serotonin toxicity.',
    discontinuationSyndrome: 'Minimal; taper is generally straightforward.',
    ongoingMonitoring: 'Mood/suicidality; blood pressure if high tyramine intake or overdose suspected; CYP2C19-inhibitor co-prescription (dose reduce).',
    majorDDI: ['Serotonergics — SSRIs/SNRIs/TCAs, tramadol, meperidine, linezolid, dextromethorphan, triptans (serotonin syndrome — the main danger)', 'Sympathomimetics (attenuated but still avoid large doses)', 'Cimetidine and other CYP2C19 inhibitors (raise levels — reduce moclobemide dose)', 'Other MAOIs'],
    contraindicatedCombos: ['SSRIs/SNRIs/clomipramine and other serotonergics', 'Meperidine (pethidine), tramadol, dextromethorphan', 'Linezolid', 'Other MAOIs', 'Sympathomimetics in large doses'],
    maoiWashout: 'Moclobemide itself clears in ~24 h (reversible, short half-life). Still leave ≥14 days after an irreversible MAOI, and the usual ~1 week (5 weeks for fluoxetine) after an SSRI/SNRI, before/after moclobemide to avoid serotonin syndrome.',
    foodInteractions: 'No strict tyramine diet — reversibility lets tyramine displace the drug from MAO-A, so ordinary meals are safe. Advise only to AVOID LARGE quantities of tyramine-rich food (a lot of aged cheese) at once, and to take moclobemide after meals.',
    pregnancy: 'Limited data; use only if benefit outweighs risk (CANMAT perinatal 2024).',
    lactation: 'Small amounts in milk; limited data — caution.',
    geriatric: 'Better tolerated than irreversible MAOIs (less orthostasis); still watch drug interactions.',
    pearls: [
      'RIMA = Reversible Inhibitor of MAO-A → tyramine can outcompete it, so NO strict low-tyramine diet and a much SHORTER washout than irreversible MAOIs.',
      'Canada-specific (Manerix) — not sold in the US; a favourite Royal-College distinguishing point.',
      'Serotonin syndrome risk PERSISTS — still contraindicated with SSRIs/SNRIs, tramadol, meperidine, dextromethorphan.',
      'Take after meals and halve the dose if given with cimetidine (CYP2C19).',
    ],
    mnemonics: ['"moclobeMIDE = MILDer MAOI": Reversible (RIMA), Minimal diet, Rapid (short) washout — but serotonin syndrome still applies.'],
    confusables: ['Moclobemide (RIMA, reversible, minimal diet) vs phenelzine/tranylcypromine (irreversible, strict tyramine diet).'],
    classDifferentiators: 'The reversible MAO-A–selective agent (RIMA): dramatically lower tyramine/hypertensive risk, no strict diet, short washout — but the serotonin-syndrome contraindications are unchanged.',
    examHooks: ['Which MAOI is reversible, MAO-A selective, Canadian, and needs no strict tyramine diet? (moclobemide)', 'Why does moclobemide avoid the cheese reaction? (reversible — tyramine displaces it from MAO-A).'],
    counsellingPoints: [
      'Take after meals; no strict special diet, but avoid eating large amounts of aged cheese or other very tyramine-rich foods at one sitting.',
      'Still do NOT combine with other antidepressants, tramadol, meperidine or dextromethorphan — serious serotonin reactions can occur.',
      'Tell any prescriber you take moclobemide before starting new medicines.',
    ],
    vignettes: [
      {
        stem: 'A Canadian patient with social anxiety disorder is intolerant of the strict tyramine diet required by classic MAOIs. Which agent offers MAOI efficacy with a much lower hypertensive-crisis risk and no strict dietary restriction, because its enzyme inhibition is reversible?',
        options: ['Phenelzine', 'Tranylcypromine', 'Moclobemide', 'Isocarboxazid'],
        answer: 'Moclobemide',
        explanation: 'Moclobemide is a RIMA (reversible inhibitor of MAO-A). Because tyramine can competitively displace it from MAO-A, the hypertensive "cheese reaction" risk is low and no strict diet is required. It is available in Canada but not the US. Serotonin-syndrome contraindications still apply.',
        testedFact: 'Moclobemide = RIMA, reversible, minimal tyramine diet (Canada-specific)',
        source: { name: 'Moclobemide (Manerix) Canadian product monograph; CANMAT 2016 MDD', origin: 'monograph' },
      },
    ],
    _prov: MAOI_PROV,
  },

  selegiline: {
    pronunciation: 'seh-LEDGE-ih-leen',
    moa: 'Irreversible MAO-B–selective inhibitor at LOW dose (raises dopamine); loses selectivity and also inhibits MAO-A at HIGH or oral antidepressant doses (then serotonergic/tyramine risks apply).',
    receptorProfile: 'MAO-B selective (dopamine) at low dose. Transdermal patch bypasses first-pass gut/hepatic MAO-A, so low patch doses spare intestinal MAO-A → no tyramine diet at 6 mg/24h.',
    onsetOfEffect: 'Antidepressant effect (patch) over 2–4 wk; dopaminergic effect in Parkinson\'s is faster.',
    halfLife: 'Parent short (~1.5–2 h); active metabolites (l-amphetamine, l-methamphetamine) longer — can cause insomnia/activation.',
    metabolism: 'Hepatic (CYP2B6 and others) → l-amphetamine and l-methamphetamine metabolites. Inhibition of MAO-B is irreversible.',
    foodEffect: 'Oral capsule/tablet is affected by first-pass; the transdermal patch specifically AVOIDS first-pass, which is why low-dose patches skip the tyramine diet.',
    approvedCanada: ['Parkinson\'s disease (oral, adjunct to levodopa)'],
    offLabel: ['Major depressive disorder (transdermal patch — US-approved as Emsam; for awareness)'],
    approvedPopulations: 'Adults.',
    startingDose: 'Transdermal (depression): 6 mg/24 h patch — no dietary restriction at this dose. Oral (Parkinson\'s): 5 mg with breakfast and 5 mg with lunch (max 10 mg/day keeps MAO-B selectivity).',
    titration: 'Patch may be increased to 9 or 12 mg/24 h (dietary tyramine restriction then required); Parkinson\'s oral kept ≤10 mg/day.',
    maxDose: 'Transdermal 12 mg/24 h; oral 10 mg/day (higher oral doses lose MAO-B selectivity).',
    frequencyTiming: 'Patch once daily; oral doses earlier in the day (activating metabolites cause insomnia).',
    startStopCrossTaper: '14-day washout each way with serotonergics (5 weeks after fluoxetine), as for other MAOIs — the serotonin-syndrome contraindication applies regardless of dose/route.',
    administrationNotes: 'Transdermal route is the trick: skipping first-pass spares intestinal MAO-A so the 6 mg/24h patch needs no diet; 9–12 mg/24h reinstate the tyramine restriction.',
    commonSE: ['Application-site reaction (patch)', 'Insomnia (amphetamine metabolites)', 'Orthostatic hypotension', 'Headache', 'Dry mouth'],
    seriousAE: ['Serotonin syndrome (with serotonergics — at ANY dose/route)', 'Hypertensive crisis (with tyramine or sympathomimetics at higher patch/oral doses that inhibit MAO-A)'],
    syndromes: ['Serotonin syndrome', 'Hypertensive reaction (dose-dependent)', 'Orthostatic hypotension'],
    overdoseLethality: 'Overdose can lose MAO-B selectivity → hypertensive/hyperthermic crisis; dangerous, especially combined with serotonergics.',
    discontinuationSyndrome: 'Generally mild.',
    ongoingMonitoring: 'Blood pressure; sleep/activation; mood/suicidality; reinforce diet at 9–12 mg/24h patch or higher oral doses.',
    majorDDI: ['Serotonergics — SSRIs/SNRIs/TCAs, tramadol, meperidine, linezolid, dextromethorphan (serotonin syndrome, at any dose)', 'Sympathomimetics / decongestants (hypertensive risk, dose-dependent)', 'Other MAOIs', 'Opioids (meperidine/tramadol contraindicated)'],
    contraindicatedCombos: ['SSRIs/SNRIs/TCAs and other serotonergics', 'Meperidine (pethidine), tramadol, methadone, dextromethorphan', 'Linezolid, methylene blue', 'Sympathomimetics', 'Other MAOIs', 'Carbamazepine, oxcarbazepine (per patch label)'],
    maoiWashout: 'Stop serotonergic ≥14 days before selegiline and stop selegiline ≥14 days before a serotonergic (5 weeks after fluoxetine) — the serotonin-syndrome rule holds at every dose/route.',
    foodInteractions: 'Dose/route dependent: the 6 mg/24 h transdermal patch needs NO tyramine restriction (first-pass sparing preserves gut MAO-A). At 9–12 mg/24 h patch, or high oral doses that inhibit MAO-A, the STRICT low-tyramine diet (aged cheese, cured meats, tap beer, fermented soy, Marmite) applies.',
    pregnancy: 'Limited data; generally avoided in psychiatric use. Weigh untreated illness (CANMAT perinatal 2024).',
    lactation: 'Limited data; caution.',
    geriatric: 'Orthostatic hypotension and insomnia; use lower doses.',
    pearls: [
      'MAO-B selective at LOW dose (dopamine, used in Parkinson\'s); loses selectivity and inhibits MAO-A at high/oral antidepressant doses → then tyramine/serotonin risks return.',
      'The transdermal patch bypasses first-pass gut MAO-A, so the 6 mg/24 h dose needs no dietary restriction — a classic exam point; 9–12 mg/24 h reinstates the diet.',
      'Metabolised to l-amphetamine and l-methamphetamine → can cause insomnia and activation.',
      'Serotonin-syndrome contraindications apply at ANY dose/route (unlike the dose-dependent tyramine risk).',
    ],
    mnemonics: ['Selegiline "B for Brain-dopamine": MAO-B selective, used in Parkinson\'s; PATCH at low dose = no diet (skips the gut).'],
    confusables: ['Selegiline (MAO-B selective, Parkinson\'s + patch for depression) vs rasagiline (also MAO-B, Parkinson\'s, no amphetamine metabolites) vs phenelzine (non-selective MAO-A/B, antidepressant, strict diet).'],
    classDifferentiators: 'The MAO-B–selective, first-pass-sparing MAOI: low-dose oral/6 mg patch spares MAO-A (no diet), but selectivity is lost at higher doses; amphetamine metabolites distinguish it.',
    examHooks: ['Which MAOI at a low transdermal dose needs no tyramine diet, and why? (selegiline 6 mg/24h patch — bypasses first-pass gut MAO-A).', 'Which MAOI is MAO-B selective and yields amphetamine metabolites? (selegiline)'],
    counsellingPoints: [
      'At the 6 mg/24 h patch no special diet is required, but at 9 or 12 mg/24 h you must follow the low-tyramine diet.',
      'Apply the patch to clean, dry, intact skin; rotate sites; do not cut the patch.',
      'Never combine with other antidepressants, tramadol, meperidine or dextromethorphan (serotonin syndrome) at any dose.',
      'Report severe headache or high blood pressure (hypertensive reaction) at higher doses.',
    ],
    vignettes: [
      {
        stem: 'A patient is started on the 6 mg/24 h selegiline transdermal patch for depression and asks whether she must avoid aged cheese and cured meats. What is the correct advice and rationale?',
        options: [
          'Strict tyramine avoidance is required, as with all MAOIs',
          'No dietary restriction is needed at 6 mg/24 h because the patch bypasses first-pass intestinal MAO-A',
          'Tyramine is irrelevant to any MAOI',
          'She must avoid only serotonergic foods',
        ],
        answer: 'No dietary restriction is needed at 6 mg/24 h because the patch bypasses first-pass intestinal MAO-A',
        explanation: 'Transdermal selegiline avoids first-pass metabolism, sparing intestinal MAO-A that normally degrades dietary tyramine; at 6 mg/24 h no tyramine diet is required. At 9 and 12 mg/24 h, MAO-A inhibition increases and the low-tyramine diet is reinstated. Serotonin-syndrome drug contraindications still apply at every dose.',
        testedFact: 'Low-dose transdermal selegiline spares MAO-A → no tyramine diet',
        source: { name: 'openFDA/DailyMed selegiline transdermal (Emsam) label — dosing/dietary modifications', origin: 'openfda' },
      },
    ],
    _prov: MAOI_PROV,
  },
};
