// authored/mood.js — authored overlay for mood stabilizers & anticonvulsants used in bipolar.
//
// Mechanism/PK/dosing summaries + the pedagogical layer, grounded in established
// pharmacology and the fetched openFDA/monograph label sections. `_prov` declares which
// safety-critical fields the label text grounds; build.js attaches that source text and,
// where a field cannot be grounded, downgrades it to origin 'authored' + verifyFlag.
//
// Group theme: this is a HIGH-STAKES class. Three agents have genuine therapeutic drug
// monitoring (lithium, valproate, carbamazepine) — the only three with `therapeuticLevel`.
// Lithium is renally excreted (NOT metabolized) with a narrow index and unique anti-suicide
// evidence. Valproate and carbamazepine are teratogens (neural-tube defects); carbamazepine
// is a potent AUTOINDUCER. Lamotrigine is titrated SLOWLY to avoid SJS/TEN and is the
// bipolar-depression/maintenance agent. Gabapentin/pregabalin/topiramate are NOT primary
// mood stabilizers.

const MOOD_PROV = {
  startingDose: 'openfda', maxDose: 'openfda', seriousAE: 'openfda', syndromes: 'openfda',
  majorDDI: 'openfda', contraindicatedCombos: 'openfda', pregnancy: 'openfda',
  overdoseLethality: 'openfda', baselineWorkup: 'openfda', ongoingMonitoring: 'openfda',
};

// The three TDM agents also declare therapeuticLevel provenance.
const TDM_PROV = { ...MOOD_PROV, therapeuticLevel: 'monograph' };

export default {
  lithium: {
    pronunciation: 'LITH-ee-um',
    moa: 'Exact mechanism uncertain. Inhibits inositol monophosphatase (inositol-depletion hypothesis) and GSK-3β; modulates second-messenger signalling; neurotrophic/neuroprotective effects.',
    receptorProfile: 'Not a receptor ligand — acts intracellularly on second-messenger cascades; handled by the body like sodium.',
    onsetOfEffect: 'Antimanic effect over ~1–2 weeks; full prophylactic and anti-suicide benefit over months.',
    halfLife: '~18–24 hours (longer in the elderly and in renal impairment, up to ~36 h).',
    timeToSteadyState: '~5 days (recheck level ~5 days after any dose change).',
    metabolism: 'NOT metabolized — no hepatic/CYP involvement. Excreted unchanged by the kidney; reabsorbed in the proximal tubule in competition with sodium.',
    activeMetabolites: 'None (parent drug is the active moiety).',
    elimination: 'Renal, entirely as unchanged drug. Clearance falls with dehydration, low sodium, and reduced GFR.',
    foodEffect: 'May be taken with food to reduce GI upset; take consistently.',
    therapeuticLevel: '0.6–1.2 mmol/L (= mEq/L; identical numerically). Maintenance ~0.6–0.8; acute mania ~0.8–1.2. Draw a 12-hour post-dose trough. Toxicity begins ~>1.5 mmol/L; severe >2.0.',
    offLabel: ['Augmentation of antidepressants in treatment-resistant depression', 'Reduction of suicide risk'],
    approvedPopulations: 'Adults; used with caution and lower targets in the elderly.',
    startingDose: '300 mg PO BID–TID (e.g., 300 mg BID), guided by serum level.',
    titration: 'Adjust by ~300 mg increments guided by 12-h trough levels; recheck level ~5 days after each change.',
    maxDose: 'Titrated to target serum level; commonly 900–1200 mg/day, occasionally up to ~1800 mg/day.',
    frequencyTiming: 'Divided BID, or once-daily at bedtime for extended-release (once-daily dosing may lessen polyuria/renal load).',
    renalHepaticAdjustment: 'Reduce dose / avoid in renal impairment; no hepatic adjustment (not hepatically cleared).',
    startStopCrossTaper: 'Taper slowly on discontinuation — abrupt stop risks rebound mania and increased suicide risk.',
    administrationNotes: 'Hold and reassess during acute illness, dehydration, or before contrast/surgery. Counsel on steady salt and fluid intake.',
    commonSE: ['Fine tremor', 'Polyuria/polydipsia', 'GI upset (nausea, diarrhea)', 'Weight gain', 'Cognitive dulling', 'Acne/psoriasis flare', 'Metallic taste', 'Benign leukocytosis'],
    seriousAE: ['Lithium toxicity (narrow index)', 'Nephrogenic diabetes insipidus', 'Chronic interstitial nephritis / CKD', 'Hypothyroidism (and goiter)', 'Hyperparathyroidism / hypercalcemia', 'Cardiac conduction effects / sinus node dysfunction', 'Ebstein anomaly with in-utero exposure'],
    syndromes: ['Lithium toxicity (coarse tremor, ataxia, dysarthria, confusion, seizures)', 'SILENT (syndrome of irreversible lithium-effectuated neurotoxicity)', 'Nephrogenic diabetes insipidus', 'Hypothyroidism'],
    overdoseLethality: 'HIGH — narrow therapeutic index; toxicity is a medical emergency. Chronic toxicity is dangerous even at modestly elevated levels; hemodialysis for severe intoxication (e.g., level >4, or >2.5 with symptoms/renal failure).',
    discontinuationSyndrome: 'No physiologic withdrawal, but abrupt cessation causes rebound mania and heightened suicide risk — taper over weeks.',
    baselineWorkup: ['Renal function (creatinine, eGFR, urinalysis)', 'Electrolytes', 'TSH', 'Serum calcium', 'ECG (age >40 or cardiac risk)', 'Pregnancy test', 'Weight/BMI', 'CBC'],
    ongoingMonitoring: 'Serum level (12-h trough) ~5 days after start/change, then every 3–6 months once stable. Renal function, TSH, and calcium every 6–12 months (sooner if unstable).',
    majorDDI: ['NSAIDs — reduce renal clearance, raise level (toxicity)', 'Thiazide diuretics — raise level', 'ACE inhibitors / ARBs — raise level', 'Dehydration / low-sodium states — raise level', 'Metronidazole — raises level', 'Caffeine (heavy) — modestly lowers level'],
    contraindicatedCombos: ['Significant renal impairment', 'Volume depletion / severe hyponatremia', 'Caution with NSAIDs, thiazides, and ACEi/ARBs (toxicity)'],
    pregnancy: 'First-trimester exposure associated with Ebstein anomaly (tricuspid valve malformation); absolute risk is lower than historically taught. If continued, monitor levels closely (clearance rises in pregnancy then falls abruptly at delivery — toxicity risk) and arrange fetal echocardiography.',
    lactation: 'Excreted into breast milk; traditionally discouraged but can be used with close monitoring of the infant (levels, TSH, hydration).',
    geriatric: 'Lower targets and doses; reduced renal clearance narrows the window and increases neurotoxicity.',
    renalHepatic: 'Renally cleared — the kidney is the key organ; monitor eGFR long-term for chronic nephropathy.',
    cardiac: 'Benign T-wave flattening/inversion; caution in sick sinus syndrome / conduction disease.',
    pearls: [
      'The gold-standard mood stabilizer and the ONLY psychotropic with robust evidence for reducing suicide.',
      'Renally excreted and NOT metabolized — anything that lowers renal clearance (dehydration, NSAIDs, thiazides, ACEi/ARBs, low sodium) precipitates toxicity.',
      'Narrow therapeutic index: therapeutic 0.6–1.2, toxic >1.5 mmol/L — small changes matter.',
      'Chronic organ toxicity clusters at the kidney (nephrogenic DI, CKD), thyroid (hypothyroid), and parathyroid (hypercalcemia).',
    ],
    mnemonics: ['"LITH" harms: Leukocytosis (benign), Insipidus (nephrogenic DI), Tremor/Thyroid (hypothyroid)/Teratogen (Ebstein), Hypercalcemia (hyperparathyroid).'],
    confusables: ['Acute mania target (~0.8–1.2) vs maintenance target (~0.6–0.8) — draw a 12-h trough for both.', 'Nephrogenic DI (lithium blocks ADH at the collecting duct) vs central DI — lithium DI does NOT respond to desmopressin; amiloride helps.'],
    classDifferentiators: 'The only agent that is renally excreted (not metabolized), the only one with anti-suicide evidence, and the narrowest therapeutic index — toxicity is a true emergency.',
    examHooks: ['Which mood stabilizer reduces suicide? (lithium)', 'Which everyday drugs precipitate lithium toxicity? (NSAIDs, thiazides, ACEi/ARBs, dehydration, low salt)', 'Cardiac malformation with in-utero lithium? (Ebstein anomaly)'],
    counsellingPoints: ['Keep fluid and salt intake steady; seek care with vomiting, diarrhea, or fever (dehydration raises the level).', 'Avoid ibuprofen/NSAIDs unless cleared by your prescriber.', 'Regular blood tests (level, kidney, thyroid, calcium) are essential.', 'Report coarse tremor, slurred speech, unsteadiness, or confusion urgently.'],
    vignettes: [
      {
        stem: 'A 58-year-old on stable lithium is started on hydrochlorothiazide for hypertension. Two weeks later she has a coarse tremor, unsteady gait, slurred speech, and confusion. What best explains this?',
        options: ['A new cerebellar stroke', 'Reduced renal lithium clearance causing lithium toxicity', 'Serotonin syndrome', 'Hypothyroid myxedema'],
        answer: 'Reduced renal lithium clearance causing lithium toxicity',
        explanation: 'Thiazides increase proximal sodium (and thus lithium) reabsorption, raising the lithium level. Coarse tremor, ataxia, dysarthria, and confusion are classic toxicity signs; NSAIDs, ACEi/ARBs, and dehydration act similarly.',
        testedFact: 'Thiazide-precipitated lithium toxicity',
        source: { name: 'openFDA/DailyMed lithium label — drug interactions/warnings', origin: 'openfda' },
      },
    ],
    _prov: TDM_PROV,
  },

  valproate: {
    pronunciation: 'val-PROH-ate (divalproex, dye-VAL-proh-ex)',
    moa: 'Increases GABAergic transmission, blocks voltage-gated sodium channels, and modulates T-type calcium channels; also inhibits histone deacetylase. Broad-spectrum anticonvulsant and antimanic agent.',
    onsetOfEffect: 'Antimanic effect within ~1–2 weeks; can be loaded for rapid control of acute mania.',
    halfLife: '~9–16 hours.',
    timeToSteadyState: '~2–4 days.',
    metabolism: 'Hepatic — glucuronidation and mitochondrial β-oxidation, with minor CYP (2C9/2C19/2A6). A CYP2C9 and UGT/epoxide-hydrolase inhibitor. Highly protein-bound (~90%), saturable at higher levels.',
    proteinBinding: '~90% (saturable — free fraction rises at high total levels and in hypoalbuminemia).',
    therapeuticLevel: '350–700 µmol/L (SI) / 50–100 µg/mL (conventional). Acute mania sometimes targeted toward the upper end (up to ~125 µg/mL). Draw a trough.',
    offLabel: ['Migraine prophylaxis', 'Agitation/aggression', 'Adjunct in schizoaffective disorder'],
    approvedPopulations: 'Adults; avoid in females of childbearing potential where alternatives exist.',
    startingDose: '250–500 mg PO BID; acute mania may be loaded at ~20–30 mg/kg/day.',
    titration: 'Increase by ~250–500 mg every few days guided by level and response.',
    maxDose: '60 mg/kg/day.',
    frequencyTiming: 'Divided BID–TID; extended-release (divalproex ER) allows once-daily dosing.',
    renalHepaticAdjustment: 'Contraindicated in significant hepatic disease; caution in the elderly (higher free fraction).',
    startStopCrossTaper: 'Taper to avoid seizure/relapse; cross-taper when switching stabilizers.',
    commonSE: ['Weight gain', 'Tremor', 'Hair loss / alopecia (zinc/selenium may help)', 'GI upset', 'Sedation', 'Thrombocytopenia (dose-related)', 'Peripheral edema'],
    seriousAE: ['Hepatotoxicity (can be fatal; highest risk <2 y and polytherapy)', 'Pancreatitis', 'Hyperammonemic encephalopathy', 'Thrombocytopenia / platelet dysfunction', 'Teratogenicity (neural-tube defects, lowest IQ)', 'DRESS'],
    syndromes: ['Hyperammonemic encephalopathy (can occur with normal LFTs)', 'Valproate hepatotoxicity', 'Acute pancreatitis'],
    overdoseLethality: 'Moderate — CNS depression, cerebral edema, and hyperammonemia; L-carnitine is used for valproate-induced hyperammonemia; supportive care and, if severe, hemodialysis.',
    discontinuationSyndrome: 'Taper to avoid rebound seizures/mood relapse.',
    baselineWorkup: ['LFTs', 'CBC with platelets', 'Pregnancy test', 'Weight/BMI'],
    ongoingMonitoring: 'Serum level (trough); LFTs and CBC/platelets periodically, especially in the first 6 months; check ammonia if unexplained lethargy/encephalopathy.',
    majorDDI: ['Lamotrigine — valproate inhibits its glucuronidation, roughly DOUBLING lamotrigine levels (halve the lamotrigine dose; SJS risk)', 'Carbapenems (e.g., meropenem) — sharply drop valproate levels', 'Aspirin — displaces protein binding, raises free valproate', 'Enzyme inducers (carbamazepine, phenytoin) — lower valproate levels'],
    contraindicatedCombos: ['Hepatic disease / significant impairment', 'Urea cycle disorders', 'Mitochondrial disease (POLG mutations — risk of fatal hepatotoxicity)', 'Pregnancy (where alternatives exist)'],
    pregnancy: 'The MOST teratogenic mood stabilizer: neural-tube defects (spina bifida), craniofacial and cardiac malformations, and dose-dependent neurodevelopmental harm including the LOWEST childhood IQ and increased autism. Avoid in people who can become pregnant; if unavoidable, use high-dose folate and the lowest effective dose.',
    lactation: 'Low milk transfer; generally considered compatible (contrast with its pregnancy risk).',
    geriatric: 'Lower doses; higher free fraction and sedation risk.',
    renalHepatic: 'Hepatic clearance — the liver is the target organ for both metabolism and toxicity.',
    pearls: [
      'Teratogen with the LOWEST IQ and highest neural-tube-defect risk — the classic "avoid in anyone who could become pregnant" mood stabilizer.',
      'Doubles lamotrigine levels by inhibiting glucuronidation — always halve the lamotrigine dose when co-prescribing (SJS risk).',
      'Hyperammonemic encephalopathy can occur even with NORMAL liver enzymes — check ammonia, not just LFTs.',
      'Broad-spectrum antimanic agent; useful for mixed features and rapid cycling; can be loaded for acute mania.',
    ],
    mnemonics: ['"VALPROATE": Vomiting, Alopecia, Liver toxicity, Pancreatitis/Platelets↓, Retention of weight, Oedema, Ataxia/Ammonia, Tremor/Teratogen, Enzyme inhibitor.'],
    confusables: ['Valproate = weight GAIN and enzyme INHIBITOR; carbamazepine = weight-neutral and enzyme INDUCER — opposite CYP effects.', 'Both valproate and carbamazepine cause neural-tube defects, but valproate carries the worse neurodevelopmental/IQ risk.'],
    classDifferentiators: 'The broad-spectrum, loadable antimanic agent — but the worst teratogen and a CYP/glucuronidation inhibitor (raises lamotrigine), the mirror image of carbamazepine.',
    examHooks: ['Which mood stabilizer has the lowest fetal IQ and highest NTD risk? (valproate)', 'What happens to lamotrigine when valproate is added? (level doubles — halve the dose)', 'Encephalopathy with normal LFTs on valproate? (hyperammonemia)'],
    counsellingPoints: ['Not for use in pregnancy or if pregnancy is possible without reliable contraception and specialist discussion.', 'Report abdominal pain (pancreatitis), yellowing/severe fatigue (liver), or unusual bruising/bleeding.', 'Expect possible weight gain, tremor, and some hair thinning.'],
    vignettes: [
      {
        stem: 'A 24-year-old woman with bipolar I disorder who hopes to conceive next year needs maintenance pharmacotherapy. Which agent is most important to AVOID because of its teratogenic and neurodevelopmental profile?',
        options: ['Lamotrigine', 'Lithium', 'Valproate', 'Quetiapine'],
        answer: 'Valproate',
        explanation: 'Valproate carries the highest neural-tube-defect risk and the greatest dose-dependent reduction in childhood IQ (with increased autism), so it is avoided in people who can become pregnant when alternatives exist; lamotrigine is comparatively safer.',
        testedFact: 'Valproate teratogenicity / lowest fetal IQ',
        source: { name: 'openFDA/DailyMed valproate label — pregnancy/boxed warning', origin: 'openfda' },
      },
    ],
    _prov: TDM_PROV,
  },

  carbamazepine: {
    pronunciation: 'kar-buh-MAZ-uh-peen',
    moa: 'Blocks voltage-gated sodium channels in a use-dependent manner, stabilizing hyperexcitable neuronal membranes. Structurally tricyclic (related to TCAs).',
    onsetOfEffect: 'Antimanic effect over ~1–2 weeks (second-line vs lithium/valproate).',
    halfLife: 'Initially ~25–65 h; falls to ~12–17 h after autoinduction (over the first few weeks).',
    timeToSteadyState: '~3–5 days initially, but shifts as autoinduction develops over ~2–4 weeks.',
    metabolism: 'Hepatic CYP3A4 to the active carbamazepine-10,11-epoxide. POTENT AUTOINDUCER — induces CYP3A4 (and 1A2, 2C9, UGT, P-gp), so it accelerates its OWN metabolism and lowers its own level over 2–4 weeks; also a broad inducer of other drugs.',
    activeMetabolites: 'Carbamazepine-10,11-epoxide (active; contributes to toxicity).',
    therapeuticLevel: '17–51 µmol/L (SI) / 4–12 µg/mL (conventional). Recheck after ~2–4 weeks once autoinduction has lowered the level.',
    offLabel: ['Acute mania / maintenance (bipolar)', 'Impulsivity/aggression', 'Trigeminal neuralgia (an approved neurology use)'],
    approvedPopulations: 'Adults; screen at-risk ancestries before starting (see baseline workup).',
    startingDose: '200 mg PO BID.',
    titration: 'Increase by ~200 mg/day at weekly intervals to response/level; anticipate re-titration as autoinduction drops the level.',
    maxDose: '~1600 mg/day (occasionally higher under monitoring).',
    frequencyTiming: 'Divided BID–QID; extended-release allows BID dosing.',
    renalHepaticAdjustment: 'Caution/avoid in hepatic impairment; adjust for hyponatremia.',
    startStopCrossTaper: 'Taper to avoid rebound seizures; remember that stopping it REMOVES enzyme induction — co-medication levels (e.g., warfarin, OCPs) will rise.',
    commonSE: ['Dizziness', 'Ataxia', 'Diplopia', 'Sedation', 'Nausea', 'Hyponatremia'],
    seriousAE: ['Stevens–Johnson syndrome / TEN (HLA-B*1502)', 'Agranulocytosis / aplastic anemia', 'Hyponatremia / SIADH', 'Hepatotoxicity', 'DRESS (HLA-A*3101)', 'Cardiac conduction abnormalities'],
    syndromes: ['SJS/TEN', 'Agranulocytosis / aplastic anemia', 'SIADH / hyponatremia', 'DRESS'],
    overdoseLethality: 'Moderate–high — CNS depression, seizures, and sodium-channel-mediated cardiotoxicity (QRS widening, arrhythmia, similar to TCA overdose); coma. Supportive care; multiple-dose activated charcoal.',
    discontinuationSyndrome: 'Taper to avoid rebound seizures; expect rising levels of previously induced co-medications.',
    baselineWorkup: ['CBC', 'LFTs', 'Serum sodium/electrolytes', 'HLA-B*1502 genotyping in patients of Asian (esp. Han Chinese/Southeast Asian) ancestry', 'Pregnancy test', 'ECG if cardiac risk'],
    ongoingMonitoring: 'Serum level with a recheck at ~2–4 weeks (autoinduction); periodic CBC, LFTs, and sodium — sooner if symptomatic (fever/sore throat, rash, lethargy).',
    majorDDI: ['Oral contraceptives — induction lowers levels → contraceptive FAILURE (use a non-hormonal method)', 'Warfarin, many psychotropics, DOACs — levels fall via 3A4 induction', 'Clozapine — additive marrow suppression (avoid)', 'Grapefruit juice / 3A4 inhibitors — raise carbamazepine to toxic levels'],
    contraindicatedCombos: ['MAOIs (tricyclic structure — separate by ≥14 days)', 'Clozapine (agranulocytosis risk)', 'Pre-existing bone-marrow suppression', 'AV block', 'Nefazodone'],
    pregnancy: 'Teratogen — neural-tube defects (spina bifida) and craniofacial/cardiac malformations (less severe overall than valproate). Use high-dose folate; consider alternatives.',
    lactation: 'Generally considered compatible with monitoring of the infant.',
    geriatric: 'Higher hyponatremia and interaction burden; start low.',
    cardiac: 'Can impair AV conduction; caution with pre-existing block.',
    pearls: [
      'AUTOINDUCER — levels drop over the first 2–4 weeks as it speeds its own metabolism, so re-titrate and recheck the level at ~1 month.',
      'Screen HLA-B*1502 (Han Chinese / Southeast Asian ancestry) before starting — strong predictor of SJS/TEN; HLA-A*3101 predicts DRESS.',
      'Potent 3A4 inducer — a classic cause of oral-contraceptive failure and subtherapeutic warfarin.',
      'Tricyclic structure → 14-day MAOI separation, and TCA-like sodium-channel cardiotoxicity in overdose.',
    ],
    mnemonics: ['"Carba = Cs": CYP inducer, Contraceptive failure, Cytopenias (agranulocytosis/aplastic anemia), Cutaneous SJS (HLA-B*1502), and Cardiac/Na (autoinduction Cuts its own level).'],
    confusables: ['Carbamazepine (potent autoinducer, marrow suppression, HLA-B*1502) vs oxcarbazepine (weaker inducer, no active epoxide, MORE hyponatremia, less marrow monitoring).', 'SJS/TEN skin risk (HLA-B*1502) vs DRESS multi-organ risk (HLA-A*3101).'],
    classDifferentiators: 'The enzyme-INDUCING sodium-channel blocker whose level self-lowers (autoinduction); defined by HLA-linked SJS, marrow suppression, hyponatremia, and defeat of OCPs.',
    examHooks: ['Which mood stabilizer autoinduces and needs a repeat level at ~1 month? (carbamazepine)', 'Which HLA allele mandates screening before carbamazepine? (HLA-B*1502)', 'Why does an OCP fail on carbamazepine? (3A4 induction)'],
    counsellingPoints: ['Report fever, sore throat, mouth ulcers, easy bruising (blood counts), or any rash immediately.', 'Hormonal birth control may not work — use an additional/non-hormonal method.', 'Regular blood tests for counts, liver, and sodium are required.'],
    vignettes: [
      {
        stem: 'A 22-year-old man of Han Chinese ancestry is being considered for carbamazepine. Which pre-treatment test most reduces the risk of a life-threatening reaction?',
        options: ['Baseline ECG', 'HLA-B*1502 genotyping', 'G6PD level', 'Slit-lamp examination'],
        answer: 'HLA-B*1502 genotyping',
        explanation: 'HLA-B*1502 (prevalent in Han Chinese and Southeast Asian populations) strongly predisposes to carbamazepine-induced Stevens–Johnson syndrome / TEN; carriers should not receive the drug. Autoinduction separately mandates a repeat level at ~1 month.',
        testedFact: 'HLA-B*1502 screening before carbamazepine / SJS risk',
        source: { name: 'openFDA/DailyMed carbamazepine label — boxed warning (HLA-B*1502)', origin: 'openfda' },
      },
    ],
    _prov: TDM_PROV,
  },

  lamotrigine: {
    pronunciation: 'luh-MOH-truh-jeen',
    moa: 'Blocks voltage-gated sodium channels and inhibits presynaptic glutamate release, stabilizing neuronal membranes.',
    onsetOfEffect: 'Slow — because of the mandatory slow titration; used for maintenance and bipolar depression rather than acute mania.',
    halfLife: '~25–33 h as monotherapy; ~14 h with enzyme inducers; prolonged to ~60+ h when combined with valproate.',
    timeToSteadyState: '~5–7 days at a given dose (but titration spans weeks).',
    metabolism: 'Hepatic glucuronidation (UGT), NOT CYP. Valproate inhibits this (doubles the level); enzyme inducers, estrogen-containing OCPs, and pregnancy lower it.',
    activeMetabolites: 'None clinically significant.',
    offLabel: ['Adjunct in treatment-resistant depression', 'Borderline personality disorder mood instability'],
    approvedPopulations: 'Adults for bipolar maintenance; anticonvulsant use across ages.',
    startingDose: 'Monotherapy: 25 mg PO daily × 2 weeks. WITH valproate: 25 mg every other day (halved). Slow titration is critical to prevent SJS.',
    titration: 'SLOW: 25 mg/day ×2 wk → 50 mg/day ×2 wk → then increase by ~50 mg weekly toward 200 mg/day. Halve every step if on valproate; go faster/higher with inducers. Restart the full titration if doses are missed for >5 days.',
    maxDose: '~200 mg/day for bipolar monotherapy (≈100 mg/day with valproate; up to ~400 mg/day with inducers).',
    frequencyTiming: 'Once or twice daily.',
    renalHepaticAdjustment: 'Reduce in significant hepatic impairment.',
    startStopCrossTaper: 'Taper to reduce seizure risk; if restarting after a gap >5 days, re-titrate from the beginning.',
    commonSE: ['Headache', 'Dizziness', 'Benign rash', 'Nausea', 'Insomnia', 'Diplopia', 'Tremor'],
    seriousAE: ['Stevens–Johnson syndrome / TEN (esp. with fast titration or valproate co-therapy)', 'DRESS', 'Aseptic meningitis', 'Hemophagocytic lymphohistiocytosis (rare)'],
    syndromes: ['SJS/TEN', 'DRESS'],
    overdoseLethality: 'Relatively low; large ingestions can cause seizures, QRS widening, and coma.',
    discontinuationSyndrome: 'Taper to avoid rebound seizure/mood relapse.',
    baselineWorkup: ['No routine bloodwork required — counsel thoroughly on rash and the slow titration schedule'],
    ongoingMonitoring: 'Clinical monitoring for rash/hypersensitivity; no routine serum level. In pregnancy, levels fall substantially — monitor and increase as needed, then reduce postpartum to avoid toxicity.',
    majorDDI: ['Valproate — DOUBLES the lamotrigine level (halve the dose; SJS risk)', 'Carbamazepine / phenytoin / rifampin — induce glucuronidation and LOWER the level', 'Estrogen-containing oral contraceptives — lower the level ~50% (and it rises during the pill-free week)', 'Pregnancy — lowers the level'],
    contraindicatedCombos: ['No absolute drug contraindication; exercise heightened caution and dose-halving with valproate'],
    pregnancy: 'Comparatively pregnancy-SAFER — no consistent major teratogenic signal; often a preferred maintenance stabilizer in pregnancy. Note that levels fall markedly during pregnancy (may need dose increases) and must be reduced postpartum.',
    lactation: 'Passes into milk in measurable amounts; can be used with infant monitoring.',
    geriatric: 'Well tolerated; standard slow titration still applies.',
    pearls: [
      'Agent for bipolar DEPRESSION and MAINTENANCE — not effective for acute mania.',
      'The SLOW titration exists to prevent SJS/TEN — never front-load, and restart from scratch after a >5-day gap.',
      'Valproate doubles the level (halve the dose); carbamazepine and estrogen-containing OCPs lower it.',
      'No routine serum level; pregnancy dramatically lowers levels (adjust up antenatally, down postpartum).',
    ],
    mnemonics: ['"Lamotrigine — LOW and SLOW" to avoid the rash; and "VALproate → VALue doubles" (halve the lamotrigine dose).'],
    confusables: ['Lamotrigine = bipolar DEPRESSION/maintenance; lithium/valproate = better for MANIA.', 'Direction of the valproate interaction: valproate RAISES lamotrigine (glucuronidation inhibition), whereas carbamazepine LOWERS it (induction).'],
    classDifferentiators: 'The maintenance/anti-depressive stabilizer with the best pregnancy profile and no routine levels — defined by slow titration to avoid SJS and by opposite interactions with valproate (up) vs carbamazepine (down).',
    examHooks: ['Which stabilizer is best for bipolar depression and pregnancy? (lamotrigine)', 'Why halve lamotrigine when adding valproate? (glucuronidation inhibition doubles the level → SJS)', 'What must you do if lamotrigine is missed for >5 days? (re-titrate from the start)'],
    counsellingPoints: ['Follow the slow dose schedule exactly — do not speed it up.', 'Report ANY rash, especially with fever, mouth/eye involvement, or swelling — seek care urgently.', 'Tell your prescriber before starting or stopping birth control pills or valproate (doses may need to change).'],
    vignettes: [
      {
        stem: 'A patient stabilized on valproate for bipolar I is started on lamotrigine for depressive episodes. Compared with lamotrigine monotherapy, how should the lamotrigine be dosed?',
        options: ['Doubled, because valproate lowers lamotrigine levels', 'Halved and titrated more slowly, because valproate roughly doubles lamotrigine levels', 'Unchanged — no interaction exists', 'Started at the full target dose to speed response'],
        answer: 'Halved and titrated more slowly, because valproate roughly doubles lamotrigine levels',
        explanation: 'Valproate inhibits lamotrigine glucuronidation, roughly doubling its concentration and markedly increasing SJS/TEN risk. Lamotrigine must be halved and titrated even more slowly when co-prescribed with valproate.',
        testedFact: 'Valproate–lamotrigine glucuronidation interaction (halve the dose)',
        source: { name: 'openFDA/DailyMed lamotrigine label — dosing with valproate/boxed warning', origin: 'openfda' },
      },
    ],
    _prov: MOOD_PROV,
  },

  oxcarbazepine: {
    pronunciation: 'ox-kar-BAZ-uh-peen',
    moa: 'Blocks voltage-gated sodium channels; the keto-analog of carbamazepine and a prodrug rapidly reduced to the active 10-monohydroxy derivative (MHD / licarbazepine).',
    onsetOfEffect: 'Days to weeks; mood evidence is weaker than for carbamazepine.',
    halfLife: 'Active MHD ~9 hours.',
    timeToSteadyState: '~2–3 days.',
    metabolism: 'Reductive metabolism to MHD (bypasses the carbamazepine epoxide pathway → no active epoxide, better tolerated). Weaker CYP3A4 inducer than carbamazepine with little autoinduction; inhibits CYP2C19.',
    activeMetabolites: 'Monohydroxy derivative (MHD / licarbazepine) — the active moiety.',
    offLabel: ['Bipolar disorder (weaker evidence than carbamazepine)', 'Trigeminal neuralgia', 'Impulsivity/aggression'],
    approvedPopulations: 'Adults; anticonvulsant use across ages.',
    startingDose: '300 mg PO BID.',
    titration: 'Increase by ~300–600 mg/day at weekly intervals.',
    maxDose: '~1200–2400 mg/day depending on indication.',
    frequencyTiming: 'Divided BID.',
    renalHepaticAdjustment: 'Reduce dose in renal impairment (MHD renally cleared).',
    startStopCrossTaper: 'Taper to avoid rebound seizures.',
    commonSE: ['Hyponatremia (more common than with carbamazepine)', 'Dizziness', 'Sedation', 'Diplopia', 'Nausea', 'Ataxia'],
    seriousAE: ['Clinically significant hyponatremia / SIADH', 'SJS/TEN (HLA-B*1502-associated, cross-risk with carbamazepine)', 'Anaphylaxis/angioedema', 'DRESS'],
    syndromes: ['Hyponatremia / SIADH', 'SJS/TEN'],
    overdoseLethality: 'Relatively low; CNS depression and hyponatremia predominate.',
    discontinuationSyndrome: 'Taper to avoid rebound seizures.',
    baselineWorkup: ['Serum sodium', 'Consider HLA-B*1502 in at-risk ancestry (cross-reactivity with carbamazepine)', 'Pregnancy test'],
    ongoingMonitoring: 'Serum sodium (particularly in the first 3 months, the elderly, and those on diuretics); less hematologic monitoring than carbamazepine.',
    majorDDI: ['Oral contraceptives — still reduced (weaker induction than carbamazepine, but contraceptive efficacy can fall)', 'Phenytoin — raised via CYP2C19 inhibition', 'Other hyponatremia-inducing drugs (diuretics, SSRIs) — additive'],
    contraindicatedCombos: ['Caution with other sodium-lowering agents', '~25–30% cross-hypersensitivity in patients with carbamazepine allergy'],
    pregnancy: 'Less data than carbamazepine; presumed teratogenic potential — not first-line in pregnancy.',
    lactation: 'Limited data; monitor the infant if used.',
    geriatric: 'Higher hyponatremia risk — monitor sodium.',
    pearls: [
      'Keto-analog of carbamazepine: no active epoxide → better tolerated and far less marrow monitoring.',
      'Hyponatremia is MORE common than with carbamazepine — check sodium, especially early and in the elderly/diuretic users.',
      'Less autoinduction and a lighter interaction burden, but weaker evidence as a mood stabilizer (off-label, not first-line).',
      'About a quarter of patients allergic to carbamazepine will cross-react.',
    ],
    mnemonics: ['"Ox loses salt" — Oxcarbazepine → more hypoNatremia than carbamazepine.'],
    confusables: ['Oxcarbazepine (more hyponatremia, no epoxide, less marrow suppression, weaker mood evidence) vs carbamazepine (potent autoinducer, agranulocytosis/aplastic anemia).'],
    classDifferentiators: 'A better-tolerated carbamazepine cousin — fewer blood dyscrasias and less autoinduction, but MORE hyponatremia and weaker mood-stabilizer evidence.',
    examHooks: ['Which agent causes hyponatremia more often than carbamazepine? (oxcarbazepine)', 'Why is oxcarbazepine better tolerated than carbamazepine? (no active epoxide, less autoinduction/marrow toxicity)'],
    counsellingPoints: ['Report headache, nausea, confusion, or new unsteadiness (possible low sodium).', 'Hormonal contraception may be less reliable — discuss backup methods.', 'Tell your prescriber if you have ever reacted to carbamazepine.'],
    vignettes: [
      {
        stem: 'Compared with carbamazepine, which adverse effect is MORE frequent with oxcarbazepine?',
        options: ['Aplastic anemia', 'Hyponatremia', 'Autoinduction of its own metabolism', 'HLA-B*1502-independent SJS'],
        answer: 'Hyponatremia',
        explanation: 'Oxcarbazepine causes clinically significant hyponatremia more often than carbamazepine, while producing less autoinduction and fewer blood dyscrasias (no active epoxide metabolite).',
        testedFact: 'Oxcarbazepine hyponatremia > carbamazepine',
        source: { name: 'openFDA/DailyMed oxcarbazepine label — warnings (hyponatremia)', origin: 'openfda' },
      },
    ],
    _prov: MOOD_PROV,
  },

  gabapentin: {
    pronunciation: 'GAB-uh-pen-tin',
    moa: 'Binds the α2δ subunit of voltage-gated calcium channels, reducing excitatory neurotransmitter release. Despite the name, it does NOT act at GABA receptors.',
    onsetOfEffect: 'Days for anxiolytic/adjunctive effects.',
    halfLife: '~5–7 hours.',
    timeToSteadyState: '~1–2 days.',
    metabolism: 'NOT metabolized — excreted unchanged by the kidney; no CYP involvement. Absorption is saturable/nonlinear (bioavailability falls at higher doses).',
    activeMetabolites: 'None.',
    elimination: 'Renal, as unchanged drug.',
    offLabel: ['Generalized anxiety / adjunctive anxiety', 'Insomnia', 'Alcohol use disorder', 'Neuropathic pain (an approved neurology use)'],
    approvedPopulations: 'Adults.',
    startingDose: '300 mg PO (often 300 mg at bedtime on day 1), titrating upward.',
    titration: 'Increase to 300 mg TID over days, then further as tolerated/needed.',
    maxDose: '~3600 mg/day in divided doses (TID).',
    frequencyTiming: 'TID (short half-life).',
    renalHepaticAdjustment: 'Renal dose reduction required (renally cleared); no hepatic adjustment.',
    startStopCrossTaper: 'Taper — abrupt discontinuation can cause anxiety/agitation and (rarely) withdrawal seizures.',
    commonSE: ['Sedation', 'Dizziness', 'Ataxia', 'Peripheral edema', 'Weight gain'],
    seriousAE: ['Respiratory depression when combined with opioids/CNS depressants', 'Misuse / dependence', 'DRESS (rare)'],
    syndromes: ['Misuse/dependence', 'CNS-depressant respiratory depression'],
    overdoseLethality: 'Low when taken alone; the danger is additive respiratory depression with opioids or other CNS depressants.',
    discontinuationSyndrome: 'Taper to avoid rebound anxiety/insomnia and rare withdrawal seizures.',
    baselineWorkup: ['Renal function (guides dosing)'],
    ongoingMonitoring: 'Renal function; sedation and, given misuse potential, signs of escalation/diversion.',
    majorDDI: ['Opioids / CNS depressants — additive sedation and respiratory depression', 'Aluminum/magnesium antacids — reduce absorption (separate by ~2 hours)'],
    contraindicatedCombos: ['Caution (not absolute) with opioids and other CNS depressants — respiratory depression'],
    pregnancy: 'Limited data; use only if clearly needed.',
    lactation: 'Excreted in milk in small amounts; often considered compatible with monitoring.',
    geriatric: 'Reduce dose for renal decline; watch sedation, falls, and edema.',
    renalHepatic: 'Renally cleared — dose to renal function; a clean choice when CYP interactions must be avoided.',
    pearls: [
      'NOT a primary mood stabilizer — negative bipolar RCTs; used adjunctively for anxiety, sleep, or pain.',
      'Renally excreted with NO CYP metabolism → a clean interaction profile (useful when polypharmacy/CYP issues matter).',
      'Recognized misuse potential (increasingly monitored/scheduled in some jurisdictions), and respiratory depression when combined with opioids.',
      'The α2δ calcium-channel mechanism is shared with pregabalin — the name is misleading (no GABA-receptor activity).',
    ],
    mnemonics: ['"GabapentIN → kidney IN, liver OUT" — renally cleared, no CYP.'],
    confusables: ['Gabapentin/pregabalin (α2δ calcium-channel ligands) vs benzodiazepines/GABA drugs — different mechanism despite "GABA" in the name.', 'Gabapentin (nonlinear, saturable absorption, TID) vs pregabalin (linear kinetics, more potent).'],
    classDifferentiators: 'A renally cleared α2δ ligand with no CYP interactions — an anxiety/sleep/pain adjunct, explicitly NOT a bipolar mood stabilizer.',
    examHooks: ['Is gabapentin an effective mood stabilizer? (no — negative bipolar trials)', 'How is gabapentin eliminated? (renally, unchanged — no CYP)', 'What raises overdose risk with gabapentin? (co-administered opioids/CNS depressants)'],
    counsellingPoints: ['Do not combine with opioids, sleeping pills, or heavy alcohol without medical advice (breathing risk).', 'Separate from antacids by a couple of hours.', 'Do not stop abruptly; taper with your prescriber.'],
    vignettes: [
      {
        stem: 'A patient with bipolar disorder asks whether gabapentin can serve as their primary mood stabilizer. What is the best evidence-based response?',
        options: ['Yes — it is first-line for mania', 'No — controlled trials do not support gabapentin as a primary mood stabilizer; it is used adjunctively for anxiety/sleep/pain', 'Yes — it is superior to lithium for maintenance', 'Only if the lithium level is subtherapeutic'],
        answer: 'No — controlled trials do not support gabapentin as a primary mood stabilizer; it is used adjunctively for anxiety/sleep/pain',
        explanation: 'Randomized trials failed to show efficacy for gabapentin in bipolar disorder; it has a role only as an adjunct (anxiety, sleep, pain). It is renally cleared with no CYP metabolism.',
        testedFact: 'Gabapentin is not a primary mood stabilizer',
        source: { name: 'CANMAT/ISBD bipolar guidance; gabapentin bipolar RCTs', origin: 'canmat' },
      },
    ],
    _prov: MOOD_PROV,
  },

  pregabalin: {
    pronunciation: 'pre-GAB-uh-lin',
    moa: 'Binds the α2δ subunit of voltage-gated calcium channels (like gabapentin), reducing excitatory neurotransmitter release; more potent with linear kinetics.',
    onsetOfEffect: 'Anxiolytic effect within about a week (faster than SSRIs for GAD).',
    halfLife: '~6 hours.',
    timeToSteadyState: '~1–2 days.',
    metabolism: 'Negligible metabolism — excreted essentially unchanged by the kidney; no CYP. Linear, predictable pharmacokinetics.',
    activeMetabolites: 'None.',
    elimination: 'Renal, as unchanged drug.',
    offLabel: ['Generalized anxiety disorder (approved in Europe; used off-label for anxiety elsewhere)', 'Insomnia adjunct'],
    approvedPopulations: 'Adults.',
    startingDose: '75 mg PO BID (or 150 mg/day divided).',
    titration: 'Increase to 150 mg BID within a week; up to 300 mg BID as needed.',
    maxDose: '600 mg/day.',
    frequencyTiming: 'BID (short half-life).',
    renalHepaticAdjustment: 'Renal dose reduction required (renally cleared); no hepatic adjustment.',
    startStopCrossTaper: 'Taper over ≥1 week — abrupt stop causes withdrawal (anxiety, insomnia, sweating).',
    commonSE: ['Dizziness', 'Sedation', 'Peripheral edema', 'Weight gain', 'Blurred vision', 'Euphoria'],
    seriousAE: ['Respiratory depression with opioids/CNS depressants', 'Misuse / dependence (controlled in some jurisdictions)', 'Angioedema'],
    syndromes: ['Misuse/dependence', 'CNS-depressant respiratory depression'],
    overdoseLethality: 'Low when taken alone; additive respiratory depression with opioids/CNS depressants is the main risk.',
    discontinuationSyndrome: 'Taper — abrupt cessation causes a withdrawal syndrome.',
    baselineWorkup: ['Renal function (guides dosing)'],
    ongoingMonitoring: 'Renal function; edema/weight; and, given misuse potential, signs of escalation/diversion.',
    majorDDI: ['Opioids / CNS depressants — additive sedation and respiratory depression'],
    contraindicatedCombos: ['Caution (not absolute) with opioids and other CNS depressants — respiratory depression'],
    pregnancy: 'Limited data with some signal of possible harm — avoid if possible.',
    lactation: 'Limited data; use with caution and infant monitoring.',
    geriatric: 'Reduce dose for renal decline; watch sedation, falls, and edema.',
    renalHepatic: 'Renally cleared — dose to renal function; clean of CYP interactions.',
    pearls: [
      'Has GAD approval (Europe) with genuine anti-anxiety efficacy and a faster onset than SSRIs — but it is an anxiolytic, NOT a bipolar mood stabilizer.',
      'Renally excreted with NO CYP metabolism and linear kinetics — clean and predictable interactions.',
      'Recognized misuse/dependence potential (scheduled/controlled in several jurisdictions); respiratory depression when combined with opioids.',
      'More potent than gabapentin with more reliable (linear) absorption.',
    ],
    mnemonics: ['"Pregabalin = Potent, Predictable (linear), Peripheral edema — and Prone to misuse."'],
    confusables: ['Pregabalin (linear kinetics, more potent, GAD-approved in Europe) vs gabapentin (nonlinear/saturable absorption).', 'α2δ ligands treat anxiety/pain — they are NOT antimanic mood stabilizers.'],
    classDifferentiators: 'The α2δ ligand with formal anxiety (GAD) approval and clean renal clearance — an anxiolytic role, not a mood-stabilizing one; more potent and linear than gabapentin.',
    examHooks: ['Which α2δ agent is approved for GAD (Europe)? (pregabalin)', 'How is pregabalin eliminated? (renally, unchanged — no CYP)', 'What limits its role in bipolar disorder? (it is an anxiolytic, not a mood stabilizer, with misuse potential)'],
    counsellingPoints: ['Do not combine with opioids, sedatives, or heavy alcohol without medical advice (breathing risk).', 'Do not stop suddenly — taper with your prescriber.', 'Report swelling of the face/lips or difficulty breathing (angioedema).'],
    vignettes: [
      {
        stem: 'A 30-year-old with generalized anxiety disorder and impaired hepatic function needs an anxiolytic with minimal CYP-mediated interactions. Which agent fits, and how is it cleared?',
        options: ['Diazepam — hepatic oxidation', 'Pregabalin — renal excretion, essentially unchanged', 'Carbamazepine — hepatic autoinduction', 'Valproate — hepatic glucuronidation'],
        answer: 'Pregabalin — renal excretion, essentially unchanged',
        explanation: 'Pregabalin is an α2δ ligand with efficacy in GAD, is excreted renally as unchanged drug with negligible metabolism, and has no CYP interactions — advantageous in hepatic impairment. It is an anxiolytic, not a bipolar mood stabilizer.',
        testedFact: 'Pregabalin GAD use and renal clearance',
        source: { name: 'openFDA/DailyMed pregabalin label — clinical pharmacology/elimination', origin: 'openfda' },
      },
    ],
    _prov: MOOD_PROV,
  },

  topiramate: {
    pronunciation: 'toh-PYRE-uh-mate',
    moa: 'Multiple actions: blocks voltage-gated sodium channels, potentiates GABA-A, antagonizes AMPA/kainate glutamate receptors, and weakly inhibits carbonic anhydrase.',
    onsetOfEffect: 'Weeks; used for weight mitigation, migraine, and off-label AUD rather than as a mood stabilizer.',
    halfLife: '~21 hours.',
    timeToSteadyState: '~4–5 days.',
    metabolism: 'Mostly excreted unchanged by the kidney (~70%); limited hepatic metabolism. Weak CYP3A4 inducer at higher doses; inhibits CYP2C19.',
    activeMetabolites: 'None clinically significant.',
    elimination: 'Predominantly renal, as unchanged drug.',
    offLabel: ['Weight-gain mitigation with other psychotropics', 'Alcohol use disorder', 'Binge-eating disorder', 'Migraine prophylaxis (an approved neurology use)'],
    approvedPopulations: 'Adults.',
    startingDose: '25–50 mg/day, titrated slowly.',
    titration: 'Increase by ~25–50 mg/week (slow titration reduces cognitive/CNS effects).',
    maxDose: '~400 mg/day.',
    frequencyTiming: 'Divided BID.',
    renalHepaticAdjustment: 'Reduce dose in renal impairment (renally cleared).',
    startStopCrossTaper: 'Taper to avoid rebound seizures.',
    commonSE: ['Weight LOSS', 'Cognitive slowing / word-finding difficulty ("dopamax")', 'Paresthesia', 'Fatigue', 'Taste changes (carbonated drinks taste flat)', 'Anorexia'],
    seriousAE: ['Metabolic (non-anion-gap) acidosis', 'Nephrolithiasis (calcium phosphate stones)', 'Acute angle-closure glaucoma (idiosyncratic, usually first month)', 'Oligohidrosis / hyperthermia (esp. children)', 'Hyperammonemia (with valproate)'],
    syndromes: ['Metabolic acidosis', 'Acute angle-closure glaucoma', 'Nephrolithiasis', 'Oligohidrosis'],
    overdoseLethality: 'Low–moderate; metabolic acidosis and CNS depression predominate.',
    discontinuationSyndrome: 'Taper to avoid rebound seizures.',
    baselineWorkup: ['Consider serum bicarbonate (metabolic acidosis)', 'Pregnancy test'],
    ongoingMonitoring: 'Serum bicarbonate for metabolic acidosis; ensure hydration to reduce stone risk; watch for visual symptoms early.',
    majorDDI: ['Other carbonic-anhydrase inhibitors (e.g., acetazolamide) — additive acidosis/stone risk', 'CNS depressants — additive sedation', 'Oral contraceptives — efficacy reduced at higher doses (>200 mg/day)', 'Valproate — hyperammonemia/encephalopathy and hypothermia'],
    contraindicatedCombos: ['Caution with other carbonic-anhydrase inhibitors', 'Caution combining with valproate (hyperammonemia)'],
    pregnancy: 'Teratogen — oral clefts (cleft lip/palate) and reduced fetal growth; also reduces oral-contraceptive efficacy, so counsel on reliable contraception.',
    lactation: 'Excreted in milk; use with infant monitoring.',
    geriatric: 'Reduce for renal decline; cognitive effects may be pronounced.',
    renalHepatic: 'Renally cleared — dose to renal function.',
    pearls: [
      'NOT a primary mood stabilizer — used for weight mitigation, migraine prophylaxis, and off-label alcohol/binge-eating disorder.',
      'The weight-LOSS anticonvulsant (contrast lithium/valproate, which cause weight GAIN).',
      'Carbonic-anhydrase inhibition explains the cluster: paresthesia, metabolic acidosis, calcium-phosphate kidney stones, and (idiosyncratically) acute angle-closure glaucoma.',
      'Cognitive "dulling"/word-finding difficulty ("dopamax") and reduced OCP efficacy + oral clefts in pregnancy.',
    ],
    mnemonics: ['"Topiramate = SKINNY & STUPID STONES": weight loss (Skinny), cognitive dulling (Stupid/word-finding), kidney Stones + acidosis + glaucoma + oligohidrosis (less Sweat).'],
    confusables: ['Topiramate = weight LOSS; lithium/valproate/gabapentin/pregabalin = weight GAIN.', 'Topiramate paresthesia/acidosis/stones/glaucoma all stem from carbonic-anhydrase inhibition — a single unifying mechanism.'],
    classDifferentiators: 'Not a mood stabilizer — the weight-LOSS, carbonic-anhydrase-inhibiting agent (stones, acidosis, glaucoma, cognitive dulling) used for migraine/AUD and to offset drug-induced weight gain.',
    examHooks: ['Which of these agents causes weight LOSS? (topiramate)', 'Acute painful red eye with vision loss weeks after starting an anticonvulsant? (topiramate — acute angle-closure glaucoma)', 'Which mechanism explains topiramate paresthesia/stones/acidosis? (carbonic-anhydrase inhibition)'],
    counsellingPoints: ['Drink plenty of fluids to reduce kidney-stone risk.', 'Report sudden eye pain, redness, or blurred vision urgently (glaucoma).', 'Birth control pills may be less effective at higher doses — discuss backup contraception.', 'Expect possible tingling, appetite/weight loss, and word-finding difficulty.'],
    vignettes: [
      {
        stem: 'A patient started on topiramate for migraine and weight-neutral mood support presents on day 20 with acute bilateral eye pain, blurred vision, and headache. Intraocular pressure is elevated. What is the most likely diagnosis?',
        options: ['Optic neuritis', 'Acute angle-closure glaucoma', 'Central retinal vein occlusion', 'Cluster headache'],
        answer: 'Acute angle-closure glaucoma',
        explanation: 'Topiramate can cause an idiosyncratic acute (usually bilateral) angle-closure glaucoma, typically within the first month, from ciliary body effusion — a medical emergency requiring drug discontinuation and ophthalmologic care. Note topiramate is not a primary mood stabilizer.',
        testedFact: 'Topiramate acute angle-closure glaucoma',
        source: { name: 'openFDA/DailyMed topiramate label — warnings (angle-closure glaucoma)', origin: 'openfda' },
      },
    ],
    _prov: MOOD_PROV,
  },
};
