// authored/sga.js — authored overlay for the second-generation (atypical) antipsychotics.
//
// Mechanism/PK/dosing summaries + the pedagogical layer, grounded in established
// pharmacology and the fetched openFDA/monograph label sections. `_prov` declares which
// safety-critical fields the label text grounds; build.js attaches that source text and,
// where a field cannot be grounded, downgrades it to origin 'authored' + verifyFlag.
//
// SGA class theme: combined 5-HT2A + D2 antagonism (or D2 PARTIAL agonism for the
// "-pip/-raz" agents: aripiprazole, brexpiprazole, cariprazine) → FEWER EPS/tardive
// dyskinesia than the FGAs, BUT the dominant class harm is METABOLIC SYNDROME (weight gain,
// dyslipidemia, insulin resistance/T2DM). Metabolic burden is worst with clozapine and
// olanzapine; intermediate with quetiapine/risperidone/paliperidone/asenapine/brexpiprazole;
// favourable (weight-/lipid-neutral) with aripiprazole, ziprasidone, lurasidone, cariprazine.
// Every agent needs metabolic monitoring (weight/BMI/waist, fasting glucose or HbA1c, lipids,
// BP) at baseline and on follow-up. Other class syndromes: NMS, tardive dyskinesia (less than
// FGA), hyperprolactinemia (risperidone/paliperidone worst), QT prolongation (ziprasidone
// worst). Clozapine is the highest-yield card: uniquely effective in treatment-RESISTANT
// schizophrenia and to reduce suicidality, but demands registry ANC monitoring for
// agranulocytosis, plus myocarditis, seizure, and severe-constipation/ileus surveillance.

const SGA_PROV = {
  startingDose: 'openfda', maxDose: 'openfda', seriousAE: 'openfda', syndromes: 'openfda',
  majorDDI: 'openfda', contraindicatedCombos: 'openfda', pregnancy: 'openfda',
  overdoseLethality: 'openfda', baselineWorkup: 'openfda', ongoingMonitoring: 'openfda',
};

export default {
  risperidone: {
    pronunciation: 'ris-PER-i-done',
    moa: 'Combined 5-HT2A and D2 receptor antagonist; the most D2-potent of the SGAs.',
    receptorProfile: 'High D2 and 5-HT2A affinity; α1/α2 and H1 antagonism; minimal muscarinic. High D2 potency drives dose-dependent EPS and hyperprolactinemia.',
    onsetOfEffect: 'Antipsychotic effect over days–weeks; full effect ~2–4 wk.',
    halfLife: 'Risperidone ~3 h; active metabolite 9-hydroxyrisperidone (paliperidone) ~21–24 h → "active moiety" ~20 h.',
    timeToSteadyState: '~1 day orally; LAI (Consta) requires 3 weeks of oral overlap and reaches steady state ~4–6 wk.',
    metabolism: 'Hepatic CYP2D6 → 9-hydroxyrisperidone (active). CYP2D6 poor metabolizers / inhibitors raise the parent level.',
    activeMetabolites: '9-hydroxyrisperidone (= paliperidone), active.',
    elimination: 'Renal (the active 9-OH moiety is renally cleared) — reduce dose in renal impairment.',
    foodEffect: 'May be taken with or without food.',
    approvedCanada: ['Schizophrenia', 'Bipolar I mania (acute)', 'Irritability/aggression associated with autism (pediatric)'],
    offLabel: ['Augmentation in treatment-resistant OCD/depression', 'Tics/Tourette'],
    approvedPopulations: 'Adults; children/adolescents for autism-associated irritability.',
    startingDose: '1–2 mg/day PO (0.5 mg BID in elderly/renal/hepatic).',
    titration: 'Increase by 1–2 mg/day at ≥24 h intervals; usual target 4–6 mg/day.',
    maxDose: '8 mg/day (little added benefit and more EPS above ~6 mg).',
    frequencyTiming: 'Once daily or divided BID; may dose at bedtime for sedation.',
    renalHepaticAdjustment: 'Start 0.5 mg BID and titrate slowly in significant renal or hepatic impairment (active moiety renally cleared).',
    startStopCrossTaper: 'Taper to switch; when converting to Consta LAI, continue oral for 3 weeks after the first injection.',
    administrationNotes: 'LAI Consta given IM every 2 weeks (requires 3-week oral overlap after first dose).',
    commonSE: ['Dose-dependent EPS', 'Akathisia', 'Hyperprolactinemia (galactorrhea, amenorrhea, gynecomastia, sexual dysfunction)', 'Sedation', 'Orthostatic hypotension', 'Weight gain (moderate)'],
    seriousAE: ['Neuroleptic malignant syndrome', 'Tardive dyskinesia', 'Marked hyperprolactinemia', 'Metabolic changes (weight/glucose/lipids, moderate)', 'Orthostasis/syncope', 'Increased mortality and cerebrovascular events in elderly dementia patients'],
    syndromes: ['EPS', 'Tardive dyskinesia', 'NMS', 'Hyperprolactinemia', 'Metabolic syndrome'],
    overdoseLethality: 'Relatively low lethality alone; sedation, tachycardia, hypotension, EPS and modest QT — supportive care.',
    baselineWorkup: ['Weight/BMI and waist circumference', 'Fasting glucose or HbA1c', 'Fasting lipid panel', 'Blood pressure', 'Personal/family metabolic and cardiac history', 'Prolactin if symptomatic; ECG if cardiac risk'],
    ongoingMonitoring: 'Weight at each visit early on; fasting glucose and lipids at ~12 weeks then annually; AIMS for tardive dyskinesia; prolactin if symptoms of hyperprolactinemia; BP for orthostasis.',
    majorDDI: ['CYP2D6 inhibitors (fluoxetine, paroxetine, bupropion) raise levels', 'Carbamazepine (enzyme inducer) lowers levels', 'Additive orthostasis with antihypertensives', 'Additive CNS depression / QT with other centrally acting or QT drugs'],
    contraindicatedCombos: ['Other strongly QT-prolonging agents (additive)'],
    pregnancy: 'Third-trimester exposure risks neonatal EPS/withdrawal; no clear major teratogenic signal — weigh untreated psychosis. Tie to CANMAT perinatal guidance.',
    lactation: 'Excreted in milk; monitor infant for sedation/EPS.',
    pediatric: 'Approved for irritability associated with autism.',
    geriatric: 'Increased mortality/stroke in dementia-related psychosis; start low, watch orthostasis and EPS.',
    cardiac: 'Modest QT effect.',
    pearls: [
      'The most D2-potent SGA → highest EPS and highest hyperprolactinemia of the atypicals (behaves like a high-potency FGA at higher doses).',
      'Its active metabolite IS paliperidone (9-hydroxyrisperidone).',
      'Consta LAI is the exception among long-acting injectables in requiring a 3-week oral overlap.',
    ],
    mnemonics: ['"RISperidone RAISES prolactin the most" — dopamine block at the tuberoinfundibular tract.'],
    confusables: ['Risperidone vs paliperidone — paliperidone IS risperidone\'s active 9-OH metabolite (renally cleared, fewer CYP interactions).'],
    classDifferentiators: 'Most EPS and most hyperprolactinemia of the SGAs; metabolic risk intermediate; renally-cleared active moiety.',
    examHooks: ['Which SGA most commonly causes hyperprolactinemia and dose-dependent EPS? (risperidone/paliperidone)'],
    counsellingPoints: ['Report breast milk production, missed periods, or sexual dysfunction (prolactin).', 'Rise slowly from sitting/lying (orthostasis).', 'If on Consta, keep taking the oral form for the first 3 weeks.'],
    vignettes: [
      {
        stem: 'A 26-year-old woman on an antipsychotic for schizophrenia develops amenorrhea, galactorrhea, and low libido; prolactin is elevated. Which agent is most likely responsible?',
        options: ['Quetiapine', 'Risperidone', 'Aripiprazole', 'Clozapine'],
        answer: 'Risperidone',
        explanation: 'Risperidone is the most D2-potent SGA and causes the most hyperprolactinemia; quetiapine, aripiprazole (a partial agonist that can lower prolactin), and clozapine are prolactin-sparing.',
        testedFact: 'Risperidone hyperprolactinemia',
        source: { name: 'openFDA/DailyMed risperidone label — warnings (hyperprolactinemia)', origin: 'openfda' },
      },
    ],
    _prov: SGA_PROV,
  },

  paliperidone: {
    pronunciation: 'pal-ee-PER-i-done',
    moa: 'Combined 5-HT2A/D2 antagonist; it is the active 9-hydroxy metabolite of risperidone.',
    receptorProfile: 'D2 and 5-HT2A antagonism with α and H1 blockade — profile similar to risperidone, including dose-dependent EPS and hyperprolactinemia.',
    onsetOfEffect: 'Days–weeks; full effect ~2–4 wk.',
    halfLife: 'Oral extended-release ~23 h; LAI forms far longer (Sustenna ~weeks, Trinza ~months).',
    timeToSteadyState: '~4–5 days for oral ER.',
    metabolism: 'Undergoes LIMITED hepatic metabolism; ~59% excreted UNCHANGED in urine — fewer CYP interactions than risperidone.',
    elimination: 'Predominantly renal (unchanged drug) — dose must be reduced in renal impairment.',
    foodEffect: 'OROS extended-release: food increases absorption; administer consistently (e.g., with breakfast).',
    approvedCanada: ['Schizophrenia', 'Schizoaffective disorder'],
    offLabel: ['Maintenance via LAI to support adherence'],
    approvedPopulations: 'Adults; adolescents for schizophrenia in some labels.',
    startingDose: '6 mg PO once daily in the morning (extended-release; no initial titration required).',
    titration: 'Adjust in 3 mg increments at intervals ≥5 days if needed; usual range 3–12 mg/day.',
    maxDose: '12 mg/day (oral ER).',
    frequencyTiming: 'Once daily in the morning (OROS delivery).',
    renalHepaticAdjustment: 'Reduce dose in renal impairment (CrCl 50–79: max 6 mg; CrCl <50: max 3 mg); not recommended in severe renal impairment. No adjustment for mild–moderate hepatic impairment.',
    administrationNotes: 'Swallow OROS tablet whole (non-absorbable ghost shell passed in stool). LAIs: Sustenna monthly, Trinza every 3 months.',
    commonSE: ['EPS/akathisia (dose-dependent)', 'Hyperprolactinemia', 'Sedation', 'Tachycardia', 'Orthostatic hypotension', 'Weight gain (moderate)'],
    seriousAE: ['NMS', 'Tardive dyskinesia', 'Hyperprolactinemia', 'Metabolic changes', 'QT prolongation', 'Increased mortality/CVA in elderly dementia'],
    syndromes: ['EPS', 'Tardive dyskinesia', 'NMS', 'Hyperprolactinemia', 'Metabolic syndrome'],
    overdoseLethality: 'Relatively low alone; sedation, EPS, hypotension, QT — supportive care.',
    baselineWorkup: ['Weight/BMI and waist circumference', 'Fasting glucose or HbA1c', 'Fasting lipids', 'Blood pressure', 'Renal function (guides dosing)', 'ECG if cardiac risk'],
    ongoingMonitoring: 'Renal function (dosing); metabolic panel at ~12 weeks then annually; AIMS for tardive dyskinesia; prolactin if symptomatic; BP.',
    majorDDI: ['Other QT-prolonging drugs (additive)', 'Carbamazepine may lower levels (P-gp/enzyme induction)', 'Additive orthostasis with antihypertensives', 'Fewer CYP interactions than risperidone (mostly renal clearance)'],
    contraindicatedCombos: ['Other strongly QT-prolonging agents (additive)'],
    pregnancy: 'As with risperidone, third-trimester neonatal EPS/withdrawal risk; weigh untreated illness. Tie to CANMAT perinatal guidance.',
    lactation: 'Excreted in milk; monitor infant.',
    geriatric: 'Increased mortality/stroke in dementia psychosis; reduce for age-related renal decline.',
    cardiac: 'Modest QT prolongation.',
    pearls: [
      'It is 9-hydroxyrisperidone — the active metabolite of risperidone, so effects mirror risperidone (EPS, prolactin).',
      'Renally excreted largely unchanged → few CYP interactions (useful with hepatic impairment or polypharmacy) BUT must be dose-reduced for renal function.',
      'LAI options (Sustenna monthly, Trinza every 3 months) are major adherence tools.',
    ],
    mnemonics: ['"PALIperidone → PEE it out" — predominantly renal (unchanged) elimination; risperidone → liver (CYP2D6).'],
    confusables: ['Paliperidone vs risperidone — same pharmacology; paliperidone is renally cleared (few CYP interactions) and needs renal dose adjustment.'],
    classDifferentiators: 'Renally-cleared risperidone metabolite: minimal CYP interactions but renal dose adjustment required; extensive LAI options.',
    examHooks: ['Which antipsychotic is eliminated largely unchanged by the kidneys and needs renal dose adjustment? (paliperidone)'],
    counsellingPoints: ['Take in the morning, consistently with respect to food.', 'You may see the empty tablet shell in your stool — the drug has been absorbed.', 'Kidney function affects your dose.'],
    vignettes: [
      {
        stem: 'A patient with schizophrenia has significant hepatic impairment and is on several CYP-inhibiting medications. Which oral antipsychotic is least dependent on hepatic CYP metabolism, being largely excreted unchanged renally?',
        options: ['Risperidone', 'Paliperidone', 'Quetiapine', 'Aripiprazole'],
        answer: 'Paliperidone',
        explanation: 'Paliperidone (9-hydroxyrisperidone) undergoes limited hepatic metabolism and is excreted ~59% unchanged in urine, minimizing CYP interactions — but it requires renal dose adjustment.',
        testedFact: 'Paliperidone renal elimination',
        source: { name: 'openFDA/DailyMed paliperidone label — clinical pharmacology (elimination)', origin: 'openfda' },
      },
    ],
    _prov: SGA_PROV,
  },

  olanzapine: {
    pronunciation: 'oh-LAN-zuh-peen',
    moa: 'Combined 5-HT2A/D2 antagonist with broad additional H1, muscarinic, 5-HT2C and α1 blockade.',
    receptorProfile: 'Broad ("dirty") receptor profile: potent H1 (sedation, weight gain), muscarinic (anticholinergic), 5-HT2C (weight/appetite), D2, α1. Low EPS/prolactin at usual doses.',
    onsetOfEffect: 'Days–weeks; calming/sedation earlier.',
    halfLife: '~21–54 h (mean ~30 h).',
    timeToSteadyState: '~1 week.',
    metabolism: 'Hepatic CYP1A2 (major, plus direct glucuronidation and minor 2D6). Smoking induces 1A2 → lowers levels; fluvoxamine (1A2 inhibitor) raises them.',
    foodEffect: 'No clinically significant food effect.',
    approvedCanada: ['Schizophrenia', 'Bipolar I mania (acute and maintenance)', 'IM formulation for acute agitation'],
    offLabel: ['Bipolar/treatment-resistant depression (with fluoxetine)', 'Appetite stimulation / chemotherapy-induced nausea', 'Adjunct in anorexia nervosa'],
    approvedPopulations: 'Adults; orally-disintegrating (Zydis) and short-acting IM available.',
    startingDose: '5–10 mg PO once daily.',
    titration: 'Adjust by 5 mg at ≥1-week intervals; usual 10–20 mg/day.',
    maxDose: '20 mg/day (higher doses used off-label with limited evidence).',
    frequencyTiming: 'Once daily, usually at bedtime (sedating).',
    administrationNotes: 'Short-acting IM for agitation and a long-acting IM (olanzapine pamoate) that carries a post-injection delirium/sedation syndrome risk requiring monitored administration.',
    commonSE: ['Marked weight gain and increased appetite', 'Sedation', 'Dyslipidemia', 'Hyperglycemia', 'Dry mouth/constipation (anticholinergic)', 'Orthostatic hypotension'],
    seriousAE: ['Severe metabolic syndrome (among the worst SGAs, with clozapine)', 'Hyperglycemia/new-onset diabetes/DKA', 'Dyslipidemia', 'NMS', 'Tardive dyskinesia', 'Increased mortality/CVA in elderly dementia', 'DRESS'],
    syndromes: ['Metabolic syndrome', 'NMS', 'Tardive dyskinesia (low)', 'Anticholinergic burden'],
    overdoseLethality: 'Sedation, tachycardia, hypotension, anticholinergic effects; deaths mostly with co-ingestants. Combining IM olanzapine with parenteral benzodiazepines risks excessive sedation and cardiorespiratory depression.',
    baselineWorkup: ['Weight/BMI and waist circumference', 'Fasting glucose or HbA1c', 'Fasting lipid panel', 'Blood pressure', 'Personal/family history of diabetes/dyslipidemia', 'Liver enzymes'],
    ongoingMonitoring: 'Weight frequently early on; fasting glucose and lipids at 12 weeks then annually (sooner if gaining weight) given high metabolic risk; AIMS for tardive dyskinesia; LFTs if indicated.',
    majorDDI: ['CYP1A2 inhibitors (fluvoxamine, ciprofloxacin) raise levels', 'Smoking (1A2 induction) lowers levels — cessation raises them', 'Carbamazepine lowers levels', 'Additive CNS depression; IM olanzapine + parenteral benzodiazepine (cardiorespiratory depression)'],
    contraindicatedCombos: ['Co-administration of IM olanzapine with parenteral benzodiazepines is not recommended (excessive sedation/cardiorespiratory depression)'],
    pregnancy: 'No clear major teratogen signal; substantial gestational weight gain / glucose effects; neonatal EPS/withdrawal in third trimester. Tie to CANMAT perinatal guidance.',
    lactation: 'Excreted in milk; monitor infant for sedation.',
    geriatric: 'Increased mortality/stroke in dementia; anticholinergic and orthostatic burden — use with caution.',
    pearls: [
      'One of the two highest metabolic-risk SGAs (with clozapine) — big weight gain, dyslipidemia, hyperglycemia/DKA.',
      'Very sedating (H1) with low EPS and low prolactin.',
      'Do not combine IM olanzapine with a parenteral benzodiazepine (cardiorespiratory depression); and remember smoking lowers levels via CYP1A2.',
    ],
    mnemonics: ['"OLANZapine = ObesitY" — highest weight gain of the mainstream SGAs (clozapine aside).'],
    confusables: ['Olanzapine vs clozapine — both thienobenzodiazepines with the worst metabolic burden, but clozapine is reserved (agranulocytosis) and uniquely effective in resistant illness.', 'Olanzapine vs quetiapine — both sedating and metabolic; olanzapine causes more weight gain and has greater efficacy.'],
    classDifferentiators: 'High efficacy, very sedating, low EPS/prolactin, but among the worst metabolically.',
    examHooks: ['Which mainstream SGA (excluding clozapine) causes the most weight gain and metabolic derangement? (olanzapine)'],
    counsellingPoints: ['Expect increased appetite/weight — diet, exercise, and monitoring matter.', 'We will check your glucose and cholesterol regularly.', 'Very sedating — usually taken at bedtime.'],
    vignettes: [
      {
        stem: 'A 30-year-old with schizophrenia gains 9 kg over 3 months on an antipsychotic, with new fasting hyperglycemia and elevated triglycerides. Which agent is the most likely cause among these?',
        options: ['Ziprasidone', 'Aripiprazole', 'Olanzapine', 'Lurasidone'],
        answer: 'Olanzapine',
        explanation: 'Olanzapine (with clozapine) carries the highest risk of weight gain, hyperglycemia and dyslipidemia; ziprasidone, aripiprazole and lurasidone are weight/metabolically favourable.',
        testedFact: 'Olanzapine metabolic risk',
        source: { name: 'openFDA/DailyMed olanzapine label — warnings (metabolic changes)', origin: 'openfda' },
      },
    ],
    _prov: SGA_PROV,
  },

  quetiapine: {
    pronunciation: 'kwe-TYE-uh-peen',
    moa: 'Combined 5-HT2A/D2 antagonist with low, transient (loose) D2 occupancy; active metabolite norquetiapine adds norepinephrine reuptake inhibition and 5-HT2C antagonism (antidepressant properties).',
    receptorProfile: 'Very high H1 (sedation), α1; loose/low D2 (low EPS and low prolactin); norquetiapine adds NET inhibition and 5-HT1A partial agonism.',
    onsetOfEffect: 'Sedation immediate; antipsychotic/antidepressant effect over weeks.',
    halfLife: 'Quetiapine ~6–7 h; norquetiapine ~9–12 h. XR permits once-daily dosing.',
    timeToSteadyState: '~1–2 days.',
    metabolism: 'Hepatic CYP3A4 (major). Strong 3A4 inhibitors (clarithromycin, ketoconazole) raise levels; inducers (carbamazepine, phenytoin) lower them substantially.',
    foodEffect: 'XR: take without food or with a light meal — a high-fat meal significantly raises Cmax. IR: with or without food.',
    approvedCanada: ['Schizophrenia', 'Bipolar I mania', 'Bipolar depression', 'Bipolar maintenance', 'Adjunctive treatment of major depressive disorder (XR)'],
    offLabel: ['Low-dose (25–50 mg) for insomnia (off-label; generally discouraged given side-effect burden)', 'Generalized anxiety'],
    approvedPopulations: 'Adults; IR and XR formulations.',
    startingDose: 'Schizophrenia: 25 mg BID (IR) titrating up; bipolar depression: XR 50 mg → target 300 mg at bedtime.',
    titration: 'Titrate to reduce orthostasis; usual 300–600 mg/day (schizophrenia up to 800 mg).',
    maxDose: '800 mg/day.',
    frequencyTiming: 'IR divided BID; XR once daily at bedtime (sedating).',
    renalHepaticAdjustment: 'Reduce and titrate slowly in hepatic impairment (extensively hepatically metabolized).',
    administrationNotes: 'XR swallowed whole. Dose–effect ladder: low dose = sedative/anxiolytic, mid dose = antidepressant (norquetiapine NET), high dose = antipsychotic.',
    commonSE: ['Sedation (potent H1)', 'Orthostatic hypotension/dizziness', 'Dry mouth', 'Weight gain (moderate)', 'Constipation', 'Low EPS/prolactin'],
    seriousAE: ['Metabolic changes (moderate)', 'Orthostasis/syncope', 'QT prolongation', 'NMS', 'Tardive dyskinesia (low)', 'Cataracts (label advises periodic lens examination)', 'Hypothyroidism', 'Increased mortality/CVA in elderly dementia'],
    syndromes: ['Metabolic syndrome', 'Orthostasis', 'QT prolongation', 'NMS'],
    overdoseLethality: 'Sedation, tachycardia, hypotension, QT prolongation; more sedating in overdose than most SGAs but deaths uncommon alone.',
    baselineWorkup: ['Weight/BMI and waist circumference', 'Fasting glucose or HbA1c', 'Fasting lipids', 'Blood pressure', 'Consider baseline lens (slit-lamp) examination for cataracts per label', 'ECG if cardiac/QT risk'],
    ongoingMonitoring: 'Metabolic panel at 12 weeks then annually; periodic ophthalmologic (lens) examination per label; BP for orthostasis; AIMS for tardive dyskinesia; TSH if symptomatic.',
    majorDDI: ['CYP3A4 inhibitors (clarithromycin, ketoconazole) raise levels', 'CYP3A4 inducers (carbamazepine, phenytoin, rifampin) markedly lower levels', 'Other QT-prolonging or CNS-depressant drugs (additive)'],
    contraindicatedCombos: ['Other strongly QT-prolonging agents (additive)'],
    pregnancy: 'No clear major teratogen signal; often used in bipolar — weigh untreated illness. Tie to CANMAT perinatal guidance.',
    lactation: 'Low relative infant dose; monitor infant sedation.',
    geriatric: 'Increased mortality/stroke in dementia; orthostasis/sedation and falls — start low.',
    cardiac: 'Dose-related QT prolongation; orthostatic hypotension.',
    pearls: [
      'Very sedating (potent H1) with the LOWEST EPS/prolactin of these agents (loose D2 binding) → a go-to in Parkinson disease psychosis and in patients prone to EPS.',
      'Dose-dependent identity: low = sedative, mid = antidepressant (norquetiapine NET inhibition), high = antipsychotic.',
      'The label recommends periodic lens/cataract examination — a classic monitoring pearl.',
    ],
    mnemonics: ['"QUETiapine = QUIET" — H1 sedation, low EPS; watch the eyes (cataracts).'],
    confusables: ['Quetiapine vs olanzapine — both sedating and metabolic, but quetiapine has lower EPS/prolactin and less weight gain, and carries the cataract/lens-exam caution.'],
    classDifferentiators: 'Lowest EPS/prolactin (with clozapine); very sedating; broad bipolar approvals including bipolar depression; cataract monitoring.',
    examHooks: ['Which SGA is first-line for bipolar depression and preferred (with clozapine) in Parkinson psychosis for its very low EPS? (quetiapine)'],
    counsellingPoints: ['Very sedating — usually taken at bedtime; rise slowly (orthostasis).', 'Take the XR form without a heavy/fatty meal.', 'Report vision changes; periodic eye checks are advised.'],
    vignettes: [
      {
        stem: 'A 68-year-old with Parkinson disease develops medication-related psychosis. Which antipsychotic is preferred because of its very low likelihood of worsening parkinsonism?',
        options: ['Risperidone', 'Haloperidol', 'Quetiapine', 'Olanzapine'],
        answer: 'Quetiapine',
        explanation: 'Quetiapine (and clozapine) have the lowest EPS liability owing to loose/low D2 occupancy, making them preferred in Parkinson disease psychosis; risperidone and haloperidol worsen motor symptoms.',
        testedFact: 'Quetiapine low EPS in Parkinson psychosis',
        source: { name: 'CANMAT/CanGeriatric guidance; quetiapine low-EPS profile', origin: 'canmat' },
      },
    ],
    _prov: SGA_PROV,
  },

  clozapine: {
    pronunciation: 'KLOH-zuh-peen',
    moa: 'Weak/loose D2 antagonist with potent 5-HT2A antagonism and broad D4, muscarinic, H1 and α1 activity; low D2 occupancy explains the absence of EPS and low prolactin. The prototype "atypical".',
    receptorProfile: 'Low D2, high 5-HT2A and D4; potent H1 (sedation), α1 (orthostasis), muscarinic (mixed — M4 partial agonism contributes to sialorrhea despite anticholinergic effects elsewhere).',
    onsetOfEffect: 'Antipsychotic benefit over weeks; unique efficacy in treatment-resistant illness; anti-suicidal benefit demonstrated (InterSePT).',
    halfLife: '~12 h (range ~6–26 h).',
    timeToSteadyState: '~3–5 days at a stable dose.',
    metabolism: 'Hepatic CYP1A2 (major), plus 3A4 and 2D6. Smoking induces 1A2 (levels fall); smoking cessation, fluvoxamine, or ciprofloxacin raise levels sharply.',
    activeMetabolites: 'Norclozapine (N-desmethylclozapine), active.',
    therapeuticLevel: 'Target trough plasma clozapine ≳350 ng/mL for response; levels >600 ng/mL raise seizure/toxicity risk (therapeutic drug monitoring is genuinely useful here).',
    foodEffect: 'No clinically significant food effect.',
    approvedCanada: ['Treatment-RESISTANT schizophrenia (inadequate response/intolerance to ≥2 antipsychotics)', 'Reduction of recurrent suicidal behaviour in schizophrenia/schizoaffective disorder'],
    offLabel: ['Parkinson disease psychosis', 'Treatment-resistant bipolar disorder / persistent aggression'],
    approvedPopulations: 'Adults; use restricted to a monitoring registry.',
    startingDose: '12.5 mg once or twice on day 1, then increase slowly (e.g., 25–50 mg/day) toward 300–450 mg/day over ~2 weeks.',
    titration: 'Slow titration limits orthostasis, seizures and myocarditis. If ≥48 h of doses are missed, RE-TITRATE from 12.5 mg.',
    therapeuticRange: 'Usual effective dose 300–600 mg/day (target level ≳350 ng/mL).',
    maxDose: '900 mg/day.',
    frequencyTiming: 'Divided dosing, often with a larger bedtime dose (sedation).',
    renalHepaticAdjustment: 'Caution and slower titration in hepatic impairment; discontinue if marked hepatotoxicity.',
    startStopCrossTaper: 'Taper gradually over 1–2 weeks when stopping electively; abrupt cessation risks cholinergic rebound and rapid psychotic relapse. Re-titrate from 12.5 mg after a gap ≥48 h.',
    administrationNotes: 'Dispensing is tied to a mandatory hematologic monitoring registry (ANC must be in range before each dispense).',
    commonSE: ['Sedation', 'Sialorrhea (paradoxical hypersalivation)', 'Constipation (may progress to ileus/obstruction)', 'Weight gain and metabolic effects', 'Orthostatic hypotension and tachycardia', 'Fever (often benign/transient)', 'Nocturnal enuresis'],
    seriousAE: ['Agranulocytosis / severe neutropenia', 'Myocarditis and cardiomyopathy (highest risk in first 6–8 weeks)', 'Seizures (dose-related, especially >600 mg/day)', 'Severe constipation → paralytic ileus/bowel obstruction (potentially fatal GI hypomotility)', 'Metabolic syndrome/hyperglycemia/DKA', 'NMS', 'Orthostatic hypotension/syncope/collapse (especially early titration or with benzodiazepines)', 'Venous thromboembolism/pulmonary embolism'],
    syndromes: ['Agranulocytosis/neutropenia', 'Myocarditis/cardiomyopathy', 'Seizures', 'Severe GI hypomotility (ileus)', 'Metabolic syndrome', 'NMS'],
    overdoseLethality: 'More dangerous in overdose than other SGAs: profound sedation/coma, hypersalivation, seizures, aspiration, hypotension, and cardiac arrhythmia can be fatal — supportive/ICU care.',
    baselineWorkup: ['CBC with differential and ANC (baseline ANC must be ≥1.5 ×10⁹/L; ≥1.0 if benign ethnic neutropenia)', 'Weight/BMI and waist circumference', 'Fasting glucose or HbA1c and fasting lipids', 'Blood pressure and heart rate', 'Baseline ECG; consider troponin and CRP for myocarditis surveillance', 'Baseline for GI (bowel) function'],
    ongoingMonitoring: 'ANC monitoring is MANDATORY and registry-enforced: WEEKLY for the first 6 months, then EVERY 2 WEEKS for months 6–12, then EVERY 4 WEEKS thereafter. Interrupt/hold for neutropenia by threshold; severe neutropenia (ANC <0.5 ×10⁹/L) → discontinue and generally do not rechallenge. Myocarditis surveillance (symptoms, HR, troponin/CRP) during the first ~4–8 weeks. Metabolic panel per schedule. Monitor bowel function (prophylactic laxatives) and clozapine level when indicated.',
    majorDDI: ['CYP1A2 inhibitors (fluvoxamine, ciprofloxacin) dramatically raise clozapine levels → toxicity/seizures', 'Smoking status (1A2): starting smoking lowers levels, stopping raises them', 'Carbamazepine — avoid (additive bone-marrow suppression plus enzyme induction)', 'Other myelosuppressive drugs — avoid (additive agranulocytosis risk)', 'Benzodiazepines — risk of respiratory/cardiac collapse, especially early', 'Anticholinergics worsen constipation/ileus'],
    contraindicatedCombos: ['Concurrent drugs known to cause agranulocytosis/bone-marrow suppression (e.g., carbamazepine)', 'Additive use with other agents that markedly lower the seizure threshold (caution)'],
    pregnancy: 'Monitoring need not be interrupted; neonatal ANC monitoring and "floppy baby"/withdrawal considerations; individualized decisions given its unique efficacy. Tie to CANMAT perinatal guidance.',
    lactation: 'Excreted in milk; generally avoided (risk of infant sedation and agranulocytosis).',
    geriatric: 'Orthostasis, anticholinergic load, constipation and sedation risks amplified — titrate very cautiously.',
    cardiac: 'Myocarditis (early) and later cardiomyopathy; tachycardia; orthostatic hypotension; some QT effect.',
    pearls: [
      'The ONLY antipsychotic proven superior for treatment-resistant schizophrenia AND to reduce suicidality — but reserved because of agranulocytosis.',
      'Agranulocytosis mandates registry ANC monitoring (weekly ×6 months → q2 weeks to 12 months → q4 weeks); hold/stop by neutrophil thresholds.',
      'Remember the early KILLERS beyond blood: myocarditis (first 6–8 weeks — check troponin/CRP/HR) and severe constipation → ileus/bowel obstruction (prescribe prophylactic laxatives).',
      'NO EPS and low prolactin (loose D2); seizures are dose-related (consider valproate cover >600 mg); sialorrhea is a paradox (M4 agonism).',
      'Levels swing with smoking and with CYP1A2 inhibitors (fluvoxamine, ciprofloxacin); re-titrate from 12.5 mg after a ≥48 h gap.',
    ],
    mnemonics: ['Clozapine\'s deadly C\'s: Cytopenia (agranulocytosis), Cardiac (myocarditis/cardiomyopathy), Convulsions (seizures), Constipation (ileus), and Cardiometabolic (weight/glucose/lipids).'],
    confusables: ['Clozapine vs clonazepam — dangerously similar names but utterly different drugs (atypical antipsychotic requiring ANC monitoring vs a benzodiazepine); a classic prescribing/dispensing error.', 'Clozapine vs olanzapine — both thienobenzodiazepines with the worst metabolic burden; clozapine adds agranulocytosis/myocarditis and unique resistant-illness efficacy.'],
    classDifferentiators: 'Uniquely effective in treatment-resistant schizophrenia and anti-suicidal; NO EPS/low prolactin; but agranulocytosis, myocarditis, seizures, ileus and severe metabolic effects — the most monitoring-intensive antipsychotic.',
    examHooks: [
      'Which antipsychotic is indicated for treatment-resistant schizophrenia and to reduce suicidality? (clozapine)',
      'State the clozapine ANC monitoring schedule (weekly ×6 months → every 2 weeks to 12 months → every 4 weeks).',
      'A patient 3 weeks into clozapine develops chest pain, tachycardia and a rising troponin — diagnosis? (myocarditis)',
    ],
    counsellingPoints: [
      'Report any fever, sore throat or flu-like symptoms immediately — we must check your white cell count (infection risk).',
      'Report chest pain, shortness of breath, palpitations or fainting (heart/myocarditis).',
      'Constipation can become dangerous — use laxatives as advised and report severe/absent bowel movements.',
      'Do not miss doses: after 2+ days off, the dose must be restarted low. Tell us if you start or stop smoking.',
    ],
    vignettes: [
      {
        stem: 'A 34-year-old on clozapine for 3 months presents with fever and sore throat; ANC is 0.4 ×10⁹/L. What is the most appropriate immediate management?',
        options: ['Reduce the clozapine dose and recheck in a week', 'Continue clozapine and add an antibiotic', 'Discontinue clozapine immediately and do not rechallenge', 'Switch to olanzapine and continue weekly ANC monitoring on clozapine'],
        answer: 'Discontinue clozapine immediately and do not rechallenge',
        explanation: 'ANC <0.5 ×10⁹/L is severe neutropenia/agranulocytosis: clozapine must be stopped immediately, the patient monitored for infection, and clozapine generally not rechallenged. This is why registry ANC monitoring is mandatory.',
        testedFact: 'Clozapine agranulocytosis management (ANC <0.5)',
        source: { name: 'openFDA/DailyMed clozapine label — boxed warning (severe neutropenia)', origin: 'openfda' },
      },
      {
        stem: 'A 28-year-old man started clozapine 18 days ago and now has fever, tachycardia, chest discomfort and dyspnea; troponin and CRP are elevated and eosinophils are raised. What is the most likely diagnosis?',
        options: ['Agranulocytosis with sepsis', 'Clozapine-induced myocarditis', 'Neuroleptic malignant syndrome', 'Pulmonary embolism'],
        answer: 'Clozapine-induced myocarditis',
        explanation: 'Myocarditis classically occurs in the first 6–8 weeks of clozapine, with tachycardia, chest pain, fever, dyspnea and rising troponin/CRP (often eosinophilia). Clozapine must be stopped and cardiology involved.',
        testedFact: 'Clozapine myocarditis timing/presentation',
        source: { name: 'openFDA/DailyMed clozapine label — warnings (myocarditis/cardiomyopathy)', origin: 'openfda' },
      },
      {
        stem: 'A patient with schizophrenia has had inadequate response to adequate trials of two different antipsychotics and has ongoing suicidal ideation. Which agent is specifically indicated?',
        options: ['High-dose olanzapine', 'Clozapine', 'Two antipsychotics combined', 'Long-acting injectable risperidone'],
        answer: 'Clozapine',
        explanation: 'Failure of ≥2 adequate antipsychotic trials defines treatment-resistant schizophrenia, for which clozapine is uniquely effective; it also has a specific indication for reducing recurrent suicidal behaviour (InterSePT).',
        testedFact: 'Clozapine for treatment-resistant schizophrenia and suicidality',
        source: { name: 'CANMAT/CPA schizophrenia guidelines — clozapine for treatment resistance', origin: 'canmat' },
      },
    ],
    _prov: { ...SGA_PROV, therapeuticLevel: 'monograph' },
  },

  ziprasidone: {
    pronunciation: 'zi-PRAY-si-done',
    moa: 'Combined 5-HT2A/D2 antagonist that is also a 5-HT1A partial agonist, 5-HT2C/1D antagonist, and a modest serotonin/norepinephrine reuptake inhibitor.',
    receptorProfile: '5-HT2A/D2 antagonism with 5-HT1A agonism; LOW H1/muscarinic → weight- and lipid-neutral, less sedation. Notable for QT prolongation.',
    onsetOfEffect: 'Days–weeks.',
    halfLife: '~7 h.',
    timeToSteadyState: '~1–3 days.',
    metabolism: 'Primarily aldehyde oxidase reduction (~2/3) with minor CYP3A4 — relatively few CYP interactions.',
    foodEffect: 'CRITICAL: absorption roughly DOUBLES with food — must be taken WITH A MEAL of ≥500 kcal or bioavailability falls ~50% (a common cause of apparent non-response).',
    approvedCanada: ['Schizophrenia', 'Bipolar I mania'],
    offLabel: ['Bipolar maintenance (adjunct)'],
    approvedPopulations: 'Adults; short-acting IM available for acute agitation.',
    startingDose: '20 mg PO BID WITH food.',
    titration: 'Increase at ≥2-day intervals; usual 40–80 mg BID.',
    maxDose: '160 mg/day (80 mg BID).',
    frequencyTiming: 'Twice daily, each dose with food (≥500 kcal).',
    administrationNotes: 'Food requirement is the defining practical issue; short-acting IM for agitation.',
    commonSE: ['Somnolence', 'Akathisia/EPS', 'Dizziness', 'Nausea', 'Weight/lipid-neutral (metabolically favourable)'],
    seriousAE: ['QT prolongation (greatest among SGAs) with torsades risk', 'NMS', 'Tardive dyskinesia', 'Orthostatic hypotension', 'Rash/DRESS', 'Increased mortality/CVA in elderly dementia'],
    syndromes: ['QT prolongation', 'EPS/akathisia', 'NMS'],
    overdoseLethality: 'Main concern is QT prolongation/arrhythmia; otherwise sedation and EPS — obtain ECG in significant ingestion.',
    baselineWorkup: ['ECG (baseline QTc) if cardiac risk or other QT drugs', 'Serum potassium and magnesium', 'Weight/BMI and waist circumference', 'Fasting glucose/HbA1c and lipids', 'Blood pressure'],
    ongoingMonitoring: 'ECG/electrolytes if QT risk factors or co-prescribed QT drugs; metabolic panel (though weight-neutral) per class practice; AIMS for tardive dyskinesia.',
    majorDDI: ['Other QT-prolonging drugs (additive — avoid)', 'Drugs causing hypokalemia/hypomagnesemia (potentiate QT)', 'Strong CYP3A4 inhibitors/inducers (modest effect)'],
    contraindicatedCombos: ['Other QT-prolonging medications', 'Use in the setting of recent MI, uncompensated heart failure, or known QT prolongation (per label cardiac cautions)'],
    pregnancy: 'Limited data; third-trimester neonatal EPS/withdrawal risk — weigh untreated illness. Tie to CANMAT perinatal guidance.',
    lactation: 'Limited data; monitor infant.',
    geriatric: 'Increased mortality/stroke in dementia; check QT and electrolytes.',
    cardiac: 'Greatest QT prolongation of the SGAs — the defining caution; avoid with other QT drugs and correct electrolytes.',
    pearls: [
      'Must be taken WITH FOOD (≥500 kcal) — on an empty stomach absorption halves, a classic cause of "treatment failure".',
      'Greatest QT prolongation of the SGAs → check ECG/electrolytes and avoid other QT-prolonging drugs.',
      'Weight- and lipid-neutral (metabolically favourable) — a reason to choose it in metabolically vulnerable patients.',
    ],
    mnemonics: ['"Ziprasidone: Zzz needs a meal, and Zaps the QT" — food ≥500 kcal; watch the QT interval.'],
    confusables: ['Ziprasidone vs lurasidone — both need food, but ziprasidone requires ≥500 kcal and prolongs QT, whereas lurasidone needs ≥350 kcal, has low QT risk, and is used for bipolar depression.'],
    classDifferentiators: 'Weight/lipid-neutral but the QT-prolonging SGA with an absolute food requirement (≥500 kcal); twice-daily dosing.',
    examHooks: ['Which SGA must be taken with a ≥500 kcal meal and carries the greatest QT risk? (ziprasidone)'],
    counsellingPoints: ['Always take with a full meal (≥500 kcal) — food is required for the drug to work.', 'Report palpitations or fainting; tell us about other heart medications.', 'It is weight-friendly compared with other options.'],
    vignettes: [
      {
        stem: 'A patient with schizophrenia on ziprasidone reports little benefit despite adherence; on review, they take it with only black coffee in the morning and nothing at the second dose. What is the most likely explanation?',
        options: ['Subtherapeutic dosing schedule', 'Reduced absorption from being taken without adequate food', 'CYP2D6 ultra-rapid metabolism', 'Development of tolerance'],
        answer: 'Reduced absorption from being taken without adequate food',
        explanation: 'Ziprasidone bioavailability roughly doubles with a ≥500 kcal meal; taken on an empty stomach, absorption falls ~50%, causing apparent non-response. It must be taken with food.',
        testedFact: 'Ziprasidone food-dependent absorption',
        source: { name: 'openFDA/DailyMed ziprasidone label — dosage/administration (with food)', origin: 'openfda' },
      },
    ],
    _prov: SGA_PROV,
  },

  aripiprazole: {
    pronunciation: 'a-ri-PIP-ra-zole',
    moa: 'Dopamine D2/D3 PARTIAL agonist ("dopamine system stabilizer") plus 5-HT1A partial agonism and 5-HT2A antagonism.',
    receptorProfile: 'D2/D3 partial agonist, 5-HT1A partial agonist, 5-HT2A antagonist; low H1/muscarinic → weight-neutral, low sedation. Can LOWER prolactin. Activating with prominent akathisia.',
    onsetOfEffect: 'Days–weeks; may be activating early.',
    halfLife: '~75 h (active metabolite dehydro-aripiprazole ~94 h) — long.',
    timeToSteadyState: '~2 weeks.',
    metabolism: 'Hepatic CYP2D6 and CYP3A4. CYP2D6 poor metabolizers or 2D6/3A4 inhibitors raise levels (dose reduction advised); inducers lower them.',
    foodEffect: 'May be taken with or without food.',
    approvedCanada: ['Schizophrenia', 'Bipolar I mania', 'Adjunctive treatment of major depressive disorder'],
    offLabel: ['Irritability associated with autism', 'Tourette/tics', 'Augmentation for impulse-control/aggression'],
    approvedPopulations: 'Adults; LAI (Maintena) monthly; adolescents in some labels.',
    startingDose: '10–15 mg/day (schizophrenia/mania); 2–5 mg/day as MDD adjunct.',
    titration: 'Adjust at ≥2-week intervals (long half-life); usual 10–30 mg/day.',
    maxDose: '30 mg/day.',
    frequencyTiming: 'Once daily; morning dosing if activating/insomnia.',
    administrationNotes: 'LAI Maintena given IM monthly (with oral overlap per label).',
    commonSE: ['Akathisia (characteristic)', 'Insomnia/activation/anxiety', 'Nausea', 'Headache', 'Weight- and prolactin-neutral (may lower prolactin)'],
    seriousAE: ['Impulse-control disorders (pathological gambling, hypersexuality, compulsive shopping/eating)', 'NMS', 'Tardive dyskinesia', 'Orthostatic hypotension', 'Increased mortality/CVA in elderly dementia'],
    syndromes: ['Akathisia', 'Impulse-control disorders', 'NMS', 'Tardive dyskinesia'],
    overdoseLethality: 'Generally low lethality; sedation, agitation, tachycardia — supportive care.',
    baselineWorkup: ['Weight/BMI and waist circumference', 'Fasting glucose/HbA1c and lipids (though usually favourable)', 'Blood pressure', 'Screen for pre-existing impulse-control tendencies'],
    ongoingMonitoring: 'Metabolic panel per class practice; ask specifically about new gambling/hypersexuality/shopping/binge-eating urges; AIMS for tardive dyskinesia; assess akathisia.',
    majorDDI: ['Strong CYP2D6 inhibitors (fluoxetine, paroxetine) and 3A4 inhibitors (ketoconazole) raise levels → halve dose per label', 'CYP3A4 inducers (carbamazepine) lower levels → may need higher dose', 'Additive with other CNS-active drugs'],
    contraindicatedCombos: [],
    pregnancy: 'No clear major teratogen signal; neonatal EPS/withdrawal in third trimester — weigh untreated illness. Tie to CANMAT perinatal guidance.',
    lactation: 'Limited data; may suppress prolactin/lactation; monitor infant.',
    geriatric: 'Increased mortality/stroke in dementia; long half-life prolongs any adverse effect.',
    pearls: [
      'D2 PARTIAL agonist ("dopamine stabilizer") → weight-neutral and prolactin-sparing (can even lower prolactin), but ACTIVATING with prominent AKATHISIA.',
      'Carries the dopamine-agonist impulse-control warning: pathological gambling, hypersexuality, compulsive shopping and binge-eating — ask about these.',
      'Very long half-life (~75 h) and an LAI (Maintena) support adherence; titrate slowly.',
    ],
    mnemonics: ['"ARIPiprazole AIMS partial (agonism): Activating, Akathisia, and Addictive urges (impulse control)."'],
    confusables: ['Aripiprazole vs brexpiprazole vs cariprazine — the three partial agonists; aripiprazole is the most activating with the most akathisia, brexpiprazole is better tolerated (adjunct MDD), cariprazine is D3-preferring (bipolar mania + depression).'],
    classDifferentiators: 'Prototype D2 partial agonist: metabolically favourable, prolactin-sparing, but activating with akathisia and impulse-control risk.',
    examHooks: ['Which antipsychotic mechanism is D2 partial agonism, and which classic behavioural adverse effect (gambling/hypersexuality) does it carry? (aripiprazole; impulse-control disorders)'],
    counsellingPoints: ['May feel restless/activated early (akathisia) — tell us if you cannot sit still.', 'Report any new urges to gamble, spend, binge-eat or hypersexuality.', 'Weight-friendly and often taken in the morning.'],
    vignettes: [
      {
        stem: 'A 45-year-old man on an antipsychotic for bipolar disorder develops new compulsive gambling with significant financial losses, resolving after the drug is changed. Which agent is most characteristically implicated?',
        options: ['Olanzapine', 'Aripiprazole', 'Quetiapine', 'Risperidone'],
        answer: 'Aripiprazole',
        explanation: 'Dopamine D2 partial agonists, especially aripiprazole, carry a recognized risk of impulse-control disorders (pathological gambling, hypersexuality, compulsive shopping/eating), typically reversible on discontinuation.',
        testedFact: 'Aripiprazole impulse-control disorders',
        source: { name: 'openFDA/DailyMed aripiprazole label — warnings (pathological gambling/impulse control)', origin: 'openfda' },
      },
    ],
    _prov: SGA_PROV,
  },

  asenapine: {
    pronunciation: 'a-SEN-a-peen',
    moa: 'Combined 5-HT2A/D2 antagonist with broad high-affinity antagonism across serotonin (2A, 2C, 6, 7), dopamine, α-adrenergic and H1 receptors; negligible muscarinic activity.',
    receptorProfile: 'Very broad serotonin/dopamine/α/H1 antagonist; minimal anticholinergic effect.',
    onsetOfEffect: 'Days–weeks.',
    halfLife: '~24 h.',
    timeToSteadyState: '~3 days.',
    metabolism: 'UGT1A4 glucuronidation and CYP1A2 oxidation. Extensive first-pass metabolism if swallowed → must be given sublingually.',
    foodEffect: 'Sublingual: do NOT eat or drink for 10 minutes after a dose (swallowing/food markedly reduces absorption).',
    approvedCanada: ['Schizophrenia', 'Bipolar I mania (monotherapy or adjunct)'],
    offLabel: ['Bipolar maintenance'],
    approvedPopulations: 'Adults; sublingual tablet.',
    startingDose: '5 mg sublingually BID (schizophrenia); 10 mg SL BID (bipolar mania).',
    titration: 'Increase to 10 mg SL BID as tolerated.',
    maxDose: '10 mg sublingually BID (20 mg/day).',
    frequencyTiming: 'Twice daily, sublingual; avoid food/drink for 10 minutes after each dose.',
    administrationNotes: 'The ONLY sublingual antipsychotic — swallowing destroys bioavailability (extensive first-pass). Place under the tongue and let dissolve; do not chew or swallow.',
    commonSE: ['Oral hypoesthesia/numbness of the tongue (characteristic)', 'Dysgeusia (altered taste)', 'Somnolence', 'Akathisia/EPS', 'Dizziness', 'Weight gain (moderate)'],
    seriousAE: ['Serious hypersensitivity reactions (anaphylaxis, angioedema — can occur with the first dose)', 'NMS', 'Tardive dyskinesia', 'QT prolongation', 'Orthostatic hypotension', 'Metabolic changes', 'Increased mortality/CVA in elderly dementia'],
    syndromes: ['Oral hypoesthesia', 'Hypersensitivity', 'EPS', 'NMS', 'Metabolic syndrome'],
    overdoseLethality: 'Sedation, agitation, EPS; limited absorption if swallowed reduces oral-overdose severity — supportive care.',
    baselineWorkup: ['Weight/BMI and waist circumference', 'Fasting glucose/HbA1c and lipids', 'Blood pressure', 'ECG if cardiac/QT risk'],
    ongoingMonitoring: 'Metabolic panel per class schedule; watch for oral lesions/hypersensitivity; AIMS for tardive dyskinesia; BP.',
    majorDDI: ['CYP1A2 inhibitors (fluvoxamine) raise levels', 'Other QT-prolonging drugs (additive)', 'Additive CNS depression'],
    contraindicatedCombos: ['Other strongly QT-prolonging agents (additive)'],
    pregnancy: 'Limited data; neonatal EPS/withdrawal risk third trimester — weigh untreated illness. Tie to CANMAT perinatal guidance.',
    lactation: 'Limited data; monitor infant.',
    geriatric: 'Increased mortality/stroke in dementia; orthostasis.',
    cardiac: 'QT prolongation possible.',
    pearls: [
      'The ONLY sublingual antipsychotic — swallowing destroys bioavailability (extensive first-pass metabolism); place under the tongue and avoid food/drink for 10 minutes.',
      'Oral hypoesthesia (tongue numbness) and altered taste are characteristic and expected.',
      'Serious hypersensitivity reactions (angioedema/anaphylaxis) can occur, even with the first dose.',
    ],
    mnemonics: ['"ASENapine = Absorbed under the tongue (Sublingual); no food/drink for 10 minutes; numbs the tongue."'],
    confusables: ['Asenapine (sublingual, must not swallow) vs olanzapine orally-disintegrating tablet (Zydis, which IS swallowed after dissolving) — different administration logic.'],
    classDifferentiators: 'Unique sublingual route with an absolute no-food/drink-for-10-minutes rule; oral hypoesthesia and hypersensitivity are signatures.',
    examHooks: ['Which antipsychotic is sublingual, causes tongue numbness, and must not be eaten/drunk over for 10 minutes? (asenapine)'],
    counsellingPoints: ['Place under the tongue and let it dissolve — do not chew or swallow.', 'Do not eat or drink for 10 minutes after each dose.', 'Temporary tongue numbness/altered taste is expected; seek urgent care for swelling of lips/tongue or trouble breathing.'],
    vignettes: [
      {
        stem: 'A patient reports no benefit from asenapine. On questioning, they swallow the tablet with a glass of water at each dose. What is the key administration error?',
        options: ['It should be taken with a high-fat meal', 'It must be dissolved sublingually, not swallowed', 'It should be crushed and taken with food', 'It must be taken only once daily'],
        answer: 'It must be dissolved sublingually, not swallowed',
        explanation: 'Asenapine undergoes extensive first-pass metabolism; swallowing gives negligible bioavailability. It must dissolve under the tongue, and the patient should avoid food/drink for 10 minutes afterward.',
        testedFact: 'Asenapine sublingual administration',
        source: { name: 'openFDA/DailyMed asenapine label — dosage/administration (sublingual)', origin: 'openfda' },
      },
    ],
    _prov: SGA_PROV,
  },

  lurasidone: {
    pronunciation: 'loo-RAS-i-done',
    moa: 'Combined 5-HT2A/D2 antagonist with potent 5-HT7 antagonism and 5-HT1A partial agonism and α2C antagonism; minimal H1/muscarinic (metabolically favourable).',
    receptorProfile: 'D2/5-HT2A/5-HT7 antagonist, 5-HT1A partial agonist; very low H1/muscarinic → weight-, lipid- and glucose-favourable; low prolactin.',
    onsetOfEffect: 'Days–weeks.',
    halfLife: '~18 h.',
    timeToSteadyState: '~7 days.',
    metabolism: 'Hepatic CYP3A4 (major) — strong 3A4 inhibitors and inducers are contraindicated (large exposure changes).',
    foodEffect: 'CRITICAL: take WITH FOOD of ≥350 kcal — food roughly doubles absorption (empty-stomach dosing gives erratic, low levels).',
    approvedCanada: ['Schizophrenia', 'Bipolar I depression (monotherapy and adjunct to lithium or valproate)'],
    offLabel: ['Bipolar maintenance (adjunct)'],
    approvedPopulations: 'Adults; adolescents for schizophrenia/bipolar depression in some labels.',
    startingDose: '20–40 mg once daily WITH food.',
    titration: 'Adjust at ≥1-week intervals; usual 40–80 mg/day.',
    maxDose: '120 mg/day (per Canadian labelling).',
    frequencyTiming: 'Once daily with a meal (≥350 kcal), often in the evening.',
    renalHepaticAdjustment: 'Reduce dose in moderate–severe renal or hepatic impairment (per label).',
    administrationNotes: 'Food requirement (≥350 kcal) is the key counselling point; less than ziprasidone\'s 500 kcal.',
    commonSE: ['Akathisia', 'Somnolence', 'Nausea', 'EPS', 'Agitation', 'Weight/lipid/glucose-favourable; low prolactin'],
    seriousAE: ['Akathisia/EPS', 'NMS', 'Tardive dyskinesia', 'Orthostatic hypotension', 'Increased mortality/CVA in elderly dementia'],
    syndromes: ['Akathisia/EPS', 'NMS', 'Tardive dyskinesia'],
    overdoseLethality: 'Generally low; sedation and EPS — supportive care.',
    baselineWorkup: ['Weight/BMI and waist circumference', 'Fasting glucose/HbA1c and lipids (usually favourable)', 'Blood pressure', 'Renal/hepatic function (guides dosing)'],
    ongoingMonitoring: 'Metabolic panel per class practice (though favourable); assess akathisia/EPS; AIMS for tardive dyskinesia.',
    majorDDI: ['Strong CYP3A4 inhibitors (ketoconazole, clarithromycin) — contraindicated', 'Strong CYP3A4 inducers (rifampin, carbamazepine) — contraindicated (loss of efficacy)', 'Grapefruit juice raises levels', 'Additive CNS depression'],
    contraindicatedCombos: ['Strong CYP3A4 inhibitors (e.g., ketoconazole, clarithromycin)', 'Strong CYP3A4 inducers (e.g., rifampin, carbamazepine)'],
    pregnancy: 'Limited data; neonatal EPS/withdrawal risk third trimester — weigh untreated illness. Tie to CANMAT perinatal guidance.',
    lactation: 'Limited data; monitor infant.',
    geriatric: 'Increased mortality/stroke in dementia; adjust for renal/hepatic decline.',
    cardiac: 'Low QT risk.',
    pearls: [
      'Take WITH FOOD (≥350 kcal) — less than ziprasidone\'s 500 kcal, but still essential for absorption.',
      'Strong first-line for BIPOLAR I DEPRESSION and metabolically favourable (weight/lipid/glucose-neutral, low prolactin, low QT).',
      'CYP3A4 substrate — strong inhibitors and inducers are contraindicated (and avoid grapefruit).',
    ],
    mnemonics: ['"LURasidone: Lunch (≥350 kcal) for Low-metabolic bipolar depression."'],
    confusables: ['Lurasidone vs ziprasidone — both require food, but lurasidone needs ≥350 kcal, is once daily, is low-QT, and treats bipolar depression; ziprasidone needs ≥500 kcal, is BID, and prolongs QT.'],
    classDifferentiators: 'Metabolically favourable, low-QT SGA for bipolar depression, but with an absolute ≥350 kcal food requirement and CYP3A4-driven contraindicated interactions.',
    examHooks: ['Which metabolically-favourable SGA is first-line for bipolar I depression and must be taken with ≥350 kcal of food? (lurasidone)'],
    counsellingPoints: ['Always take with a meal of at least 350 kcal.', 'Avoid grapefruit and tell us about antibiotics/antifungals or anti-seizure drugs (interactions).', 'It is weight- and cholesterol-friendly.'],
    vignettes: [
      {
        stem: 'A 32-year-old with bipolar I disorder in a depressive episode has a strong family history of diabetes and is very concerned about weight gain. Which agent is a good evidence-based, metabolically favourable choice (taken with food)?',
        options: ['Olanzapine', 'Lurasidone', 'Quetiapine', 'Clozapine'],
        answer: 'Lurasidone',
        explanation: 'Lurasidone is approved for bipolar I depression and is weight/lipid/glucose-favourable; it must be taken with ≥350 kcal of food for adequate absorption. Olanzapine and quetiapine carry more metabolic risk.',
        testedFact: 'Lurasidone for bipolar depression, metabolically favourable, food requirement',
        source: { name: 'CANMAT bipolar guidelines; lurasidone label (with food)', origin: 'canmat' },
      },
    ],
    _prov: SGA_PROV,
  },

  brexpiprazole: {
    pronunciation: 'brex-PIP-ra-zole',
    moa: 'Dopamine D2 PARTIAL agonist (lower intrinsic activity than aripiprazole) with 5-HT1A partial agonism, 5-HT2A antagonism and α1B/2C antagonism.',
    receptorProfile: 'D2/5-HT1A partial agonist, 5-HT2A antagonist; the lower D2 intrinsic activity gives less activation/akathisia than aripiprazole; low prolactin.',
    onsetOfEffect: 'Days–weeks.',
    halfLife: '~91 h (long).',
    timeToSteadyState: '~10–14 days.',
    metabolism: 'Hepatic CYP2D6 and CYP3A4 — 2D6 poor metabolizers or 2D6/3A4 inhibitors raise levels (dose adjust per label).',
    foodEffect: 'May be taken with or without food.',
    approvedCanada: ['Schizophrenia', 'Adjunctive treatment of major depressive disorder'],
    offLabel: ['Agitation associated with dementia (approved in some jurisdictions)'],
    approvedPopulations: 'Adults.',
    startingDose: '1 mg/day (0.5–1 mg for MDD adjunct); titrate toward 2–4 mg.',
    titration: 'Increase at ≥1-week intervals (long half-life); usual 2–4 mg/day.',
    maxDose: '4 mg/day.',
    frequencyTiming: 'Once daily.',
    commonSE: ['Akathisia (less than aripiprazole)', 'Weight gain (slightly more than aripiprazole)', 'Headache', 'Somnolence', 'Low prolactin'],
    seriousAE: ['Impulse-control disorders (class effect of dopamine partial agonists)', 'NMS', 'Tardive dyskinesia', 'Orthostatic hypotension', 'Metabolic changes (modest)', 'Increased mortality/CVA in elderly dementia'],
    syndromes: ['Akathisia (mild)', 'Impulse-control disorders', 'NMS', 'Tardive dyskinesia'],
    overdoseLethality: 'Generally low lethality; sedation — supportive care.',
    baselineWorkup: ['Weight/BMI and waist circumference', 'Fasting glucose/HbA1c and lipids', 'Blood pressure', 'Screen for impulse-control tendencies'],
    ongoingMonitoring: 'Metabolic panel per class practice; ask about new impulse-control urges (gambling/hypersexuality/shopping/eating); AIMS for tardive dyskinesia.',
    majorDDI: ['Strong CYP2D6 inhibitors (fluoxetine, paroxetine) and 3A4 inhibitors raise levels → dose reduce per label', 'CYP3A4/2D6 inducers lower levels', 'Additive CNS depression'],
    contraindicatedCombos: [],
    pregnancy: 'Limited data; neonatal EPS/withdrawal risk third trimester — weigh untreated illness. Tie to CANMAT perinatal guidance.',
    lactation: 'Limited data; monitor infant.',
    geriatric: 'Increased mortality/stroke in dementia; long half-life prolongs adverse effects.',
    pearls: [
      'A D2 partial agonist like aripiprazole but with LESS akathisia/activation (lower D2 intrinsic activity) — better tolerated for restlessness, though slightly more weight gain.',
      'Approved as an ADJUNCT for major depressive disorder (partial response to an antidepressant).',
      'Shares the dopamine-agonist impulse-control warning; long half-life (~91 h).',
    ],
    mnemonics: ['"BREXpiprazole = a BRakes-on aripiprazole" — less akathisia; adjunct for MDD."'],
    confusables: ['Brexpiprazole vs aripiprazole — same partial-agonist mechanism; brexpiprazole is less activating (less akathisia) but slightly more weight gain, and is a common MDD adjunct.'],
    classDifferentiators: 'Partial agonist optimized for tolerability (less akathisia than aripiprazole); adjunctive MDD role.',
    examHooks: ['Which D2 partial agonist is used to augment antidepressants in MDD and causes less akathisia than aripiprazole? (brexpiprazole)'],
    counsellingPoints: ['Report new urges to gamble, spend, or binge-eat (class effect).', 'It may take a couple of weeks to reach full effect.', 'Watch for restlessness, though usually milder than with similar drugs.'],
    vignettes: [
      {
        stem: 'A 50-year-old with major depression has only partially responded to an adequate SSRI trial. Which of the following is an approved dopamine D2 partial-agonist adjunct associated with less akathisia than its predecessor?',
        options: ['Brexpiprazole', 'Haloperidol', 'Ziprasidone', 'Risperidone LAI'],
        answer: 'Brexpiprazole',
        explanation: 'Brexpiprazole is a D2 partial agonist approved as an adjunct in MDD; its lower D2 intrinsic activity produces less activation/akathisia than aripiprazole.',
        testedFact: 'Brexpiprazole adjunct MDD, less akathisia',
        source: { name: 'openFDA/DailyMed brexpiprazole label — indications (adjunctive MDD)', origin: 'openfda' },
      },
    ],
    _prov: SGA_PROV,
  },

  cariprazine: {
    pronunciation: 'kar-IP-ra-zeen',
    moa: 'Dopamine D3-PREFERRING D2/D3 partial agonist (highest D3 affinity of the class) with 5-HT1A partial agonism and 5-HT2A/2B antagonism.',
    receptorProfile: 'D3-preferring D2/D3 partial agonist, 5-HT1A partial agonist, 5-HT2A/2B antagonist; low H1/muscarinic (metabolically favourable), low prolactin; D3 preference may benefit negative symptoms/anhedonia.',
    onsetOfEffect: 'Days–weeks; onset and offset are slow because of long-lived active metabolites.',
    halfLife: 'Cariprazine ~2–4 days; ACTIVE metabolites (desmethyl- and didesmethyl-cariprazine) very long (~1–3 weeks) → effective half-life of weeks.',
    timeToSteadyState: '~1–3 weeks (driven by the long-lived metabolites).',
    metabolism: 'Hepatic CYP3A4 (and minor 2D6) → avoid strong 3A4 inhibitors/inducers; the didesmethyl metabolite accumulates and clears slowly.',
    foodEffect: 'May be taken with or without food.',
    approvedCanada: ['Schizophrenia', 'Bipolar I disorder — acute manic/mixed episodes AND bipolar I depression'],
    offLabel: ['Adjunctive treatment of major depressive disorder (approved in some jurisdictions)'],
    approvedPopulations: 'Adults.',
    startingDose: '1.5 mg once daily; titrate toward 1.5–6 mg.',
    titration: 'Adjust at intervals of several days but reassess over 1–2 weeks (metabolites accumulate slowly); usual 1.5–6 mg/day.',
    maxDose: '6 mg/day.',
    frequencyTiming: 'Once daily.',
    commonSE: ['Akathisia', 'EPS/parkinsonism', 'Insomnia', 'Nausea', 'Weight-neutral/low metabolic; low prolactin'],
    seriousAE: ['Akathisia/EPS', 'NMS', 'Tardive dyskinesia', 'Late-emerging or persistent adverse effects due to long-lived metabolites', 'Increased mortality/CVA in elderly dementia'],
    syndromes: ['Akathisia/EPS', 'NMS', 'Tardive dyskinesia'],
    overdoseLethality: 'Generally low lethality; note prolonged effects from long-lived metabolites — supportive care.',
    baselineWorkup: ['Weight/BMI and waist circumference', 'Fasting glucose/HbA1c and lipids (usually favourable)', 'Blood pressure', 'Screen for impulse-control tendencies (partial-agonist class)'],
    ongoingMonitoring: 'Metabolic panel per class practice; assess akathisia/EPS; AIMS for tardive dyskinesia; remember effects persist for weeks after stopping (metabolite clearance).',
    majorDDI: ['Strong CYP3A4 inhibitors (ketoconazole) raise levels — dose reduce/avoid', 'Strong CYP3A4 inducers (rifampin, carbamazepine) lower levels', 'Additive CNS depression'],
    contraindicatedCombos: ['Concomitant strong CYP3A4 inhibitors or inducers (per label caution)'],
    pregnancy: 'Limited data; neonatal EPS/withdrawal risk third trimester; note prolonged fetal exposure from long metabolite half-life — weigh untreated illness. Tie to CANMAT perinatal guidance.',
    lactation: 'Limited data; monitor infant.',
    geriatric: 'Increased mortality/stroke in dementia; long-lived metabolites prolong any adverse effect.',
    pearls: [
      'D3-PREFERRING partial agonist — the most D3-selective antipsychotic; theorized benefit for negative symptoms/anhedonia.',
      'Covers BOTH poles of bipolar I (mania/mixed AND depression) — a distinguishing indication among partial agonists.',
      'Very long-lived active metabolites (weeks) → slow onset AND slow offset: dose changes take time to show, and side effects/effects persist long after stopping.',
    ],
    mnemonics: ['"CARIprazine: D3, Covers bipolar (mania + depression), and Carries on for weeks (long metabolites)."'],
    confusables: ['Cariprazine vs aripiprazole/brexpiprazole — all partial agonists; cariprazine is D3-preferring with uniquely long metabolites and both bipolar mania and depression indications.'],
    classDifferentiators: 'D3-preferring partial agonist with the longest effective half-life (weeks) and dual bipolar (mania + depression) coverage; metabolically favourable but EPS/akathisia-prone.',
    examHooks: ['Which partial-agonist antipsychotic is D3-preferring, treats both bipolar mania and depression, and has active metabolites lasting weeks? (cariprazine)'],
    counsellingPoints: ['Effects (good and bad) build and fade slowly over weeks because of long-lasting active metabolites.', 'Report restlessness or muscle stiffness (akathisia/EPS).', 'Do not double up if you feel no immediate effect — it takes time.'],
    vignettes: [
      {
        stem: 'A patient stops cariprazine but continues to experience both therapeutic and adverse effects for several weeks. What property best explains this?',
        options: ['Irreversible receptor binding', 'Active metabolites with very long half-lives', 'Enterohepatic recirculation', 'Autoinduction of metabolism'],
        answer: 'Active metabolites with very long half-lives',
        explanation: 'Cariprazine forms desmethyl- and didesmethyl-cariprazine, active metabolites with half-lives of roughly 1–3 weeks, so effects persist long after the parent drug is stopped.',
        testedFact: 'Cariprazine long-lived active metabolites',
        source: { name: 'openFDA/DailyMed cariprazine label — clinical pharmacology (metabolites)', origin: 'openfda' },
      },
    ],
    _prov: SGA_PROV,
  },
};
