// authored/snri_atypical.js — authored overlay for the SNRIs and atypical antidepressants.
//
// Mechanism/PK/dosing summaries + the pedagogical layer, grounded in established
// pharmacology and the fetched openFDA/monograph label sections. `_prov` declares which
// safety-critical fields the label text grounds; build.js attaches that source text and,
// where a field cannot be grounded, downgrades it to origin 'authored' + verifyFlag.
//
// Group theme: SNRIs add NET blockade to SERT blockade (dose-dependent noradrenergic
// effect → BP rise; worse discontinuation than SSRIs from short half-lives). The atypicals
// each carry a signature receptor twist — bupropion (NDRI: no sexual dysfunction/weight
// gain, seizure risk), mirtazapine (NaSSA: α2 + H1 → sedation/appetite), trazodone (SARI:
// α1 block → priapism/orthostasis), vortioxetine (multimodal: SERT + 5-HT receptor
// modulation). MAOI combination is contraindicated across the group (serotonin syndrome;
// hypertensive risk with bupropion). All raise the FDA young-adult suicidality warning.

const GROUP_PROV = {
  startingDose: 'openfda', maxDose: 'openfda', seriousAE: 'openfda', syndromes: 'openfda',
  majorDDI: 'openfda', contraindicatedCombos: 'openfda', pregnancy: 'openfda',
  overdoseLethality: 'openfda',
};

export default {
  venlafaxine: {
    pronunciation: 'ven-luh-FAX-een',
    moa: 'Serotonin-norepinephrine reuptake inhibitor (blocks SERT and NET). Serotonergic at low doses; the noradrenergic effect is dose-dependent and emerges above ~150 mg/day; weak dopamine reuptake inhibition only at very high doses.',
    receptorProfile: 'SERT >> NET (NET recruited at higher doses); negligible muscarinic/histaminic/α1 — few "off-target" effects but dose-dependent noradrenergic tone.',
    onsetOfEffect: '1–2 wk early effects; 4–6 wk full antidepressant effect.',
    halfLife: 'Venlafaxine ~5 h; active metabolite O-desmethylvenlafaxine (desvenlafaxine) ~11 h — short, hence prominent discontinuation.',
    timeToSteadyState: '~3 days.',
    metabolism: 'Hepatic CYP2D6 → O-desmethylvenlafaxine (active); minor CYP3A4. Weak CYP2D6 inhibitor — fewer interactions than fluoxetine/paroxetine.',
    activeMetabolites: 'O-desmethylvenlafaxine (desvenlafaxine) — itself a marketed SNRI.',
    elimination: 'Renal (parent + metabolites); reduce dose in renal/hepatic impairment.',
    foodEffect: 'Take XR with food to reduce nausea.',
    approvedCanada: ['Major depressive disorder', 'Generalized anxiety disorder', 'Social anxiety disorder', 'Panic disorder'],
    offLabel: ['PTSD', 'Neuropathic pain', 'Menopausal hot flashes'],
    approvedPopulations: 'Adults.',
    startingDose: '37.5–75 mg/day XR (37.5 mg to limit early nausea/activation).',
    titration: 'Increase by ~75 mg at ≥4-day intervals; noradrenergic (BP) effect grows with dose.',
    maxDose: '225 mg/day (XR); up to 375 mg/day (divided IR) in severe hospitalized depression.',
    frequencyTiming: 'XR once daily with food; IR divided BID–TID.',
    renalHepaticAdjustment: 'Reduce dose ~25–50% in significant renal or hepatic impairment.',
    startStopCrossTaper: 'Taper slowly — worst discontinuation syndrome of the SNRIs (short half-life). Missing even one dose can trigger symptoms.',
    administrationNotes: 'Check BP before and during titration, especially above 150 mg/day.',
    commonSE: ['Nausea', 'Headache', 'Insomnia', 'Sweating (diaphoresis)', 'Dry mouth', 'Sexual dysfunction', 'Constipation'],
    seriousAE: ['Dose-dependent hypertension (sustained diastolic BP rise)', 'Serotonin syndrome', 'Hyponatremia/SIADH', 'Increased suicidality (young adults)', 'Bleeding risk', 'Severe discontinuation syndrome'],
    syndromes: ['Serotonin syndrome', 'SNRI discontinuation (worst-in-class)', 'SIADH/hyponatremia', 'Dose-dependent hypertension'],
    overdoseLethality: 'More toxic in overdose than SSRIs — seizures, serotonin toxicity, and cardiotoxicity (QRS/QT changes, arrhythmia) reported in large ingestions.',
    discontinuationSyndrome: 'Prominent — dizziness, nausea, irritability, flu-like symptoms and "brain zaps"; the short half-life makes it the most abrupt of the SNRIs. Taper.',
    baselineWorkup: ['Baseline blood pressure (repeat during titration)'],
    ongoingMonitoring: 'Blood pressure at each dose increase; mood/suicidality; sodium if hyponatremia symptoms.',
    majorDDI: ['MAOIs (contraindicated — serotonin syndrome)', 'Other serotonergics (triptans, tramadol, linezolid)', 'CYP2D6 inhibitors (raise venlafaxine, lower active metabolite)', 'NSAIDs/anticoagulants — bleeding'],
    contraindicatedCombos: ['MAOIs (within 14 days each way)'],
    maoiWashout: '14 days each way.',
    pregnancy: 'No consistent major teratogenic signal; late-pregnancy exposure may cause neonatal adaptation/discontinuation symptoms. Weigh untreated illness — tie to CANMAT perinatal guidance.',
    lactation: 'Excreted into milk (parent + active metabolite); monitor infant. Sertraline often preferred if initiating in lactation.',
    geriatric: 'Watch blood pressure and hyponatremia; renal dose adjustment.',
    cardiac: 'Dose-dependent hypertension and overdose cardiotoxicity — monitor BP; caution in uncontrolled hypertension.',
    pearls: [
      'Noradrenergic (and BP) effect is DOSE-DEPENDENT — check blood pressure as you titrate above ~150 mg/day.',
      'Worst discontinuation syndrome of the antidepressants because of the very short half-life — never stop abruptly.',
      'More dangerous in overdose than SSRIs (seizures, cardiotoxicity).',
    ],
    mnemonics: ['"Venlafaxine → Vitals": watch the blood pressure as the dose climbs; Very short half-life = Vicious withdrawal.'],
    confusables: ['Venlafaxine vs desvenlafaxine — desvenlafaxine IS venlafaxine\'s active metabolite (bypasses CYP2D6).'],
    classDifferentiators: 'The prototype SNRI: dose-dependent noradrenergic effect and hypertension, shortest half-life → worst discontinuation.',
    examHooks: ['Which antidepressant needs blood-pressure monitoring as the dose increases? (venlafaxine)', 'Worst discontinuation syndrome among antidepressants? (venlafaxine)'],
    counsellingPoints: ['Take the XR capsule with food.', 'Do not stop suddenly — even a missed dose can cause dizziness/"zaps".', 'We will monitor your blood pressure.'],
    vignettes: [
      {
        stem: 'A 48-year-old with depression is titrated to venlafaxine XR 225 mg/day. At follow-up his blood pressure is 148/96 (previously normal). What is the best explanation?',
        options: ['Serotonin syndrome', 'Dose-dependent noradrenergic effect of venlafaxine', 'White-coat hypertension only', 'Anticholinergic effect'],
        answer: 'Dose-dependent noradrenergic effect of venlafaxine',
        explanation: 'Venlafaxine recruits norepinephrine reuptake inhibition at higher doses, producing dose-dependent, sustained increases in blood pressure — monitoring BP during titration is standard.',
        testedFact: 'Venlafaxine dose-dependent hypertension',
        source: { name: 'openFDA/DailyMed venlafaxine label — warnings (blood pressure)', origin: 'openfda' },
      },
    ],
    _prov: GROUP_PROV,
  },

  desvenlafaxine: {
    pronunciation: 'des-ven-luh-FAX-een',
    moa: 'Serotonin-norepinephrine reuptake inhibitor (blocks SERT and NET); it is the major active metabolite (O-desmethylvenlafaxine) of venlafaxine.',
    receptorProfile: 'SERT > NET; negligible muscarinic/histaminic/α1.',
    onsetOfEffect: '1–2 wk early; 4–6 wk full effect.',
    halfLife: '~11 hours.',
    timeToSteadyState: '~4–5 days.',
    metabolism: 'Primarily conjugation (phase II glucuronidation, UGT); only minor oxidative (CYP3A4) metabolism and essentially NO CYP2D6 dependence → predictable levels and few interactions.',
    activeMetabolites: 'None of clinical significance (it is itself venlafaxine\'s active metabolite).',
    elimination: 'Renal (~45% excreted unchanged); reduce dose in renal impairment.',
    foodEffect: 'May be taken with or without food.',
    approvedCanada: ['Major depressive disorder'],
    offLabel: ['Menopausal vasomotor symptoms', 'Generalized anxiety disorder'],
    approvedPopulations: 'Adults.',
    startingDose: '50 mg PO once daily (also the usual target dose — flat dose-response, no titration needed for most).',
    titration: 'Higher doses add little efficacy but more adverse effects; 50 mg is the recommended dose.',
    maxDose: '100 mg/day for most patients (higher doses studied without added antidepressant benefit).',
    frequencyTiming: 'Once daily, same time each day.',
    renalHepaticAdjustment: 'Reduce/space dosing in moderate–severe renal impairment (e.g., 50 mg every other day); modest hepatic adjustment.',
    startStopCrossTaper: 'Taper to limit discontinuation (short half-life like venlafaxine).',
    administrationNotes: 'Extended-release tablet — swallow whole; a matrix "ghost tablet" may appear in stool.',
    commonSE: ['Nausea', 'Dizziness', 'Sweating', 'Insomnia', 'Constipation', 'Sexual dysfunction'],
    seriousAE: ['Dose-dependent hypertension', 'Serotonin syndrome', 'Hyponatremia/SIADH', 'Increased suicidality (young adults)', 'Bleeding risk'],
    syndromes: ['Serotonin syndrome', 'SNRI discontinuation', 'SIADH/hyponatremia', 'Dose-dependent hypertension'],
    overdoseLethality: 'As an SNRI, more concerning than SSRIs (seizures, serotonin toxicity, cardiac effects) but data limited; treat as venlafaxine.',
    discontinuationSyndrome: 'Similar to venlafaxine — taper.',
    baselineWorkup: ['Baseline blood pressure'],
    ongoingMonitoring: 'Blood pressure; mood/suicidality; sodium if symptomatic.',
    majorDDI: ['MAOIs (contraindicated)', 'Other serotonergics', 'NSAIDs/anticoagulants — bleeding'],
    contraindicatedCombos: ['MAOIs (within 14 days each way)'],
    maoiWashout: '14 days each way.',
    pregnancy: 'Treat as venlafaxine — no consistent major teratogenic signal; possible neonatal adaptation late in pregnancy. Weigh untreated illness.',
    lactation: 'Excreted into milk; monitor infant.',
    geriatric: 'Watch BP and hyponatremia; adjust for renal function.',
    pearls: [
      'It IS venlafaxine\'s active metabolite — so it bypasses CYP2D6, giving predictable levels and few drug interactions (useful in CYP2D6 poor metabolizers or on 2D6 inhibitors).',
      'Flat dose-response: 50 mg/day is both start and target — going higher mostly adds side effects.',
      'Still an SNRI — dose-dependent BP rise and discontinuation apply.',
    ],
    mnemonics: ['"DES-venlafaxine = venlafaxine minus the CYP" — the DEmethylated metabolite, minimal CYP2D6.'],
    confusables: ['Desvenlafaxine vs venlafaxine — same molecule downstream; desvenlafaxine avoids the 2D6 step.'],
    classDifferentiators: 'The metabolically "clean" SNRI — minimal CYP metabolism, predictable kinetics, flat dosing.',
    examHooks: ['Which SNRI is chosen to avoid CYP2D6 variability/interactions? (desvenlafaxine)'],
    counsellingPoints: ['One tablet daily; no titration usually needed.', 'You may see a tablet shell in your stool — the drug is absorbed.', 'Do not stop abruptly.'],
    vignettes: [
      {
        stem: 'A patient is a CYP2D6 poor metabolizer and takes several CYP2D6-inhibiting drugs. Which SNRI has the most predictable levels because it is minimally CYP-metabolized?',
        options: ['Venlafaxine', 'Duloxetine', 'Desvenlafaxine', 'Levomilnacipran'],
        answer: 'Desvenlafaxine',
        explanation: 'Desvenlafaxine is cleared mainly by glucuronidation with minimal CYP (especially 2D6) involvement, so its levels are largely independent of CYP2D6 status and inhibitors.',
        testedFact: 'Desvenlafaxine minimal CYP2D6 metabolism',
        source: { name: 'openFDA/DailyMed desvenlafaxine label — clinical pharmacology (metabolism)', origin: 'openfda' },
      },
    ],
    _prov: GROUP_PROV,
  },

  duloxetine: {
    pronunciation: 'doo-LOX-uh-teen',
    moa: 'Serotonin-norepinephrine reuptake inhibitor (blocks SERT and NET) with a relatively balanced 5-HT/NE effect across the usual dose range; the noradrenergic action also mediates its analgesic effect.',
    receptorProfile: 'SERT and NET affinity (more balanced than venlafaxine at usual doses); negligible off-target receptor binding.',
    onsetOfEffect: 'Mood: 4–6 wk. Neuropathic/fibromyalgia pain: often within 1–4 wk (independent of mood).',
    halfLife: '~12 hours.',
    timeToSteadyState: '~3 days.',
    metabolism: 'Hepatic CYP1A2 (major) and CYP2D6; moderate CYP2D6 inhibitor. Smoking (a CYP1A2 inducer) lowers duloxetine levels.',
    activeMetabolites: 'Numerous metabolites, none clinically important.',
    elimination: 'Renal (metabolites); avoid in severe renal impairment (CrCl <30).',
    foodEffect: 'May be taken with or without food (food slightly delays absorption).',
    approvedCanada: ['Major depressive disorder', 'Generalized anxiety disorder', 'Diabetic peripheral neuropathic pain', 'Fibromyalgia', 'Chronic musculoskeletal pain'],
    offLabel: ['Stress urinary incontinence', 'Chemotherapy-induced neuropathy'],
    approvedPopulations: 'Adults.',
    startingDose: '30–60 mg/day (start 30 mg to improve tolerability, then 60 mg).',
    titration: 'Increase to 60 mg/day; 60 mg is usually optimal for depression — higher doses add side effects more than efficacy.',
    maxDose: '120 mg/day.',
    frequencyTiming: 'Once daily (may divide BID); delayed-release capsule swallowed whole.',
    renalHepaticAdjustment: 'Avoid in significant hepatic impairment and in severe renal impairment (CrCl <30 mL/min).',
    startStopCrossTaper: 'Taper to limit discontinuation.',
    administrationNotes: 'Do not crush/chew the enteric-coated capsule.',
    commonSE: ['Nausea', 'Dry mouth', 'Constipation', 'Somnolence or insomnia', 'Sweating', 'Decreased appetite', 'Sexual dysfunction'],
    seriousAE: ['Hepatotoxicity (avoid in hepatic disease / heavy alcohol use)', 'Serotonin syndrome', 'Hypertension', 'Hyponatremia/SIADH', 'Increased suicidality (young adults)', 'Bleeding risk'],
    syndromes: ['Serotonin syndrome', 'Hepatotoxicity', 'SNRI discontinuation', 'SIADH/hyponatremia'],
    overdoseLethality: 'SNRI overdose — seizures, serotonin toxicity, and cardiac effects possible; more concerning than SSRIs.',
    discontinuationSyndrome: 'Moderate — dizziness, nausea, irritability, paresthesias; taper.',
    baselineWorkup: ['Blood pressure', 'Consider LFTs / alcohol history given hepatotoxicity risk'],
    ongoingMonitoring: 'Blood pressure; watch for hepatic signs (jaundice, RUQ pain); mood/suicidality; sodium if symptomatic.',
    majorDDI: ['MAOIs (contraindicated)', 'Potent CYP1A2 inhibitors (fluvoxamine, ciprofloxacin) markedly raise levels', 'CYP2D6 substrates (duloxetine inhibits 2D6)', 'Other serotonergics', 'NSAIDs/anticoagulants — bleeding'],
    contraindicatedCombos: ['MAOIs (within 14 days each way)', 'Potent CYP1A2 inhibitors (e.g., fluvoxamine — avoid combination)'],
    maoiWashout: '14 days each way.',
    pregnancy: 'Limited data; possible neonatal adaptation late in pregnancy. Weigh untreated illness — tie to CANMAT perinatal guidance.',
    lactation: 'Low relative infant dose; monitor infant.',
    geriatric: 'Watch hyponatremia, BP, falls; renal/hepatic caution.',
    renalHepatic: 'Avoid in hepatic impairment and significant alcohol use (hepatotoxicity); avoid in severe renal impairment (CrCl <30).',
    pearls: [
      'The SNRI with strong pain indications — diabetic neuropathy, fibromyalgia, chronic musculoskeletal pain (analgesia is partly noradrenergic and can precede mood benefit).',
      'Hepatotoxicity — avoid in liver disease or substantial alcohol use.',
      'CYP1A2 substrate: smoking lowers levels; fluvoxamine (potent 1A2 inhibitor) dangerously raises them.',
    ],
    mnemonics: ['"Duloxetine does DOLOR (pain)" — dual reuptake for neuropathy/fibromyalgia; "Don\'t Use in Liver."'],
    confusables: ['Duloxetine vs venlafaxine — duloxetine has the pain indications and a hepatotoxicity/CYP1A2 profile; venlafaxine is BP/discontinuation-forward.'],
    classDifferentiators: 'Balanced SNRI with formal chronic-pain indications; hepatotoxicity caution; CYP1A2 + 2D6 involvement.',
    examHooks: ['SNRI of choice when depression coexists with diabetic neuropathy or fibromyalgia? (duloxetine)', 'Which SNRI is avoided in hepatic impairment / heavy alcohol use? (duloxetine)'],
    counsellingPoints: ['Swallow the capsule whole.', 'Avoid heavy alcohol; report yellowing of skin/eyes.', 'Pain relief can appear before mood improves.'],
    vignettes: [
      {
        stem: 'A 58-year-old with major depression also has painful diabetic peripheral neuropathy. Which single antidepressant best addresses both?',
        options: ['Sertraline', 'Duloxetine', 'Bupropion', 'Mirtazapine'],
        answer: 'Duloxetine',
        explanation: 'Duloxetine is an SNRI approved for both depression and diabetic peripheral neuropathic pain (and fibromyalgia); its noradrenergic action underlies the analgesic effect.',
        testedFact: 'Duloxetine dual depression + neuropathic pain indication',
        source: { name: 'openFDA/DailyMed duloxetine label — indications', origin: 'openfda' },
      },
    ],
    _prov: GROUP_PROV,
  },

  levomilnacipran: {
    pronunciation: 'LEE-voh-mil-NAS-ip-ran',
    moa: 'Serotonin-norepinephrine reuptake inhibitor; the active enantiomer of milnacipran. Relatively MORE noradrenergic — greater potency at NET than SERT (the reverse of most SNRIs).',
    receptorProfile: 'NET > SERT selectivity; negligible off-target receptor activity.',
    onsetOfEffect: '1–2 wk early; 4–6 wk full effect.',
    halfLife: '~12 hours.',
    timeToSteadyState: '~2–3 days.',
    metabolism: 'Hepatic CYP3A4 (major); not a significant CYP inhibitor.',
    activeMetabolites: 'None clinically important.',
    elimination: 'Renal (~58% excreted unchanged); dose-cap in renal impairment.',
    foodEffect: 'May be taken with or without food; swallow ER capsule whole.',
    approvedCanada: ['Major depressive disorder'],
    offLabel: [],
    approvedPopulations: 'Adults.',
    startingDose: '20 mg PO once daily for 2 days, then 40 mg once daily (ER).',
    titration: 'Increase by 40 mg at ≥2-day intervals as tolerated; usual range 40–120 mg/day.',
    maxDose: '120 mg/day.',
    frequencyTiming: 'Once daily; ER capsule swallowed whole.',
    renalHepaticAdjustment: 'Renal dose caps — max 80 mg/day (moderate) and 40 mg/day (severe renal impairment). No adjustment for hepatic impairment.',
    startStopCrossTaper: 'Taper to limit discontinuation.',
    administrationNotes: 'Assess for urinary hesitancy (noradrenergic) before/during use.',
    commonSE: ['Nausea', 'Constipation', 'Sweating', 'Tachycardia/palpitations', 'Urinary hesitancy', 'Erectile dysfunction', 'Increased blood pressure'],
    seriousAE: ['Hypertension and tachycardia (noradrenergic)', 'Serotonin syndrome', 'Urinary retention', 'Hyponatremia/SIADH', 'Increased suicidality (young adults)'],
    syndromes: ['Serotonin syndrome', 'Dose-dependent hypertension/tachycardia', 'SNRI discontinuation', 'SIADH/hyponatremia'],
    overdoseLethality: 'Limited data; expect SNRI-type toxicity (serotonin/noradrenergic effects, seizures).',
    discontinuationSyndrome: 'Taper — SNRI-class discontinuation.',
    baselineWorkup: ['Blood pressure and heart rate'],
    ongoingMonitoring: 'Blood pressure and heart rate; urinary symptoms; mood/suicidality.',
    majorDDI: ['MAOIs (contraindicated)', 'Strong CYP3A4 inhibitors (e.g., ketoconazole) raise levels — cap dose', 'Other serotonergics', 'Sympathomimetics (additive noradrenergic effect)'],
    contraindicatedCombos: ['MAOIs (within 14 days each way)'],
    maoiWashout: '14 days each way.',
    pregnancy: 'Limited data; weigh untreated illness. Possible neonatal adaptation late in pregnancy.',
    lactation: 'Limited data; monitor infant.',
    geriatric: 'Watch BP/HR, urinary retention; renal dose caps.',
    cardiac: 'More noradrenergic — expect the greatest heart-rate/BP effect of the SNRIs; monitor.',
    pearls: [
      'The MOST noradrenergic SNRI (NET > SERT) — so expect more tachycardia, BP rise and urinary hesitancy than serotonergic-leaning SNRIs.',
      'Active enantiomer of milnacipran; CYP3A4-metabolized (cap dose with strong 3A4 inhibitors and in renal impairment).',
      'Twice-daily 20 mg for the first 2 days is a deliberate tolerability step before once-daily 40 mg.',
    ],
    mnemonics: ['"Levomilnacipran = Levo/NE-heavy" — the norepinephrine-leaning SNRI (racing heart, urinary hesitancy).'],
    confusables: ['Levomilnacipran (MDD) vs milnacipran (marketed for fibromyalgia) — enantiomer vs racemate.'],
    classDifferentiators: 'The noradrenergic-predominant SNRI; CYP3A4 substrate with renal dose caps.',
    examHooks: ['Which SNRI is the most noradrenergic (NET > SERT)? (levomilnacipran)'],
    counsellingPoints: ['Swallow the capsule whole.', 'Report a racing heart, trouble urinating, or high blood-pressure readings.', 'Do not stop abruptly.'],
    vignettes: [
      {
        stem: 'A patient started on an SNRI develops notable tachycardia and urinary hesitancy, effects reflecting predominant norepinephrine reuptake inhibition. Which agent is most consistent with this?',
        options: ['Levomilnacipran', 'Sertraline', 'Desvenlafaxine', 'Vortioxetine'],
        answer: 'Levomilnacipran',
        explanation: 'Levomilnacipran is the most noradrenergic SNRI (greater NET than SERT potency), so noradrenergic effects such as tachycardia, raised BP and urinary hesitancy are more prominent.',
        testedFact: 'Levomilnacipran noradrenergic predominance',
        source: { name: 'openFDA/DailyMed levomilnacipran label — clinical pharmacology', origin: 'openfda' },
      },
    ],
    _prov: GROUP_PROV,
  },

  bupropion: {
    pronunciation: 'byoo-PROH-pee-on',
    moa: 'Norepinephrine-dopamine reuptake inhibitor (NDRI) — blocks NET and DAT; also a nicotinic acetylcholine receptor antagonist (basis for smoking cessation). No direct serotonergic activity.',
    receptorProfile: 'NET/DAT reuptake inhibition; nicotinic antagonism; negligible histaminic/muscarinic/α1 — hence activating and weight-neutral.',
    onsetOfEffect: '1–2 wk early (energy/activation); 4–6 wk full antidepressant effect.',
    halfLife: 'Bupropion ~21 h; active metabolite hydroxybupropion ~20 h.',
    timeToSteadyState: '~5–8 days (including metabolite).',
    metabolism: 'Hepatic CYP2B6 → hydroxybupropion (active). Bupropion and hydroxybupropion are POTENT CYP2D6 INHIBITORS.',
    activeMetabolites: 'Hydroxybupropion (active; contributes substantially to effect).',
    foodEffect: 'May be taken with or without food; SR/XL swallowed whole.',
    approvedCanada: ['Major depressive disorder', 'Seasonal affective disorder', 'Smoking cessation (as Zyban)'],
    offLabel: ['Adjunct for SSRI-induced sexual dysfunction', 'ADHD (adjunct)', 'Antidepressant augmentation'],
    approvedPopulations: 'Adults.',
    startingDose: 'SR 150 mg PO in the AM; XL 150 mg PO in the AM.',
    titration: 'SR: to 150 mg BID after ~1 week (doses ≥8 h apart). XL: to 300 mg once daily. Keep single doses low to limit seizure risk.',
    maxDose: 'SR 400 mg/day; XL 450 mg/day (single SR dose ≤200 mg).',
    frequencyTiming: 'Morning dosing (activating); avoid late doses (insomnia). Space SR doses to reduce peak-related seizure risk.',
    startStopCrossTaper: 'No serotonergic discontinuation syndrome; can generally stop without a serotonin-type taper.',
    administrationNotes: 'Do not crush/split SR/XL tablets — defeats controlled release and raises seizure risk.',
    commonSE: ['Insomnia', 'Agitation/activation/anxiety', 'Dry mouth', 'Headache', 'Tremor', 'Decreased appetite/weight loss', 'Constipation'],
    seriousAE: ['Dose-dependent SEIZURES (lowered threshold)', 'Hypertension', 'Psychosis/agitation/activation', 'Increased suicidality (young adults)'],
    syndromes: ['Seizure (dose-dependent)', 'Activation/agitation', 'Hypertension'],
    overdoseLethality: 'Seizures and cardiac/QRS effects in overdose; can be dangerous in large ingestions (seizure risk exceeds SSRIs).',
    discontinuationSyndrome: 'Minimal serotonergic discontinuation; abrupt stop generally tolerated.',
    baselineWorkup: ['Screen for seizure risk and eating-disorder history', 'Blood pressure'],
    ongoingMonitoring: 'Mood/activation/suicidality; blood pressure (especially if combined with nicotine patch).',
    majorDDI: ['MAOIs (contraindicated — hypertensive risk)', 'CYP2D6 substrates (bupropion inhibits 2D6 → raises TCAs, atomoxetine, metoprolol, risperidone; lowers tamoxifen activation)', 'Drugs that lower seizure threshold (additive)', 'CYP2B6 inducers/inhibitors alter levels'],
    contraindicatedCombos: ['MAOIs (within 14 days each way)'],
    maoiWashout: '14 days each way.',
    pregnancy: 'No strong teratogenic signal; sometimes used when smoking cessation is also a goal. Weigh untreated illness.',
    lactation: 'Excreted into milk; monitor infant (rare seizure reports).',
    geriatric: 'Reasonable (weight-neutral, no anticholinergic/sexual effects) but watch seizure risk and agitation/insomnia.',
    pearls: [
      'No sexual dysfunction and no weight gain (often weight loss) — favoured when those SSRI effects are limiting, and as an augmenting agent for SSRI-induced sexual dysfunction.',
      'Lowers the seizure threshold — CONTRAINDICATED in seizure disorders and in eating disorders (bulimia/anorexia) and with abrupt alcohol/benzodiazepine withdrawal.',
      'Activating (energizing, can worsen anxiety/insomnia); also a potent CYP2D6 inhibitor and a smoking-cessation aid (Zyban).',
    ],
    mnemonics: ['"Bupropion = the exception": no Sex/weight problems, but Seizures and eating disorders say NO."'],
    confusables: ['Bupropion (NDRI, activating, no sexual SE) vs buspirone (5-HT1A partial agonist anxiolytic) — sound-alike, unrelated.'],
    classDifferentiators: 'The dopaminergic/noradrenergic outlier: activating, weight-neutral, no sexual dysfunction, no serotonin syndrome — but seizure-threshold lowering.',
    examHooks: ['Antidepressant with no sexual dysfunction and no weight gain? (bupropion)', 'Antidepressant contraindicated in bulimia/anorexia and seizure disorder? (bupropion)'],
    counsellingPoints: ['Take in the morning to avoid insomnia; swallow tablets whole.', 'Tell us about any seizures or eating-disorder history.', 'It should not cause sexual side effects or weight gain.'],
    vignettes: [
      {
        stem: 'A 26-year-old woman with depression and a history of bulimia nervosa needs an antidepressant. Which agent is CONTRAINDICATED?',
        options: ['Sertraline', 'Bupropion', 'Escitalopram', 'Mirtazapine'],
        answer: 'Bupropion',
        explanation: 'Bupropion lowers the seizure threshold and is contraindicated in patients with eating disorders (bulimia/anorexia) — who are prone to electrolyte disturbance and seizures — as well as in seizure disorders.',
        testedFact: 'Bupropion contraindicated in eating disorders (seizure risk)',
        source: { name: 'openFDA/DailyMed bupropion label — contraindications/warnings (seizure)', origin: 'openfda' },
      },
    ],
    _prov: GROUP_PROV,
  },

  mirtazapine: {
    pronunciation: 'mur-TAZ-uh-peen',
    moa: 'Noradrenergic and specific serotonergic antidepressant (NaSSA): central presynaptic α2-adrenergic antagonist → increases NE and 5-HT release; additionally blocks postsynaptic 5-HT2A, 5-HT2C and 5-HT3 receptors and is a potent H1 antihistamine.',
    receptorProfile: 'α2 antagonist; 5-HT2A/2C and 5-HT3 antagonist; POTENT H1 antagonist (sedation/appetite). 5-HT3 block → antiemetic and less nausea/sexual dysfunction than SSRIs.',
    onsetOfEffect: 'Sleep/appetite benefit within days; 2–4 wk for mood; 4–6 wk full effect.',
    halfLife: '~20–40 hours.',
    timeToSteadyState: '~5 days.',
    metabolism: 'Hepatic CYP2D6, CYP1A2 and CYP3A4 (substrate); not a significant CYP inhibitor.',
    activeMetabolites: 'Desmethylmirtazapine (weakly active).',
    foodEffect: 'May be taken with or without food; an orally disintegrating tablet is available.',
    approvedCanada: ['Major depressive disorder'],
    offLabel: ['Insomnia', 'Depression with poor appetite/weight loss', 'Antidepressant augmentation ("California rocket fuel" with venlafaxine)', 'Nausea'],
    approvedPopulations: 'Adults.',
    startingDose: '15 mg PO at bedtime.',
    titration: 'Increase to 30–45 mg at ≥1–2-week intervals as needed.',
    maxDose: '45 mg/day.',
    frequencyTiming: 'Once daily at bedtime (sedation). Paradoxically, LOW doses can be MORE sedating (H1 effect dominates; higher doses add offsetting noradrenergic tone).',
    startStopCrossTaper: 'Taper to limit discontinuation; can be combined with an SSRI/SNRI for augmentation.',
    administrationNotes: 'Bedtime dosing exploits sedation for insomnia and appetite for weight loss/cachexia.',
    commonSE: ['Sedation/somnolence', 'Increased appetite and weight gain', 'Dry mouth', 'Dizziness', 'Constipation', 'Increased cholesterol/triglycerides'],
    seriousAE: ['Agranulocytosis/neutropenia (rare)', 'Serotonin syndrome', 'Hyponatremia/SIADH', 'Increased suicidality (young adults)'],
    syndromes: ['Agranulocytosis (rare)', 'Serotonin syndrome', 'Metabolic effects (weight/lipids)', 'SIADH/hyponatremia'],
    overdoseLethality: 'Relatively safe in overdose alone (sedation the main effect); more dangerous with co-ingestants.',
    discontinuationSyndrome: 'Generally mild; taper.',
    baselineWorkup: ['Weight/BMI', 'Consider baseline lipids given metabolic effect'],
    ongoingMonitoring: 'Weight and lipids; CBC if signs of infection (fever, sore throat — possible agranulocytosis); mood/suicidality.',
    majorDDI: ['MAOIs (contraindicated)', 'Other serotonergics', 'CNS depressants/alcohol (additive sedation)', 'CYP3A4/1A2 inhibitors raise levels'],
    contraindicatedCombos: ['MAOIs (within 14 days each way)'],
    maoiWashout: '14 days each way.',
    pregnancy: 'Limited data; no strong teratogenic signal. Weigh untreated illness — sometimes used for hyperemesis/poor intake.',
    lactation: 'Low relative infant dose; monitor sedation/weight gain in infant.',
    geriatric: 'Useful for depression with insomnia/poor appetite/weight loss; watch sedation, falls and hyponatremia.',
    pearls: [
      'Sedation and appetite/weight gain are WORSE at LOW doses — the potent H1 antihistamine effect dominates until higher doses add offsetting noradrenergic drive.',
      'Best for depression with insomnia, poor appetite or weight loss (cachexia); 5-HT3 blockade gives antiemetic effect and less nausea/sexual dysfunction than SSRIs.',
      'Rare but serious agranulocytosis — tell patients to report fever/sore throat.',
    ],
    mnemonics: ['"Mirtazapine = More at night, More munchies" — sedation + appetite, strongest at LOW dose; the "M" is for Munchies and Metabolic gain.'],
    confusables: ['Mirtazapine vs mianserin (related tetracyclic) and vs trazodone — all sedating atypicals but different receptor targets.'],
    classDifferentiators: 'Presynaptic α2 antagonist (not a reuptake inhibitor): sedation + appetite (LOW-dose predominant), antiemetic, low sexual dysfunction, rare agranulocytosis.',
    examHooks: ['Antidepressant that helps insomnia, poor appetite and nausea, and is MORE sedating at LOW dose? (mirtazapine)', 'Which antidepressant causes rare agranulocytosis? (mirtazapine)'],
    counsellingPoints: ['Take at bedtime — it helps sleep and appetite.', 'Expect possible weight gain; we will track weight and lipids.', 'Report fever or sore throat promptly (rare blood-count effect).'],
    vignettes: [
      {
        stem: 'A depressed 70-year-old with insomnia, 6 kg unintentional weight loss and poor appetite needs an antidepressant. Which best targets all three problems?',
        options: ['Fluoxetine', 'Bupropion', 'Mirtazapine', 'Venlafaxine'],
        answer: 'Mirtazapine',
        explanation: 'Mirtazapine\'s potent H1 antihistamine and 5-HT2C/5-HT3 effects promote sleep and appetite/weight gain, making it well suited to depression with insomnia and weight loss — often chosen in older adults with these features.',
        testedFact: 'Mirtazapine for depression with insomnia/anorexia/weight loss',
        source: { name: 'CANMAT 2016 MDD; mirtazapine pharmacology', origin: 'canmat' },
      },
    ],
    _prov: GROUP_PROV,
  },

  trazodone: {
    pronunciation: 'TRAZ-oh-done',
    moa: 'Serotonin antagonist and reuptake inhibitor (SARI): postsynaptic 5-HT2A antagonism plus (dose-dependent) SERT inhibition. Also α1-adrenergic and H1 antagonism — the basis for its sedative/hypnotic and orthostatic effects at low doses.',
    receptorProfile: '5-HT2A antagonist; α1-adrenergic antagonist (orthostasis, priapism); H1 antagonist (sedation); SERT inhibition mainly at higher (antidepressant) doses.',
    onsetOfEffect: 'Hypnotic effect same night; antidepressant effect 2–4 wk (needs higher doses many cannot tolerate).',
    halfLife: '~7–10 hours (biphasic).',
    timeToSteadyState: '~3 days.',
    metabolism: 'Hepatic CYP3A4 (substrate) → active metabolite mCPP (via CYP2D6). CYP3A4 inhibitors raise levels (sedation/QT).',
    activeMetabolites: 'm-Chlorophenylpiperazine (mCPP) — a 5-HT2C agonist that can cause anxiety/migraine-like effects.',
    foodEffect: 'Take with food to slow absorption and reduce dizziness/light-headedness.',
    approvedCanada: ['Major depressive disorder'],
    offLabel: ['Insomnia (low-dose, very common)', 'Augmentation of other antidepressants'],
    approvedPopulations: 'Adults.',
    startingDose: 'Insomnia (off-label): 25–50 mg at bedtime. Depression: 150 mg/day in divided doses, titrate up.',
    titration: 'For depression, increase by ~50 mg every few days as tolerated; sedation often limits dosing.',
    maxDose: '400 mg/day (outpatient); up to 600 mg/day (inpatient).',
    frequencyTiming: 'Bedtime (sedating); divided dosing with food for higher antidepressant doses.',
    startStopCrossTaper: 'Taper if on antidepressant doses; low hypnotic doses usually stopped without serotonergic withdrawal.',
    administrationNotes: 'Widely used as a non-habit-forming hypnotic at low dose — but antidepressant efficacy needs doses that are often too sedating.',
    commonSE: ['Sedation/somnolence (prominent)', 'Orthostatic hypotension/dizziness', 'Dry mouth', 'Headache', 'Nausea', 'Blurred vision'],
    seriousAE: ['PRIAPISM (urologic emergency)', 'Orthostatic hypotension/syncope', 'QT prolongation/arrhythmia', 'Serotonin syndrome', 'Increased suicidality (young adults)'],
    syndromes: ['Priapism', 'Orthostatic hypotension', 'QT prolongation', 'Serotonin syndrome'],
    overdoseLethality: 'Relatively less lethal than TCAs but CNS depression, hypotension and QT/arrhythmia can occur; danger increases with co-ingestants.',
    discontinuationSyndrome: 'Mild at hypnotic doses; taper antidepressant doses.',
    ongoingMonitoring: 'Orthostatic BP; mood/suicidality; ECG if cardiac/QT risk.',
    majorDDI: ['MAOIs (contraindicated)', 'Strong CYP3A4 inhibitors (ritonavir, ketoconazole) raise levels', 'Other QT-prolonging drugs (additive)', 'Antihypertensives/α-blockers (additive hypotension)', 'Other serotonergics'],
    contraindicatedCombos: ['MAOIs (within 14 days each way)'],
    maoiWashout: '14 days each way.',
    pregnancy: 'Limited data; no strong teratogenic signal. Weigh untreated illness.',
    lactation: 'Limited data; monitor infant sedation.',
    geriatric: 'Common low-dose hypnotic, but orthostatic hypotension → falls risk; use cautiously.',
    cardiac: 'Can prolong QT and cause orthostatic hypotension; caution with cardiac disease/other QT drugs.',
    pearls: [
      'PRIAPISM is the classic board fact — α1 blockade; warn men to seek emergency care for an erection lasting >4 hours.',
      'Used mainly as a low-dose hypnotic; antidepressant doses are often too sedating and cause orthostatic hypotension.',
      'α1-adrenergic blockade also explains the orthostatic hypotension/dizziness.',
    ],
    mnemonics: ['"traZODone → ZZZ (sleep) but watch the erection that won\'t quit (priapism) and the drop on standing (orthostasis)."'],
    confusables: ['Trazodone vs nefazodone — both SARIs; nefazodone carries a hepatotoxicity black-box and is rarely used.'],
    classDifferentiators: 'The sedating SARI hypnotic — 5-HT2A/α1/H1 block; signature priapism and orthostatic hypotension; sub-therapeutic-dose sleep use.',
    examHooks: ['Antidepressant/hypnotic associated with priapism? (trazodone)', 'Which sedating antidepressant is limited by orthostatic hypotension? (trazodone)'],
    counsellingPoints: ['Take at bedtime with a snack; rise slowly to avoid dizziness.', 'Men: an erection lasting over 4 hours is an emergency — go to the ER.', 'Expect drowsiness, especially early on.'],
    vignettes: [
      {
        stem: 'A 45-year-old man on an antidepressant for insomnia presents with a painful erection lasting 5 hours. Which drug is the most likely cause?',
        options: ['Sertraline', 'Trazodone', 'Bupropion', 'Mirtazapine'],
        answer: 'Trazodone',
        explanation: 'Trazodone\'s α1-adrenergic antagonism can cause priapism, a urologic emergency; patients should be warned to seek immediate care for a prolonged erection.',
        testedFact: 'Trazodone-induced priapism',
        source: { name: 'openFDA/DailyMed trazodone label — warnings (priapism)', origin: 'openfda' },
      },
    ],
    _prov: GROUP_PROV,
  },

  vortioxetine: {
    pronunciation: 'vor-tee-OX-uh-teen',
    moa: 'Multimodal antidepressant: serotonin reuptake inhibition (SERT) PLUS direct 5-HT receptor modulation — 5-HT3, 5-HT7 and 5-HT1D antagonism, 5-HT1B partial agonism and 5-HT1A agonism.',
    receptorProfile: 'SERT inhibitor; 5-HT1A agonist; 5-HT1B partial agonist; 5-HT3/5-HT7/5-HT1D antagonist. The 5-HT3 block (like ondansetron) shapes its GI/nausea profile.',
    onsetOfEffect: '1–2 wk early; 4–6 wk full antidepressant effect.',
    halfLife: '~66 hours (long).',
    timeToSteadyState: '~2 weeks.',
    metabolism: 'Hepatic CYP2D6 (primary) then further oxidation/conjugation. CYP2D6 poor metabolizers or strong 2D6 inhibitors raise levels — cap at 10 mg with a strong 2D6 inhibitor.',
    activeMetabolites: 'Principal metabolite is inactive.',
    foodEffect: 'May be taken with or without food.',
    approvedCanada: ['Major depressive disorder'],
    offLabel: ['Depression with prominent cognitive symptoms'],
    approvedPopulations: 'Adults.',
    startingDose: '10 mg PO once daily (5 mg if tolerability a concern).',
    titration: 'Increase to 20 mg/day as tolerated (target for many); reduce to 5 mg if needed.',
    maxDose: '20 mg/day (10 mg/day with a strong CYP2D6 inhibitor).',
    frequencyTiming: 'Once daily, any time of day.',
    startStopCrossTaper: 'Long half-life makes discontinuation mild; abrupt stop of 15–20 mg may warrant a brief down-titration.',
    administrationNotes: 'Long half-life buffers missed doses and eases discontinuation.',
    commonSE: ['Nausea (most common, dose-dependent)', 'Vomiting', 'Constipation', 'Sexual dysfunction (lower than SSRIs)', 'Dizziness'],
    seriousAE: ['Serotonin syndrome', 'Hyponatremia/SIADH', 'Bleeding risk', 'Increased suicidality (young adults)'],
    syndromes: ['Serotonin syndrome', 'SIADH/hyponatremia', 'Nausea (dose-dependent)'],
    overdoseLethality: 'Relatively safe; main effect is nausea/GI; treat as an SSRI-like agent.',
    discontinuationSyndrome: 'Mild (long half-life); brief taper for higher doses.',
    ongoingMonitoring: 'Mood/suicidality; sodium if symptomatic; response of cognitive symptoms if that is a target.',
    majorDDI: ['MAOIs (contraindicated)', 'Strong CYP2D6 inhibitors (e.g., bupropion, fluoxetine, paroxetine) — halve the dose', 'Strong CYP inducers (rifampin) lower levels', 'Other serotonergics', 'NSAIDs/anticoagulants — bleeding'],
    contraindicatedCombos: ['MAOIs (within 14 days each way)'],
    maoiWashout: '14 days each way (21 days after stopping vortioxetine before an MAOI in some labels).',
    pregnancy: 'Limited data; weigh untreated illness. Possible neonatal adaptation late in pregnancy.',
    lactation: 'Limited data; monitor infant.',
    geriatric: 'Generally well tolerated; watch hyponatremia; cognitive-symptom benefit is of interest in this group.',
    pearls: [
      'Multimodal — SERT inhibition PLUS direct 5-HT receptor modulation (1A agonist, 3/7 antagonist, etc.), distinguishing it from plain SSRIs.',
      'Pro-cognitive claims — some evidence for improving cognitive dysfunction (processing speed, executive function) in depression, partly independent of mood.',
      'Nausea is the dominant, DOSE-DEPENDENT side effect; sexual dysfunction is lower than with SSRIs.',
    ],
    mnemonics: ['"Vortioxetine = the thinking SSRI-plus" — multimodal, marketed for cognition; the price of admission is dose-dependent nausea.'],
    confusables: ['Vortioxetine vs vilazodone — both newer serotonergic "multimodal-ish" agents (vilazodone is an SSRI + 5-HT1A partial agonist); different molecules.'],
    classDifferentiators: 'Multimodal serotonergic (reuptake + receptor modulation): long half-life, pro-cognitive claims, dose-dependent nausea, lower sexual dysfunction.',
    examHooks: ['Which antidepressant is "multimodal" and marketed for cognitive symptoms of depression? (vortioxetine)', 'Which antidepressant\'s main dose-dependent side effect is nausea? (vortioxetine)'],
    counsellingPoints: ['Take once daily; nausea usually eases over the first couple of weeks.', 'It may help concentration/thinking as well as mood.', 'Report any easy bruising or bleeding.'],
    vignettes: [
      {
        stem: 'A 55-year-old with depression reports prominent difficulty concentrating and slowed thinking. Which antidepressant is specifically noted for a multimodal mechanism and evidence in cognitive symptoms?',
        options: ['Paroxetine', 'Vortioxetine', 'Trazodone', 'Venlafaxine'],
        answer: 'Vortioxetine',
        explanation: 'Vortioxetine is a multimodal agent (SERT inhibition plus 5-HT receptor modulation) with data supporting improvement in cognitive dysfunction in depression, partly independent of its antidepressant effect.',
        testedFact: 'Vortioxetine multimodal mechanism / pro-cognitive effect',
        source: { name: 'CANMAT 2016 MDD; vortioxetine cognition evidence', origin: 'canmat' },
      },
    ],
    _prov: GROUP_PROV,
  },
};
