// authored/ssri.js — authored overlay for the SSRI class.
//
// Mechanism/PK/dosing summaries + the pedagogical layer, grounded in established
// pharmacology and the fetched openFDA/monograph label sections. `_prov` declares which
// safety-critical fields the label text grounds; build.js attaches that source text and,
// where a field cannot be grounded, downgrades it to origin 'authored' + verifyFlag.
//
// SSRI class theme: SERT blockade; ~2–4 wk onset; serotonin syndrome with MAOIs (washout);
// hyponatremia/SIADH (esp. elderly); GI + sexual dysfunction; discontinuation syndrome
// (worst with short half-life / no active metabolite → paroxetine, fluvoxamine); relatively
// SAFE in overdose (vs TCA/MAOI) — a high-yield contrast.

const SSRI_PROV = {
  startingDose: 'openfda', maxDose: 'openfda', seriousAE: 'openfda', syndromes: 'openfda',
  majorDDI: 'openfda', contraindicatedCombos: 'openfda', pregnancy: 'openfda',
  overdoseLethality: 'openfda',
};

export default {
  fluoxetine: {
    pronunciation: 'floo-OX-uh-teen',
    moa: 'Selective serotonin reuptake inhibitor (blocks SERT), increasing synaptic 5-HT.',
    receptorProfile: 'High SERT affinity; some 5-HT2C antagonism (mildly activating). Minimal H1/M1/α1.',
    onsetOfEffect: 'Emotional/somatic symptoms 1–2 wk; full antidepressant effect 4–6 wk.',
    halfLife: 'Fluoxetine 1–4 days; active metabolite norfluoxetine 7–15 days (longest of the SSRIs).',
    timeToSteadyState: '~4–6 weeks (long half-life).',
    metabolism: 'Hepatic CYP2D6 (also 2C9/2C19/3A4). Potent CYP2D6 inhibitor; moderate 2C19/3A4 inhibitor.',
    activeMetabolites: 'Norfluoxetine (active, very long half-life).',
    foodEffect: 'May be taken with or without food.',
    approvedCanada: ['Major depressive disorder', 'OCD', 'Bulimia nervosa', 'Panic disorder', 'PMDD (some formulations)'],
    offLabel: ['PTSD', 'Social anxiety disorder'],
    approvedPopulations: 'Adults; pediatric use for MDD/OCD in some jurisdictions.',
    startingDose: '20 mg PO once daily (usually AM due to activation).',
    titration: 'May increase after several weeks; usual 20–60 mg/day.',
    maxDose: '80 mg/day.',
    frequencyTiming: 'Once daily, morning (activating).',
    startStopCrossTaper: 'Self-tapering due to long half-life — discontinuation syndrome rare. Long washout needed before starting an MAOI (5 weeks).',
    administrationNotes: 'Long half-life is an advantage for non-adherent patients.',
    commonSE: ['Nausea', 'Insomnia', 'Activation/anxiety', 'Headache', 'Sexual dysfunction', 'Decreased appetite'],
    seriousAE: ['Serotonin syndrome', 'Hyponatremia/SIADH', 'Increased suicidality (young adults)', 'Bleeding risk (with NSAIDs/anticoagulants)'],
    syndromes: ['Serotonin syndrome', 'SIADH/hyponatremia', 'Sexual dysfunction', 'SSRI discontinuation (rare here)'],
    overdoseLethality: 'Relatively safe in overdose compared with TCAs/MAOIs; seizures and serotonin toxicity possible in large ingestions or combinations.',
    discontinuationSyndrome: 'Uncommon because of the long half-life — effectively self-tapering.',
    ongoingMonitoring: 'Monitor for clinical worsening/suicidality (esp. first weeks and after dose changes); serum sodium if symptoms of hyponatremia.',
    majorDDI: ['MAOIs (contraindicated — serotonin syndrome; 5-wk washout after fluoxetine)', 'CYP2D6 substrates (e.g., TCAs, metoprolol, atomoxetine, risperidone) — levels rise', 'Other serotonergics (triptans, tramadol, linezolid)', 'NSAIDs/anticoagulants — bleeding'],
    contraindicatedCombos: ['MAOIs (incl. within 14 days of stopping an MAOI; 5 weeks after stopping fluoxetine)', 'Pimozide, thioridazine (QT/levels)'],
    maoiWashout: 'Stop MAOI ≥14 days before fluoxetine; stop fluoxetine ≥5 weeks before an MAOI (long half-life).',
    pregnancy: 'Generally considered compatible; weigh untreated depression risk. Long half-life and secretion into milk are considerations. Tie to CANMAT perinatal 2024.',
    lactation: 'Excreted in breast milk more than sertraline; sertraline/citalopram often preferred if starting in lactation.',
    geriatric: 'Long half-life and CYP2D6 inhibition raise interaction/accumulation risk; watch hyponatremia.',
    pearls: [
      'Longest half-life SSRI → best for non-adherent patients and least discontinuation syndrome.',
      'Most activating SSRI — dose in the morning; can worsen initial anxiety/insomnia.',
      'Potent CYP2D6 inhibitor — a classic source of interactions.',
    ],
    mnemonics: ['"Fluoxetine = the long one" — 5-week MAOI washout because norfluoxetine lingers.'],
    confusables: ['Fluoxetine vs fluvoxamine vs fluphenazine — all "flu-" but different classes.'],
    classDifferentiators: 'The activating, longest-half-life SSRI; strong 2D6 inhibitor.',
    examHooks: ['Which SSRI needs a 5-week washout before an MAOI? (fluoxetine)'],
    counsellingPoints: ['Take in the morning.', 'Full effect takes 4–6 weeks.', 'Do not combine with MAOIs.'],
    vignettes: [
      {
        stem: 'A 24-year-old started on an SSRI 3 months ago must switch to phenelzine (an MAOI). Compared with other SSRIs, which requires the LONGEST washout before starting the MAOI?',
        options: ['Sertraline', 'Paroxetine', 'Fluoxetine', 'Citalopram'],
        answer: 'Fluoxetine',
        explanation: 'Fluoxetine and its active metabolite norfluoxetine have very long half-lives, requiring ~5 weeks off fluoxetine before starting an MAOI (vs ~2 weeks for other SSRIs).',
        testedFact: 'MAOI washout after fluoxetine',
        source: { name: 'openFDA/DailyMed SSRI label — contraindications/MAOI', origin: 'openfda' },
      },
    ],
    _prov: SSRI_PROV,
  },

  sertraline: {
    pronunciation: 'SER-truh-leen',
    moa: 'Selective serotonin reuptake inhibitor (blocks SERT). Weak dopamine reuptake inhibition and sigma-1 binding at higher doses.',
    receptorProfile: 'High SERT affinity; minor sigma-1; minimal H1/M1/α1 (well tolerated).',
    onsetOfEffect: '1–2 wk early effects; 4–6 wk full effect.',
    halfLife: '~26 hours (active metabolite desmethylsertraline weaker, ~62–104 h).',
    timeToSteadyState: '~1 week.',
    metabolism: 'Hepatic (CYP2B6/2C19/2C9/3A4); mild CYP2D6 inhibitor (dose-dependent). Fewer interactions than fluoxetine/paroxetine.',
    activeMetabolites: 'Desmethylsertraline (much weaker).',
    foodEffect: 'Absorption increased modestly with food; take consistently.',
    approvedCanada: ['Major depressive disorder', 'OCD', 'Panic disorder', 'PTSD', 'Social anxiety disorder', 'PMDD'],
    offLabel: ['GAD'],
    approvedPopulations: 'Adults; pediatric OCD.',
    startingDose: '50 mg PO once daily (25 mg in panic disorder to limit activation).',
    titration: 'Increase by 50 mg at ≥1-week intervals as needed.',
    maxDose: '200 mg/day.',
    frequencyTiming: 'Once daily, morning or evening; take with food to reduce GI upset.',
    startStopCrossTaper: 'Taper on discontinuation to limit withdrawal.',
    administrationNotes: 'Broadest anxiety-spectrum approvals; a common first choice.',
    commonSE: ['Diarrhea (characteristic)', 'Nausea', 'Insomnia', 'Sexual dysfunction', 'Tremor', 'Dry mouth'],
    seriousAE: ['Serotonin syndrome', 'Hyponatremia/SIADH', 'Increased suicidality (young adults)', 'Bleeding risk'],
    syndromes: ['Serotonin syndrome', 'SIADH/hyponatremia', 'Sexual dysfunction', 'SSRI discontinuation'],
    overdoseLethality: 'Relatively safe in overdose; among the safer SSRIs. Serotonin toxicity risk with co-ingestants.',
    discontinuationSyndrome: 'Moderate — taper to avoid flu-like symptoms, dizziness, "brain zaps".',
    ongoingMonitoring: 'Monitor mood/suicidality; sodium if hyponatremia symptoms; generally no routine bloodwork.',
    majorDDI: ['MAOIs (contraindicated)', 'Other serotonergics', 'Pimozide (contraindicated — QT)', 'NSAIDs/anticoagulants — bleeding'],
    contraindicatedCombos: ['MAOIs (within 14 days)', 'Pimozide', 'Oral concentrate with disulfiram (contains alcohol)'],
    maoiWashout: '14 days each way.',
    pregnancy: 'One of the preferred SSRIs in pregnancy/lactation given data and low milk transfer; per CANMAT perinatal 2024, treat maternal illness.',
    lactation: 'Low relative infant dose — often first-choice SSRI in breastfeeding.',
    geriatric: 'Favourable interaction profile; watch hyponatremia.',
    cardiac: 'Preferred SSRI post-MI (SADHART evidence); minimal QT effect.',
    pearls: [
      'Preferred SSRI in cardiac disease (SADHART) and in pregnancy/lactation.',
      'Diarrhea is the signature GI effect.',
      'Broadest anxiety-disorder approvals of the SSRIs.',
    ],
    mnemonics: ['"Sertraline for the heart" — safest SSRI post-MI.'],
    confusables: ['Sertraline (SSRI) vs sertindole (antipsychotic).'],
    classDifferentiators: 'Clean interaction profile; cardiac- and lactation-preferred; GI (diarrhea) prominent.',
    examHooks: ['Best antidepressant shortly after MI? (sertraline)'],
    counsellingPoints: ['Take with food to ease nausea/diarrhea.', 'Effect builds over 4–6 weeks.', 'Taper when stopping.'],
    vignettes: [
      {
        stem: 'A 61-year-old develops major depression 4 weeks after an acute MI. Which antidepressant has the best cardiac safety evidence to start?',
        options: ['Amitriptyline', 'Sertraline', 'Venlafaxine', 'Bupropion'],
        answer: 'Sertraline',
        explanation: 'Sertraline has the strongest post-MI safety data (SADHART) with minimal cardiac/QT effect; TCAs are avoided post-MI.',
        testedFact: 'Sertraline cardiac safety',
        source: { name: 'CANMAT 2016 MDD; cardiac SSRI evidence', origin: 'canmat' },
      },
    ],
    _prov: SSRI_PROV,
  },

  paroxetine: {
    pronunciation: 'puh-ROX-uh-teen',
    moa: 'Selective serotonin reuptake inhibitor (blocks SERT); mild anticholinergic and weak NET effects.',
    receptorProfile: 'High SERT affinity; notable muscarinic (M1) antagonism (most anticholinergic SSRI).',
    onsetOfEffect: '1–2 wk early; 4–6 wk full.',
    halfLife: '~21 hours (short; no active metabolite).',
    timeToSteadyState: '~1–2 weeks.',
    metabolism: 'Hepatic CYP2D6 — and a POTENT CYP2D6 inhibitor (inhibits its own metabolism → nonlinear kinetics).',
    activeMetabolites: 'None clinically significant.',
    foodEffect: 'With or without food.',
    approvedCanada: ['Major depressive disorder', 'OCD', 'Panic disorder', 'Social anxiety disorder', 'GAD', 'PTSD'],
    offLabel: ['Menopausal hot flashes'],
    approvedPopulations: 'Adults (avoid in pregnancy where possible).',
    startingDose: '20 mg PO once daily.',
    titration: 'Increase by 10 mg/day at ≥1-week intervals.',
    maxDose: '50 mg/day (60 mg for OCD in some labels).',
    frequencyTiming: 'Once daily, often morning; more sedating than other SSRIs.',
    startStopCrossTaper: 'Taper slowly — worst discontinuation syndrome of the SSRIs (short half-life, no active metabolite).',
    administrationNotes: 'CR formulation available.',
    commonSE: ['Sedation', 'Weight gain (most of the SSRIs)', 'Sexual dysfunction (most)', 'Constipation/dry mouth (anticholinergic)', 'Nausea'],
    seriousAE: ['Serotonin syndrome', 'Hyponatremia/SIADH', 'Increased suicidality (young adults)', 'Bleeding risk', 'Anticholinergic effects'],
    syndromes: ['Serotonin syndrome', 'Anticholinergic burden', 'SIADH/hyponatremia', 'SSRI discontinuation (worst)'],
    overdoseLethality: 'Relatively safe in overdose vs TCA/MAOI; discontinuation and anticholinergic effects notable.',
    discontinuationSyndrome: 'Worst-in-class — dizziness, paresthesia, "brain zaps", flu-like symptoms; taper very slowly.',
    ongoingMonitoring: 'Mood/suicidality; sodium if symptomatic; caution for anticholinergic load in elderly.',
    majorDDI: ['MAOIs (contraindicated)', 'CYP2D6 substrates (TCAs, tamoxifen — reduces active endoxifen, metoprolol)', 'Other serotonergics', 'Anticholinergics (additive)'],
    contraindicatedCombos: ['MAOIs', 'Thioridazine/pimozide', 'Tamoxifen (avoid — reduces efficacy)'],
    maoiWashout: '14 days each way.',
    pregnancy: 'Associated with cardiac malformations (e.g., septal defects) in some studies — generally AVOIDED in pregnancy; formerly higher-risk category. Tie to CANMAT perinatal 2024.',
    lactation: 'Low milk levels but generally not first-choice if initiating.',
    geriatric: 'Most anticholinergic SSRI — caution (falls, confusion, constipation); on Beers-type caution lists.',
    pearls: [
      'Worst discontinuation syndrome + most anticholinergic + most weight gain + most sexual dysfunction of the SSRIs.',
      'Potent CYP2D6 inhibitor; reduces tamoxifen activation.',
      'Generally avoided in pregnancy (cardiac malformation signal).',
    ],
    mnemonics: ['"Paroxetine = the problem child": Pregnancy risk, weight gain, anticholinergic, discontinuation.'],
    confusables: ['Paroxetine vs fluoxetine — opposite ends: short vs long half-life, worst vs least discontinuation.'],
    classDifferentiators: 'Short half-life, potent 2D6 inhibitor, anticholinergic, sedating, pregnancy-avoid.',
    examHooks: ['Which SSRI is most associated with discontinuation syndrome and with pregnancy cardiac risk? (paroxetine)'],
    counsellingPoints: ['Do not stop abruptly — taper.', 'Avoid in pregnancy/if planning pregnancy — discuss.', 'May cause weight gain and sedation.'],
    vignettes: [
      {
        stem: 'A patient abruptly stops their SSRI and 2 days later has dizziness, nausea, paresthesias and "electric shock" sensations. Which SSRI is MOST likely responsible?',
        options: ['Fluoxetine', 'Paroxetine', 'Sertraline', 'Escitalopram'],
        answer: 'Paroxetine',
        explanation: 'Paroxetine has the shortest half-life and no active metabolite, giving it the most prominent discontinuation syndrome; fluoxetine (long half-life) has the least.',
        testedFact: 'Paroxetine discontinuation syndrome',
        source: { name: 'openFDA/DailyMed paroxetine label — discontinuation', origin: 'openfda' },
      },
    ],
    _prov: SSRI_PROV,
  },

  citalopram: {
    pronunciation: 'sy-TAL-oh-pram',
    moa: 'Selective serotonin reuptake inhibitor (racemic; R- and S-citalopram).',
    receptorProfile: 'High SERT affinity; very clean off-target profile.',
    onsetOfEffect: '1–2 wk early; 4–6 wk full.',
    halfLife: '~35 hours.',
    timeToSteadyState: '~1 week.',
    metabolism: 'Hepatic CYP2C19 (and 3A4/2D6); weak CYP inhibitor overall.',
    activeMetabolites: 'Demethylcitalopram (minor).',
    foodEffect: 'With or without food.',
    approvedCanada: ['Major depressive disorder'],
    offLabel: ['Anxiety disorders', 'Behavioural symptoms in dementia'],
    approvedPopulations: 'Adults.',
    startingDose: '20 mg PO once daily.',
    titration: 'Increase to 40 mg/day after ≥1 week if needed.',
    maxDose: '40 mg/day (20 mg/day if >60 years, hepatic impairment, or CYP2C19 poor metabolizers/inhibitors) — due to dose-dependent QT prolongation.',
    frequencyTiming: 'Once daily.',
    startStopCrossTaper: 'Taper to limit discontinuation.',
    administrationNotes: 'QT ceiling is the defining prescribing constraint.',
    commonSE: ['Nausea', 'Somnolence', 'Sexual dysfunction', 'Sweating', 'Dry mouth'],
    seriousAE: ['Dose-dependent QT prolongation', 'Serotonin syndrome', 'Hyponatremia/SIADH', 'Increased suicidality (young adults)'],
    syndromes: ['QT prolongation', 'Serotonin syndrome', 'SIADH/hyponatremia', 'Sexual dysfunction'],
    overdoseLethality: 'Relatively safe but more QT risk in overdose than other SSRIs — ECG monitoring in significant ingestion.',
    discontinuationSyndrome: 'Mild–moderate; taper.',
    baselineWorkup: ['Consider baseline ECG if cardiac risk, on other QT drugs, or electrolyte abnormality'],
    ongoingMonitoring: 'ECG/electrolytes if QT risk factors; mood/suicidality; sodium if symptomatic.',
    majorDDI: ['MAOIs (contraindicated)', 'Other QT-prolonging drugs (additive)', 'CYP2C19 inhibitors (omeprazole, cimetidine) raise levels', 'Other serotonergics'],
    contraindicatedCombos: ['MAOIs', 'Other QT-prolonging agents at high dose', 'Pimozide'],
    maoiWashout: '14 days each way.',
    pregnancy: 'No consistent major teratogenic signal; weigh untreated illness. Tie to CANMAT perinatal 2024.',
    lactation: 'Acceptable; monitor infant.',
    geriatric: 'Max 20 mg/day in >60 y due to QT; watch hyponatremia.',
    cardiac: 'Dose-dependent QT prolongation — the key caution; keep ≤40 mg (≤20 mg in elderly/hepatic).',
    pearls: [
      'The QT SSRI — hard dose ceilings (40 mg general; 20 mg elderly/hepatic/2C19 issues).',
      'Very clean interaction profile otherwise.',
      'Escitalopram is its purified S-enantiomer.',
    ],
    mnemonics: ['"CiTalopram → hearT (QT)".'],
    confusables: ['Citalopram vs escitalopram — same family; escitalopram is the S-enantiomer with a 20 mg cap.'],
    classDifferentiators: 'Clean, but dose-capped for QT.',
    examHooks: ['Which SSRI has a dose-dependent QT warning with a 40 mg (20 mg elderly) ceiling? (citalopram)'],
    counsellingPoints: ['Do not exceed the prescribed dose.', 'Report palpitations/fainting.'],
    vignettes: [
      {
        stem: 'A 72-year-old with depression is prescribed an SSRI. Which agent carries a specific dose limit of 20 mg/day in this age group because of QT prolongation?',
        options: ['Sertraline', 'Citalopram', 'Fluvoxamine', 'Paroxetine'],
        answer: 'Citalopram',
        explanation: 'Citalopram causes dose-dependent QT prolongation; the maximum is 40 mg/day generally and 20 mg/day in patients >60 years or with hepatic impairment / CYP2C19 issues.',
        testedFact: 'Citalopram QT dose ceiling',
        source: { name: 'openFDA/DailyMed citalopram label — warnings (QT)', origin: 'openfda' },
      },
    ],
    _prov: { ...SSRI_PROV, therapeuticRange: 'openfda' },
  },

  escitalopram: {
    pronunciation: 'es-sy-TAL-oh-pram',
    moa: 'Selective serotonin reuptake inhibitor; the active S-enantiomer of citalopram (allosteric SERT binding).',
    receptorProfile: 'High, selective SERT affinity; cleanest off-target profile of the SSRIs.',
    onsetOfEffect: '1–2 wk early; 4–6 wk full.',
    halfLife: '~27–32 hours.',
    timeToSteadyState: '~1 week.',
    metabolism: 'Hepatic CYP2C19 (and 3A4/2D6); minimal CYP inhibition — few interactions.',
    activeMetabolites: 'S-desmethylescitalopram (minor).',
    foodEffect: 'With or without food.',
    approvedCanada: ['Major depressive disorder', 'Generalized anxiety disorder'],
    offLabel: ['Panic disorder', 'Social anxiety disorder'],
    approvedPopulations: 'Adults; adolescents for MDD in some labels.',
    startingDose: '10 mg PO once daily.',
    titration: 'Increase to 20 mg/day after ≥1 week if needed.',
    maxDose: '20 mg/day (10 mg/day in elderly/hepatic impairment).',
    frequencyTiming: 'Once daily.',
    startStopCrossTaper: 'Taper to limit discontinuation.',
    administrationNotes: 'Often first-line for its tolerability and clean interactions.',
    commonSE: ['Nausea', 'Insomnia or somnolence', 'Sexual dysfunction', 'Fatigue', 'Sweating'],
    seriousAE: ['Serotonin syndrome', 'Hyponatremia/SIADH', 'QT prolongation (less than citalopram)', 'Increased suicidality (young adults)'],
    syndromes: ['Serotonin syndrome', 'SIADH/hyponatremia', 'QT (mild)', 'Sexual dysfunction'],
    overdoseLethality: 'Relatively safe in overdose; QT less of a concern than citalopram.',
    discontinuationSyndrome: 'Mild–moderate; taper.',
    ongoingMonitoring: 'Mood/suicidality; sodium if symptomatic; ECG only if QT risk.',
    majorDDI: ['MAOIs (contraindicated)', 'Other serotonergics', 'Other QT drugs (additive, less than citalopram)'],
    contraindicatedCombos: ['MAOIs', 'Pimozide'],
    maoiWashout: '14 days each way.',
    pregnancy: 'No consistent major teratogenic signal; a reasonable choice — weigh untreated illness. Tie to CANMAT perinatal 2024.',
    lactation: 'Acceptable; monitor infant.',
    geriatric: 'Max 10 mg/day in elderly/hepatic; well tolerated.',
    cardiac: 'Some QT effect but less than citalopram.',
    pearls: [
      'Often first-line: best-tolerated, cleanest interactions.',
      'S-enantiomer of citalopram; 20 mg escitalopram ≈ 40 mg citalopram.',
      'CANMAT first-line for MDD and approved for GAD.',
    ],
    mnemonics: ['"Escitalopram = the clean one" — few interactions, first-line.'],
    confusables: ['Escitalopram vs citalopram — half the max dose (20 vs 40 mg).'],
    classDifferentiators: 'Tolerability/interaction sweet spot; GAD approval.',
    examHooks: ['First-line, best-tolerated SSRI with GAD approval? (escitalopram)'],
    counsellingPoints: ['Once daily.', 'Effect over 4–6 weeks.', 'Report palpitations.'],
    vignettes: [
      {
        stem: 'A patient on high-dose omeprazole needs an SSRI with minimal CYP-mediated interactions and both MDD and GAD approval. Which is the best fit?',
        options: ['Fluvoxamine', 'Paroxetine', 'Escitalopram', 'Fluoxetine'],
        answer: 'Escitalopram',
        explanation: 'Escitalopram has minimal CYP inhibition and clean interactions and is approved for both MDD and GAD; fluvoxamine/paroxetine/fluoxetine are stronger CYP inhibitors.',
        testedFact: 'Escitalopram clean interactions + GAD approval',
        source: { name: 'CANMAT 2016 MDD; escitalopram label', origin: 'canmat' },
      },
    ],
    _prov: SSRI_PROV,
  },

  fluvoxamine: {
    pronunciation: 'floo-VOX-uh-meen',
    moa: 'Selective serotonin reuptake inhibitor; also a sigma-1 receptor agonist.',
    receptorProfile: 'High SERT affinity; sigma-1 agonism; minimal H1/M1/α1.',
    onsetOfEffect: '1–2 wk early; OCD response may take 6–12 wk.',
    halfLife: '~15 hours (shortest SSRI besides paroxetine).',
    timeToSteadyState: '~1 week.',
    metabolism: 'Hepatic; POTENT CYP1A2 and CYP2C19 inhibitor (also 3A4/2D6) — the most interaction-prone SSRI.',
    activeMetabolites: 'None clinically significant.',
    foodEffect: 'With or without food.',
    approvedCanada: ['OCD', 'Major depressive disorder (some labels)'],
    offLabel: ['Social anxiety disorder', 'Panic disorder'],
    approvedPopulations: 'Adults; pediatric OCD.',
    startingDose: '50 mg PO at bedtime (sedating).',
    titration: 'Increase by 50 mg every 4–7 days; doses >100 mg often split BID.',
    maxDose: '300 mg/day (divide doses >100 mg).',
    frequencyTiming: 'Bedtime (sedating); BID at higher doses.',
    startStopCrossTaper: 'Taper — short half-life gives notable discontinuation symptoms.',
    administrationNotes: 'Strong choice for OCD; interaction profile is the main drawback.',
    commonSE: ['Nausea (most GI of the SSRIs)', 'Sedation', 'Sexual dysfunction', 'Constipation', 'Headache'],
    seriousAE: ['Serotonin syndrome', 'Hyponatremia/SIADH', 'Interaction-driven toxicity (e.g., raising clozapine/theophylline)', 'Increased suicidality (young adults)'],
    syndromes: ['Serotonin syndrome', 'SIADH/hyponatremia', 'CYP1A2/2C19 interaction cascade', 'SSRI discontinuation'],
    overdoseLethality: 'Relatively safe alone; danger is largely via interactions (e.g., elevating clozapine/theophylline levels).',
    discontinuationSyndrome: 'Moderate — taper.',
    ongoingMonitoring: 'Mood/suicidality; if combined with CYP1A2 substrates (clozapine, theophylline), monitor those levels closely; sodium if symptomatic.',
    majorDDI: ['MAOIs (contraindicated)', 'CYP1A2 substrates: clozapine, olanzapine, theophylline, caffeine, tizanidine (levels rise sharply)', 'CYP2C19 substrates', 'Ramelteon (contraindicated in some labels)', 'Other serotonergics'],
    contraindicatedCombos: ['MAOIs', 'Tizanidine (CYP1A2 — contraindicated)', 'Ramelteon/alosetron/thioridazine/pimozide (per label)'],
    maoiWashout: '14 days each way.',
    pregnancy: 'Data more limited than sertraline/citalopram; weigh untreated illness. Tie to CANMAT perinatal 2024.',
    lactation: 'Used; monitor infant.',
    geriatric: 'Interaction burden and sedation — use care.',
    pearls: [
      'Most drug interactions of the SSRIs — potent CYP1A2 & 2C19 inhibitor (raises clozapine, theophylline, caffeine, tizanidine).',
      'A go-to for OCD.',
      'Sigma-1 agonism is a distinctive feature.',
    ],
    mnemonics: ['"FluvoxaMINE mines the CYPs" — biggest interaction footprint; think clozapine/theophylline levels up.'],
    confusables: ['Fluvoxamine vs fluoxetine — fluvoxamine = 1A2/2C19 (OCD), fluoxetine = 2D6, long half-life.'],
    classDifferentiators: 'Highest interaction burden; OCD-oriented; sedating; short half-life.',
    examHooks: ['Which SSRI dangerously raises clozapine and theophylline levels? (fluvoxamine — CYP1A2)'],
    counsellingPoints: ['Take at bedtime.', 'Tell prescribers about all medications (interactions).', 'Taper when stopping.'],
    vignettes: [
      {
        stem: 'A patient on clozapine is started on an SSRI for OCD and develops sedation, hypersalivation and a rising clozapine level. Which SSRI most likely caused this?',
        options: ['Sertraline', 'Fluvoxamine', 'Escitalopram', 'Citalopram'],
        answer: 'Fluvoxamine',
        explanation: 'Fluvoxamine is a potent CYP1A2 inhibitor; clozapine is a CYP1A2 substrate, so fluvoxamine markedly raises clozapine levels — a classic dangerous interaction.',
        testedFact: 'Fluvoxamine CYP1A2 → clozapine',
        source: { name: 'openFDA/DailyMed fluvoxamine label — drug interactions (CYP1A2)', origin: 'openfda' },
      },
    ],
    _prov: SSRI_PROV,
  },
};
