// authored/sud.js — authored overlay for substance-use-disorder (SUD) pharmacotherapy.
//
// Mechanism/PK/dosing summaries + the pedagogical layer, grounded in established
// pharmacology and the fetched openFDA/monograph label sections. `_prov` declares which
// safety-critical fields the label text grounds; build.js attaches that source text and,
// where a field cannot be grounded, downgrades it to origin 'authored' + verifyFlag.
//
// SUD class theme: opioid agonist therapy (OAT) — methadone (FULL mu agonist, no ceiling,
// QT/torsades, long/variable half-life → induction accumulation, CYP3A4 DDIs) vs
// buprenorphine (PARTIAL mu agonist, ceiling on respiratory depression → safer, but high
// affinity → precipitated withdrawal if started too soon). Antagonists: naltrexone
// (maintenance — need opioid-free window) vs naloxone (acute overdose rescue — short-acting).
// Alcohol-use-disorder agents: naltrexone (anti-craving/reward), acamprosate (glutamate/GABA
// modulator, renally cleared, TID), disulfiram (ALDH inhibitor → aversive acetaldehyde
// reaction). Plus varenicline (α4β2 nicotinic partial agonist for smoking cessation).
// High-yield contrasts: full vs partial agonist; naltrexone vs naloxone; aversive vs
// anti-craving.

const SUD_PROV = {
  startingDose: 'openfda', maxDose: 'openfda', seriousAE: 'openfda', syndromes: 'openfda',
  majorDDI: 'openfda', contraindicatedCombos: 'openfda', pregnancy: 'openfda',
  overdoseLethality: 'openfda',
};

export default {
  methadone: {
    pronunciation: 'METH-uh-done',
    moa: 'Full mu-opioid receptor agonist (also NMDA antagonist + monoamine reuptake inhibition). Long-acting; cross-tolerance suppresses withdrawal/craving and blunts the euphoria of other opioids.',
    receptorProfile: 'Full agonist at mu (some kappa/delta); NMDA antagonism; SNRI-like monoamine effects. No ceiling on respiratory depression.',
    onsetOfEffect: 'Analgesia 30–60 min; withdrawal suppression within hours, but OAT steady state takes ~5 days.',
    halfLife: 'Long and highly variable (~8–59 h, can exceed 100 h). Elimination half-life far outlasts the ~6–8 h analgesic duration → accumulation risk.',
    timeToSteadyState: '~5 days (4–5 half-lives) — most induction deaths occur here as levels climb.',
    metabolism: 'Hepatic, chiefly CYP3A4 (also 2B6, 2C19, 2D6) → EDDP (inactive). Substrate of many CYP inducers/inhibitors.',
    activeMetabolites: 'None clinically significant (EDDP inactive).',
    elimination: 'Hepatic metabolism with renal and fecal excretion.',
    foodEffect: 'Not clinically significant.',
    approvedCanada: ['Opioid use disorder (opioid agonist therapy)', 'Analgesia (methadone for pain)'],
    approvedPopulations: 'Adults; specially authorized prescribers for OAT.',
    startingDose: 'OAT induction typically 10–30 mg PO on day 1 (do not exceed ~30–40 mg first day); "start low, go slow".',
    titration: 'Increase by ~5–10 mg only every ≥5 days (steady state), watching for sedation; usual maintenance 60–120 mg/day.',
    maxDose: 'No fixed ceiling — individualized to tolerance; higher maintenance doses reduce illicit opioid use but raise QT risk.',
    frequencyTiming: 'Once daily for OAT (witnessed dosing initially); split (q6–12h) for analgesia.',
    renalHepaticAdjustment: 'Caution in hepatic impairment (accumulation).',
    administrationNotes: 'Witnessed daily dosing at induction; take-home "carries" earned with stability and clean urine screens.',
    commonSE: ['Constipation', 'Sweating', 'Sedation', 'Weight gain', 'Decreased libido/hypogonadism', 'Nausea'],
    seriousAE: ['Respiratory depression (esp. induction + CNS depressants)', 'QT prolongation / torsades de pointes', 'Overdose from accumulation', 'Hypogonadism'],
    syndromes: ['Opioid overdose (respiratory depression)', 'QT prolongation / torsades', 'Opioid withdrawal (if abrupt stop)', 'Serotonin syndrome (rare)'],
    overdoseLethality: 'HIGH — full agonist with no ceiling on respiratory depression; the long half-life prolongs toxicity and delays overdose during induction. Fatal with alcohol/benzodiazepines. Reverse with naloxone but expect re-narcotization (naloxone is far shorter-acting) → repeat doses or infusion.',
    baselineWorkup: ['Baseline ECG (QTc), especially with cardiac risk factors, other QT drugs, or doses >100 mg/day'],
    ongoingMonitoring: 'ECG at baseline, ~30 days, then periodically (and with dose >100 mg or risk factors); close observation for sedation during induction; urine drug screens.',
    majorDDI: ['CYP3A4/2B6 inducers (rifampin, carbamazepine, phenytoin, efavirenz) → lower levels/withdrawal', 'CYP3A4 inhibitors (azoles, macrolides, protease inhibitors) → toxicity', 'Other QT-prolonging drugs (additive torsades risk)', 'CNS depressants — benzodiazepines, alcohol, gabapentinoids (respiratory depression)', 'Other serotonergics'],
    contraindicatedCombos: ['MAOIs', 'Concurrent alcohol / benzodiazepines / other CNS depressants (respiratory-depression risk)'],
    maoiWashout: 'Avoid with MAOIs / within 14 days.',
    pregnancy: 'OAT (methadone or buprenorphine) is standard of care in pregnancy — do NOT withdraw. Neonatal opioid withdrawal (NAS) is expected and managed. Tie to CRISM/CANMAT OAT guidance.',
    lactation: 'Compatible — small amounts in milk; breastfeeding encouraged if stable.',
    cardiac: 'Dose-dependent QT prolongation → torsades; obtain baseline and follow-up ECG.',
    pearls: [
      'Full mu agonist → NO ceiling on respiratory depression (unlike buprenorphine).',
      'Long, variable half-life → accumulation and delayed overdose during induction; most induction deaths fall in the first 1–2 weeks — "start low, go slow".',
      'Dose-dependent QT prolongation / torsades — get an ECG (baseline, then follow-up, especially >100 mg).',
      'CYP3A4 substrate — inducers (rifampin, carbamazepine) precipitate withdrawal; inhibitors cause toxicity.',
    ],
    mnemonics: ['"Methadone = the marathon opioid" — long half-life, slow induction, QT watch. And "methaDONE can leave your heart DONE" (torsades).'],
    confusables: ['Methadone (full agonist, no ceiling, QT/overdose risk, long half-life) vs buprenorphine (partial agonist, ceiling, precipitated withdrawal).'],
    classDifferentiators: 'The full-agonist OAT: no ceiling, QT/torsades, long-half-life accumulation, CYP3A4-driven interactions — opposite the buprenorphine safety profile.',
    examHooks: ['Which OAT agent needs baseline + follow-up ECG for QT? (methadone)', 'Why do methadone overdose deaths cluster in the first 2 weeks of induction? (accumulation from long, variable half-life)'],
    counsellingPoints: ['Daily observed dosing at first — do not miss or double up.', 'Never combine with alcohol, benzodiazepines, or other sedatives.', 'Toxicity builds over days; do not "top up" between doses.', 'Store securely — a single dose can be lethal to a child.'],
    vignettes: [
      {
        stem: 'A 34-year-old begins methadone for opioid use disorder at 30 mg/day. Feeling little effect on day 3, they are tempted to take extra. On day 5 they are found deeply sedated with a respiratory rate of 6. What pharmacologic property best explains this delayed deterioration?',
        options: ['Rapid CYP3A4 induction lowering the dose', 'Accumulation due to a long, variable elimination half-life reaching steady state over ~5 days', 'A ceiling effect on respiratory depression', 'Precipitated withdrawal from partial agonism'],
        answer: 'Accumulation due to a long, variable elimination half-life reaching steady state over ~5 days',
        explanation: 'Methadone is a full mu agonist with an elimination half-life (up to >100 h) far longer than its analgesic duration. Plasma levels accumulate over ~4–5 days to steady state, so a dose that felt sub-therapeutic early can become toxic — hence "start low, go slow" and no early dose escalation.',
        testedFact: 'Methadone induction accumulation / delayed overdose',
        source: { name: 'openFDA/DailyMed methadone label — warnings (accumulation, respiratory depression)', origin: 'openfda' },
      },
      {
        stem: 'A patient stable on high-dose methadone develops syncope. ECG shows QTc 520 ms and a run of polymorphic VT. Which intervention is most directly indicated by methadone’s characteristic cardiac risk?',
        options: ['Start a beta-blocker for rate control', 'Review/withdraw QT-prolonging co-medications and correct electrolytes for torsades risk', 'Increase the methadone dose to stabilize levels', 'Add naltrexone'],
        answer: 'Review/withdraw QT-prolonging co-medications and correct electrolytes for torsades risk',
        explanation: 'Methadone causes dose-dependent QT prolongation and torsades de pointes. Management targets the arrhythmogenic substrate: correct K+/Mg2+, stop other QT-prolonging agents, and reconsider the methadone dose or switch to buprenorphine (much lower QT risk).',
        testedFact: 'Methadone QT prolongation / torsades',
        source: { name: 'openFDA/DailyMed methadone label — QT prolongation warning', origin: 'openfda' },
      },
    ],
    _prov: SUD_PROV,
  },

  buprenorphine: {
    pronunciation: 'byoo-preh-NOR-feen',
    moa: 'PARTIAL mu-opioid receptor agonist (high affinity, low intrinsic activity) with kappa antagonism. Partial activation gives a ceiling on respiratory depression; high affinity displaces full agonists.',
    receptorProfile: 'High mu affinity, partial agonist; slow receptor dissociation → long duration and a plateau in opioid effect at higher doses.',
    onsetOfEffect: 'Sublingual onset ~30–60 min; long duration allows once-daily (or less) dosing.',
    halfLife: 'Long — sublingual terminal half-life ~24–42 h.',
    timeToSteadyState: '~3–7 days.',
    metabolism: 'Hepatic CYP3A4 → norbuprenorphine (weakly active) plus glucuronidation.',
    activeMetabolites: 'Norbuprenorphine (weakly active).',
    elimination: 'Mostly biliary/fecal; renal minor.',
    foodEffect: 'Sublingual — avoid eating/drinking until the film/tablet dissolves.',
    approvedCanada: ['Opioid use disorder (OAT)', 'Chronic pain (transdermal/buccal formulations)'],
    approvedPopulations: 'Adults.',
    startingDose: 'Induction ONLY once in objective withdrawal (e.g., COWS ≥ ~8–12) to avoid precipitated withdrawal: 2–4 mg SL, reassess in 1–2 h; day-1 total often 8–12 mg.',
    titration: 'Titrate by 2–4 mg to suppress withdrawal/craving; usual maintenance 12–24 mg/day.',
    maxDose: 'Little added benefit above ~24 mg/day (max ~24–32 mg).',
    frequencyTiming: 'Once daily sublingually (some patients alternate-day at higher doses).',
    startStopCrossTaper: 'Because of high mu affinity, it can precipitate withdrawal if a full agonist is still on board — start only in withdrawal; micro-dosing ("Bernese") protocols allow overlap induction.',
    administrationNotes: 'Sublingual — let it dissolve fully; observed dosing initially, carries with stability.',
    commonSE: ['Constipation', 'Headache', 'Sweating', 'Nausea', 'Insomnia', 'Oral hypoesthesia (sublingual)'],
    seriousAE: ['Precipitated withdrawal (if given too soon)', 'Respiratory depression (ceiling, but rises with other CNS depressants)', 'Hepatotoxicity', 'QT prolongation (less than methadone)'],
    syndromes: ['Precipitated opioid withdrawal', 'Opioid withdrawal', 'Opioid overdose (less likely due to ceiling)'],
    overdoseLethality: 'LOWER than methadone — the ceiling on respiratory depression makes buprenorphine alone relatively safe. Danger rises sharply with benzodiazepines/alcohol/other sedatives. High receptor affinity can make naloxone reversal harder (may need higher/repeated doses).',
    ongoingMonitoring: 'Assess withdrawal/craving and sedation; urine drug screens; LFTs if hepatic risk.',
    majorDDI: ['CYP3A4 inhibitors (raise levels) and inducers (rifampin, carbamazepine → lower levels)', 'CNS depressants — benzodiazepines, alcohol, gabapentinoids (respiratory depression)', 'Other QT-prolonging drugs (minor)'],
    contraindicatedCombos: ['Concurrent full mu agonists (precipitated withdrawal / competition)', 'Caution with benzodiazepines and other CNS depressants'],
    pregnancy: 'Acceptable OAT in pregnancy; associated with less severe neonatal abstinence syndrome than methadone (MOTHER trial). Do not withdraw OAT in pregnancy. Tie to CRISM/CANMAT OAT guidance.',
    lactation: 'Compatible — low milk transfer; breastfeeding encouraged if stable.',
    pearls: [
      'Partial agonist with a CEILING on respiratory depression → safer in overdose than methadone.',
      'High mu affinity displaces full agonists → precipitated withdrawal if started too soon; wait for objective withdrawal (COWS) or use micro-dosing induction.',
      'Long half-life → once-daily; minimal QT effect vs methadone.',
      'CRISM guidance favours buprenorphine/naloxone as first-line OAT over methadone for most patients (safety).',
    ],
    mnemonics: ['"Buprenorphine = the Brake" — partial agonist puts a ceiling on respiratory depression. "Start too soon and you Bring on Bad withdrawal."'],
    confusables: ['Buprenorphine (partial agonist, ceiling, precipitated withdrawal) vs methadone (full agonist, no ceiling, QT/overdose).', 'Buprenorphine mono product vs buprenorphine/naloxone (added abuse deterrent).'],
    classDifferentiators: 'The partial-agonist OAT: ceiling on respiratory depression (safer), precipitated-withdrawal risk on induction, minimal QT — opposite the methadone profile.',
    examHooks: ['Which OAT agent has a ceiling on respiratory depression? (buprenorphine)', 'Why must buprenorphine be started only once the patient is in withdrawal? (high mu affinity displaces residual full agonist → precipitated withdrawal)'],
    counsellingPoints: ['Do not take your first dose until you feel clearly in withdrawal.', 'Let the film/tablet dissolve under the tongue — do not swallow, eat, or drink until gone.', 'Avoid alcohol and benzodiazepines.', 'Much safer than methadone in overdose, but not risk-free with sedatives.'],
    vignettes: [
      {
        stem: 'A patient who used hydromorphone 4 hours ago is given sublingual buprenorphine in clinic. Within 30 minutes they develop worsening yawning, gooseflesh, abdominal cramps, myalgias and dysphoria — worse than before dosing. What is the mechanism?',
        options: ['Serotonin syndrome from monoamine effects', 'Precipitated withdrawal — high-affinity partial agonist displacing the full agonist from mu receptors', 'Opioid overdose from additive full agonism', 'Torsades de pointes'],
        answer: 'Precipitated withdrawal — high-affinity partial agonist displacing the full agonist from mu receptors',
        explanation: 'Buprenorphine binds mu receptors with high affinity but only partially activates them. Given while a full agonist still occupies receptors, it displaces the full agonist and drops net opioid effect, precipitating acute withdrawal. Induction should wait until the patient is already in objective withdrawal (COWS).',
        testedFact: 'Buprenorphine precipitated withdrawal on early induction',
        source: { name: 'openFDA/DailyMed buprenorphine label — warnings (precipitated withdrawal)', origin: 'openfda' },
      },
    ],
    _prov: SUD_PROV,
  },

  buprenorphine_naloxone: {
    pronunciation: 'byoo-preh-NOR-feen / nal-OX-one',
    moa: 'Combination: buprenorphine (partial mu agonist, ceiling on respiratory depression) + naloxone (mu antagonist). Naloxone is poorly bioavailable sublingually → essentially inert when taken correctly, but if the product is dissolved and injected the naloxone blocks the high and precipitates withdrawal (abuse deterrent).',
    receptorProfile: 'Buprenorphine drives the therapeutic effect (high-affinity partial agonist); naloxone contributes only if misused parenterally.',
    onsetOfEffect: 'Sublingual ~30–60 min (buprenorphine-driven); long duration.',
    halfLife: 'Buprenorphine ~24–42 h; sublingual naloxone negligible (poorly absorbed, rapidly cleared).',
    metabolism: 'Buprenorphine via CYP3A4 → norbuprenorphine + glucuronidation; naloxone glucuronidated.',
    elimination: 'Biliary/fecal (buprenorphine); renal (naloxone conjugates).',
    foodEffect: 'Sublingual — do not eat/drink until dissolved.',
    approvedCanada: ['Opioid use disorder (opioid agonist therapy) — first-line'],
    approvedPopulations: 'Adults.',
    startingDose: 'Dosed by buprenorphine content; induction ONLY once in objective withdrawal (COWS) to avoid precipitated withdrawal: start ~2/0.5–4/1 mg SL, day-1 total ~8/2–12/3 mg.',
    titration: 'Titrate buprenorphine component to suppress craving; maintenance ~12/3–24/6 mg/day.',
    maxDose: 'Little added benefit above ~24 mg buprenorphine/day.',
    frequencyTiming: 'Once daily sublingually.',
    startStopCrossTaper: 'Same precipitated-withdrawal caution as buprenorphine; the mono (naloxone-free) product is sometimes preferred in pregnancy.',
    administrationNotes: 'Sublingual film/tablet — let dissolve fully; abuse-deterrent formulation.',
    commonSE: ['Constipation', 'Headache', 'Sweating', 'Nausea', 'Insomnia', 'Oral hypoesthesia'],
    seriousAE: ['Precipitated withdrawal (early induction or if injected)', 'Respiratory depression (with other CNS depressants)', 'Hepatotoxicity'],
    syndromes: ['Precipitated opioid withdrawal', 'Opioid withdrawal', 'Opioid overdose (less likely due to ceiling)'],
    overdoseLethality: 'LOWER than methadone owing to the buprenorphine ceiling; naloxone adds diversion deterrence, not overdose protection when taken as directed. Risk rises with benzodiazepines/alcohol.',
    ongoingMonitoring: 'Withdrawal/craving and sedation; urine drug screens; LFTs if hepatic risk.',
    majorDDI: ['CYP3A4 inhibitors/inducers (via buprenorphine)', 'CNS depressants — benzodiazepines, alcohol (respiratory depression)', 'Other QT-prolonging drugs (minor)'],
    contraindicatedCombos: ['Concurrent full mu agonists', 'Caution with benzodiazepines/other CNS depressants'],
    pregnancy: 'OAT is standard of care in pregnancy; some guidance prefers the buprenorphine mono product over the combination in pregnancy, though the combination is also used. Do not withdraw OAT. Tie to CRISM/CANMAT OAT guidance.',
    lactation: 'Compatible if stable.',
    pearls: [
      'Naloxone is inactive sublingually (poor bioavailability) — it only matters if the product is injected, where it precipitates withdrawal to deter IV misuse.',
      'First-line OAT (CRISM) over methadone for most patients because of the buprenorphine safety ceiling.',
      'Precipitated-withdrawal caution on induction is driven by buprenorphine, not naloxone — start in objective withdrawal.',
    ],
    mnemonics: ['"Suboxone: the naloxone is a Sub-lingual dud, a Shot spoiler" — inert if dissolved under the tongue, but wrecks the high if injected.'],
    confusables: ['The naloxone here is a diversion deterrent — do not confuse with naloxone the overdose-rescue drug or with naltrexone the maintenance antagonist.'],
    classDifferentiators: 'Same partial-agonist ceiling/precipitated-withdrawal profile as buprenorphine, plus an abuse-deterrent naloxone component; first-line OAT.',
    examHooks: ['Why is naloxone added to sublingual buprenorphine? (deters IV misuse — inactive sublingually, precipitates withdrawal if injected)', 'Which OAT is generally first-line in Canada? (buprenorphine/naloxone)'],
    counsellingPoints: ['Take under the tongue and let it dissolve — never inject it (the naloxone will cause severe withdrawal).', 'Start only once you are clearly in withdrawal.', 'Avoid alcohol and benzodiazepines.'],
    vignettes: [
      {
        stem: 'A patient asks why their sublingual buprenorphine product also contains naloxone, since naloxone reverses opioids. What is the correct explanation?',
        options: ['Naloxone provides the main therapeutic anti-craving effect', 'Naloxone protects against overdose when taken as directed', 'Naloxone is poorly absorbed sublingually and is inert if taken correctly, but precipitates withdrawal if the product is injected — an abuse deterrent', 'Naloxone shortens buprenorphine’s half-life'],
        answer: 'Naloxone is poorly absorbed sublingually and is inert if taken correctly, but precipitates withdrawal if the product is injected — an abuse deterrent',
        explanation: 'Sublingual naloxone has very low bioavailability, so when the combination is used as directed it contributes nothing. If dissolved and injected, naloxone becomes bioavailable and precipitates withdrawal, discouraging parenteral misuse. Buprenorphine remains the active therapeutic component.',
        testedFact: 'Naloxone as sublingual abuse deterrent in buprenorphine/naloxone',
        source: { name: 'openFDA/DailyMed buprenorphine/naloxone label — clinical pharmacology', origin: 'openfda' },
      },
    ],
    _prov: SUD_PROV,
  },

  naltrexone: {
    pronunciation: 'nal-TREX-one',
    moa: 'Opioid receptor ANTAGONIST — competitively blocks mu (and kappa/delta) receptors. In alcohol use disorder it blunts the endogenous-opioid–mediated reward of drinking, reducing craving and heavy-drinking days.',
    receptorProfile: 'Pure competitive mu antagonist; no agonist activity.',
    onsetOfEffect: 'Opioid blockade within ~1 h of oral dosing; AUD craving benefit over days–weeks.',
    halfLife: 'Naltrexone ~4 h; active metabolite 6-β-naltrexol ~13 h. IM depot (Vivitrol) provides ~4 weeks of blockade.',
    metabolism: 'Hepatic (non-CYP; dihydrodiol dehydrogenase) → 6-β-naltrexol (active).',
    activeMetabolites: '6-β-naltrexol (active).',
    elimination: 'Renal (metabolites).',
    foodEffect: 'May be taken with food to reduce nausea.',
    approvedCanada: ['Alcohol use disorder', 'Opioid use disorder (relapse prevention in the detoxified/abstinent patient)'],
    approvedPopulations: 'Adults.',
    startingDose: 'Oral 50 mg PO daily. For OUD the patient MUST be opioid-free ~7–10 days first (optionally confirmed by naloxone challenge) or blockade precipitates withdrawal. IM: 380 mg gluteal every 4 weeks.',
    titration: 'Usually fixed dosing (50 mg/day oral; some use 100 mg on alternate schedules).',
    maxDose: 'Oral ~100 mg/day; IM 380 mg q4 weeks.',
    frequencyTiming: 'Once daily (oral) or once monthly (IM depot).',
    renalHepaticAdjustment: 'Avoid in acute hepatitis or hepatic failure; caution with elevated transaminases.',
    startStopCrossTaper: 'For OUD, confirm an opioid-free window before the first dose; there is no cross-taper — it is the opposite of an agonist.',
    administrationNotes: 'IM depot improves adherence; carry a card noting opioid blockade for emergencies.',
    commonSE: ['Nausea', 'Headache', 'Dizziness', 'Fatigue', 'Anxiety/insomnia', 'Injection-site reaction (IM)'],
    seriousAE: ['Hepatotoxicity (dose-dependent transaminitis)', 'Precipitated withdrawal (if opioids present)', 'Overdose on relapse due to lost tolerance', 'Severe injection-site reactions (IM)'],
    syndromes: ['Precipitated opioid withdrawal', 'Hepatotoxicity', 'Loss-of-tolerance overdose on relapse'],
    overdoseLethality: 'Naltrexone itself has low intrinsic toxicity. The lethal danger is indirect: blockade lowers opioid tolerance, so relapse (or attempts to override the block with high-dose opioids) can cause fatal overdose.',
    baselineWorkup: ['Baseline LFTs; confirm opioid-free status (history ± urine ± naloxone challenge) before starting for OUD'],
    ongoingMonitoring: 'Periodic LFTs; monitor for relapse risk; ensure a plan for acute pain (opioids will be blocked).',
    majorDDI: ['Opioids of any kind — analgesia is BLOCKED (plan non-opioid/regional analgesia for pain or surgery)', 'Opioid-containing antidiarrheals/antitussives (blocked)', 'Yohimbine/other agents may worsen withdrawal in dependent patients'],
    contraindicatedCombos: ['Current opioid use or opioid dependence (precipitates withdrawal)', 'Acute opioid withdrawal', 'Acute hepatitis / hepatic failure'],
    pregnancy: 'Data more limited than agonist OAT; agonist therapy is usually preferred in pregnancy. Individualize. Tie to CRISM/CANMAT guidance.',
    lactation: 'Limited data; use with caution.',
    renalHepatic: 'Hepatotoxic potential — avoid in acute hepatitis/liver failure; monitor LFTs.',
    pearls: [
      'ANTAGONIST — the patient must be opioid-free ~7–10 days before starting for OUD, or you precipitate withdrawal.',
      'Dual use: reduces craving/heavy drinking in alcohol use disorder AND prevents relapse in detoxified OUD.',
      'Blocks opioid analgesia — plan ahead for surgery/acute pain (non-opioid or regional).',
      'Hepatotoxic — check baseline and periodic LFTs; IM depot (Vivitrol) aids adherence.',
    ],
    mnemonics: ['"NaltrexONE = the long ONE that blocks" — maintenance antagonist (daily pill / monthly shot), for the long haul.'],
    confusables: ['Naltrexone (long-acting maintenance antagonist; AUD + OUD relapse prevention; hepatic) vs naloxone (short-acting acute overdose RESCUE). Same "opioid antagonist" family, opposite clinical use.'],
    classDifferentiators: 'Maintenance opioid antagonist (not an agonist) — needs an opioid-free window, treats alcohol AND opioid use disorder, and is hepatotoxic; contrast with naloxone (acute rescue) and with the agonists (methadone/buprenorphine).',
    examHooks: ['Why must a patient be opioid-free before starting naltrexone for OUD? (antagonist precipitates withdrawal)', 'Which agent treats BOTH alcohol and opioid use disorder? (naltrexone)'],
    counsellingPoints: ['Do not use any opioids — they will not work and could be dangerous.', 'Tell any surgeon/anaesthetist you are on naltrexone (opioid analgesia is blocked).', 'Your opioid tolerance drops — relapse carries a high overdose risk.', 'Report yellowing skin, dark urine, or right-upper-quadrant pain (liver).'],
    vignettes: [
      {
        stem: 'A patient who used heroin two days ago requests oral naltrexone for opioid use disorder. What is the most appropriate next step?',
        options: ['Give 50 mg naltrexone now to block further use', 'Do NOT start yet — confirm an opioid-free interval of ~7–10 days (± naloxone challenge) to avoid precipitated withdrawal', 'Start buprenorphine and naltrexone together', 'Give naloxone first, then naltrexone'],
        answer: 'Do NOT start yet — confirm an opioid-free interval of ~7–10 days (± naloxone challenge) to avoid precipitated withdrawal',
        explanation: 'Naltrexone is a full opioid antagonist. Given while opioids remain on board it abruptly displaces them and precipitates withdrawal. Guidelines require an opioid-free window (roughly 7–10 days, shorter for short-acting opioids) before induction, sometimes verified with a naloxone challenge.',
        testedFact: 'Opioid-free window required before naltrexone',
        source: { name: 'openFDA/DailyMed naltrexone label — contraindications/warnings', origin: 'openfda' },
      },
    ],
    _prov: SUD_PROV,
  },

  acamprosate: {
    pronunciation: 'a-KAM-pro-sate',
    moa: 'Modulates glutamatergic (NMDA) and GABAergic neurotransmission — helps restore the excitatory/inhibitory balance disrupted by chronic alcohol, easing protracted withdrawal/craving and supporting maintenance of abstinence.',
    receptorProfile: 'NMDA-receptor modulation and GABA-ergic effects; a structural analogue of taurine. No abuse potential.',
    onsetOfEffect: 'Craving/abstinence benefit builds over weeks; best started once abstinence is achieved.',
    halfLife: '~20–33 h.',
    timeToSteadyState: '~5–7 days.',
    metabolism: 'NOT metabolized — excreted unchanged by the kidneys (no hepatic metabolism, negligible CYP interactions).',
    activeMetabolites: 'None (parent drug is active).',
    proteinBinding: 'Negligible.',
    elimination: 'Renal (unchanged) — the rate-limiting route.',
    foodEffect: 'May be taken with meals (aids the TID schedule); food modestly reduces absorption but not clinically significant.',
    approvedCanada: ['Maintenance of abstinence in alcohol use disorder (in abstinent patients)'],
    approvedPopulations: 'Adults.',
    startingDose: '666 mg PO three times daily (two 333 mg tablets TID) in patients ≥60 kg; start after abstinence is achieved.',
    titration: 'Usually fixed dosing; reduce to 333 mg TID in moderate renal impairment (CrCl 30–50).',
    maxDose: '1998 mg/day (666 mg TID).',
    frequencyTiming: 'Three times daily — adherence is the main practical limitation.',
    renalHepaticAdjustment: 'Reduce dose if CrCl 30–50 mL/min; CONTRAINDICATED if CrCl <30. Safe in hepatic impairment (no hepatic metabolism).',
    administrationNotes: 'Enteric-coated — swallow whole; diarrhea is the common early effect.',
    commonSE: ['Diarrhea (most common)', 'Flatulence', 'Nausea', 'Abdominal discomfort', 'Pruritus'],
    seriousAE: ['Rare; monitor for depression/suicidality', 'Severe diarrhea/dehydration in some patients'],
    syndromes: ['(No characteristic toxidrome — very low toxicity)'],
    overdoseLethality: 'Very low toxicity in overdose; the main effect is diarrhea. No abuse potential.',
    ongoingMonitoring: 'Renal function (baseline and as clinically indicated); mood/suicidality; abstinence support.',
    majorDDI: ['Minimal — not protein-bound, no hepatic metabolism, no significant CYP interactions (an advantage over disulfiram/naltrexone). Can be combined with naltrexone.'],
    contraindicatedCombos: ['Severe renal impairment (CrCl <30 mL/min)'],
    pregnancy: 'Limited human data; use only if benefit outweighs risk.',
    lactation: 'Limited data; caution.',
    renalHepatic: 'Renally cleared → adjust/avoid in renal impairment; hepatically SAFE (good option in alcoholic liver disease).',
    pearls: [
      'Renally excreted unchanged, not hepatically metabolized → a good choice in alcoholic liver disease, but must adjust/avoid in renal impairment.',
      'Maintains abstinence (best in already-abstinent patients) — it does NOT treat acute withdrawal and is not aversive.',
      'TID dosing hurts adherence; diarrhea is the signature side effect.',
      'Minimal drug interactions; can be paired with naltrexone.',
    ],
    mnemonics: ['"ACamprosate = Abstinence Continued; Avoid in CKD" — renal clearance, TID, keeps sober patients sober.'],
    confusables: ['Acamprosate (glutamate/GABA modulator, renal, TID, anti-craving) vs naltrexone (opioid antagonist, hepatic, reduces reward) vs disulfiram (ALDH inhibitor, aversive).'],
    classDifferentiators: 'Anti-craving AUD agent that is renally (not hepatically) cleared and non-aversive — the liver-friendly option; contrast with hepatically-handled naltrexone and aversive disulfiram.',
    examHooks: ['Which AUD drug is renally excreted and safe in significant liver disease? (acamprosate)', 'Which AUD agent requires TID dosing? (acamprosate)'],
    counsellingPoints: ['Take three times a day, every day — even if you feel well.', 'Diarrhea is common early and usually settles.', 'It helps you stay off alcohol; it is not a punishment drug and will not make you sick if you drink.', 'Tell your doctor about any kidney problems.'],
    vignettes: [
      {
        stem: 'A 55-year-old with alcohol use disorder and Child-Pugh B cirrhosis wants pharmacotherapy to maintain abstinence. Renal function is normal. Which agent is best suited to their hepatic impairment?',
        options: ['Disulfiram', 'Oral naltrexone', 'Acamprosate', 'High-dose benzodiazepine'],
        answer: 'Acamprosate',
        explanation: 'Acamprosate is not hepatically metabolized — it is eliminated unchanged by the kidneys — so it is preferred when the liver is impaired. Naltrexone and disulfiram are both hepatotoxic/hepatically handled. Acamprosate would be avoided instead if renal function were poor (CrCl <30).',
        testedFact: 'Acamprosate is renally cleared / liver-friendly',
        source: { name: 'openFDA/DailyMed acamprosate label — use in hepatic/renal impairment', origin: 'openfda' },
      },
    ],
    _prov: SUD_PROV,
  },

  disulfiram: {
    pronunciation: 'dy-SUL-fi-ram',
    moa: 'Irreversibly inhibits aldehyde dehydrogenase (ALDH). If alcohol is consumed, acetaldehyde accumulates and produces the aversive "disulfiram–alcohol reaction" (flushing, throbbing headache, nausea/vomiting, tachycardia, hypotension, dyspnea) — a deterrent to drinking.',
    receptorProfile: 'Enzyme inhibitor (ALDH; also inhibits dopamine-β-hydroxylase and several CYPs, e.g., 2E1, 2C9, 3A4).',
    onsetOfEffect: 'Aversive sensitivity develops over ~12 h; because ALDH inhibition is irreversible, sensitivity persists ~1–2 weeks after the last dose.',
    halfLife: 'Parent ~7 h, but the clinical effect outlasts it (irreversible enzyme inhibition) — reactions possible up to ~14 days after stopping.',
    metabolism: 'Hepatic; potent inhibitor of several CYPs and of ALDH/dopamine-β-hydroxylase.',
    elimination: 'Hepatic metabolism; renal/pulmonary excretion of metabolites.',
    approvedCanada: ['Adjunct in the management of chronic alcohol use disorder (aversive therapy in motivated, abstinent patients)'],
    approvedPopulations: 'Adults with good insight/motivation and no significant cardiac/hepatic contraindication.',
    startingDose: '250 mg PO once daily (range 125–500 mg); begin only after ≥12–24 h of abstinence from alcohol.',
    titration: 'Usually maintained at 250 mg/day; up to 500 mg if reactions are insufficient at usual exposure.',
    maxDose: '500 mg/day.',
    frequencyTiming: 'Once daily; supervised (e.g., partner-observed) dosing improves adherence.',
    renalHepaticAdjustment: 'Avoid in significant hepatic disease; monitor LFTs.',
    administrationNotes: 'Best under supervision; patient must understand the reaction and avoid all alcohol sources.',
    commonSE: ['Drowsiness/fatigue', 'Metallic or garlic-like aftertaste', 'Headache', 'Dermatitis'],
    seriousAE: ['Disulfiram–alcohol reaction (can be severe: arrhythmia, hypotension, MI, seizures, death with a large alcohol load)', 'Hepatotoxicity (can be fulminant)', 'Peripheral neuropathy', 'Optic neuritis', 'Psychosis'],
    syndromes: ['Disulfiram–alcohol (acetaldehyde) reaction', 'Hepatotoxicity', 'Peripheral neuropathy'],
    overdoseLethality: 'The drug alone is moderately toxic (hepatotoxicity, neuropsychiatric effects). Combined with alcohol the acetaldehyde reaction can be life-threatening — cardiovascular collapse and death with a large alcohol load.',
    baselineWorkup: ['Baseline LFTs; assess cardiac status and motivation/insight before starting'],
    ongoingMonitoring: 'Periodic LFTs (baseline, ~2 weeks, then periodically); watch for neuropathy/visual changes and psychiatric effects.',
    majorDDI: ['Alcohol in ANY form — including mouthwash, cough/cold syrups, sauces, hand sanitizer, aftershave, and alcohol-vehicle medications', 'Warfarin — INR rises (inhibits metabolism)', 'Phenytoin — levels rise', 'Metronidazole — psychosis/confusion (avoid)', 'Isoniazid, theophylline'],
    contraindicatedCombos: ['Alcohol in any form (including hidden sources)', 'Metronidazole', 'Severe cardiac disease / recent MI', 'Psychosis'],
    pregnancy: 'Avoid — teratogenicity concerns and the risk of an acetaldehyde reaction; generally not used in pregnancy.',
    lactation: 'Avoid.',
    renalHepatic: 'Hepatotoxic — avoid in significant liver disease; monitor LFTs.',
    pearls: [
      'Aversive (not anti-craving) therapy — needs a motivated, insightful, abstinent patient; NOT first-line (naltrexone/acamprosate preferred).',
      'Avoid ALL alcohol, including hidden sources (mouthwash, cough syrup, sauces, hand sanitizer, aftershave); the reaction can occur up to ~2 weeks after the last dose (irreversible ALDH inhibition).',
      'Hepatotoxic — baseline and periodic LFTs; can be fulminant.',
      'Inhibits several CYPs → raises warfarin (bleeding) and phenytoin; avoid metronidazole (psychosis).',
    ],
    mnemonics: ['"diSULFIRam → you SUFFER if you drink" — acetaldehyde builds up: flushing, headache, vomiting, racing heart.'],
    confusables: ['Disulfiram (aversive, ALDH inhibitor) vs naltrexone/acamprosate (anti-craving, not aversive). Beware disulfiram-LIKE reactions from metronidazole and some cephalosporins.'],
    classDifferentiators: 'The only aversive AUD agent — it punishes drinking via acetaldehyde rather than reducing craving; hepatotoxic, interaction-prone, and second-line vs naltrexone/acamprosate.',
    examHooks: ['A patient on disulfiram flushes and vomits after cough syrup — why? (hidden alcohol → acetaldehyde reaction)', 'Which AUD drug inhibits aldehyde dehydrogenase? (disulfiram)'],
    counsellingPoints: ['Avoid every source of alcohol — read labels on mouthwash, cough syrups, sauces, hand sanitizer, and aftershave.', 'A reaction can happen even up to 2 weeks after your last dose.', 'Take it only when committed to abstinence; supervised dosing helps.', 'Report yellow skin, dark urine, numbness/tingling, or vision changes.'],
    vignettes: [
      {
        stem: 'A patient on disulfiram for alcohol use disorder develops sudden facial flushing, a pounding headache, nausea/vomiting, palpitations and hypotension about 20 minutes after taking an over-the-counter cough syrup. What is the mechanism?',
        options: ['Serotonin syndrome', 'Anaphylaxis to the cough syrup', 'Accumulation of acetaldehyde because disulfiram inhibits aldehyde dehydrogenase and the syrup contained alcohol', 'Opioid withdrawal'],
        answer: 'Accumulation of acetaldehyde because disulfiram inhibits aldehyde dehydrogenase and the syrup contained alcohol',
        explanation: 'Disulfiram irreversibly inhibits ALDH, so any ingested alcohol — including the ethanol in many cough syrups — is metabolized only to acetaldehyde, which accumulates and produces the flushing, headache, vomiting, tachycardia and hypotension of the disulfiram–alcohol reaction. Patients must avoid all hidden alcohol sources.',
        testedFact: 'Disulfiram–alcohol (acetaldehyde) reaction from hidden alcohol',
        source: { name: 'openFDA/DailyMed disulfiram label — warnings (disulfiram–alcohol reaction)', origin: 'openfda' },
      },
    ],
    _prov: SUD_PROV,
  },

  varenicline: {
    pronunciation: 'vair-EN-ih-kleen',
    moa: 'Partial agonist at the α4β2 nicotinic acetylcholine receptor — partial stimulation relieves craving/withdrawal while blocking nicotine binding reduces the reward of smoking.',
    receptorProfile: 'High-affinity α4β2 nicotinic partial agonist (also some α7/5-HT3 activity, contributing to nausea).',
    onsetOfEffect: 'Start ~1 week before the quit date; craving/withdrawal relief over the first week or two.',
    halfLife: '~24 h.',
    timeToSteadyState: '~4 days.',
    metabolism: 'Minimal metabolism — excreted largely UNCHANGED by the kidneys.',
    activeMetabolites: 'None significant.',
    elimination: 'Renal (unchanged) — the rate-limiting route.',
    foodEffect: 'Take with food and a full glass of water to reduce nausea.',
    approvedCanada: ['Smoking cessation (nicotine dependence)'],
    approvedPopulations: 'Adults.',
    startingDose: 'Begin 1 week before the target quit date. Days 1–3: 0.5 mg once daily; days 4–7: 0.5 mg twice daily; day 8 onward: 1 mg twice daily.',
    titration: 'Fixed titration to 1 mg BID over the first week; reduce in severe renal impairment.',
    maxDose: '1 mg twice daily (2 mg/day).',
    frequencyTiming: 'Twice daily after titration; take with food/water. Typical course 12 weeks (may extend 12 more).',
    renalHepaticAdjustment: 'Reduce dose in severe renal impairment (CrCl <30: max 0.5 mg BID); no hepatic adjustment needed.',
    administrationNotes: 'Some patients set the quit date up to ~5 weeks in (flexible-quit) or reduce-to-quit over up to 12 weeks.',
    commonSE: ['Nausea (most common)', 'Vivid/abnormal dreams', 'Insomnia', 'Headache', 'Constipation'],
    seriousAE: ['Neuropsychiatric symptoms (mood/behaviour changes, agitation) — monitor, esp. with psychiatric history', 'Rare suicidal ideation', 'Seizures', 'Somnambulism / sleep behaviours', 'Small cardiovascular signal'],
    syndromes: ['Neuropsychiatric symptom monitoring', 'Nausea/GI intolerance'],
    overdoseLethality: 'Low intrinsic toxicity in overdose; supportive care.',
    ongoingMonitoring: 'Monitor mood/behaviour and any new neuropsychiatric symptoms; assess quit progress; renal function if impaired.',
    majorDDI: ['Minimal — renally excreted, not CYP-metabolized', 'Smoking cessation itself raises levels of CYP1A2 substrates (e.g., clozapine, theophylline) once tobacco is stopped — an indirect effect', 'Possible reduced alcohol tolerance (rare)'],
    contraindicatedCombos: ['Hypersensitivity (few absolute contraindications)'],
    pregnancy: 'Limited data; behavioural support and, if needed, nicotine replacement are generally preferred in pregnancy — individualize.',
    lactation: 'Limited data; caution.',
    renalHepatic: 'Renally cleared → reduce dose in severe renal impairment; hepatically fine.',
    pearls: [
      'α4β2 nicotinic PARTIAL agonist — the most effective single pharmacotherapy for smoking cessation.',
      'Nausea and vivid/abnormal dreams are the hallmark side effects; start ~1 week before the quit date.',
      'Renally cleared with few drug interactions — adjust only in severe renal impairment.',
      'EAGLES trial: neuropsychiatric risk was lower than the earlier boxed-warning concerns suggested, but still monitor mood/behaviour.',
    ],
    mnemonics: ['"Varenicline — Vivid dreams + Vomiting (nausea)" hallmark side effects; a partial agonist that keeps you off the nicotine.'],
    confusables: ['Varenicline (α4β2 nicotinic partial agonist) vs bupropion (NDRI + nicotinic antagonist) — both aid smoking cessation but by different mechanisms.'],
    classDifferentiators: 'Nicotinic (not opioid or alcohol) target — a partial agonist for smoking cessation; renally cleared, interaction-light, with neuropsychiatric monitoring rather than QT/hepatotoxicity concerns.',
    examHooks: ['Most effective monotherapy for smoking cessation? (varenicline)', 'At which receptor is varenicline a partial agonist? (α4β2 nicotinic)'],
    counsellingPoints: ['Keep smoking for the first week — set your quit date about 8 days in.', 'Take with food and water to limit nausea.', 'Vivid dreams are common and usually harmless.', 'Report any new depression, agitation, or unusual thoughts/behaviour.'],
    vignettes: [
      {
        stem: 'A motivated smoker wants the most effective single medication to quit. Which agent, and by what mechanism, best fits?',
        options: ['Nicotine patch — full agonist replacement', 'Varenicline — α4β2 nicotinic partial agonist that reduces craving while blocking nicotine reward', 'Bupropion — selective serotonin reuptake inhibitor', 'Naltrexone — opioid antagonist'],
        answer: 'Varenicline — α4β2 nicotinic partial agonist that reduces craving while blocking nicotine reward',
        explanation: 'Varenicline is a partial agonist at the α4β2 nicotinic receptor: partial stimulation relieves withdrawal/craving, while occupying the receptor blunts the reinforcing effect of smoked nicotine. It is the most effective single pharmacotherapy for cessation. (Bupropion is an NDRI/nicotinic antagonist, not an SSRI.)',
        testedFact: 'Varenicline mechanism / efficacy in smoking cessation',
        source: { name: 'openFDA/DailyMed varenicline label — clinical pharmacology', origin: 'openfda' },
      },
    ],
    _prov: SUD_PROV,
  },

  naloxone: {
    pronunciation: 'nal-OX-one',
    moa: 'Pure opioid receptor ANTAGONIST — competitively displaces opioids at mu receptors, rapidly reversing respiratory depression and sedation. The opioid-overdose rescue agent.',
    receptorProfile: 'Competitive mu (and kappa/delta) antagonist; no agonist activity.',
    onsetOfEffect: 'IV ~1–2 min; IM/intranasal ~2–5 min.',
    halfLife: 'SHORT (~30–90 min) — often shorter than the opioid being reversed (e.g., methadone, sustained-release or fentanyl analogues), so re-narcotization can occur.',
    timeToSteadyState: 'Not applicable (acute, single/repeated dosing).',
    metabolism: 'Hepatic glucuronidation (rapid).',
    activeMetabolites: 'None significant.',
    elimination: 'Renal (conjugates).',
    approvedCanada: ['Emergency treatment of known or suspected opioid overdose (respiratory/CNS depression)'],
    approvedPopulations: 'All ages, including in pregnancy for maternal overdose (benefit outweighs risk).',
    startingDose: '0.4–2 mg IV/IM/SC, repeat every 2–3 min as needed, titrated to adequate respiration; intranasal 4 mg per spray, repeat in alternate nostril if no response.',
    titration: 'Titrate to restore breathing — not to full alertness — to limit precipitated withdrawal; repeat because it is short-acting.',
    maxDose: 'No fixed max — give what is needed to restore ventilation; consider an infusion for long-acting opioid overdoses.',
    frequencyTiming: 'Repeat every 2–3 min PRN; continuous infusion for long-acting opioids (methadone, extended-release).',
    administrationNotes: 'Take-home naloxone kits (IM or intranasal) for patients/families; always call emergency services — effect may wear off.',
    commonSE: ['Acute opioid withdrawal (agitation, nausea/vomiting, sweating, tachycardia)', 'Restlessness', 'Hypertension'],
    seriousAE: ['Precipitated acute withdrawal in dependence (vomiting → aspiration; agitation)', 'Re-narcotization when it wears off', 'Rare pulmonary edema/arrhythmia'],
    syndromes: ['Precipitated opioid withdrawal', 'Re-narcotization (recurrent respiratory depression)'],
    overdoseLethality: 'Naloxone itself is essentially non-toxic (no opioid activity). The main harms are precipitated withdrawal in dependent patients and recurrence of overdose (re-narcotization) once it wears off — hence monitoring and repeat dosing.',
    ongoingMonitoring: 'Continuous observation for recurrent respiratory depression (re-narcotization), especially after long-acting opioids; monitor airway and vitals.',
    majorDDI: ['Reverses/blocks all opioid analgesics and agonist effects (including buprenorphine — may need higher doses given high buprenorphine affinity)'],
    contraindicatedCombos: ['(None absolute in overdose) — use cautiously in known dependence to avoid severe precipitated withdrawal, but never withhold in life-threatening overdose'],
    pregnancy: 'Use for maternal opioid overdose — maternal benefit outweighs risk; may precipitate withdrawal/fetal distress, so monitor.',
    lactation: 'Compatible in the emergency setting.',
    pearls: [
      'Overdose RESCUE agent — SHORT-acting, so it can wear off before long opioids (methadone, fentanyl, extended-release) → watch for re-narcotization and re-dose or start an infusion.',
      'Precipitates withdrawal in dependence — titrate to restore breathing, not full consciousness.',
      'Available as take-home IM and intranasal kits; always summon emergency help even after a response.',
    ],
    mnemonics: ['"NaloxONE = number ONE for overdose rescue" — fast and short, so keep watching (re-narcotization).'],
    confusables: ['Naloxone (SHORT-acting acute overdose rescue) vs naltrexone (LONG-acting maintenance antagonist). Also distinct from the naloxone inside buprenorphine/naloxone (a sublingual abuse deterrent).'],
    classDifferentiators: 'The acute rescue antagonist: rapid onset, short duration (re-narcotization risk), given emergently — contrast with naltrexone (chronic maintenance blockade) and with the agonists.',
    examHooks: ['Why can a patient who overdosed on methadone deteriorate again after an initial naloxone response? (naloxone is shorter-acting than methadone → re-narcotization)', 'Naloxone vs naltrexone — which is the acute overdose rescue? (naloxone)'],
    counsellingPoints: ['Keep a naloxone kit accessible and make sure family/friends know how to use it.', 'Always call emergency services — the effect can wear off and breathing may stop again.', 'Stay with the person and be ready to give a second dose.'],
    vignettes: [
      {
        stem: 'A patient who overdosed on methadone is revived with intranasal naloxone and begins breathing normally. Forty-five minutes later they again become unresponsive with a respiratory rate of 5. What best explains this?',
        options: ['A second, separate overdose', 'Re-narcotization — naloxone’s short duration of action wore off before the long-acting methadone', 'An allergic reaction to naloxone', 'Precipitated serotonin syndrome'],
        answer: 'Re-narcotization — naloxone’s short duration of action wore off before the long-acting methadone',
        explanation: 'Naloxone has a short half-life (~30–90 min), typically shorter than methadone. As naloxone is cleared, unopposed methadone at the mu receptor again causes respiratory depression (re-narcotization). Such patients need repeat naloxone or a continuous infusion and prolonged observation.',
        testedFact: 'Naloxone short duration → re-narcotization with long-acting opioids',
        source: { name: 'openFDA/DailyMed naloxone label — warnings (duration of action / repeat dosing)', origin: 'openfda' },
      },
    ],
    _prov: SUD_PROV,
  },
};
