// authored/tca.js — authored overlay for the tricyclic/tetracyclic antidepressant (TCA) class.
//
// Mechanism/PK/dosing summaries + the pedagogical layer, grounded in established
// pharmacology and the fetched openFDA/monograph label sections. `_prov` declares which
// safety-critical fields the label text grounds; build.js attaches that source text and,
// where a field cannot be grounded, downgrades it to origin 'authored' + verifyFlag.
//
// TCA class theme: block NE + 5-HT reuptake (NET + SERT) AND antagonize H1 (sedation/weight
// gain), M1 (anticholinergic — dry mouth, constipation, urinary retention, blurred vision),
// and α1 (orthostatic hypotension). Fast cardiac Na-channel blockade → membrane-stabilizing
// cardiotoxicity. OVERDOSE IS LETHAL (narrow therapeutic index): the "3 C's" — Cardiotoxicity
// (wide QRS, arrhythmia), Convulsions, Coma — plus anticholinergic toxidrome; a ~1–2 week
// supply can kill. This lethality is the key high-yield contrast with SSRIs. Secondary amines
// (nortriptyline, desipramine, protriptyline) are demethylated, more noradrenergic and better
// tolerated than tertiary amines (amitriptyline, imipramine, clomipramine, doxepin,
// trimipramine). Nortriptyline has a genuine therapeutic window (~50–150 ng/mL → TDM).
// ECG at baseline (esp. age >40 / cardiac disease). MAOIs contraindicated (washout each way).

const TCA_PROV = {
  startingDose: 'openfda', maxDose: 'openfda', seriousAE: 'openfda', syndromes: 'openfda',
  majorDDI: 'openfda', contraindicatedCombos: 'openfda', pregnancy: 'openfda',
  overdoseLethality: 'openfda',
};

export default {
  amitriptyline: {
    pronunciation: 'am-ee-TRIP-tuh-leen',
    moa: 'Tertiary-amine tricyclic; blocks NE and 5-HT reuptake (NET + SERT). Potent H1, M1 (muscarinic) and α1 antagonist.',
    receptorProfile: 'Strong H1 (sedation), M1 (anticholinergic) and α1 (orthostasis) blockade — most sedating/anticholinergic TCA. Fast Na-channel blockade underlies overdose cardiotoxicity.',
    onsetOfEffect: 'Mood 2–4 wk (full 4–6 wk); analgesic/sleep benefit often within days at low dose.',
    halfLife: '~10–28 hours (parent); active metabolite nortriptyline extends effect.',
    timeToSteadyState: '~1 week.',
    metabolism: 'Hepatic — demethylated to nortriptyline (active). CYP2D6 substrate (also 2C19/3A4/1A2); 2D6 polymorphism drives level variability.',
    activeMetabolites: 'Nortriptyline (active secondary amine).',
    proteinBinding: 'High (>90%).',
    offLabel: ['Migraine prophylaxis', 'Neuropathic pain', 'Chronic tension-type headache', 'Fibromyalgia', 'Insomnia (low dose)'],
    approvedPopulations: 'Adults; not first-line in elderly (anticholinergic/orthostatic burden).',
    startingDose: '25 mg PO at bedtime for depression (10–25 mg qhs for pain/insomnia).',
    titration: 'Increase by 25 mg every few days as tolerated; give sedating dose at bedtime.',
    maxDose: '150 mg/day outpatient (up to 300 mg/day inpatient).',
    frequencyTiming: 'Once daily at bedtime (sedation is useful for sleep).',
    startStopCrossTaper: 'Taper to avoid cholinergic-rebound discontinuation (nausea, malaise, insomnia). 14-day MAOI washout each way.',
    commonSE: ['Sedation', 'Dry mouth', 'Constipation', 'Weight gain', 'Orthostatic hypotension', 'Blurred vision', 'Urinary hesitancy'],
    seriousAE: ['Cardiac conduction delay / arrhythmia (wide QRS, QT prolongation)', 'Seizures', 'Anticholinergic delirium (esp. elderly)', 'Orthostatic hypotension → falls', 'Increased suicidality (young adults)'],
    syndromes: ['Anticholinergic toxidrome', 'Cardiotoxicity (Na-channel block)', 'Serotonin syndrome (with MAOI/serotonergics)', 'Discontinuation (cholinergic rebound)'],
    overdoseLethality: 'HIGH — one of the most lethal antidepressants in overdose. Na-channel blockade → wide QRS/ventricular arrhythmia, plus seizures and coma (the 3 C\'s) and severe anticholinergic toxicity. Narrow therapeutic index; a ~1–2 week supply can be fatal. IV sodium bicarbonate for QRS >100 ms.',
    discontinuationSyndrome: 'Cholinergic rebound (nausea, GI upset, malaise, vivid dreams, insomnia) — taper.',
    baselineWorkup: ['ECG (baseline, especially age >40 or known cardiac disease)'],
    ongoingMonitoring: 'Mood/suicidality; anticholinergic and orthostatic burden; ECG if cardiac risk or dose escalation.',
    majorDDI: ['MAOIs (contraindicated — serotonin syndrome / hyperpyrexia; 14-day washout)', 'CYP2D6 inhibitors (fluoxetine, paroxetine, bupropion) raise TCA levels', 'Other anticholinergics (additive toxidrome)', 'QT-prolonging drugs / class I antiarrhythmics', 'CNS depressants / alcohol'],
    contraindicatedCombos: ['MAOIs (incl. within 14 days)', 'Recent acute MI / significant conduction disease', 'Concurrent QT-prolonging antiarrhythmics'],
    maoiWashout: '14 days each way.',
    pregnancy: 'Long human experience; weigh untreated illness. Nortriptyline (its metabolite) often preferred if a TCA is needed. Tie to CANMAT perinatal 2024.',
    lactation: 'Excreted in low amounts; generally considered compatible with monitoring.',
    geriatric: 'Avoid where possible — most anticholinergic/orthostatic TCA (falls, confusion, constipation, urinary retention); on Beers list. Prefer nortriptyline.',
    cardiac: 'Class-IA–like Na-channel block: prolongs QRS/QT; avoid post-MI and in conduction disease.',
    pearls: [
      'The most sedating and most anticholinergic TCA — hence the migraine/neuropathic-pain/insomnia off-label niche at low dose.',
      'Demethylated to nortriptyline; a tertiary amine, so more serotonergic and less well tolerated than its secondary-amine metabolite.',
      'Overdose is potentially lethal — never a first-line antidepressant in a patient with suicide risk.',
    ],
    mnemonics: ['TCA overdose = the "3 C\'s": Cardiotoxicity, Convulsions, Coma (+ anticholinergic).'],
    confusables: ['Amitriptyline (tertiary, sedating) vs nortriptyline (its secondary-amine metabolite, better tolerated, TDM window).'],
    classDifferentiators: 'Prototypical sedating/anticholinergic tertiary-amine TCA; low-dose analgesic/hypnotic uses.',
    examHooks: ['Which TCA is most sedating/anticholinergic and used off-label for migraine and neuropathic pain? (amitriptyline)'],
    counsellingPoints: ['Take at bedtime (causes drowsiness).', 'Rise slowly (dizziness on standing).', 'Overdose is dangerous — keep secured; never double up.', 'Dry mouth/constipation are common.'],
    vignettes: [
      {
        stem: 'A 34-year-old with chronic migraine and insomnia is started on a low-dose tricyclic. Which agent is the classic sedating TCA chosen for migraine prophylaxis and neuropathic pain?',
        options: ['Desipramine', 'Amitriptyline', 'Protriptyline', 'Fluoxetine'],
        answer: 'Amitriptyline',
        explanation: 'Amitriptyline is the most sedating/anticholinergic TCA and, at low doses, is a standard off-label choice for migraine prophylaxis, neuropathic pain and insomnia. Secondary amines (desipramine, protriptyline) are more activating.',
        testedFact: 'Amitriptyline off-label pain/migraine use',
        source: { name: 'openFDA/DailyMed amitriptyline label; CANMAT/neuropathic pain guidance', origin: 'openfda' },
      },
    ],
    _prov: TCA_PROV,
  },

  nortriptyline: {
    pronunciation: 'nor-TRIP-tuh-leen',
    moa: 'Secondary-amine tricyclic (active metabolite of amitriptyline); blocks NE > 5-HT reuptake. Less H1/M1/α1 blockade than tertiary amines.',
    receptorProfile: 'More noradrenergic and cleaner than amitriptyline: least orthostatic hypotension of the TCAs, less sedation/anticholinergic load. Retains Na-channel block in overdose.',
    onsetOfEffect: 'Mood 2–4 wk (full 4–6 wk).',
    halfLife: '~18–44 hours (~30 h).',
    timeToSteadyState: '~4–7 days.',
    metabolism: 'Hepatic; hydroxylated primarily by CYP2D6 (2D6 polymorphism affects levels).',
    activeMetabolites: '10-hydroxynortriptyline (minor).',
    proteinBinding: 'High (~90%).',
    therapeuticLevel: 'Therapeutic window ~50–150 ng/mL (curvilinear — efficacy falls off above ~150 ng/mL); one of the few antidepressants with genuine TDM.',
    offLabel: ['Neuropathic pain', 'Smoking cessation', 'Chronic pain / migraine prophylaxis'],
    approvedPopulations: 'Adults; preferred TCA in the elderly when a TCA is required.',
    startingDose: '25 mg PO at bedtime (10–25 mg in elderly).',
    titration: 'Increase by 25 mg every few days toward 75–100 mg/day; check level to target window.',
    therapeuticRange: '~50–150 ng/mL (therapeutic window).',
    maxDose: '150 mg/day.',
    frequencyTiming: 'Once daily at bedtime or divided.',
    startStopCrossTaper: 'Taper to limit cholinergic rebound. 14-day MAOI washout each way.',
    commonSE: ['Dry mouth', 'Constipation', 'Mild sedation', 'Blurred vision', 'Mild orthostasis (least of TCAs)'],
    seriousAE: ['Cardiac conduction delay / arrhythmia (wide QRS, QT)', 'Seizures', 'Orthostatic hypotension (less than tertiary amines)', 'Increased suicidality (young adults)'],
    syndromes: ['Cardiotoxicity (Na-channel block)', 'Anticholinergic toxidrome', 'Serotonin syndrome (with MAOI/serotonergics)'],
    overdoseLethality: 'HIGH — like all TCAs, lethal in overdose via Na-channel-blockade cardiotoxicity (wide QRS, arrhythmia), seizures and coma. Narrow therapeutic index despite better routine tolerability. IV sodium bicarbonate for QRS >100 ms.',
    discontinuationSyndrome: 'Cholinergic rebound — taper.',
    baselineWorkup: ['ECG (baseline, especially age >40 or cardiac disease)', 'Plasma level to target therapeutic window (~50–150 ng/mL)'],
    ongoingMonitoring: 'Serum level (TDM) toward 50–150 ng/mL; mood/suicidality; ECG if cardiac risk.',
    majorDDI: ['MAOIs (contraindicated; 14-day washout)', 'CYP2D6 inhibitors (fluoxetine, paroxetine, bupropion) raise levels', 'QT-prolonging drugs / class I antiarrhythmics', 'Other anticholinergics (additive)', 'CNS depressants / alcohol'],
    contraindicatedCombos: ['MAOIs (incl. within 14 days)', 'Recent acute MI / significant conduction disease'],
    maoiWashout: '14 days each way.',
    pregnancy: 'Long experience; often the preferred TCA in pregnancy when one is needed — weigh untreated illness. Tie to CANMAT perinatal 2024.',
    lactation: 'Low relative infant dose; generally compatible with monitoring.',
    geriatric: 'Preferred TCA in older adults — least orthostatic hypotension and less anticholinergic than amitriptyline; still monitor and use TDM.',
    cardiac: 'Na-channel effects persist — ECG and caution in conduction disease; avoid post-MI.',
    pearls: [
      'Therapeutic WINDOW (~50–150 ng/mL): a rare antidepressant with true therapeutic drug monitoring — levels above the window can reduce efficacy.',
      'Secondary-amine metabolite of amitriptyline: more noradrenergic, less sedating/anticholinergic, and the least-orthostatic TCA → preferred in the elderly.',
    ],
    mnemonics: ['"NORtriptyline has a NARrow window" — target 50–150 ng/mL (check a level).'],
    confusables: ['Nortriptyline (secondary amine, TDM window, better tolerated) vs amitriptyline (its sedating tertiary-amine parent).', 'Nortriptyline vs protriptyline — both secondary amines, but protriptyline is activating, not sedating.'],
    classDifferentiators: 'The better-tolerated secondary-amine TCA with a genuine therapeutic window; TDM-guided; elderly-preferred.',
    examHooks: ['Which TCA has a therapeutic WINDOW (~50–150 ng/mL) rather than a floor? (nortriptyline)'],
    counsellingPoints: ['We will check a blood level to get the dose right.', 'Take at bedtime.', 'Rise slowly.', 'Overdose is dangerous — keep secured.'],
    vignettes: [
      {
        stem: 'A 68-year-old on a TCA for depression has a partial response; the level returns at 210 ng/mL. What is the best next step and why?',
        options: ['Increase the dose — higher levels are more effective', 'Reduce the dose — the level is above the therapeutic window', 'Add lithium and keep the dose', 'No change — TCAs have no useful level'],
        answer: 'Reduce the dose — the level is above the therapeutic window',
        explanation: 'Nortriptyline shows a curvilinear therapeutic window (~50–150 ng/mL); efficacy can fall at higher levels, so lowering the dose into the window is appropriate. It is one of the few antidepressants with genuine TDM.',
        testedFact: 'Nortriptyline therapeutic window (TDM)',
        source: { name: 'Nortriptyline product monograph — therapeutic plasma levels', origin: 'monograph' },
      },
    ],
    _prov: { ...TCA_PROV, therapeuticLevel: 'monograph' },
  },

  imipramine: {
    pronunciation: 'im-IP-ruh-meen',
    moa: 'Tertiary-amine tricyclic (the prototype TCA); blocks NE and 5-HT reuptake. H1/M1/α1 antagonist.',
    receptorProfile: 'Balanced NE/5-HT reuptake block with significant anticholinergic/antihistaminic/α1 effects; Na-channel block in overdose.',
    onsetOfEffect: 'Mood 2–4 wk; antienuretic effect within days.',
    halfLife: '~11–25 hours (parent); active metabolite desipramine longer.',
    timeToSteadyState: '~2–5 days.',
    metabolism: 'Hepatic — demethylated to desipramine (active). CYP2D6 and CYP2C19/1A2/3A4 substrate.',
    activeMetabolites: 'Desipramine (active secondary amine).',
    proteinBinding: 'High (~90%).',
    approvedCanada: ['Depression', 'Nocturnal enuresis (children)'],
    offLabel: ['Panic disorder', 'Neuropathic pain'],
    approvedPopulations: 'Adults; children ≥6 y for enuresis (short-term).',
    startingDose: '25–75 mg PO daily for depression; enuresis 25 mg qhs (age-adjusted).',
    titration: 'Increase gradually; give larger portion at bedtime.',
    maxDose: '200 mg/day outpatient (up to 300 mg/day inpatient); enuresis usually ≤50–75 mg qhs.',
    frequencyTiming: 'Once daily (bedtime) or divided.',
    startStopCrossTaper: 'Taper to avoid cholinergic rebound. 14-day MAOI washout each way.',
    commonSE: ['Dry mouth', 'Sedation', 'Constipation', 'Orthostatic hypotension', 'Weight gain', 'Sweating'],
    seriousAE: ['Cardiac conduction delay / arrhythmia (wide QRS, QT)', 'Seizures', 'Anticholinergic delirium', 'Orthostatic hypotension → falls', 'Increased suicidality (young adults)'],
    syndromes: ['Cardiotoxicity (Na-channel block)', 'Anticholinergic toxidrome', 'Serotonin syndrome (with MAOI/serotonergics)'],
    overdoseLethality: 'HIGH — lethal in overdose (3 C\'s: cardiotoxicity, convulsions, coma) plus anticholinergic toxicity; particular caution because it is prescribed to children for enuresis (accidental pediatric ingestion). IV sodium bicarbonate for QRS >100 ms.',
    discontinuationSyndrome: 'Cholinergic rebound — taper.',
    baselineWorkup: ['ECG (baseline, especially age >40, cardiac disease, or before pediatric enuresis dosing)'],
    ongoingMonitoring: 'Mood/suicidality; anticholinergic/orthostatic effects; ECG with cardiac risk or higher doses.',
    majorDDI: ['MAOIs (contraindicated; 14-day washout)', 'CYP2D6 inhibitors (fluoxetine, paroxetine, bupropion) raise levels', 'QT-prolonging drugs / class I antiarrhythmics', 'Other anticholinergics (additive)', 'CNS depressants / alcohol'],
    contraindicatedCombos: ['MAOIs (incl. within 14 days)', 'Recent acute MI / significant conduction disease'],
    maoiWashout: '14 days each way.',
    pregnancy: 'Long experience; weigh untreated illness. Tie to CANMAT perinatal 2024.',
    lactation: 'Excreted in small amounts; monitor infant.',
    geriatric: 'Anticholinergic/orthostatic — prefer a secondary amine (desipramine/nortriptyline) if a TCA is required.',
    cardiac: 'Na-channel block; ECG and caution in conduction disease; classic caution with pediatric enuresis dosing.',
    pearls: [
      'Prototype TCA; classic agents for childhood nocturnal enuresis and for panic disorder.',
      'Demethylated to desipramine (active) — a tertiary→secondary amine pair mirroring amitriptyline→nortriptyline.',
      'Overdose lethality is especially concerning when tablets are in a household with children (enuresis indication).',
    ],
    mnemonics: ['"imIPramine → Incontinence (Pediatric)": the enuresis TCA.'],
    confusables: ['Imipramine (tertiary) vs desipramine (its secondary-amine, most noradrenergic metabolite).'],
    classDifferentiators: 'Prototype tertiary-amine TCA with enuresis and panic indications; parent of desipramine.',
    examHooks: ['Which TCA is classically used for childhood nocturnal enuresis? (imipramine)'],
    counsellingPoints: ['For enuresis, dose at bedtime and secure tablets from children.', 'Rise slowly (dizziness).', 'Effect on mood takes weeks.', 'Overdose is dangerous.'],
    vignettes: [
      {
        stem: 'A 9-year-old with refractory nocturnal enuresis (after alarms and desmopressin) may be offered a tricyclic. Which TCA is the classic choice, and what must be counselled about supply safety?',
        options: ['Clomipramine — highest seizure risk', 'Imipramine — secure tablets (overdose is lethal)', 'Doxepin — used as a topical', 'Amoxapine — causes EPS'],
        answer: 'Imipramine — secure tablets (overdose is lethal)',
        explanation: 'Imipramine is the classic TCA for nocturnal enuresis. Because TCA overdose is lethal (cardiotoxicity, seizures, coma) and the drug is used in a household with a child, families must secure the tablets.',
        testedFact: 'Imipramine for enuresis + overdose safety',
        source: { name: 'openFDA/DailyMed imipramine label — enuresis indication & overdosage', origin: 'openfda' },
      },
    ],
    _prov: TCA_PROV,
  },

  desipramine: {
    pronunciation: 'des-IP-ruh-meen',
    moa: 'Secondary-amine tricyclic (active metabolite of imipramine); the most selective noradrenergic reuptake inhibitor of the TCAs.',
    receptorProfile: 'Most noradrenergic, least anticholinergic/sedating TCA — comparatively "activating". Na-channel block persists in overdose.',
    onsetOfEffect: 'Mood 2–4 wk.',
    halfLife: '~15–24 hours.',
    timeToSteadyState: '~2–5 days.',
    metabolism: 'Hepatic; hydroxylated primarily by CYP2D6 (2D6 poor metabolizers accumulate drug).',
    activeMetabolites: '2-hydroxydesipramine (minor).',
    proteinBinding: 'High (~90%).',
    offLabel: ['Neuropathic pain', 'ADHD (adjunct)'],
    approvedPopulations: 'Adults. Note: pediatric sudden-death reports — generally avoided in children.',
    startingDose: '25–75 mg PO daily.',
    titration: 'Increase gradually toward 100–200 mg/day.',
    maxDose: '200 mg/day outpatient (up to 300 mg/day inpatient).',
    frequencyTiming: 'Once daily (may be given in the morning given its activating profile) or divided.',
    startStopCrossTaper: 'Taper. 14-day MAOI washout each way.',
    commonSE: ['Less sedation/dry mouth than tertiary amines', 'Insomnia/activation', 'Orthostatic hypotension', 'Sweating', 'Tremor'],
    seriousAE: ['Cardiac conduction delay / arrhythmia (wide QRS, QT); pediatric sudden-death reports', 'Seizures', 'Orthostatic hypotension → falls', 'Increased suicidality (young adults)'],
    syndromes: ['Cardiotoxicity (Na-channel block)', 'Anticholinergic toxidrome (least, but present)', 'Serotonin syndrome (with MAOI/serotonergics)'],
    overdoseLethality: 'HIGH — lethal in overdose via Na-channel-blockade cardiotoxicity (wide QRS, arrhythmia), seizures and coma, despite the lightest routine anticholinergic load. Sudden death has been reported in children. IV sodium bicarbonate for QRS >100 ms.',
    discontinuationSyndrome: 'Cholinergic rebound — taper.',
    baselineWorkup: ['ECG (baseline, especially age >40 or cardiac disease)'],
    ongoingMonitoring: 'Mood/suicidality; ECG with cardiac risk or dose escalation.',
    majorDDI: ['MAOIs (contraindicated; 14-day washout)', 'CYP2D6 inhibitors (fluoxetine, paroxetine, bupropion) raise levels markedly', 'QT-prolonging drugs / class I antiarrhythmics', 'CNS depressants / alcohol'],
    contraindicatedCombos: ['MAOIs (incl. within 14 days)', 'Recent acute MI / significant conduction disease'],
    maoiWashout: '14 days each way.',
    pregnancy: 'Weigh untreated illness; nortriptyline usually preferred if a TCA is needed. Tie to CANMAT perinatal 2024.',
    lactation: 'Small amounts in milk; monitor infant.',
    geriatric: 'Among the better-tolerated TCAs (low anticholinergic load) but still cardiotoxic — ECG and caution.',
    cardiac: 'Na-channel block; ECG required. Pediatric sudden-death reports underscore cardiac risk.',
    pearls: [
      'The most noradrenergic and least anticholinergic/sedating TCA — the closest to a "clean," activating tricyclic.',
      'Secondary-amine metabolite of imipramine; a strong CYP2D6 substrate, so 2D6 inhibitors (fluoxetine/paroxetine/bupropion) sharply raise its level.',
    ],
    mnemonics: ['"DESipramine = DEStination Noradrenaline" — most NE-selective, least anticholinergic TCA.'],
    confusables: ['Desipramine (secondary, noradrenergic) vs imipramine (its tertiary-amine parent).', 'Desipramine vs desvenlafaxine (an SNRI) — similar prefix, different class.'],
    classDifferentiators: 'The most noradrenergic / least anticholinergic TCA; activating rather than sedating.',
    examHooks: ['Which TCA is the most selective noradrenergic reuptake inhibitor and least sedating/anticholinergic? (desipramine)'],
    counsellingPoints: ['May be more activating — take earlier if it disrupts sleep.', 'Rise slowly.', 'Overdose is dangerous — keep secured.'],
    vignettes: [
      {
        stem: 'A depressed patient with prominent daytime fatigue is intolerant of anticholinergic effects. If a TCA is chosen, which secondary amine is the most noradrenergic and least anticholinergic option?',
        options: ['Amitriptyline', 'Doxepin', 'Desipramine', 'Clomipramine'],
        answer: 'Desipramine',
        explanation: 'Desipramine (a secondary amine, metabolite of imipramine) is the most selective noradrenergic reuptake inhibitor and the least anticholinergic/sedating TCA — but it remains cardiotoxic in overdose.',
        testedFact: 'Desipramine = most noradrenergic / least anticholinergic TCA',
        source: { name: 'openFDA/DailyMed desipramine label — pharmacology', origin: 'openfda' },
      },
    ],
    _prov: TCA_PROV,
  },

  clomipramine: {
    pronunciation: 'kloh-MIP-ruh-meen',
    moa: 'Tertiary-amine tricyclic; the most serotonergic TCA — potent SERT inhibition by the parent (its metabolite desmethylclomipramine is noradrenergic). Also H1/M1/α1 blockade.',
    receptorProfile: 'Strongest 5-HT reuptake block of the TCAs (basis for OCD efficacy); anticholinergic/sedating; Na-channel block in overdose; lowers seizure threshold most.',
    onsetOfEffect: 'Depression 2–4 wk; OCD response often 6–12 wk.',
    halfLife: '~20–30 hours (parent); active metabolite desmethylclomipramine longer.',
    timeToSteadyState: '~1–2 weeks.',
    metabolism: 'Hepatic; CYP2D6 (also 1A2/3A4/2C19) — demethylated to desmethylclomipramine (active, noradrenergic).',
    activeMetabolites: 'Desmethylclomipramine (active).',
    proteinBinding: 'High (~97%).',
    approvedCanada: ['Obsessive-compulsive disorder', 'Depression'],
    offLabel: ['Panic disorder', 'Premature ejaculation'],
    approvedPopulations: 'Adults; children ≥10 y for OCD (specialist).',
    startingDose: '25 mg PO daily, increased gradually.',
    titration: 'Increase over ~2 weeks toward 100–250 mg/day; do not exceed the seizure-limited ceiling.',
    maxDose: '250 mg/day (ceiling driven by dose-dependent seizure risk).',
    frequencyTiming: 'Once daily at bedtime (sedating) once titrated.',
    startStopCrossTaper: 'Taper to avoid cholinergic rebound. 14-day MAOI washout each way.',
    commonSE: ['Dry mouth', 'Sedation', 'Constipation', 'Weight gain', 'Sexual dysfunction (marked)', 'Sweating', 'Tremor'],
    seriousAE: ['Seizures (highest risk of the TCAs — dose-dependent, esp. >250 mg)', 'Cardiac conduction delay / arrhythmia (wide QRS, QT)', 'Anticholinergic delirium', 'Orthostatic hypotension', 'Increased suicidality (young adults)'],
    syndromes: ['Seizure (lowest threshold TCA)', 'Cardiotoxicity (Na-channel block)', 'Serotonin syndrome (with MAOI/serotonergics)', 'Anticholinergic toxidrome'],
    overdoseLethality: 'HIGH — lethal in overdose: cardiotoxicity (wide QRS, arrhythmia), coma and, notably, the greatest seizure risk of the TCAs. Narrow therapeutic index; IV sodium bicarbonate for QRS >100 ms and benzodiazepines for seizures.',
    discontinuationSyndrome: 'Cholinergic rebound — taper.',
    baselineWorkup: ['ECG (baseline, especially age >40 or cardiac disease)'],
    ongoingMonitoring: 'Mood/OCD symptoms/suicidality; seizure history at higher doses; ECG if cardiac risk.',
    majorDDI: ['MAOIs (contraindicated — serotonin syndrome; 14-day washout)', 'CYP2D6/1A2/3A4 inhibitors raise levels and seizure risk', 'Other serotonergics (triptans, tramadol, linezolid) — serotonin syndrome', 'Seizure-threshold-lowering drugs (additive)', 'QT-prolonging drugs'],
    contraindicatedCombos: ['MAOIs (incl. within 14 days)', 'Recent acute MI / significant conduction disease'],
    maoiWashout: '14 days each way.',
    pregnancy: 'Weigh untreated illness; SSRIs generally preferred for OCD in pregnancy. Tie to CANMAT perinatal 2024.',
    lactation: 'Small amounts in milk; monitor infant.',
    geriatric: 'Anticholinergic/sedating and seizure-lowering — use cautiously; prefer an SSRI for OCD.',
    cardiac: 'Na-channel block; ECG and caution in conduction disease.',
    pearls: [
      'The most serotonergic TCA and the historical gold-standard TCA for OCD — the only TCA with robust OCD efficacy.',
      'Highest seizure risk of the TCAs (dose-dependent) → the 250 mg/day ceiling; watch combinations that add to serotonergic or seizure burden.',
    ],
    mnemonics: ['"CLOMIpramine = OCD + Convulsions" — most serotonergic TCA, highest seizure risk.'],
    confusables: ['Clomipramine (TCA for OCD) vs clomifene/clomiphene (ovulation induction) — sound-alikes, unrelated.', 'Clomipramine (serotonergic TCA) vs clonidine (α2 agonist).'],
    classDifferentiators: 'Most serotonergic TCA; OCD indication; highest seizure risk / lowest seizure threshold.',
    examHooks: ['Which TCA is most serotonergic, is used for OCD, and carries the highest seizure risk? (clomipramine)'],
    counsellingPoints: ['OCD response can take 6–12 weeks.', 'Report any seizure-like episodes; avoid unnecessary seizure-lowering drugs.', 'Sexual side effects are common.', 'Overdose is dangerous.'],
    vignettes: [
      {
        stem: 'A patient with severe OCD who failed two SSRIs is considered for a tricyclic. Which TCA has the best OCD evidence, and what dose-limiting adverse effect must be counselled?',
        options: ['Nortriptyline — orthostasis', 'Clomipramine — seizures (highest TCA risk)', 'Desipramine — sedation', 'Doxepin — EPS'],
        answer: 'Clomipramine — seizures (highest TCA risk)',
        explanation: 'Clomipramine is the most serotonergic TCA and the tricyclic with established OCD efficacy. It has the highest (dose-dependent) seizure risk of the class, which caps dosing around 250 mg/day.',
        testedFact: 'Clomipramine OCD + highest seizure risk',
        source: { name: 'openFDA/DailyMed clomipramine label — indications & seizure warning', origin: 'openfda' },
      },
    ],
    _prov: TCA_PROV,
  },

  doxepin: {
    pronunciation: 'DOX-uh-pin',
    moa: 'Tertiary-amine tricyclic; blocks NE and 5-HT reuptake and is one of the most potent H1 antihistamines available. M1/α1 antagonist.',
    receptorProfile: 'Extremely potent H1 blockade → strong sedation, exploited at very low dose as a selective H1 hypnotic. Anticholinergic; Na-channel block in overdose at antidepressant doses.',
    onsetOfEffect: 'Sleep onset benefit same night at low dose; antidepressant effect 2–4 wk.',
    halfLife: '~15 hours (parent); active metabolite nordoxepin ~30 h.',
    timeToSteadyState: '~1 week.',
    metabolism: 'Hepatic; CYP2D6 (also 1A2/2C19/3A4) — demethylated to nordoxepin (active).',
    activeMetabolites: 'Nordoxepin (active).',
    proteinBinding: 'High.',
    offLabel: ['Chronic urticaria / pruritus (antihistamine)', 'Topical for pruritus'],
    approvedPopulations: 'Adults; low-dose formulation for insomnia (sleep-maintenance).',
    startingDose: 'Depression 25–75 mg qhs; insomnia 3–6 mg qhs (low-dose H1 hypnotic).',
    titration: 'For depression, increase gradually; the insomnia dose is not titrated upward.',
    maxDose: '150 mg/day outpatient (up to 300 mg/day inpatient); insomnia 6 mg/day.',
    frequencyTiming: 'Bedtime (sedating).',
    startStopCrossTaper: 'Taper at antidepressant doses. 14-day MAOI washout each way.',
    commonSE: ['Sedation (marked)', 'Dry mouth', 'Constipation', 'Weight gain', 'Orthostatic hypotension', 'Next-day drowsiness'],
    seriousAE: ['Cardiac conduction delay / arrhythmia (wide QRS, QT) at antidepressant doses', 'Seizures', 'Anticholinergic delirium', 'Orthostatic hypotension → falls', 'Increased suicidality (young adults)'],
    syndromes: ['Anticholinergic toxidrome', 'Cardiotoxicity (Na-channel block)', 'Serotonin syndrome (with MAOI/serotonergics)'],
    overdoseLethality: 'HIGH at antidepressant doses — cardiotoxicity (wide QRS, arrhythmia), seizures and coma; the low-dose (3–6 mg) hypnotic formulation carries far less TCA cardiotoxicity but a full antidepressant supply is lethal. IV sodium bicarbonate for QRS >100 ms.',
    discontinuationSyndrome: 'Cholinergic rebound at antidepressant doses — taper.',
    baselineWorkup: ['ECG (baseline at antidepressant doses, especially age >40 or cardiac disease)'],
    ongoingMonitoring: 'Sedation/next-day impairment; mood/suicidality; ECG if cardiac risk at higher doses.',
    majorDDI: ['MAOIs (contraindicated; 14-day washout)', 'CYP2D6 inhibitors (fluoxetine, paroxetine, bupropion) raise levels', 'Other sedatives / CNS depressants / alcohol (additive sedation)', 'QT-prolonging drugs', 'Other anticholinergics'],
    contraindicatedCombos: ['MAOIs (incl. within 14 days)', 'Untreated narrow-angle glaucoma / urinary retention (strong anticholinergic)', 'Recent acute MI / conduction disease'],
    maoiWashout: '14 days each way.',
    pregnancy: 'Weigh untreated illness. Tie to CANMAT perinatal 2024.',
    lactation: 'A case of infant sedation/respiratory depression reported — generally avoided in breastfeeding.',
    geriatric: 'Anticholinergic/sedating at antidepressant doses; the low-dose hypnotic (3–6 mg) is comparatively better studied for insomnia in older adults.',
    cardiac: 'Na-channel block at antidepressant doses; ECG and caution.',
    pearls: [
      'One of the most potent H1 antihistamines — at low dose (3–6 mg) it is a selective histamine-blocking hypnotic for sleep maintenance, with minimal TCA toxicity.',
      'At full antidepressant doses it behaves like any tertiary-amine TCA: sedating, anticholinergic and cardiotoxic in overdose.',
    ],
    mnemonics: ['"Low-dose Doxepin = Dozing (H1 hypnotic)".'],
    confusables: ['Doxepin (TCA / H1 hypnotic) vs doxazosin (α1-blocker for BPH/HTN) — sound-alikes.'],
    classDifferentiators: 'The most antihistaminic TCA; uniquely repurposed at very low dose as a pure H1 hypnotic.',
    examHooks: ['Which tricyclic, at 3–6 mg, is used as a selective H1-antihistamine hypnotic for sleep maintenance? (doxepin)'],
    counsellingPoints: ['Very sedating — take at bedtime and beware next-day drowsiness.', 'Do not combine with alcohol/other sedatives.', 'Full antidepressant doses are dangerous in overdose.'],
    vignettes: [
      {
        stem: 'A 70-year-old with sleep-maintenance insomnia but no depression is prescribed a 3 mg tricyclic at bedtime. Which agent is being used, and why is this low dose favoured?',
        options: ['Amitriptyline — for its analgesia', 'Doxepin — selective H1 blockade with minimal anticholinergic/cardiac effect', 'Clomipramine — for serotonergic sleep effects', 'Protriptyline — for its sedation'],
        answer: 'Doxepin — selective H1 blockade with minimal anticholinergic/cardiac effect',
        explanation: 'At 3–6 mg, doxepin acts as a nearly pure H1 antihistamine hypnotic for sleep maintenance, avoiding the anticholinergic and cardiotoxic effects seen at antidepressant doses.',
        testedFact: 'Low-dose doxepin as H1 hypnotic',
        source: { name: 'openFDA/DailyMed doxepin (low-dose) label — insomnia indication', origin: 'openfda' },
      },
    ],
    _prov: TCA_PROV,
  },

  trimipramine: {
    pronunciation: 'try-MIP-ruh-meen',
    moa: 'Tertiary-amine tricyclic; weak monoamine reuptake inhibition relative to its strong H1/M1/α1 antagonism — behaves mainly as a sedating antidepressant.',
    receptorProfile: 'Marked H1 (sedation) and anticholinergic blockade with comparatively weak reuptake inhibition; little REM suppression. Na-channel block in overdose.',
    onsetOfEffect: 'Sleep benefit early; mood 2–4 wk.',
    halfLife: '~20–26 hours.',
    timeToSteadyState: '~1 week.',
    metabolism: 'Hepatic; CYP2D6 (also 2C19) substrate.',
    proteinBinding: 'High (~95%).',
    approvedCanada: ['Depression'],
    offLabel: ['Depression with prominent insomnia'],
    approvedPopulations: 'Adults.',
    startingDose: '25–50 mg PO at bedtime.',
    titration: 'Increase gradually toward 75–150 mg/day.',
    maxDose: '150 mg/day outpatient (up to 300 mg/day inpatient).',
    frequencyTiming: 'Bedtime (sedating).',
    startStopCrossTaper: 'Taper. 14-day MAOI washout each way.',
    commonSE: ['Sedation (marked)', 'Dry mouth', 'Constipation', 'Weight gain', 'Orthostatic hypotension'],
    seriousAE: ['Cardiac conduction delay / arrhythmia (wide QRS, QT)', 'Seizures', 'Anticholinergic delirium', 'Orthostatic hypotension → falls', 'Increased suicidality (young adults)'],
    syndromes: ['Anticholinergic toxidrome', 'Cardiotoxicity (Na-channel block)', 'Serotonin syndrome (with MAOI/serotonergics)'],
    overdoseLethality: 'HIGH — like other tertiary-amine TCAs, lethal in overdose (cardiotoxicity, seizures, coma) plus anticholinergic toxicity. Narrow therapeutic index; IV sodium bicarbonate for QRS >100 ms.',
    discontinuationSyndrome: 'Cholinergic rebound — taper.',
    baselineWorkup: ['ECG (baseline, especially age >40 or cardiac disease)'],
    ongoingMonitoring: 'Sedation; mood/suicidality; ECG if cardiac risk.',
    majorDDI: ['MAOIs (contraindicated; 14-day washout)', 'CYP2D6 inhibitors (fluoxetine, paroxetine, bupropion) raise levels', 'Other sedatives / CNS depressants / alcohol', 'QT-prolonging drugs', 'Other anticholinergics'],
    contraindicatedCombos: ['MAOIs (incl. within 14 days)', 'Recent acute MI / significant conduction disease'],
    maoiWashout: '14 days each way.',
    pregnancy: 'Weigh untreated illness. Tie to CANMAT perinatal 2024.',
    lactation: 'Small amounts in milk; monitor infant.',
    geriatric: 'Sedating/anticholinergic — use cautiously; prefer a secondary amine if a TCA is needed.',
    cardiac: 'Na-channel block; ECG and caution in conduction disease.',
    pearls: [
      'A markedly sedating tertiary-amine TCA with relatively weak reuptake inhibition — chosen mainly for depression with prominent insomnia.',
      'Notable for causing little REM-sleep suppression compared with other TCAs, but still fully cardiotoxic in overdose.',
    ],
    mnemonics: ['"triMIPramine = time for sleep" — sedating TCA for depression with insomnia.'],
    confusables: ['Trimipramine (sedating TCA) vs trifluoperazine (an FGA antipsychotic) — similar prefix, different class.'],
    classDifferentiators: 'A sedating tertiary-amine TCA with weak reuptake inhibition and minimal REM suppression.',
    examHooks: ['Which sedating TCA has relatively weak reuptake inhibition and little REM suppression? (trimipramine)'],
    counsellingPoints: ['Very sedating — take at bedtime.', 'Rise slowly.', 'Avoid alcohol/other sedatives.', 'Overdose is dangerous.'],
    vignettes: [
      {
        stem: 'A patient with depression and severe insomnia is started on a sedating tertiary-amine TCA noted for weak reuptake inhibition and minimal REM suppression. Which agent fits best?',
        options: ['Desipramine', 'Protriptyline', 'Trimipramine', 'Nortriptyline'],
        answer: 'Trimipramine',
        explanation: 'Trimipramine is a strongly sedating tertiary-amine TCA with comparatively weak monoamine reuptake inhibition and little REM suppression, favouring depression with prominent insomnia. The listed secondary amines are more activating.',
        testedFact: 'Trimipramine sedating profile / weak reuptake',
        source: { name: 'openFDA/DailyMed trimipramine label — pharmacology', origin: 'openfda' },
      },
    ],
    _prov: TCA_PROV,
  },

  maprotiline: {
    pronunciation: 'ma-PROH-tih-leen',
    moa: 'Tetracyclic antidepressant; selective noradrenergic (NET) reuptake inhibitor with strong H1 and moderate M1/α1 blockade — pharmacologically TCA-like.',
    receptorProfile: 'Selective NE reuptake block; sedating/anticholinergic; notably lowers the seizure threshold. Na-channel block in overdose.',
    onsetOfEffect: 'Mood 2–4 wk.',
    halfLife: 'Long — ~27–58 hours (~43 h); accumulation contributes to seizure/toxicity risk.',
    timeToSteadyState: '~2 weeks (long half-life).',
    metabolism: 'Hepatic; CYP2D6 substrate — demethylmaprotiline metabolite.',
    proteinBinding: 'High (~88%).',
    approvedCanada: ['Depression'],
    approvedPopulations: 'Adults.',
    startingDose: '25–75 mg PO daily.',
    titration: 'Increase slowly (long half-life → accumulation); keep at the low end of the range to limit seizure risk.',
    maxDose: '150 mg/day outpatient (up to 225 mg/day short-term specialist use) — seizure-risk limited.',
    frequencyTiming: 'Once daily (bedtime) or divided.',
    startStopCrossTaper: 'Taper. 14-day MAOI washout each way.',
    commonSE: ['Sedation', 'Dry mouth', 'Constipation', 'Skin rash (relatively common)', 'Weight gain', 'Orthostatic hypotension'],
    seriousAE: ['Seizures (high risk — dose- and accumulation-dependent)', 'Cardiac conduction delay / arrhythmia (wide QRS, QT)', 'Anticholinergic delirium', 'Skin rash / photosensitivity', 'Increased suicidality (young adults)'],
    syndromes: ['Seizure (high risk)', 'Cardiotoxicity (Na-channel block)', 'Anticholinergic toxidrome'],
    overdoseLethality: 'HIGH — lethal in overdose with cardiotoxicity (wide QRS, arrhythmia), coma and prominent seizures owing to its long half-life and strong seizure-lowering effect. IV sodium bicarbonate for QRS >100 ms; benzodiazepines for seizures.',
    discontinuationSyndrome: 'Taper (long half-life softens but does not eliminate rebound).',
    baselineWorkup: ['ECG (baseline, especially age >40 or cardiac disease)'],
    ongoingMonitoring: 'Seizure risk (avoid rapid titration/high doses); mood/suicidality; ECG if cardiac risk; skin rash.',
    majorDDI: ['MAOIs (contraindicated; 14-day washout)', 'CYP2D6 inhibitors (fluoxetine, paroxetine, bupropion) raise levels', 'Seizure-threshold-lowering drugs (additive)', 'QT-prolonging drugs', 'Other anticholinergics / CNS depressants'],
    contraindicatedCombos: ['MAOIs (incl. within 14 days)', 'Recent acute MI / significant conduction disease', 'Seizure disorder (relative)'],
    maoiWashout: '14 days each way.',
    pregnancy: 'Weigh untreated illness. Tie to CANMAT perinatal 2024.',
    lactation: 'Excreted in milk; monitor infant.',
    geriatric: 'Long half-life → accumulation; sedating/anticholinergic and seizure-lowering — use cautiously.',
    cardiac: 'Na-channel block; ECG and caution in conduction disease.',
    pearls: [
      'A tetracyclic that is functionally a selective-noradrenergic TCA; its long half-life and strong seizure-lowering effect give it a notably HIGH seizure risk — titrate slowly and cap the dose.',
      'Skin rash is a recognized, relatively common adverse effect.',
    ],
    mnemonics: ['"Maprotiline = More seizures" — tetracyclic with high seizure risk and a long half-life.'],
    confusables: ['Maprotiline (tetracyclic, high seizure risk) vs mirtazapine (a NaSSA tetracyclic — very different pharmacology).', 'Maprotiline vs protriptyline — different classes, both activating/noradrenergic-flavoured.'],
    classDifferentiators: 'Tetracyclic, selective-NE, long half-life, high seizure risk; TCA-like toxicity.',
    examHooks: ['Which tetracyclic antidepressant carries a notably high seizure risk (long half-life, NE-selective)? (maprotiline)'],
    counsellingPoints: ['Report any seizure-like episodes.', 'Avoid rapid dose increases.', 'Watch for skin rash.', 'Overdose is dangerous — keep secured.'],
    vignettes: [
      {
        stem: 'A tetracyclic antidepressant with a long half-life is being titrated for depression. Compared with other antidepressants, which adverse effect is it particularly known for?',
        options: ['Priapism', 'Seizures', 'Agranulocytosis', 'Serotonin-only toxicity'],
        answer: 'Seizures',
        explanation: 'Maprotiline is a tetracyclic with a long half-life that markedly lowers the seizure threshold — seizures are a signature risk, especially with rapid titration, high doses, or overdose.',
        testedFact: 'Maprotiline high seizure risk',
        source: { name: 'openFDA/DailyMed maprotiline label — warnings (seizures)', origin: 'openfda' },
      },
    ],
    _prov: TCA_PROV,
  },

  amoxapine: {
    pronunciation: 'a-MOX-uh-peen',
    moa: 'Tetracyclic antidepressant (metabolite of the antipsychotic loxapine); blocks NE (and some 5-HT) reuptake AND antagonizes D2 dopamine receptors — a unique dual profile.',
    receptorProfile: 'NE reuptake block plus D2 antagonism (via 7-hydroxyamoxapine) → can cause extrapyramidal symptoms, tardive dyskinesia, hyperprolactinemia and neuroleptic malignant syndrome. Anticholinergic; Na-channel block in overdose.',
    onsetOfEffect: 'Mood 1–2 wk early, full 2–4 wk (relatively faster onset claimed).',
    halfLife: '~8 hours (parent); active metabolite 7-hydroxyamoxapine ~30 h.',
    timeToSteadyState: '~2–3 days (parent).',
    metabolism: 'Hepatic; hydroxylated to 7- and 8-hydroxyamoxapine (7-OH has antipsychotic-like D2 activity). CYP-mediated.',
    proteinBinding: 'High (~90%).',
    approvedPopulations: 'Adults.',
    startingDose: '50 mg PO two to three times daily.',
    titration: 'Increase toward 200–300 mg/day divided (single doses ≤300 mg).',
    maxDose: '400 mg/day outpatient (up to 600 mg/day inpatient).',
    frequencyTiming: 'Divided or once daily at bedtime once titrated.',
    startStopCrossTaper: 'Taper. 14-day MAOI washout each way.',
    commonSE: ['Sedation', 'Dry mouth', 'Constipation', 'Orthostatic hypotension', 'Weight gain', 'Extrapyramidal effects (akathisia, parkinsonism)'],
    seriousAE: ['Extrapyramidal symptoms, tardive dyskinesia, hyperprolactinemia (D2 blockade)', 'Neuroleptic malignant syndrome', 'Cardiac conduction delay / arrhythmia (wide QRS, QT)', 'Seizures (prominent in overdose)', 'Acute renal failure reported in overdose', 'Increased suicidality (young adults)'],
    syndromes: ['Extrapyramidal / tardive dyskinesia (D2 block)', 'Neuroleptic malignant syndrome', 'Cardiotoxicity (Na-channel block)', 'Anticholinergic toxidrome'],
    overdoseLethality: 'HIGH — TCA-type cardiotoxicity (wide QRS, arrhythmia) plus notably severe seizures/status epilepticus, coma and reports of acute renal failure and NMS. Narrow therapeutic index; IV sodium bicarbonate for QRS >100 ms, benzodiazepines for seizures.',
    discontinuationSyndrome: 'Cholinergic rebound — taper.',
    baselineWorkup: ['ECG (baseline, especially age >40 or cardiac disease)'],
    ongoingMonitoring: 'Watch for EPS/tardive dyskinesia and hyperprolactinemia (D2 blockade); mood/suicidality; ECG if cardiac risk.',
    majorDDI: ['MAOIs (contraindicated; 14-day washout)', 'CYP2D6 inhibitors raise levels', 'Other D2 antagonists / antipsychotics (additive EPS, NMS)', 'QT-prolonging drugs', 'Other anticholinergics / CNS depressants'],
    contraindicatedCombos: ['MAOIs (incl. within 14 days)', 'Recent acute MI / significant conduction disease'],
    maoiWashout: '14 days each way.',
    pregnancy: 'Weigh untreated illness; other antidepressants generally preferred given the D2/EPS profile. Tie to CANMAT perinatal 2024.',
    lactation: 'Excreted in milk; monitor infant.',
    geriatric: 'D2 blockade adds EPS/tardive-dyskinesia risk on top of TCA toxicity — generally avoid.',
    cardiac: 'Na-channel block; ECG and caution in conduction disease.',
    pearls: [
      'The odd TCA/tetracyclic out: as a metabolite of the antipsychotic loxapine it has D2 antagonism, so it can cause EPS, tardive dyskinesia, hyperprolactinemia and even NMS — unlike other TCAs.',
      'Overdose is especially dangerous: severe seizures/status epilepticus and reports of acute renal failure add to the usual TCA cardiotoxicity.',
    ],
    mnemonics: ['"amOXAPINE from lOXAPINE" — the TCA with antipsychotic (D2) actions → EPS/NMS.'],
    confusables: ['Amoxapine (antidepressant, D2-blocking) vs loxapine (its parent antipsychotic).', 'Amoxapine vs amoxicillin — sound-alike, unrelated.'],
    classDifferentiators: 'The only TCA-class agent with clinically relevant D2 antagonism → EPS/TD/NMS; severe overdose (seizures, renal failure).',
    examHooks: ['Which TCA/tetracyclic can cause EPS, tardive dyskinesia and NMS because of D2 blockade? (amoxapine)'],
    counsellingPoints: ['Report abnormal movements, stiffness or high fever (EPS/NMS).', 'Rise slowly.', 'Overdose is dangerous — keep secured.'],
    vignettes: [
      {
        stem: 'A patient on a tetracyclic antidepressant develops cogwheel rigidity, bradykinesia and elevated prolactin. Which antidepressant explains these antipsychotic-like effects, and why?',
        options: ['Maprotiline — via NE reuptake block', 'Amoxapine — its metabolite has D2 antagonism', 'Nortriptyline — via anticholinergic effects', 'Desipramine — via α1 blockade'],
        answer: 'Amoxapine — its metabolite has D2 antagonism',
        explanation: 'Amoxapine is a metabolite of the antipsychotic loxapine; its 7-hydroxy metabolite blocks D2 receptors, so it can cause parkinsonism, akathisia, tardive dyskinesia, hyperprolactinemia and NMS — unusual for a TCA.',
        testedFact: 'Amoxapine D2 antagonism → EPS/NMS',
        source: { name: 'openFDA/DailyMed amoxapine label — warnings (EPS/tardive dyskinesia/NMS)', origin: 'openfda' },
      },
    ],
    _prov: TCA_PROV,
  },

  protriptyline: {
    pronunciation: 'proh-TRIP-tuh-leen',
    moa: 'Secondary-amine tricyclic; potent noradrenergic (NET) reuptake inhibitor. Activating rather than sedating; anticholinergic; Na-channel block in overdose.',
    receptorProfile: 'Strong NE reuptake block with an activating/stimulating profile (least sedating TCA); still meaningfully anticholinergic. Very long half-life.',
    onsetOfEffect: 'Mood 2–4 wk; activation/energy may appear earlier.',
    halfLife: 'Long — ~54–92 hours (~74 h), the longest of the TCAs.',
    timeToSteadyState: '~2 weeks (long half-life).',
    metabolism: 'Hepatic; CYP2D6 substrate.',
    proteinBinding: 'High (~92%).',
    offLabel: ['Narcolepsy / daytime somnolence', 'Depression with psychomotor retardation'],
    approvedPopulations: 'Adults.',
    startingDose: '5–10 mg PO three times daily (avoid late-evening doses — activating).',
    titration: 'Increase gradually; the most potent TCA per mg, so doses are low.',
    maxDose: '60 mg/day.',
    frequencyTiming: 'Divided doses earlier in the day (activating — avoid bedtime).',
    startStopCrossTaper: 'Taper. 14-day MAOI washout each way.',
    commonSE: ['Insomnia / activation', 'Dry mouth', 'Constipation', 'Tachycardia', 'Orthostatic hypotension', 'Anxiety/agitation'],
    seriousAE: ['Cardiac conduction delay / arrhythmia (wide QRS, QT); tachycardia prominent', 'Seizures', 'Anticholinergic delirium', 'Increased suicidality (young adults)'],
    syndromes: ['Cardiotoxicity (Na-channel block)', 'Anticholinergic toxidrome', 'Serotonin syndrome (with MAOI/serotonergics)'],
    overdoseLethality: 'HIGH — lethal in overdose via Na-channel-blockade cardiotoxicity (wide QRS, arrhythmia), seizures and coma; very long half-life prolongs toxicity. Narrow therapeutic index; IV sodium bicarbonate for QRS >100 ms.',
    discontinuationSyndrome: 'Cholinergic rebound — taper (very long half-life softens it).',
    baselineWorkup: ['ECG (baseline, especially age >40 or cardiac disease)'],
    ongoingMonitoring: 'Activation/insomnia and tachycardia; mood/suicidality; ECG if cardiac risk.',
    majorDDI: ['MAOIs (contraindicated; 14-day washout)', 'CYP2D6 inhibitors (fluoxetine, paroxetine, bupropion) raise levels', 'Sympathomimetics (additive tachycardia/pressor effects)', 'QT-prolonging drugs', 'Other anticholinergics'],
    contraindicatedCombos: ['MAOIs (incl. within 14 days)', 'Recent acute MI / significant conduction disease'],
    maoiWashout: '14 days each way.',
    pregnancy: 'Weigh untreated illness; nortriptyline usually preferred if a TCA is needed. Tie to CANMAT perinatal 2024.',
    lactation: 'Small amounts in milk; monitor infant.',
    geriatric: 'Activating with prominent tachycardia and anticholinergic effects — use cautiously; the very long half-life aids accumulation.',
    cardiac: 'Na-channel block plus tachycardia; ECG and caution in conduction disease.',
    pearls: [
      'The activating, least-sedating TCA — a secondary amine used for depression with psychomotor retardation or hypersomnia; dose early in the day to avoid insomnia.',
      'Longest half-life of the TCAs (~74 h) and the most potent per milligram, so doses are low (≤60 mg/day).',
    ],
    mnemonics: ['"PROtriptyline = PROceed/GO" — the activating (stimulating), non-sedating TCA.'],
    confusables: ['Protriptyline (activating secondary amine) vs nortriptyline (sedating-leaning secondary amine with a TDM window).', 'Protriptyline vs amitriptyline — activating vs very sedating.'],
    classDifferentiators: 'The activating, non-sedating secondary-amine TCA; longest half-life, lowest mg doses.',
    examHooks: ['Which TCA is activating (not sedating) and used for depression with psychomotor retardation/hypersomnia? (protriptyline)'],
    counsellingPoints: ['Take earlier in the day — it can be stimulating/cause insomnia.', 'Report palpitations.', 'Rise slowly.', 'Overdose is dangerous — keep secured.'],
    vignettes: [
      {
        stem: 'A patient with depression marked by fatigue and psychomotor retardation is intolerant of sedation. Which secondary-amine TCA is uniquely activating and is dosed low and early in the day?',
        options: ['Doxepin', 'Trimipramine', 'Protriptyline', 'Amitriptyline'],
        answer: 'Protriptyline',
        explanation: 'Protriptyline is the activating, least-sedating TCA — a potent noradrenergic secondary amine dosed low (≤60 mg/day) and earlier in the day to avoid insomnia; the other options are sedating tertiary/tetracyclic agents.',
        testedFact: 'Protriptyline activating profile',
        source: { name: 'openFDA/DailyMed protriptyline label — pharmacology & dosing', origin: 'openfda' },
      },
    ],
    _prov: TCA_PROV,
  },
};
