export default [
  {
    id: "vx_seq_mdd_residual_cognition",
    stem: "A 41-year-old software developer with major depression has taken sertraline at an adequate dose for 8 weeks. Her mood and sleep have improved, but she remains distressed by persistent difficulty concentrating and slowed processing that impair her work, and she strongly wishes to avoid worsening the sexual side effects she already has. Which switch best targets her residual symptoms?",
    options: ["Vortioxetine", "Amitriptyline", "Paroxetine", "Phenelzine"],
    answer: "Vortioxetine",
    explanation: "For a partial responder whose residual burden is cognitive dysfunction with a wish to limit sexual side effects, vortioxetine (multimodal, marketed for cognitive symptoms of depression, lower sexual dysfunction than SSRIs) is the best-matched switch. Amitriptyline and paroxetine are anticholinergic and worsen cognition/sexual function, and phenelzine is a later-line MAOI reserved for treatment resistance.",
    meds: ["vortioxetine", "amitriptyline", "paroxetine", "phenelzine"],
    disorder: "Major depressive disorder",
    difficulty: 2,
    tags: ["switching", "residual-symptoms", "canmat"],
    source: { name: "CANMAT 2016 MDD Guidelines", origin: "canmat" }
  },
  {
    id: "vx_seq_mdd_augment_suicide",
    stem: "A 55-year-old with recurrent major depression has failed two adequate antidepressant trials and now has only a partial response to venlafaxine, which he tolerates well. He has chronic passive suicidal ideation and a prior attempt. You elect to augment rather than switch. Which agent adds the strongest evidence for reducing suicide risk in this setting?",
    options: ["Lithium", "Gabapentin", "Buspirone", "Trazodone"],
    answer: "Lithium",
    explanation: "Lithium augmentation of an antidepressant is an established treatment-resistant-depression strategy and is the only psychotropic with robust evidence for reducing suicide, making it the best choice given his chronic suicidality. Gabapentin has no antidepressant evidence, and buspirone or trazodone augmentation may help symptoms but carry no anti-suicide benefit.",
    meds: ["lithium", "gabapentin", "buspirone", "trazodone"],
    disorder: "Major depressive disorder",
    difficulty: 3,
    tags: ["augmentation", "treatment-resistant", "suicide"],
    source: { name: "CANMAT 2016 MDD Guidelines", origin: "canmat" }
  },
  {
    id: "vx_seq_gad_augment_no_dependence",
    stem: "A 34-year-old with generalized anxiety disorder and a history of alcohol use disorder in sustained remission has a partial response to escitalopram after 10 weeks. He and you agree to add a daily anxiolytic while explicitly avoiding any agent with dependence potential. Which is the best add-on?",
    options: ["Buspirone", "Clonazepam", "Diazepam", "Alprazolam"],
    answer: "Buspirone",
    explanation: "Buspirone is approved for GAD, augments antidepressants, and has no dependence or abuse potential, making it the anxiolytic of choice when a substance-use history rules out benzodiazepines. Clonazepam, diazepam, and alprazolam all carry tolerance and dependence risk that is inappropriate here.",
    meds: ["buspirone", "clonazepam", "diazepam", "alprazolam"],
    disorder: "Generalized anxiety disorder",
    difficulty: 1,
    tags: ["augmentation", "substance-use", "canmat"],
    source: { name: "Canadian Anxiety Guidelines 2014", origin: "canmat" }
  },
  {
    id: "vx_seq_gad_switch_comorbid_pain",
    stem: "A 62-year-old with generalized anxiety disorder has had no meaningful response to escitalopram at maximum tolerated dose over 12 weeks. She also has fibromyalgia and chronic musculoskeletal pain that dominate her presentation. Which switch best covers both her anxiety and her pain?",
    options: ["Duloxetine", "Bupropion", "Desvenlafaxine", "Mirtazapine"],
    answer: "Duloxetine",
    explanation: "Duloxetine is approved for GAD and for fibromyalgia and chronic musculoskeletal pain, so a single switch addresses both problems. Bupropion lacks anxiety efficacy, desvenlafaxine is approved only for depression (GAD is off-label with no pain indication), and mirtazapine covers neither GAD nor pain.",
    meds: ["duloxetine", "bupropion", "desvenlafaxine", "mirtazapine"],
    disorder: "Generalized anxiety disorder",
    difficulty: 2,
    tags: ["switching", "comorbidity", "canmat"],
    source: { name: "Canadian Anxiety Guidelines 2014", origin: "canmat" }
  },
  {
    id: "vx_seq_ocd_switch_clomipramine",
    stem: "A 28-year-old with obsessive-compulsive disorder has been pushed to a high dose of sertraline for 12 weeks and separately failed an adequate high-dose fluoxetine trial, with minimal reduction in obsessions. You want to switch to the agent with the strongest disorder-specific antiobsessional evidence. Which do you choose?",
    options: ["Clomipramine", "Amitriptyline", "Bupropion", "Venlafaxine"],
    answer: "Clomipramine",
    explanation: "After adequate high-dose, long-duration SSRI trials fail in OCD, clomipramine is the evidence-based next step as the most serotonergic TCA and the only tricyclic with robust antiobsessional efficacy. Amitriptyline and bupropion have no OCD efficacy, and venlafaxine has only weak OCD evidence.",
    meds: ["clomipramine", "amitriptyline", "bupropion", "venlafaxine"],
    disorder: "Obsessive-compulsive disorder",
    difficulty: 2,
    tags: ["switching", "high-dose", "canmat"],
    source: { name: "Canadian Anxiety Guidelines 2014", origin: "canmat" }
  },
  {
    id: "vx_seq_ocd_augment_antipsychotic",
    stem: "A 37-year-old with obsessive-compulsive disorder and comorbid chronic motor tics has had adequate trials of two high-dose SSRIs and clomipramine, achieving only a partial response. The next-step strategy is low-dose antipsychotic augmentation. Which agent has the best evidence for augmenting an SSRI in treatment-resistant OCD?",
    options: ["Risperidone", "Lithium", "Lamotrigine", "Buspirone"],
    answer: "Risperidone",
    explanation: "Adding a low-dose antipsychotic such as risperidone to an SSRI is the evidence-based augmentation for treatment-resistant OCD, and its benefit is greatest with comorbid tics. Lithium augmentation is a depression strategy, lamotrigine has no OCD evidence, and buspirone augmentation is ineffective for OCD.",
    meds: ["risperidone", "lithium", "lamotrigine", "buspirone"],
    disorder: "Obsessive-compulsive disorder",
    difficulty: 3,
    tags: ["augmentation", "treatment-resistant", "canmat"],
    source: { name: "Canadian Anxiety Guidelines 2014", origin: "canmat" }
  },
  {
    id: "vx_seq_ptsd_adjunct_nightmares",
    stem: "A 44-year-old veteran with PTSD has improved overall on sertraline after 10 weeks, with reduced avoidance and hyperarousal, but continues to have distressing recurrent trauma-related nightmares that fragment his sleep. What is the best targeted add-on?",
    options: ["Prazosin", "Quetiapine", "Zopiclone", "Clonazepam"],
    answer: "Prazosin",
    explanation: "Prazosin at bedtime is the evidence-based adjunct for PTSD-associated nightmares and trauma-related sleep disruption, directly targeting his residual symptom. Quetiapine carries an unfavourable metabolic/sedation burden for this indication, zopiclone treats insomnia but not nightmares, and benzodiazepines such as clonazepam are discouraged in PTSD and do not address nightmares.",
    meds: ["prazosin", "quetiapine", "zopiclone", "clonazepam"],
    disorder: "Post-traumatic stress disorder",
    difficulty: 2,
    tags: ["augmentation", "residual-symptoms"],
    source: { name: "Canadian Anxiety Guidelines 2014", origin: "canmat" }
  },
  {
    id: "vx_seq_ptsd_switch_snri",
    stem: "A 39-year-old with PTSD has had an adequate 12-week trial of paroxetine with inadequate response and is bothered by weight gain and difficult discontinuation symptoms on missed doses. You decide to switch to another agent with randomized-trial evidence in PTSD. Which is the best choice?",
    options: ["Venlafaxine", "Bupropion", "Trazodone", "Amitriptyline"],
    answer: "Venlafaxine",
    explanation: "Venlafaxine (SNRI) has randomized controlled evidence in PTSD and is an appropriate first-line-equivalent switch after an SSRI fails. Bupropion has no PTSD efficacy, trazodone is used mainly for sleep rather than core PTSD symptoms, and amitriptyline is a later-line, poorly tolerated tricyclic.",
    meds: ["venlafaxine", "bupropion", "trazodone", "amitriptyline"],
    disorder: "Post-traumatic stress disorder",
    difficulty: 2,
    tags: ["switching", "canmat"],
    source: { name: "Canadian Anxiety Guidelines 2014", origin: "canmat" }
  },
  {
    id: "vx_seq_sad_switch_rima",
    stem: "A 30-year-old with generalized social anxiety disorder has failed adequate trials of two SSRIs and venlafaxine. You are choosing the next-step agent and want an antidepressant with a Canadian social anxiety indication that avoids the dietary tyramine restriction of an irreversible MAOI. Which do you select?",
    options: ["Moclobemide", "Phenelzine", "Bupropion", "Desvenlafaxine"],
    answer: "Moclobemide",
    explanation: "Moclobemide, a reversible inhibitor of MAO-A, is approved for social anxiety disorder and is preferred before an irreversible MAOI because it does not require strict tyramine dietary restriction. Phenelzine works for social anxiety but is a later-line irreversible MAOI needing dietary precautions, bupropion is ineffective for social anxiety, and desvenlafaxine has no anxiety indication.",
    meds: ["moclobemide", "phenelzine", "bupropion", "desvenlafaxine"],
    disorder: "Social anxiety disorder",
    difficulty: 3,
    tags: ["switching", "treatment-resistant", "canmat"],
    source: { name: "Canadian Anxiety Guidelines 2014", origin: "canmat" }
  },
  {
    id: "vx_seq_sad_performance_prn",
    stem: "A 26-year-old violinist reports intense anxiety with palpitations and tremor confined to solo public performances a few times a month; she is asymptomatic in all other social situations. She wants something to use only for those events. What is the best next step?",
    options: ["Propranolol", "Sertraline", "Clonazepam", "Buspirone"],
    answer: "Propranolol",
    explanation: "For discrete performance (non-generalized) social anxiety, a PRN beta-blocker such as propranolol before the event blunts the autonomic symptoms (palpitations, tremor) and is the preferred targeted strategy. A daily SSRI like sertraline is disproportionate for isolated performance anxiety, PRN clonazepam carries dependence risk, and buspirone is ineffective taken PRN.",
    meds: ["propranolol", "sertraline", "clonazepam", "buspirone"],
    disorder: "Social anxiety disorder",
    difficulty: 2,
    tags: ["first-line", "prn"],
    source: { name: "Canadian Anxiety Guidelines 2014", origin: "canmat" }
  },
  {
    id: "vx_seq_panic_bridge_benzo",
    stem: "A 33-year-old with panic disorder is starting low-dose sertraline. In the first two weeks she has frequent, disabling panic attacks and cannot work while waiting for the SSRI to take effect. You add a time-limited scheduled agent to bridge the latency. Which is the most appropriate?",
    options: ["Clonazepam", "Buspirone", "Propranolol", "Zopiclone"],
    answer: "Clonazepam",
    explanation: "Clonazepam is approved for panic disorder and, given its long half-life and consequent smooth coverage, is a suitable short-term scheduled bridge while the SSRI reaches efficacy. Buspirone is ineffective for panic, propranolol does not prevent panic attacks, and zopiclone is a hypnotic with no antipanic action.",
    meds: ["clonazepam", "buspirone", "propranolol", "zopiclone"],
    disorder: "Panic disorder",
    difficulty: 2,
    tags: ["cross-taper", "bridging"],
    source: { name: "Canadian Anxiety Guidelines 2014", origin: "canmat" }
  },
  {
    id: "vx_seq_panic_switch_snri",
    stem: "A 47-year-old with panic disorder has had an adequate 12-week trial of paroxetine with persistent frequent attacks and troublesome weight gain. You plan to switch to another agent with an approved panic disorder indication. Which is the best choice?",
    options: ["Venlafaxine", "Bupropion", "Mirtazapine", "Desvenlafaxine"],
    answer: "Venlafaxine",
    explanation: "Venlafaxine is approved for panic disorder and is an appropriate evidence-based switch after an SSRI fails. Bupropion can worsen anxiety and is not effective for panic, while mirtazapine and desvenlafaxine lack a panic disorder indication.",
    meds: ["venlafaxine", "bupropion", "mirtazapine", "desvenlafaxine"],
    disorder: "Panic disorder",
    difficulty: 2,
    tags: ["switching", "canmat"],
    source: { name: "Canadian Anxiety Guidelines 2014", origin: "canmat" }
  },
  {
    id: "vx_seq_bpii_depression_firstline",
    stem: "A 29-year-old with bipolar II disorder presents in an acute depressive episode. A walk-in physician had recently started citalopram monotherapy, without a mood stabilizer. You reassess and choose an evidence-based first-line treatment for the acute bipolar depression. Which is best?",
    options: ["Quetiapine", "Bupropion", "Desvenlafaxine", "Gabapentin"],
    answer: "Quetiapine",
    explanation: "Quetiapine is CANMAT first-line for acute bipolar depression and appropriately replaces antidepressant monotherapy, which is discouraged in bipolar disorder because of limited efficacy and switch risk. Bupropion and desvenlafaxine are antidepressants that should not be used as monotherapy here, and gabapentin has no efficacy in bipolar depression.",
    meds: ["quetiapine", "bupropion", "desvenlafaxine", "gabapentin"],
    disorder: "Bipolar II disorder",
    difficulty: 2,
    tags: ["first-line", "canmat"],
    source: { name: "CANMAT/ISBD 2018 Bipolar Guidelines", origin: "canmat" }
  },
  {
    id: "vx_seq_bpii_maintenance_polarity",
    stem: "A 45-year-old with bipolar II disorder is now euthymic after an acute episode. Reviewing her course, her recurrences are overwhelmingly depressive, with no history of significant hypomanic relapse, and you are selecting a maintenance agent to best prevent further depressive episodes. Which is the best choice?",
    options: ["Lamotrigine", "Valproate / Divalproex", "Risperidone", "Aripiprazole"],
    answer: "Lamotrigine",
    explanation: "Lamotrigine is CANMAT first-line for bipolar maintenance with a depression-prevention profile, making it ideal for a predominantly depressive course. Valproate, risperidone, and aripiprazole are anti-manic agents that do not provide the same protection against depressive recurrence.",
    meds: ["lamotrigine", "valproate", "risperidone", "aripiprazole"],
    disorder: "Bipolar II disorder",
    difficulty: 3,
    tags: ["maintenance", "residual-symptoms", "canmat"],
    source: { name: "CANMAT/ISBD 2018 Bipolar Guidelines", origin: "canmat" }
  }
];
